### ISSUE TITLE
[mrp_production_real_costs] No contabiliza nuevos productos consumidos

### ISSUE THREAD

**Issue by cor9003** [odoomrp/odoomrp-wip#1001]
Hola, Una vez se ha iniciado la orden de produccion, es posible consumir nuevos productos no planificados inicialmente antes de dar el producto por fabricado. Cuando se añaden esos productos, no se contabilizan, con lo que no calcula en los costes totales asociados a esa orden de facturacion.

**Comment by anajuaristi** [comment]
Hola David, gracias por reportarlo en el sitio correcto.
Lo miramos y te decimos algo a lo largo de la semana que viene.
Saludos!!

**Comment by agaldona** [comment]
Buenas tardes,

Después de hacer varias pruebas he dado con el problema.
La forma de calcular los costes de productos consumidos se hace en una función llamada action_consume. Cuando se ejecuta esta función para un movimiento, comprueba que tenga valor en el campo raw_material_production_id, es decir, comprueba que este movimiento está asociado a una OF y que además es un producto que se va a consumir.
Debido a esto, si nosotros añadimos un nuevo componente en el asistente de consumir de una OF, no nos carga los costes, ya que la función de action_consume se ejecuta antes de que le asigne en el campo raw_material_production_id la OF correspondiente. Pero si añadimos este componente en la ficha de la OF utilizando la opción de "Add extra raw material", no nos encontramos con este problema, ya que al tener el id de la OF antes de ejecutar el action_consume, nos crea la línea analítica de coste correspondiente.

Espero haber aclarado vuestras dudas.
Saludos,
Ainara.

**Comment by cor9003** [comment]
Hola Ainara,
La unica forma de añadir nuevas materias primas desde la OF es con el boton de fabricar y seleccionado el modo de "consumir unicamente", que entiendo es a lo que te refieres que no lleva informado el campo raw_material_production_id, y por consiguiente no contabiliza los costes. 

No he visto otra manera de incluir materia prima en la OF como comentas.
Tengo instalados en V8 los modulos de MRP standard y mrp_production_real_costs con todas sus dependencias y no aparece ninguna opcion "Add extra raw material".

¿ He de instalar algun modulo adicional al mrp_production_real_costs (y sus dependencias) ?

Gracias de antemano por tu ayuda
David

**Comment by agaldona** [comment]
Buenas tardes David,

He comprobado que si que hay un módulo adicional que incluye este botón en la OF. Se llama, mrp_production_add_middle_stuff.

Espero que te sirva de ayuda.
Nosotros mientras tanto intentamos buscar la mejor solución para el caso que nos has reportado.
¡Muchisimas gracias!
Un saludo,
Ainara.

**Comment by cor9003** [comment]
Hola Ainara,

He añadido el modulo que comentas y es un buen modulo, que facilita la operacion de insertar una materia prima. Es mejor para el usuario que tener que ir al boton de fabricar, eliminando así el riesgo a que le de a fabricar y no solo a consumir los materiales.
Pero ni  con este modulo me ha contabilizado analiticamente los nuevos materiales, unicamente contabiliza los que estaban planificados desde la la lista de materiales.
He probado tanto con materials que existian en la Ldm( como por ejemplo un material consumido pero que se necesita mas materia prima ), como uno nuevo ( que no hubiera estado planificado). En ninguno de los casos los ha contabilizado.

Quedo a tu disposicion para cualquier duda/ayuda y por supuesto ... gracias de nuevo.

Un saludo
David

**Comment by agaldona** [comment]
Hola David,
El problema que puedes encontrar es que si metes una línea de componente nueva y no le asignas una workorder, te sale en un subapartado "indefinido" cuando vas a los costes de la OF. Puede ser esto lo que te este pasando?
Me dices algo,
Saludos,
Ainara.

**Comment by cor9003** [comment]
Hola,
He probado con ordenes de produccion con componentes que tienen y que no tienen workorder. Efectivamente cuando no tienen work order asignada el subapartado es "indefinido", y cuando tiene, sale dentro del subapartado de la work order, pero en ninguno de los casos crea el apunte analitico de costes del material añadido, y entiendo que deberia crearlo en ambos casos para imputar los costes del material.

**Comment by agaldona** [comment]
Buenas tardes David,

Voy a enseñarte un ejemplo mediante imágenes, ya que a mi al menos si me crea la línea analítica.

He creado una nueva OF de un producto con cuatro componentes.

![captura de pantalla de 2015-09-22 13 36 46](https://cloud.githubusercontent.com/assets/8297237/10018629/99133412-6138-11e5-8756-c1eba3615de3.png)

En la pestaña de productos planificados, pulso el botón Cargar Datos para que me traiga los datos correspondientes.

![captura de pantalla de 2015-09-22 13 37 14](https://cloud.githubusercontent.com/assets/8297237/10018628/991343ee-6138-11e5-85b1-925adae33f2d.png)

Una vez hago esto, confirmo la OF. Así me arrastra los productos planificados, a productos a consumir. Y aquí, pulso "Add extra raw material" .

![captura de pantalla de 2015-09-22 13 38 15](https://cloud.githubusercontent.com/assets/8297237/10018626/99102f10-6138-11e5-9a9c-b356ea5bc0e7.png)

Elijo un componente que se llama "asdfasdfasdf", añado 8 unidades y lo meto en la workorder de "Hacer agujero".

![captura de pantalla de 2015-09-22 13 39 08](https://cloud.githubusercontent.com/assets/8297237/10018630/9913f7d0-6138-11e5-9c61-cc33858dfb91.png)

Una vez tengo los materiales reservados, procedo a consumir.

![captura de pantalla de 2015-09-22 13 39 53](https://cloud.githubusercontent.com/assets/8297237/10018627/99104d24-6138-11e5-9b35-b017adf83336.png)

En la pantalla de consumir y producir. Asigno los lotes correspondientes si fuese necesario y le doy a confirmar.

![captura de pantalla de 2015-09-22 13 40 16](https://cloud.githubusercontent.com/assets/8297237/10018632/99274902-6138-11e5-89b3-1e4d4d92c9ef.png)

Una vez he procesado bien solo consumir o bien consumir y producir. Puedo ver las imputaciones de costes en "Production Costs" (lo verás en rojo en la siguiente imagen). 

![captura de pantalla de 2015-09-22 13_41_19](https://cloud.githubusercontent.com/assets/8297237/10018890/63d621ae-613a-11e5-85f3-84d4c4b41e09.png)

En la pantalla que me abre el botón, si despliego los costes, hasta llegar a la workorder de "Hacer agujero"  y dentro de esa "Materiales", veo que me ha imputado el coste del componente adicional que he añadido yo.

![captura de pantalla de 2015-09-22 13 41 37](https://cloud.githubusercontent.com/assets/8297237/10018634/992842ee-6138-11e5-89f0-c176f71febdd.png)

Por lo que veo a mi me esta funcionando correctamente, no se a que te refieres cuando dices que a ti no te crea la imputación correspondiente. No se si estamos siguiendo los mismos pasos o no, pero entiendo que si sigues estos, te debería de crear la imputación igual que a mi.

Cualquier cosa me comentas sin problemas.
Saludos,
Ainara.

**Comment by cor9003** [comment]
Hola Ainara, si son los pasos que sigo, pero solo me contabiliza los planificados en la Ldm, no los añadidos.
Te paso las pantallas 
1) Creo una orden de produccion con 3 materiales asociados a 1 work order
![1](https://cloud.githubusercontent.com/assets/6442086/10039006/5d17740a-61ce-11e5-9dd6-6e340d2476d2.jpg)

Confirmo y me arrastra los componentes y los reservo
![2](https://cloud.githubusercontent.com/assets/6442086/10039084/dd27f980-61ce-11e5-98df-75b894b41500.jpg)
Ahora añado un componente que me ha hecho falta pulsando el boton de "añadir producto extra"
y lo reservo
![3](https://cloud.githubusercontent.com/assets/6442086/10039183/ce836ada-61cf-11e5-9595-d80000abe7a3.jpg)
Le doy a consumit y fabricar y despues voy al boton de "Production Cost", y como puedes ver solo me ha imputado los que estaban planificados desde un inicio y no el añadido, que es la silicona
![4](https://cloud.githubusercontent.com/assets/6442086/10039260/77334308-61d0-11e5-9f78-18534629c570.jpg)
En cambio en la orden de produccion si que se han consumido todos los materiales, lo unico que no se ha imputado en la cuenta analitica
![5](https://cloud.githubusercontent.com/assets/6442086/10039294/ca722c14-61d0-11e5-938e-a4e5dca0d123.jpg)
estoy dandole vueltas y vueltas y creo que puede ser algo con las variantes, o que me falte algun modulo que no este puesto como dependencia y que sean necesario instalar.

Gracias por tu ayuda de nuevo

Saludos
David

**Comment by agaldona** [comment]
Buenos días David,

Solo hay dos condiciones para crear la imputación de coste. Uno que este asociado a una OF por el campo raw_material_id, eso ya veo que es así en tu caso. Y otro que el producto que está en el campo product_id de la línea tenga un cost_price > 0 
Podría ser que bien, o no te esté metiendo el producto en el product_id(que es raro) o que el coste del producto lo tengas a 0?
Como te digo, en el código son las únicas condiciones que se aplican.
Ya me dices si puede ser eso o no.
Saludos,
Ainara.

**Comment by cor9003** [comment]
Ainara, perfecto era eso.
El "precio de coste (variante)", ha de estar informado, pero solo para los añadidos posteriormente. El modulo funciona de forma diferente para materiales añadidos que para los planificados. Me explico:
1) Cuando un material ya estaba planificado en la Ldm, para crear el apunte analitico de costes da igual que el "precio de coste (variante)" sea > 0, con el "precio de coste manual" es suficiente.aunque en este caso el campo  "importe" no lo calcula, lo deja a 0, aunque si calcula correctamente  el "coste standard estimado" y "cantidad".

2) Cuando un material es añadido a los ya planificados, ha de tener obligadamente informado el campo "precio de coste (variante)"  con valor > 0, si no, no crea el apunte analitico. Aunque el "precio de coste manual" sea > 0 no se crea el apunte analitico. De esta manera calcula correctamente los campos "coste estandard estimado", "cantidad" e "importe"

Ainara, muhisimas muchisimas gracias

Si en algún momento necesitas alguna mano para que te ayude en algún test unitario de este módulo, por favor, cuenta conmigo. Será un placer devolverte esta inestimable ayuda recibida.

Saludos
David

**Comment by agaldona** [comment]
Buenas David,

Nosotros estamos aquí para ayudar en lo que podamos. Y que sepas que tendré en cuenta tu propuesta.

Respecto a lo que me comentas de costes. Acabo de darme cuenta de que en todo momento me he estado refiriendo a los costes reales de una OF. Pero es verdad que tenemos otro módulo que genera  los costes estimados de una OF cuando este se confirma.
Los costes reales siempre tienen en cuenta el precio coste del producto, pero los costes estimados los campos que tienen en cuenta son los campos precio de coste manual y el coste estándar estimado.

Los costes estimados están pensados para que podamos tener una visión de lo que nos va a costar una producción en concreto, y al ser una cosa a futuro los datos que utilizamos para calcularlo también son datos que prevemos, no datos reales. Por eso tenemos estos dos nuevos campos en la ficha de producto. Para que el usuario pueda definir el supuesto coste de este producto.

Los costes reales en cambio, se calculan ya cuando se realizan las cosas, es decir cuando se consume un producto, cuando imputa un operario o cuando una máquina deja de trabajar. El coste que utilizamos en estos casos son los costes definidos en cada caso, pero siempre pensando que son los datos reales. Es decir el precio hora que nos cuesta un operario o el coste que nos ha supuesto un producto según las compras que hayamos hecho. Por ello cuando cargamos un coste de producto, utilizamos el campo cost_price del mismo. Lo que sí, si un coste real nos sale a 0 no hacemos ninguna imputación.

Respecto a la imputación. Los costes reales y estimados, no se imputan de la misma forma. Los costes estimados, tienen unos campos adicionales en analítica donde se carga el coste de cada imputación y en el campo amount habitual lleva 0. Menos en los costes pre-operación y post-operación de una máquina. En este caso la imputación real y estimada se hace en una única línea. 
Los costes reales en cambio, llevan el coste en el campo amount y los campos de costes estimados los lleva a 0. Por eso al ver las sumas de las imputaciones, podemos ver en un vistazo lo que estimábamos y lo que ha sido realmente.

En tu caso, al meter el producto adicional en la OF después de que el mismo se haya confirmado, no te lo imputa como coste estimado. De todas formas, si mal no recuerdo tienes un asistente para que te los recalcule siempre que los necesites.

No se si con esto te aclaro algo el tema de los costes en OdooMRP. Como siempre, si tienes cualquier duda, puedes consultarnos.

Saludos,
Ainara.

**Comment by pedrobaeza** [comment]
Ainara, para tu información, en los próximos días, voy a darle una vuelta a eso del precio coste variante y demás, porque el interfaz es muy confuso, ya que no deberían aparecer datos discordantes de un sitio a otro para evitar estas confusiones. Básicamente será:
- Si pones un precio de coste en la ficha de producto, se lleva a las distintas variantes.
- En la variante, ocultar el precio de coste de la plantilla para no confundir.
- Homogeneizar nomenclatura.
