### ISSUE TITLE
[mrp_operation_extension] Traspaso de materiales planificados de Ldm a OF

### ISSUE THREAD

**Issue by cor9003** [odoomrp/odoomrp-wip#1007]
Hola,
Cuando el mismo material se ha definido 2 veces en una Ldm porque participa en 2 operaciones diferentes, cuando se pulsa el boton de calcular datos en la OF para planificar los productos a consumir, esta los genera incorrectamente, pues si que crea 2 lineas de materiales a consumir con las cantidades correctas, pero deberia ser cada una con una operacion diferente y en cambio pone la misma operacion.

Ejemplo
Creamos una Ldm que utiliza silicona  que se consumen en 2 operaciones diferentes ( ensamblado e integracion componentes). La OF deberia tener los materiales planificados de esta manera:

Silicona --> Ensamblado --> 20 unidades
Silicona --> Integracion componentes --> 10 unidades

Pero en cambio genera las siguientes lineas de material de consumo

Silicona --> Ensamblado --> 20 unidades
Silicona --> Ensamblado -->  10 unidades ( esta es la linea erronea)

Los ha planificado ambos para la misma operacion

Saludos
David

**Comment by cor9003** [comment]
Hola,
Simplemente con el animo de ayudar os comento que he realizado unos pequeños cambios en el codigo de la funcion get_workorder_in_product_lines para que funcione cuando se usa el mismo material en más de una operacion de una Ldm.

El codigo antiguo era:

```
        for p_line in product_lines:
            for bom_line in self.bom_id.bom_line_ids:
                if bom_line.product_id.id == p_line.product_id.id:
                    for wc_line in workcenter_lines:
                        if wc_line.routing_wc_line.id == bom_line.operation.id:
                            p_line.work_order = wc_line.id
                            break
```

El codigo que he probado y me funciona es:

```
        bom_line_checked = []
        for p_line in product_lines:
            flag_exit_material = 0
            for bom_line in self.bom_id.bom_line_ids:
                if flag_exit_material == 1:
                    flag_exit_material = 0
                    break
                if bom_line.product_id.id == p_line.product_id.id:
                    for wc_line in workcenter_lines:
                        if wc_line.routing_wc_line.id == bom_line.operation.id and bom_line not in bom_line_checked:
                            p_line.work_order = wc_line.id
                            bom_line_checked.append(bom_line)
                            flag_exit_material = 1
                            break
```

Basicamente lo que he hecho es que cuando la OF planifique un material  desde la Ldm, recuerde que esa linea de la LDm ya ha sido usada y no vuelva a usarla en el siguiente material

Gracias de nuevo por la ayuda recibida

Saludos
David

**Comment by pedrobaeza** [comment]
Cualquiera de estos métodos sufre del mismo problema: el tener que reconstruir los datos a posteriori. He propuesto unos hooks que nos ayuden a poder hacer esto correctamente. Por favor, revisad y dad vuestro +1: https://github.com/odoo/odoo/pull/8885

**Comment by Daniel-CA** [comment]
Correcto, eso ya lo contemplamos a la hora de hacer la asignación de operaciones a componentes, tal y como estaba definido el _bom_explode no permitía saber a que operación pertenecía el material si era del mismo tipo en dos operaciones diferentes.
Necesitaríamos las funciones hook que propone Pedro, a ver si los de Odoo le dan el visto bueno.

**Comment by pedrobaeza** [comment]
Me temo que no nos van a admitir los hooks en v8, aunque sí en v9 según dice @odony. Por lo tanto, necesitamos seguir buscando trucos como el que dice @cor9003 para salvar estos errores. Luego volveré a mirar posibilidades para hacerlo lo más elegante posible.

**Comment by anajuaristi** [comment]
¿Lo admitiría OCA en V8 OCB?

**Comment by pedrobaeza** [comment]
No, Ana, porque eso significaría que hay un módulo que funciona en OCB y no en Odoo. Antes es más fácil/factible sobreescribir entero el método _bom_explode que eso.

**Comment by anajuaristi** [comment]
@pedrobaeza 
Entonces, si técnicamente es correcto entiendo que hay que hacer un PR con el código de @cor9003 y validarlo funcionalmente.
Si es así, @Daniel-CA o @cor9003 ¿Podríais cualquiera de los dos hacer este PR para que podamos probarlo funcionalmente en runbot?

Gracias!!

**Comment by pedrobaeza** [comment]
Finalmente he optado por proveer esos hooks en un módulo aparte llamado hook, que sobreescribe totalmente el método _bom_explode, y proveer por nuestra cuenta de esos hooks. Ahora, todos los módulos que quieran usarlo, sólo tienen que depender de ese módulo. Por contra, estamos rompiendo la cadena de herencia, pero en este caso es justificable debido a las dificultades que ya hemos comentado.

Aquí el commit implicado: https://github.com/odoomrp/odoomrp-wip/commit/fd27730c7dfc757a2c2b00744541d19aa5441432
