### ISSUE TITLE
Bugs related to mrp_production_real_cost and mrp_production_stimated_cost

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#1010]
Testing the last versions of those modules I could find the following errors on them

The button "upload cost" to product is uploading the price negative (-206.60) to product form. It should be positive (206.60)
Real cost is informing the fields avg_cost and manual_stimated_cost in analytic line. This is incorrect. They should be zero. Real cost must assing a value only in field amount on analytic line. Otherwise it's duplicating the stimated cost. This was working before. The bug has been introduced on a merge made on summer or september.
Created final product related quant value is cero. It should be the total real cost(sum amount) / produced units. The final product related move has got a value on price_unit field. It seems that is not copied on quant cost field,
I still need to test more. But It's quite urgent we solve these bugs asap. 
Thank you:
Ana

**Comment by pedrobaeza** [comment]
Check with current version to see if it's correct.

**Comment by anajuaristi** [comment]
The button "upload cost" to product is uploading the price negative (-206.60) to product form. It should be positive (206.60) --> Still happens

---

There is another big bug. Pushing the button upload cost should only modify the specific selected variant price but it's modifying template cost and all variants cost. We are loosing previous values on variants. 
This could be caused by changes defined on https://github.com/odoomrp/odoomrp-wip/issues/1001
.- Si pones un precio de coste en la ficha de producto, se lleva a las distintas variantes. --> I think this should not be made. Template cost is not valid in any case since each variant could have totally different cost,  

---

Real cost is informing the fields avg_cost and manual_stimated_cost in analytic line. This is incorrect. They should be zero. Real cost must assing a value only in field amount on analytic line. Otherwise it's duplicating the stimated cost. This was working before. The bug has been introduced on a merge made on summer or september. --> Has been corrected

---

Created final product related quant value is cero. It should be the total real cost(sum amount) / produced units. The final product related move has got a value on price_unit field. It seems that is not copied on quant cost field, --> Still happens

For the move It's taking the template cost value. It should take from variant
The quant cost value is still zero
It acts same way when product form is set real cost or avg cost 

---

It must be still strongly tested. 

At the end the fields "cost" on quant and "price_unit" on stock move should be "visible" on quant and stock move tree views, to make easier testing and give more visibility about cost used on each moment

**Comment by pedrobaeza** [comment]
The problem is the field variant cost price you introduced. As I said, it's not a good idea to duplicate one field if you have another that have the same purpose and override all processes that write/read this field. You should provide instead a transparent method to handle this at model level. I'll work on this part next week.

**Comment by anajuaristi** [comment]
The new field has absolutly nothing to see for real costs. The problem
comes from changing the avg cost field to variant and this one is
mandatory. It has been even changed on V9.
I think before to make any change will be necesary to write spec.
It's necesary taking in mind that odoo has got 3 different cost methods and
we need to act like core does
