### ISSUE TITLE
[mrp_production_real_costs]. ¿ Como y cuando se calculan los costes reales  ?

### ISSUE THREAD

**Issue by cor9003** [odoomrp/odoomrp-wip#1013]
Hola,
No estoy muy seguro de entender como se calculas los costes reales de una OF. He realizado el calculo de los costes estimados y me los crea.Inicialmente pense que al iniciar la OF, conforme fuera consumiendo materiales en la OF, podria ver los costes reales de la OF mediante el boton Production Cost, pero no los veo . Tampoco los veo una vez he consumido todos los materiales, realizado todas las operaciones  y finalizado la orden de produccion.

Adjunto pantallas

![sin titulo1](https://cloud.githubusercontent.com/assets/6442086/10241156/51a1b338-68e5-11e5-9dd7-10ccf7e85053.png)

![sin titulo2](https://cloud.githubusercontent.com/assets/6442086/10241157/5711026a-68e5-11e5-8d9a-6bafdc45458e.png)

Gracias

**Comment by pedrobaeza** [comment]
Pues yo sí que estoy viendo 2 importes de 703,86 € en tu desglose. Revisa que tienes bien puesto el coste de variante en todos tus productos.

**Comment by cor9003** [comment]
Hola Pedro,

De los 2 materiales que he puesto para probar (Silicona y Loctite) solo ha contabilizado los costes de 1 de ellos, el de Silicona, que son los 700€ que ves, que cuadran con el estimado. En cambio del otro que esta en la pantalla (Loctite), si que ha calculado bien los estimados pero no en cambio el real, que esta a cero.
Los 2 materiales tienen correctamente los costes, porque en caso contrario no no hubiera calculado los estimados y ambos han sido consumidos durante el proceso de la OF..
![sin titulo](https://cloud.githubusercontent.com/assets/6442086/10242316/4487c768-68f0-11e5-9f8f-10d5ebb80441.png)

Adjunto pantalla

**Comment by cor9003** [comment]
Hola, desconozco si al estar cerrado el issue lo que escribo aqui se mira, pero he seguido haciendo más pruebas y he encontrado la casuistica de cuando NO se imputan correctamente los costes de los materiales..

Como funciona bien:
Funciona correctamente el coste de los materiales cuando el consumo de materiales se realiza con boton fabricar de la OF y se elije la opcion de consumir y fabricar, en ese momento imputa bien los costes de los materiales.

Como NO funciona correcatmente
Cuando los consumos de materiales se realizan  desde el tab de "Productos a consumir". En ese caso no se imputan los costes.
Por eso en la pantallas mias de arriba habia un material que lo imputaba correctamente y otro que no. 

Como NO funciona correcatmente
Tampoco imputa los costes reales del consumo de materiales cuando este se realiza desde la Orden de trabajo

Gracias por el soporte

Saludos
David

**Comment by pedrobaeza** [comment]
Los costes se imputan solamente cuando se cierra la orden, así que hasta que no cierres la orden no tendrás ningún coste real. No se van imputando conforme consumes los materiales.

**Comment by cor9003** [comment]
Hola Pedro,
Tampoco se imputan al cerrar la orden. No se si falta algun modulo o el motivo, pero las pantallas que he adjuntado arriba fijate que la orden ya esta cerrada y no se ha imputado los costes del material consumido en el tab de Productos a consumir. He realizado varias pruebas.

¿ Quieres que abra de nuevo explicandolo de manera más concisa ?

**Comment by pedrobaeza** [comment]
Comprueba que tienes la última versión y que todos los campos de coste en la variante de producto están rellenos. Le tenemos que dar una vuelta para que los campos no sean confusos, pero por lo demás, esto está funcionando.

**Comment by anajuaristi** [comment]
Solo comentar que los costes si que se deben imputar cada vez que se hace
un consumo de material o se cierra una ot o se imputan tiempos en una
tarea. No se imputan todos al cierre de la Of sino que se van añadiendo
durante la obra en curso.
No obstante estamos dando una vuelta y revisando el modulo punto a punto ya
que el cambio de enfoque de tener los costes en la plantilla a tenerlos en
el producto añadido a una optimizacion de codigo ha sido un cambio muy
grande.
A lo largo de la semana revisaremos lo que nos reportas.
Gracias:
Ana

**Comment by pedrobaeza** [comment]
Ana, ayer miré el código y veo que se hace en el cierre: https://github.com/odoomrp/odoomrp-wip/blob/8.0/mrp_production_real_costs/models/mrp_production.py#L54. ¿O es que el código está disperso por otros modelos?

**Comment by cor9003** [comment]
Hola, 
Ya he averiguado porque no se imputan los costes reales cuando se consume un material de una OF desde otro sitio que no sea el boton de fabricar. El módulo unicamente imputa costes cuando se pasa por la función action_consume (stock_move.py), pero cuando se consume el material de la OF desde otro sitio, como por ejemplo haciendo click en el propio material a consumir( desde el tab de productos a consumir), como no se ejecuta esta función, no se crea el apunte analitico.

Para solucionarlo he eliminado el codigo del action_consume (stock_move.py) que genera el apunte analitico y lo he puesto en la funcion action_done, donde mediante super llamamos a la funcion original (action_done) y posteriormente creamos la linea analitica.

La funcion action_done ( a diferencia de action_consume) se ejecuta tanto desde el boton de fabricar y consumir como desde el consumo del material, y ya se crean  los costes reales en ambos casos.
Me falta mirar porque no se imputan cuando se cierra la orden como comenta Pedro, que posiblemente sea una buena solución, cuando se cierre, revise todos los materiales consumidos y cree los costes reales en ese momento.

Saludos

**Comment by pedrobaeza** [comment]
Estupendo, gracias por investigar esto. Efectivamente, lo que propones es una mejora interesante. @agaldona, puedes tenerlo en cuenta?
