### ISSUE TITLE
[review] Modulo caducidades

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#103]
Hay un modulo llamado **product_expiry_ext** que según @anajuaristi no hace lo que debe, pero los requerimientos exactos no se encuentran en la tarea. Por lo que he visto si que hace algunos cálculos, pero como desconozco que color y estado debe de aplicarse según las fechas, no puedo decir si es correcto.

Supongo que @mikelarre tendrá la misma duda. Ya que es el quien tiene ahora asignada la tarea.

Está aprobado por @pedrobaeza :wink:

**Comment by anajuaristi** [comment]
Supongamos que un producto caduca el 1 de enero, entonces a partir de dicha
fecha la línea debe aparecer en rojo.
Hasta ahí correcto, pero yo no he conseguido que cambie de color aun
asignando fechas futuras o pasadas con respecto al día de hoy.

Luego, el lío se monta con los otros 3 campos que tiene el módulo expiry.
Están pensados para dar aviso al usuario de que le están venciendo
distintas cosas, aunque los nombres no son muy explicativos.

Yo haría así, independientemente de cómo se llamen, se pone Fecha1, fecha2,
fecha3 y fecha4. La cuarta es la de caducidad.
Las fechas se rellenan con 4 campos que hay en la ficha del producto, donde
indico número de días, supongamos que aquí pongo 30, 60, 90, 120 --> Cada
número de estos, incrementa el correspondiente número de días desde la
fecha en que se creó el lote. Con esa configuración
A un lote que entra hoy, le cascaría las fechas hoy + 30 días, hoy + 60
días... etc.

Todas las fechas indican una "alarma" y deberían ser configuradas en orden,
es decir, en la etiqueta de ficha de producto yo indicaría en el help o
algo, que lo pongan de esa forma.

Luego, los colores se pueden asignar por ejemplo:
Si hoy es menor que fecha1 verde
Si pasa fecha1, azul
Si pasa fecha2, amarillo oscuro
Si pasa fecha3, naranja
Si pasa fecha4, rojo.

Con esto queda en plan semáforo y bien. Si solo quieren usar fecha4, pongan
120 en todas las casillas de la ficha de producto. Si quieren naranja y
rojo, pongan el mismo valor en las 3 casillas primeras y mayor en la
última. O también, que pongan cero, en cuyo caso, no se asigna fecha en el
lote por tanto no se puede evaluar color.

Para asignar color siempre empezamos a verificar de la última fecha a la
primera.
Ok?

@pedrobaeza verificar especificación y si va adelante, que Oihane copie
este texto en la descripción de la tarea y tiramos con ello para dejarlo
acabado.

Saludos!!
Ana

El 24 de septiembre de 2014, 12:59, oihane notifications@github.com
escribió:

> Hay un modulo llamado _product_expiry_ext_ que según @anajuaristi
> https://github.com/anajuaristi no hace lo que debe, pero los
> requerimientos exactos no se encuentran en la tarea. Por lo que he visto si
> que hace algunos cálculos, pero como desconozco que color y estado debe de
> aplicarse según las fechas, no puedo decir si es correcto.
> 
> Supongo que @mikelarre https://github.com/mikelarre tendrá la misma
> duda. Ya que es el quien tiene ahora asignada la tarea.
> 
> Está aprobado por @pedrobaeza https://github.com/pedrobaeza [image:
> :wink:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/103.

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com soporte@avanzosc.com *

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
*_administracion@avanzosc.com
soporte@avanzosc.com *
_This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
soporte@avanzosc.com_

**Comment by oihane** [comment]
- Fecha 1 - **alert_date** : Alert Date (_Fecha de alerta_),
  This is the date on which an alert should be notified about the goods with this Serial Number.
- Fecha 2 - **removal_date** : Removal Date (_Fecha de eliminación_),
  This is the date on which the goods with this Serial Number should be removed from the stock.
- Fecha 3 - **use_date** : Best before Date (_Consumir preferentemente antes de_),
  This is the date on which the goods with this Serial Number start deteriorating, without being dangerous yet.
- Fecha 4 - **life_date** : End of Life Date (_Fecha de caducidad_),
  This is the date on which the goods with this Serial Number may become dangerous and must not be consumed.

Esto lo he sacado mirando los datos demo del `product_expiry`

**Comment by oihane** [comment]
PR #130

**Comment by anajuaristi** [comment]
Cierro issue... en principio, estaría duplicado porque ya hay tarea.
