### ISSUE TITLE
Account Treasury Forecast Inserción traducción faltante

### ISSUE THREAD

**Issue by CarlesAntoli** [odoomrp/odoomrp-wip#1035]
Hola, he visto que en el módulo no esta incluida la cadena final_amount, he modificado el archivo pot para incluirla, quería preguntaros que debo hacer con el archivo pot actualizado, ¿se debe subir el archivo en algún sitio o comunicar la incidencia al autor?. Gracias

**Comment by pedrobaeza** [comment]
Puedes traducirlo directamente en Transifex: https://www.transifex.com/oca/odoomrp-wip-8-0/dashboard/

**Comment by CarlesAntoli** [comment]
Hola Pedro, En transifex pone que esta traducido el módulo al 100% la cadena que comento no está.

**Comment by pedrobaeza** [comment]
Entonces será porque esa cadena no es exportable. Dónde aparece?

**Comment by CarlesAntoli** [comment]
En Previsión de tesoreria->Previsión de tesorería-> Final amount ( debajo de Importe inicial). He revisado el .pot y no está incluida.

**Comment by pedrobaeza** [comment]
He intentado que aparezca pero parece ser un bug de Odoo, ya que no hay forma de que lo exporte. Me temo que tendrás que realizar la traducción a mano.
