### ISSUE TITLE
Does product_variant_default_code works with import CSV Products?

### ISSUE THREAD

**Issue by davidperezgar** [odoomrp/odoomrp-wip#1046]
Hello, the module product_variant_default_code does it works with Product CSV import?

**Comment by pedrobaeza** [comment]
We haven't tried that use case, but it can be, because the triggers are launched on create.

**Comment by davidperezgar** [comment]
I can confirm you that it works for CSV import.

Thanks for your reply.
Regards.

**Comment by davidperezgar** [comment]
I've seen that the variable "Variant Reference Mask" has to be filled in order to put a default code for variants.
When I'm trying to import it it gets this error: 
Unknown error during import: <class 'openerp.exceptions.except_orm'>: (u'Error', u'Found unrecognized attribute name in "Variant Reference Mask"') at row 2
Resolve other errors first

the variant mask in the CSV file is: A098849494 [Color Prov] where A098849494 is the code for the product. Is something wrong?

**Comment by anajuaristi** [comment]
Variant reference Mask is the "formula"/"mask" used to calculate the product.product default code so it must only be filled on template, never in variants.

The error is because of that. 

I re-close the issue.

**Comment by davidperezgar** [comment]
Hello Ana, It's imported in product not variants... 

I use this first row:
product_variant_ids/attribute_line_ids/attribute_id,product_variant_ids/attribute_line_ids/value_ids, reference_mask

**Comment by anajuaristi** [comment]
Reference mask should have not a default code value but a "formula" related
to attributes. That's the error.

2015-12-01 10:50 GMT+01:00 David Perez notifications@github.com:

> Hello Ana, It's imported in product not variants...
> 
> I use this first row:
> product_variant_ids/attribute_line_ids/attribute_id,product_variant_ids/attribute_line_ids/value_ids,
> reference_mask
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/1046#issuecomment-160915959
> .

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

_El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Klara Donea 13, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
*_administracion@avanzosc.
soporte@avanzosc.eses*

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: *_Klara
Donea 13*\* 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 - *
_administracion@avanzosc. soporte@avanzosc.eses_ _This message and all
documents attached to it are confidential and intended only for the person
or entity to which it is addressed. Any use of this information by
unauthorised persons is prohibited under current legislation. If you
received this message by error, please advise us, destroy it and refrain
from communicating its contents to third parties. We apologise for any
inconvenience receiving this email improperly may cause to you. Your
personal data are included in a file owned by Avanzosc, S.L. If you want to
exercise your rights of access, correction, erasure and objection you can
contact the Controller at *_Klara Donea 13*\* 20720, Azkoitia (Gipuzkoa), T:
943 02 69 02 – administracion@avanzosc. soporte@avanzosc.eses*

**Comment by davidperezgar** [comment]
Ok Thanks
