### ISSUE TITLE
purchase_product_variants error

### ISSUE THREAD

**Issue by aitorbouzas** [odoomrp/odoomrp-wip#1049]
Hello,

I'm having an issue when trying to access to a purchase.order.line with purchase_product_variants module installed:

`File "/opt/bitnami/apps/odoo/lib/odoo-8.0_a2115ef-py2.7.egg/openerp/addons/purchase_product_variants/models/purchase_order.py", line 187, in onchange_product_id
    state=state)
TypeError: onchange_product_id() takes at least 9 arguments (12 given)`

The error is in the call to the inherited function:

`res = super(PurchaseOrderLine, self).onchange_product_id(
    pricelist_id, product_id, qty, uom_id, partner_id,
    date_order=date_order, fiscal_position_id=fiscal_position_id,
    date_planned=date_planned, name=name, price_unit=price_unit,
    state=state)`

**Comment by pedrobaeza** [comment]
Do you have any custom module that also touches this method?

**Comment by pedrobaeza** [comment]
Try to reproduce the issue on runbot: https://runbot.odoo-community.org/runbot/repo/github-com-odoomrp-odoomrp-wip-188

**Comment by aitorbouzas** [comment]
Yes. warning module:

`def onchange_product_id(self,cr, uid, ids, pricelist, product, qty, uom,
            partner_id, date_order=False, fiscal_position_id=False, date_planned=False,
            name=False, price_unit=False, state='draft', notes=False, context=None):`

And the purchase itself:

`def onchange_product_id(self, cr, uid, ids, pricelist_id, product_id, qty, uom_id,
            partner_id, date_order=False, fiscal_position_id=False, date_planned=False,
            name=False, price_unit=False, state='draft', context=None):`

**Comment by aitorbouzas** [comment]
Also, we created the database with demo content, but that shouldn't interfere...

**Comment by pedrobaeza** [comment]
Please check it on runbot (with that module installed/not installed) to check if it happens.

**Comment by aitorbouzas** [comment]
Installing warning seems to stop this error... Maybe it should be added as a dependency?

**Comment by aitorbouzas** [comment]
Well, in runbot it's not happening even warning is not installed... But on my own odoo it does.

**Comment by aitorbouzas** [comment]
Just checked that in my own odoo it is still happening after I installed warning, but now instead of showing the error as you try to create a new line on a purchase, it shows it right after changing product_template field.

**Comment by pedrobaeza** [comment]
That's why I told you to check other custom modules in your side or maybe you have an obsolete version? Update Odoo code to check.

**Comment by aitorbouzas** [comment]
There's no custom modules installed in our side. Could you please tell how to update the code? Some guide or manual...

**Comment by pedrobaeza** [comment]
Download last code from git or daily build and put --update=all on the command line.

**Comment by aitorbouzas** [comment]
The problem is that this is a bitnami VM, so I don't know in which directory I should do "git pull" to update the code...

**Comment by pedrobaeza** [comment]
I understand that is a prebuilt image. I suggest you to download code from github.com/odoo/odoo instead and redirect the addons-path to the downloaded code.

**Comment by aitorbouzas** [comment]
Ok, it seems to be a problem with the old coded. Just tried the module on a new and recently installed odoo and it worked perfect. Thanks!

**Comment by pedrobaeza** [comment]
Glad to hear that. I close the issue.
