### ISSUE TITLE
mrp_bom_component_change: Does not seem to work on demo.odoomrp.com

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#1054]
Hi,

Don't know, if it is a feature or an issue. I made a test to change one component from multiple boms that was of type phantom, but the system did not find it.

steps to reproduce:
1. create a BOM with one line containing a product A
2. Save and activate the bomb
3. Go to the BOM component modification
4. Enter as old product the product A and replace it with product B
5. Run the replacement.
6. You get an error message that the product A is not found in BOM.

Note: the BOM has no assigned routing.

**Comment by Daniel-CA** [comment]
This Fixed in #930
