### ISSUE TITLE
rangos de calidad, solo crean un bloque de muestra en la inspección

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#1059]
Aunque se definan rangos con más de un bloque de preguntas de test en la inspección, siempre crea un único bloque

Pasos para reproducirlo:
1. Definir un rango de cantidades con más de un bloque
2. Asignar a una plantilla
3. Definir un disparador para albarán de compra
4. Hacer pedido con una cantidad de dicho producto que correspondería a más de un bloque
5. Confirmar el pedido y realizar la transferencia de la recepción
6. Navegar al test y 
   ---> Siempre crea un único bloque de preguntas independientemente del número de bloques definido en el rango

**Comment by pedrobaeza** [comment]
Prueba en https://github.com/odoomrp/odoomrp-wip/pull/1060 si sigue ocurriendo
