### ISSUE TITLE
08 [IMP] Análisis de Costes 

### ISSUE THREAD

**Issue by JMODaERP** [odoomrp/odoomrp-wip#1062]
Improvement
 
La estrategia del 85% de las empresas del tejido productivo español es la estrategia en costes. Es por ello que aquellas empresas que fabrican lo que venden y que tienen siempre presente aportar el máximo valor a sus inversores,  aportando asimismo más valor a sus clientes que sus competidoras, pongan gran énfasis en el análisis de costes de producción.
 
Creo que desde Odoo deberíamos darle mayor valor a la herramienta incorporando en el MRP el siguiente análisis:
 
        **Menú Informes è Producción è Análisis de Costes Reales**

a)  **Coste de materiales**: Número de unidades, de materias primas consumidas producidas (product.qty del objeto mrp.production.product.line) por el Precio de Coste de cada la materia/s prima/s (cost_price del objeto product.product, en la pestaña de abastecimientos de la ficha del producto materia prima). 

**Coste de Materiales** = ∑ Materiali (product.qty del objeto mrp.production.product.line)*Precio de Costei (cost_price del objeto product.product); Siendo i = 1… n (cada una de las líneas de materiales consumidos).

b)    **Cálculo de las horas de producción real** en función del inicio/paro de una orden de trabajo. 
Una vez creada una orden de trabajo, bien por haber pinchado el botón Calcular datos o bien al Confirmar la orden de producción se crean tantas órdenes de trabajo como operaciones se hayan incluido en la ruta de producción. 

El responsable de producción o el operario responsabilizado marca los inicios y los paros del trabajo que sea realiza en el centro de trabajo , mediante los botones; Iniciada, Finalizada, Pendiente del objeto mrp.production.workcenter.line . 

El total horas de producción en el centro será la suma de los intervalos de producción real: ∑hfi-hii, para todo i = al número de intervalos (marcha/paro), siendo hii la hora de inicio y hfi la hora de paro o fin del intervalo.

c) **Coste de máquina**: Cuando medimos en horas: es el Precio de Coste del producto determinado en Producto centro de producción (product_id del objeto mrp.wokcenter), colocado en el Coste horas (cost_hour del objeto mrp.wokcenter), por las horas calculadas en b.

Será igual al (cost_cycle del objeto mrp_wokcenter) por los ciclos realizados, cuando medimos en ciclos número de ciclos es igual a la cantidad fabricada dividido entre la capacidad del ciclo definida en la línea CT de la ruta (opc_wc_lines del objeto mrp.routing.workcenter/capacity_per_cycle). 

d)  **Costes de operarios**. Se compone de la suma de: 

1.- Precio medio determinado en la pestaña Operarios (op_avg_cost del objeto mrp.workcenter) por la suma de las horas realizadas por cada operario. Horas imputadas que se reflejarán en le nueva pestaña “tareas” (de proyecto) en la orden de trabajo, a la derecha de Información extra.

2.- Precio del producto de coste de pre-operación, pre_op_product del objeto mrp.workcenter, (cost_price del objeto product.product) por las horas de pre-producción (time_start de la línea de CT de la orden, tiempo antes de prod). 

3.- Precio del producto de coste de post-operación, post_op_product del objeto mrp.workcenter, (cost_price del objeto product.product, precio de coste variante) por las horas de post-producción (time_stop de la línea de CT, tiempo después de prod).

**Comment by anajuaristi** [comment]
Estupendo análisis pero de todo esto que dices qué ves que falte?
No entiendo bien la solicitud

**Comment by JMODaERP** [comment]
Buenos días Ana, me das la luz que necesitaba para encender este
proyecto común que es Odoo, (parafraseo a Matia Bazar en su canción
Sólo Tú)

Necesito un informe, en Reporting  ==> Manufacturing ==> Análisis de
Costes de Producción que me agrupe por periodos, clientes, órdenes de
producción, centros de trabajo, productos o combinaciones de estas
dimensiones y con las medidas o hechos descritas en la solicitud.

Mi intención es ir un  poco más allá, necesitaría un informe
equivalente en dimensiones y medidas para lo planificado, actualmente
existe toda la información  pero no está agrupada en un informe al que
el cliente pueda acceder.

Una vez que tengamos ambas vistas (informes exportables e
imprimibles), el tercero es las desviaciones entre lo planificado y lo
realizado. Mostrando cada una de las partidas (conceptos) con sus
cantidades, precios, importes y diferencia aritmética y porcentual.

Se que esto para Odoo está hecho, o es fácilmente realizable y estos
requerimientos  junto a algunas incidencias pequeñas o no tan pequeñas
(como la actualización del standard_price del product.product mediante
el cálculo del precio medio cuando el método de coste sea Price
Average), es fundamental para la implantación a primeros de diciemere
de los módulos de almacén y producción en mi cliente (el primero no lo
utilizan porqué como no tienen en marcha la producción el inventario
está siempre en negativo), que dicho sea de paso está muy
desmoralizado y enfadado con Odoo.

Por tanto Ana, dado que es muy importante que el cliente arranque el
ejercicio 2.016 y al final tenga datos de todo el año, y  porque he
conocido a otro cliente potencial, en casa de éste,  que está a la
espera de que esto lo implantemos en diciembre y funcione, te ruego,
que yo se que tú controlas mucho los desarrollos, me facilites la
resolución de estos pocos temas en un breve  plazo. Ese plazo en el
que yo me he comprometido es la resolución de las incidencias 20 de
noviembre, cumplimiento de los requerimientos funcionales 27 de
noviembre, implantación de almacén/producción 30 de noviembre.

Gracias por ver válido el análisis parcial de las necesidades del
cliente, lo que es más loable por decirlo, estaba empezando a pensar
que en este entorno las cosas eran demasiado distintas a los ciclos de
vida de los desarrollos convencionales y que los proyectos, por falta
de comunicación se convertían en Torres de Babel.

Te reitero las gracias y estoy a tu plena disposición para lo que necesites.

**Comment by anajuaristi** [comment]
Pues estaremos encantados de revisar tus contribuciones tanto sean para la
construccion de los informes que necesita tu cliente como para los parches
que resuelvan posibles bugs

Muchas gracias
Ana

**Comment by rafaelbn** [comment]
@anajuaristi @pedrobaeza this issue must be opened here https://github.com/OCA/margin-analysis? or here https://github.com/OCA/manufacture? or here https://github.com/OCA/manufacture-reporting?

**Comment by JMODaERP** [comment]
cc @rafaelbn
