### ISSUE TITLE
[8.0][mrp_operations_extension + mrp_subcontracting] Campo picking_type_id duplicado

### ISSUE THREAD

**Issue by zamberjo** [odoomrp/odoomrp-wip#1107]
Si se instalan los módulos **mrp_operations_extension** y **mrp_subcontracting** aparece un campo duplicado en el modelo **mrp.routing.workcenter**. Las vistas son:
- _odoomrp_wip/mrp_operations_extension/views/mrp_routing_view.xml:63-65_
- _odoomrp_wip/mrp_subcontracting/views/mrp_routing_workcenter_view.xml:19-25_

**Comment by pedrobaeza** [comment]
Efectivamente, el campo sobra ya en mrp_subcontracting. Puedes hacer un PR quitándolo?
