### ISSUE TITLE
*_pricelist_rules missing fields

### ISSUE THREAD

**Issue by levkar** [odoomrp/odoomrp-wip#1108]
_pricelist_rules addons use supplier_ids and customer_ids fields on product.product model which is missing. when a pricelist version with base calculated from "supplier price", it crashes.

As far as I understand, there has to be another addon which adds these fields and it's best to add that addon as dependency to be safe.

**Comment by pedrobaeza** [comment]
You need the module _product_supplierinfo_for_customer_ for having this field. Can you point me which is the code line that mention this field?

**Comment by levkar** [comment]
I couldn't see that addon on odoomrp-wip. Probably deleted.

Example lines:

https://github.com/odoomrp/odoomrp-wip/blob/8.0/product_pricelist_rules/models/product_pricelist.py#L162

https://github.com/odoomrp/odoomrp-wip/blob/8.0/product_pricelist_rules/models/product_pricelist.py#L164

Thank you very much.

**Comment by pedrobaeza** [comment]
The module is in https://github.com/OCA/product-attribute/tree/8.0/product_supplierinfo_for_customer. Download and install it on your system.

The dependency has been fixed in https://github.com/odoomrp/odoomrp-wip/commit/bddc79d84e69dbdaf7ee91399ee77e93918a78bc
