### ISSUE TITLE
[8.0][sale_product_variant] Attribute Price Extra

### ISSUE THREAD

**Issue by burnout75** [odoomrp/odoomrp-wip#1121]
The Attribute Price Extra is not based on sale order pricelist selected: need to be calculate.
The product price unit is wrong if pricelist include discount or a different currecy.

**Comment by pedrobaeza** [comment]
Module?

**Comment by burnout75** [comment]
sale_product_variants on sale_order

**Comment by pedrobaeza** [comment]
We haven't found that problem from now (or we are not using that features in our customers). If you make a PR solving the issues, we will review it, but it's not something that we are going to fix for now.
