### ISSUE TITLE
[8.0][product_variants_no_automatic_creation] "Use the category value" no traducido en el es.po

### ISSUE THREAD

**Issue by JGarcia-Panach** [odoomrp/odoomrp-wip#1124]
Buenos días!

En la siguiente línea falta de traducir "use the category value"
https://github.com/slevenhagen/odoomrp-wip-npg/blob/052254398716e4f6ca7cf010d3b3f04d601b4412/product_variants_no_automatic_creation/i18n/es.po#L88

Propongo: Utilizar el valor de la categoría.

Si os parece bien hacemos el PR.

Un saludo y muchas gracias por vuestro trabajo!!

**Comment by pedrobaeza** [comment]
De acuerdo, gracias.
