### ISSUE TITLE
[8.0][mrp_production_add_middle_stuff_operations] Import models

### ISSUE THREAD

**Issue by maurochip** [odoomrp/odoomrp-wip#1135]
En este módulo la carpeta "models" no se está importando para su uso. Estoy buscando un módulo que me pueda asignar las ubicaciones de stock (de origen y/o destino) según la operación especificada del centro de producción. Este módulo, según el código fuente, parece que intenta hacerlo asignando las ubicaciones del tipo de albarán en la operación, pero parece que solo lo hará cuando se añada un producto desde el botón de 'Añadir producto extra'. No se si el objetivo de este módulo es lo que intento explicar o no.
Gracias de antemano!!

**Comment by pedrobaeza** [comment]
@Daniel-CA, puedes revisar?

**Comment by Daniel-CA** [comment]
Correcto, faltaba añadir el import de la carpeta models, se añadió código en el módulo para que en caso de que estuviera instalado el módulo de subcontrataciones permitiera añadirlas.
De todas formas @maurochip este módulo es solo un módulo puente para que funcionen los otros dos en caso de tenerlos instalados, el módulo en si no añade funcionalidad extra.
