### ISSUE TITLE
Costo promedio trasladado a Producto Terminado

### ISSUE THREAD

**Issue by nestoravalos** [odoomrp/odoomrp-wip#1146]
Hola a todos!

Creo porque aún lo estoy probando, pero el módulo del MRP no traslada el costo de Producción en Proceso al Producto Terminado, alguien que me pueda orientar si si está probada está parte.

Ejemplificando con el tipo de Coste Promedio y Valuación del Inventario en Tiempo Real:

Producto Terminado: PT01 (Costo Promedio = 0) -> No se ha producido nada.
Insumo: Insumo01 (Costo Promedio = 9)
Lista de Materiales PT01: Insumo01 con cantidad igual a 1

Creamos Órden de Manufactura: MO0001 del PT01

INICIAMOS PRODUCCIÓN:
Almacén Materia Prima: Insumo01 con Precio de Costo = 9
Almacén Producción: Insumo01 con Precio Costo = 9

PRODUCIMOS:
Almacén Producto Terminado: PT01 con Precio Costo = 0

Cuando se produce, el Costo de la Producción en Proceso o en el almacén de Producción se debería trasladar al Almacén de Producto Terminado con Costo = 9, pero NO LO HACE.

Valor de los productos por Almacén:

Materia Prima - Insumo01 = 9
Producción - Insumo01 = 9
Producto Terminado - PT01 = 0

Como debería quedar el valor de los Productos por Almacén:
Materia Prima - Insumo01 = 9
Producción - Insumo01 = 9
Producto Terminado - PT01 = 9

Me gustaría saber si Odoo en la Versión 8 está diseñado para hacer esté tipo de Costo en empresas de Fabricación?

Quedo a sus órdenes para cualquier comentario que me pueda orientar.

Saludos.

**Comment by JMODaERP** [comment]
Imagino que ya lo has descubierto y por eso has cerrado la consulta, en otro caso te diré que si lo hace, y además bien. Debes tener un problema de configuración. Un saludo.

**Comment by nestoravalos** [comment]
Hola JMODaERP, si ya encontre el detalle, y si lo hace bien como comentas, era un detalle con un módulo.

Saludos.

**Comment by rene-flores** [comment]
Hola JMODaERP,
Tengo el mismo problema, puedes indicarme por favor como proceder.

Saludos,

**Comment by fergancino** [comment]
Hola .
Estimados, espero sea posible me puedan ayudar con el tema en debate ya que estoy en el mismo inconveniente detallado por Nestor Avalos, con la diferencia que no se me calcula el costo  en la primera etapa de producción, menos aun en la etapa final de producción.
Estoy utilizando odoo 10. Por lo cual solicito alguien de ustedes pueda ayudarme con este tema de ante mano quedo muy agradecido.
Saludos.
