### ISSUE TITLE
[8.0][mrp_operations_extension] Duda en número de operadores

### ISSUE THREAD

**Issue by rubencr7** [odoomrp/odoomrp-wip#1154]
Hola, tengo la siguiente duda:
En la ruta de producción cuando se selecciona la operación para copiar sus datos en la linea de centros de trabajo, está cargando cada línea con datos respectivos a cada centro de trabajo de dicha operación. Está cargando en cada línea el número de operadores de la operación (mediante `onchange_operation()` en la clase `MrpRoutingWorkcenter`, se podría corregir de la siguiente forma y cogerlos también del centro de trabajo, añadiendo además el coste medio de operador:

```
data = {
    'default': is_default,
    'workcenter': operation_wc.id,
    'capacity_per_cycle': operation_wc.capacity_per_cycle,
    'time_efficiency': operation_wc.time_efficiency,
    'time_cycle': operation_wc.time_cycle,
    'time_start': operation_wc.time_start,
    'time_stop': operation_wc.time_stop,
    # vvvv Original vvvv
    # 'op_number': self.operation.op_number,
    # vvvv Propuesta vvvv
    'op_number': operation_wc.op_number,
    'op_avg_cost': operation_wc.op_avg_cost,
}
```

Saludos!

**Comment by pedrobaeza** [comment]
Buenas, Rubén, varios módulos de aquí están ya obsoletos al haber sido movidos a OCA/manufacture, entre ellos el que mencionas. Revisa allí si tienes el mismo problema, y si es así, pones un issue en ese proyecto.
