### ISSUE TITLE
product_variants_mrp modifica la introducción de datos en BOM y se pierde Operation

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#116]
Se pierde la operación del proceso en la que se consumen materiales. 
Revisar herencia de vistas con el módulo operations extension

**Comment by anajuaristi** [comment]
@oihane 
Sigue pasando esto.
Si instalo product_variants_mrp, la vista de lista de materiales pierde la operación y también se pierde el tree editable. 
En BOM, no es necesario lanzar el configurador. Quita la vista que hereda y listo.

**Comment by oihane** [comment]
PR #173
