### ISSUE TITLE
 [8.0][xxx_product_variants_types] small useability improvement

### ISSUE THREAD

**Issue by roedeorm** [odoomrp/odoomrp-wip#1168]
Here's a suggestion for a small usability improvement for attribute of types range:

In the xxxxx_product_variant_types modules, where attribute range is min=max (i.e. where only one value is allowed), enter this value in the field custom value automatically.

Example on demo.odoomrp.com
Product LAMP has attribute size with attribute value 100 and attribute value 20 - 55.
Attribute value 20 - 55 obviously has min=20 and max=55 and user input is needed.
Attribute value 100 however has min=100.0 and max=100.0 and no user input is needed. Hence just write 100.0 in the custom value of sale order line, puchase order line and manufactoring order. Also the pop-up window informing the user about the allowed values can be skipped when min=max.

**Comment by anajuaristi** [comment]
In that case Attribute value will not be range but numeric so you can set directly 100 on value.

I close the issue. Thank you for reporting

**Comment by pedrobaeza** [comment]
Being more specific, you already have an attribute type called "Numeric", where you can enter directly an specific number for each attribute value.
