### ISSUE TITLE
[8.0][mrp_wizzard_filter_task] Impute/Search imputation in task produces error

### ISSUE THREAD

**Issue by roedeorm** [odoomrp/odoomrp-wip#1173]
Got to Manufatoring>Manufactoring>Impute/Search imputation in task

Opening results in 
...
File "/opt/odoo/demo_odoomrp/odoomrp_addons/mrp_wizard_filter_task/wizard/wizard_filter_mrp_task.py", line 52, in task_onchange
    self.wk_order = self.task.wk_order.id or False
AttributeError: 'project.task' object has no attribute 'wk_order'

This can be clicked away.

Trying to add a task resuts in
...
File "/opt/odoo/demo_odoomrp/core/openerp/osv/expression.py", line 830, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'wk_order' in leaf "<osv.ExtendedLeaf: ('wk_order', '=', 911) on project_task (ctx: )>"

Tested on 
demo.odoomrp.com
db=September_2015_EN

**Comment by pedrobaeza** [comment]
This module is deprecated and not supported. See OCA/manufacture.
