### ISSUE TITLE
Operations extension con productos trazables

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#1178]
Hay algo que sigue sin estar bien en el consumo de material de una operación, con materiales trazables.
Ejemplo en demo, bbdd septiembre

OF MO00201, fabricando mermelada granel.
Hay 3 operaciones. En la primera se consume la fruta que es trazable. 
El quant trazable, con su lote está asignado.
Inicio primera operación y pulso el botón "consumir"
El wizard muestra el lote a consumir.
Sin cambiar nada pulso el botón aceptar

Se obtiene el siguiente mensaje que en ese punto no tiene sentido ya que el lote ya ha sido asignado en el wizard

Aviso!
Porque el producto Mermelada granel lo requiere, debe asignar un nº de serie a su materia prima albaricoque granel para poder continuar con la producción. Utilice el botón 'Producir' para ello.

Es un bug bloqueante ya que no se puede continuar con el consumo del material en ese punto.
@Daniel-CA le echas un vistazo porfa?

CC @pedrobaeza

**Comment by Daniel-CA** [comment]
Determinado que es por la función `check_tracking` del módulo `mrp` y la trazabilidad en producción.

**Comment by anajuaristi** [comment]
Me explayo un poquito más.

El tema es que parece que  hay un bug en el core, ya que si en un componente se activa la opción "trazabilidad en producción", lo que hace el check_tracking es mirar si el producto a producir (el padre) tiene asignado un lote. No tiene absolutamente ningún sentido mirar eso ya que lo que es trazable es el componente!!!. 

En cualquier caso, es sencillo de saltárselo porque con activar SOLO "trazabilidad en entrada y salida" en el componente ya va bien. Al transferir un albarán de entrada se obliga a meter un lote  por lo que a almacén llegan únicamente quants trazados. No es posible consumir en producción componentes sin lote, aunque el componente en sí no tenga marcada la casilla de fabricación.

Por mi parte, al tener la solución tan sencilla, cierro el issue y listo. Pero hay que tenerlo en cuenta para siguientes veces que pueda pasar.
