### ISSUE TITLE
Ultimo precio y fechas de venta y compra product_last_purchase_sale_info

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#118]
DUDA: No sé si la actualización de datos en la ficha debería hacerse al confirmar el pedido y no al guardar. Por otro lado, veo peligroso independizar la asignación de cliente de venta del importe de venta ya que podrías facturar antes algo que el pedido has enviado después. 
Por mi parte voto porque el precio se ponga al confirmar la venta y ya está. Es un dato informativo temporal y lo veo más consistente de esa forma. 

Al confirmar factura de venta o la de compra da este Traceback:

```
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/server-v8/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/server-v8/openerp/tools/safe_eval.py", line 315, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/addons_OdooMRP/odoomrp-wip/product_last_purchase_sale_info/models/account_invoice.py", line 40, in action_date_assign
    product_obj.write(self.cr, self.uid, [line.product_id.id],
ValueError: "'account.invoice' object has no attribute 'cr'" while evaluating
u'action_date_assign()'
```

**Comment by pedrobaeza** [comment]
Aprovechando esto, yo le cambiaría el nombre a _product_last_price_info_.

**Comment by anajuaristi** [comment]
@alfredoavanzosc creo que esto ya está hecho. Verifica si se ha incluido en algún PR y si es así, me dices den cual y cierra el Issue.

**Comment by alfredoavanzosc** [comment]
A este módulo se le cambió el nombre, ahora se llama "product_last_price_info", se le cambió el nombre a petición de Pedro.

**Comment by alfredoavanzosc** [comment]
Ana... a mi no me aparece para poder cerrar este issu.

**Comment by anajuaristi** [comment]
Ya está, cerrado
