### ISSUE TITLE
Glitch on odoomrp -> oca migration

### ISSUE THREAD

**Issue by andhit-r** [odoomrp/odoomrp-wip#1193]
Hi,

On my server i clone both OCA modules and odoomrp modules. On last pull (saturday 16/04/2016 UTC+7) i noticed that **mrp_hook** has been migrated to oca/manufacture (with same module name). So the that module move from odoomrp-wip to manufacture on my server. **The thing is there are still mrp_hook folder on my odoomrp-wip that contains only .pyc files**. This will caused odoo to false read module information. **mrp_hook detected as uninstallable**. It break it's dependency.

I fix it by:
1. Manually delete mrp_hook folder on odoomrp. 
2. Restart odoo server
3. Update module list
4. Upgrade all broken modules

Does someone know automatic solution for this so this glitch can be mitigated? 

Note:

On my addons_path, i registered odoomrp-wip first than oca/manufacture

Many thanks

**Comment by pedrobaeza** [comment]
The solution is to put first in the addons path all the OCA addons instead odoomrp-wip, or instruct your server to not generate pyc files. I'm afraid there's no better solution.

**Comment by andhit-r** [comment]
@pedrobaeza thank you for your advice
