### ISSUE TITLE
sale_product_variant, does not allow to set custom value on range type attributes

### ISSUE THREAD

**Issue by pauloneda** [odoomrp/odoomrp-wip#1209]
After updating product configurator
When chaning line sales order, the custom value of a range attribute is lost, ie set to zero again.
And price product maintains the initial product

**Comment by yastri** [comment]
i have same problem :(

**Comment by anajuaristi** [comment]
Tested in http://3147210-8-0-de2977.runbot1.odoo-community.org/web?db=3147210-8-0-de2977-base

Steps to reproduce
1. Create a new sale quotation
2. Select product "pvariant" on sale line --> try to assign any value on "custom" field. it's impossible because it's disabled.

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/odoomrp/odoomrp-wip/commit/aef30ed0ee519f7ce556db6635a9b60f97011610
