### ISSUE TITLE
Una máquina varios workcenters y no al revés

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#121]
En el maestro de máquinas hay un many2one a workcenters. 
Debería ser al revés workcenter tendría un many2one a máquinas

**Comment by anajuaristi** [comment]
Dani... este para la semana que viene, como hemos hablado. 

Aparte, vamos a hacer 2 módulos enlace, uno con compras (dependiente de compras) y otro con assets (account_asset)
1. purchase_machine: dependencia con maestro de máquinas + purchase

Hay que hacer:
Al confirmar una factura de compra, por cada línea de factura
Si existe máquina con producto = producto de la línea --> Crear máquina donde
- Producto = producto de la línea de factura
- Fecha compra = fecha factura
- Comprado en = proveedor de la factura
- Factura = id factura que ha creado la máquina
- Valor de compra = precio unitario de la línea

NOTA: crear tantas máquinas como cantidad indique la línea de factura, todas con los mismos valores --> (Es posible que la línea indique que se han comprado más de una máquina) 
1. assets-purchase-machine: Dependencia del módulo anterior con account_assets
   Añadir en machine un campo many2one a asset
   Si la factura de compra crea un asset para la máquina (esto lo hace assets) y además el purchase crea una varias máquinas, asignar el id del asset creado a la máquina creada.
   Ocultar los campos detalles financieros de la máquina, o bien copiarlos desde el asset ya que son los mismos (voto por ocultarlos o quitarlos de la ficha) 

@pedrobaeza  ¿que opinas?  Si alguien no tiene asset instalado, podría usar los campos a modo informativo, pero no hacen mucho más. 
Por otro lado, valida enfoque porfa, para que Dani se pueda poner con ello la semana que viene.

**Comment by pedrobaeza** [comment]
Me parece bien, aunque faltaría el nº de serie/lote de la máquina. En asset, como dices, los campos financieros que pasen a ser related del asset.

**Comment by anajuaristi** [comment]
Dani, pues adelante con los 2 módulos enlace.
Aparte, como comenta Pedro, sustituye el campo texto del maestro: Product Serial #, por un many2one a lotes, filtrado por el producto de compra asociado a la máquina.

**Comment by Daniel-CA** [comment]
Donde dice: 
Si existe máquina con producto = producto de la línea --> Crear máquina donde
- Producto = producto de la línea de factura

No entiendo muy bien esa frase. Hay que crear una máquina nueva si el producto está asignado a una máquina?

Actualmente las máquinas tienen un producto asignado y es único, relación 1-1, y el producto tiene el mismo nombre que la máquina. Esto se hizo así para que si había que enviar a reparar una máquina tuviera su contrapartida en un producto ya que las reparaciones van contra un producto.

Entonces se pierde la lógica si tengo que asignar el mismo producto a diferentes máquinas.

**Comment by anajuaristi** [comment]
¿Relación 1-1? Que va... 
En la máquina hay un many2one a producto. Por lo tanto el mismo producto puede usarse para ser asociado a varias máquinas.
La identificación de una máquina concreta se hace de toda la vida con un número de serie/lote. 
Si hay que enviar a reparar una máquina, se manda ese ID de máquina. ¿No puede tener una empresa 6 reactores, 4 microscopios y varios ordenadores iguales? 

Para hacerlo ya de nota, si la factura viene de un albarán de compra, en dicho albarán ha tenido que crearse el lote/número de serie de la máquina y habría que asignar ese en la ficha de la propia máquina. Pero el producto puede ser el mismo para N máquinas y de hecho, es normal que sea así.

**Comment by Daniel-CA** [comment]
Vale, de esta forma es más lógico. Hago una pequeña modificación en el maestro de máquinas para que se mantenga este enfoque.

**Comment by anajuaristi** [comment]
OK

**Comment by Daniel-CA** [comment]
Respecto a lo que comentas:
Para hacerlo ya de nota, si la factura viene de un albarán de compra, en dicho albarán ha tenido que crearse el lote/número de serie de la máquina y habría que asignar ese en la ficha de la propia máquina.

Tengo el problema cuando en el albarán vienen varios productos, ya que hay varias opciones en este sentido que tienen tratamientos diferentes:
- Que todos los productos tengan el mismo lote.
- Que todos los productos tengan un lote diferente.
- Que algunos tengan y otros no. (Entrega parcial).

Por lo que no se que lote se debe asignar cuando se crea la máquina, aparte de que tendría que relacionar los stock_pack_operations (el objeto que relaciona los movimientos con lotes) con las máquinas para saber cuales han sido ya asignados en caso de que sean lotes diferentes para todas.
Darle una pensada y me comentáis.

**Comment by pedrobaeza** [comment]
Es tan fácil como ir restringiendo y mostrar errores si no cumplen las condiciones que a ti te interesan. Cuando se recepciona un producto que sea máquina, y debe llevar nº de serie, no permitas que cantidad sea mayor de 1, y ya está.

**Comment by Daniel-CA** [comment]
Entiendo, la idea es recepcionar esos productos 1 por 1 y obligarle a que generé una linea por cada uno para que pueda enlazarla. :+1:

**Comment by pedrobaeza** [comment]
No es necesario recepcionar uno por uno, pero sí que en cada línea haya un sólo elemento con su nº de serie. Es eso lo que quieres decir, ¿no?

**Comment by Daniel-CA** [comment]
Si, me refería a un elemento por linea con su número de serie.

**Comment by pedrobaeza** [comment]
OK, pues estás tardando :wink:

**Comment by Daniel-CA** [comment]
Una duda que tengo sobre estos dos requerimientos:

```
Un enlace máquina-operarios, donde un operario puede estar homologado para operar con ciertas máquinas y una máquina puede ser operada por diferentes operarios. (many2many workcenter-user)
Un enlace máquina-operación, donde se especifica qué operaciones puede realizar una máquina y en qué máquinas puede ser realizada una operación (many2many workcenter-operacion)
```

Estaba en la tarea de maestro de máquinas, pero hay que diferenciar con que debe ir el enlace de operarios por que el maestro de máquinas tal y como esta ahora tiene una relación many2one de Workcenter (mrp.workcenter) con máquina (mrp.machinery).
Por lo que los operarios deberían ir enlazados al workcenter, entonces lo más lógico sería añadir esa relación en el mrp_operations_extension, ya que no es necesario tener el módulo de mrp_machinery para dicha relación.

Por otra parte Ana añade está última pregunta.
Duda: 
¿Enlace operario / maestro operaciones para cubrir requerimiento? ¿O mejor enlace operario/maestro máquinas (permitido utilizar máquina que realiza operaciones) como en enfoque OpenMRP?
En principio, un operador que esté capacitado para manejar una máquina podrá realizar todas las operaciones que realiza la máquina.

Cual es el mejor enfoque en este caso?

**Comment by anajuaristi** [comment]
Yo pondría enlace workcenter / Users many2many y efectivamente, un operario asociado a un workcenter podría realizar todas las operaciones que permita ese workcenter.
También es correcta la asociación con workcenter y no con machine si nos fijamos sólo en fabricación pero... ¿Y si no tienen fabricación instalado? Es decir... ¿Querriamos controlar que un determinado operador pueda manejar una máquina del almacén o del laboratorio? En este caso sería en Machines. Me surge la duda... @pedrobaeza lo hacemos general? O sólo para workcenters de fabricación? 
Yo lo hacía general, aunque tengan que instalar machines...

**Comment by anajuaristi** [comment]
@Daniel-CA  metemos 2 enlaces independientes
Uno en workorders, donde indica operadores asignados a la máquina
Uno en machines, donde indica operadores que están homologados para trabajar con la máquina.

Si en el enlace de machines, metemos fecha inicio y fecha fin, se indicaría periodo de homologación de ese operador con esa máquina.

En workcenters se podría incluir una automatización donde al asociar la máquina, se traiga todos los operadores homologados en ese momento y luego se puede realizar mantenimiento manualmente.
Por otro lado, si el workcenter, tiene máquina asociada, se puede poner un domain que solo me permita seleccionar operadores homologados en la máquina o si no, que pueda coger cualquiera.

Y así queda listo.
@pedrobaeza validar.

**Comment by pedrobaeza** [comment]
Lo hablado por chat: cada módulo tiene su many2many a res.users independiente. Si instalas sólo machines o sólo fabricación, pues entonces puede poner los datos en su lado. Si instalas ambos, con un módulo auto_install, como entiendo que una machine está relacionada con un workcenter (y si no, se añade ese many2one), entonces se sincroniza la información en ambos.

**Comment by Daniel-CA** [comment]
Entendido todo, lo único tal y como esta ahora el machine_manager es dependiente de mrp, ya que tengo que añadir la relación many2one con mrp.workcenter, si los queremos independientes tendría que añadir otro módulo especifico que la añada en caso de que los dos módulos se instalen (con el auto-install)

**Comment by pedrobaeza** [comment]
Lo suyo, según quiere Ana, es que sea independiente un módulo del otro. La relación many2one habría que meterla precisamente en ese módulo puente.

**Comment by Daniel-CA** [comment]
Vale, entonces tengo que mover la relación de user-workcenter a otro módulo, comentaba con @oihane  de moverla a mrp_operations_extension que ella estaba modificándolo actualmente.

**Comment by pedrobaeza** [comment]
mrp_operations_extension tiene dependencia con el de máquinas? No debe ser así. Lo que buscamos es que puedas instalar mrp o machine_manager por separado.

**Comment by Daniel-CA** [comment]
No, me refería a que la relación de operarios(users) con Workcenters ahora esta en el mrp_machine_manager, y deberá ir en otro módulo, me idea era meterla en mrp_operation_extension.

Por otra parte si el mrp_machine_manager ya no es dependiente de mrp, tiene lógica que lo lleve en el nombre del módulo así como los nombres de las clases?

**Comment by pedrobaeza** [comment]
Lo del nombre, desde luego que sí: mrp_machine_manager debería ser machine_manager.

Lo de la relación de operarios, hay que meterlo donde tenga sentido utilizar esa relación, y para mí sería en mrp_project_link, que es donde asocia las OFs a proyectos, para meter esas horas, ¿no crees? Faltaría encajar el módulo de meter horas de Mikel: a ver de cuál depende y si necesita esa relación.

**Comment by Daniel-CA** [comment]
Vale, añado la relación de operarios-workcenters en mrp_project_link, y hago un módulo intermedio que dependa para instalarse de mrp_project_link y machine_manager que relacionará los dos.
También cambio los nombres de módulo y clases del mrp_machine_manager para que no hagan referencia a mrp.

**Comment by anajuaristi** [comment]
@Daniel-CA @pedrobaeza Cierro esto que ya está
:+1:
