### ISSUE TITLE
Duplicate module with OCA/manufacture

### ISSUE THREAD

**Issue by andhit-r** [odoomrp/odoomrp-wip#1216]
I noticed that several modules avalaible both on odoomrp-wip and oca/manufacture. Is it intentionally leave already migrated OCA modules in here? Or those module will be removed from odoomrp? If those modules will be removed may i help?

Many thanks

**Comment by pedrobaeza** [comment]
The idea is to remove them once we have migrated all the customers that are using them, but sometimes the process can be slow.

Which ones are you talking about?

**Comment by andhit-r** [comment]
hi @pedrobaeza , here are the list of modules that duplicate with OCA/manufacture:
1. mrp_operations_extension
2. mrp_operations_project
3. mrp_operations_time_control

If you confirm that those modules can be removed from odoomrp-wip, i could create a PR to remote them.

**Comment by pedrobaeza** [comment]
Indeed, they should be removed. @anajuaristi, have you finished migrating customers out of these modules?

**Comment by pedrobaeza** [comment]
@andhit-r, purge has started with https://github.com/odoomrp/odoomrp-wip/pull/1183

**Comment by andhit-r** [comment]
Thanks @pedrobaeza
