### ISSUE TITLE
[8.0][mrp_product_variants] Cannot Compute Data

### ISSUE THREAD

**Issue by yastri** [odoomrp/odoomrp-wip#1217]
Hello,
After updating product configurator, there's and error when compute data in manufacturing order.

>   File "/opt/odoo/server/addons/mrp_product_variants/models/mrp_bom.py", line 137, in _prepare_consume_line
>     production.product_attributes))
>   File "/opt/odoo/server/addons/mrp_product_variants/models/product_attribute.py", line 35, in _get_product_attributes_inherit_dict
>     attr['attribute']).parent_inherited:
> KeyError: 'attribute'

and there's error log when restart odoo module 

> 2016-05-09 03:18:47,266 947 WARNING demo1 openerp.modules.loading: Model product.attribute.configurator is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
> 2016-05-09 03:18:47,266 947 WARNING demo1 openerp.modules.loading: Model product.product.attribute is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
> 2016-05-09 03:18:47,698 947 INFO demo1 openerp.modules.loading: Modules loaded.

thanks

**Comment by yastri** [comment]
Hello,

I've found the problem for compute data, the problem will be appear when there's no product variant defined in BOM.

Regards.

**Comment by oihane** [comment]
We are working on updating mrp_product_variants to the last changes in base module, it is not finished yet.

The PR is https://github.com/odoomrp/odoomrp-wip/pull/1208

**Comment by yastri** [comment]
Hi ..
Thanks for update.
After update PR #1208 , there's new error produce when create new packaging order

>   File "/opt/odoo/server/addons/mrp_packaging/models/mrp_production.py", line 127, in create_mo_from_packaging_operation
>     new_op = self.create(production_vals)
>   File "/opt/odoo/server/openerp/api.py", line 266, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/server/addons/mrp_production_estimated_cost/models/mrp_production.py", line 66, in create
>     return super(MrpProduction, self).create(values)
>   File "/opt/odoo/server/openerp/api.py", line 266, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/server/openerp/api.py", line 508, in new_api
>     result = method(self._model, cr, uid, _args, *_old_kwargs)
>   File "/opt/odoo/server/addons/mail/mail_thread.py", line 381, in create
>     thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
>   File "/opt/odoo/server/openerp/api.py", line 268, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/opt/odoo/server/openerp/api.py", line 372, in old_api
>     result = method(recs, _args, *_kwargs)
>   File "/opt/odoo/server/addons/connector/producer.py", line 48, in create
>     record_id = create_original(self, vals)
>   File "/opt/odoo/server/openerp/api.py", line 266, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/server/openerp/models.py", line 4094, in create
>     record = self.browse(self._create(old_vals))
>   File "/opt/odoo/server/openerp/api.py", line 266, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/server/openerp/api.py", line 508, in new_api
>     result = method(self._model, cr, uid, _args, *_old_kwargs)
>   File "/opt/odoo/server/openerp/models.py", line 4279, in _create
>     result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
>   File "/opt/odoo/server/openerp/osv/fields.py", line 797, in set
>     act[2][self._fields_id] = id
> TypeError: 'tuple' object does not support item assignment

**Comment by oihane** [comment]
yes I detected also minutes before you write this issue, I am fixing it in PR https://github.com/odoomrp/odoomrp-wip/pull/1220

**Comment by yastri** [comment]
thanks
