### ISSUE TITLE
[8.0] [sale_order_allowed_products] [purchase_order_allowed_products] Attribute Error

### ISSUE THREAD

**Issue by sandrafig** [odoomrp/odoomrp-wip#1226]
On an updated installation of Odoo, I cannot install these two modules, they raise the following errors:

**AttributeError: El campo `allowed_products` no existe**
Error de contexto:
Vista `purchase.order.allowed.form`
[view_id: 1910, xml_id: purchase_order_allowed_product.purchase_order_allowed_form_view, model: purchase.order, parent_id: 719]

**AttributeError: El campo `allowed_products` no existe**
Error de contexto:
Vista `sale.order.allowed.form`
[view_id: 1912, xml_id: sale_order_allowed_product.sale_order_allowed_form_view, model: sale.order, parent_id: 676]

Every repository is up to date and the database has been updated too, any idea why this is happening?

**Comment by pedrobaeza** [comment]
Remove by hand the implied views (IDs 1910 and 1912).

**Comment by sandrafig** [comment]
Thank you Pedro, it works now! :+1:
