### ISSUE TITLE
Integrity Error object with reference: owner_model - owner.model, executing procurement from sales to mrp

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#1229]
Tested in runbot, 
http://3147210-8-0-de2977.runbot1.odoo-community.org/web?db=3147210-8-0-de2977-base

Steps to reproduce
1. Sale the product pvariant (stockable, make to order, Manufacture, having dinamic BOM) selecting any atribute + values
2. Run asociated MTO procurement
3. You will obtain this Integrity Error:

Integrity Error

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: owner_model - owner.model]

**Comment by anajuaristi** [comment]
@mikelarre 
At the sametime, please take a look to procurements created for products having "custom" values, because I think it's not working yet. 

Thank you

**Comment by pedrobaeza** [comment]
Solved in https://github.com/odoomrp/odoomrp-wip/commit/18f3a1a455b824e934c32fb3c3101eba9f1ab595 (custom values not tested).
