### ISSUE TITLE
Inherit check on mrp attributes doesn't work anymore

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#1230]
Tested on runbot:
http://3147210-8-0-de2977.runbot1.odoo-community.org/web?db=3147210-8-0-de2977-base

Steps to reproduce:
1. Create a new manufacturing order, using product "pvariant", select any attribute value on configurator.
2. Go to scheduled products page 
3. Push compute data

Expected behavior: 
The component configurator for PC Assemble + Custom (PC on Demand), should have inherited the "color" attribute value from parent variant. 

Obtained behavior:
The value for "color" attribute on component configurator is null, so the correct component will not be automatically selected as it was done before.

**Comment by anajuaristi** [comment]
@pedrobaeza 
Any clue about why is this happening today? Any recent change on variants code that could cause the problem?
This functionality has been working longtime and today I realized it's broken now. 
I assign Mikel to take a look to it.

**Comment by pedrobaeza** [comment]
This hasn't been touched with the refactoring, so no idea for now. If you can't find it, let me know and I'll check, although I'm not using it.

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/odoomrp/odoomrp-wip/commit/a7ed4f70d54fa5e635f2b5362da2dc67b5ab554b
