### ISSUE TITLE
Procurement confirm doesn't find bom related to product template

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#1231]
Tested on http://3147214-8-0-18f3a1.runbot1.odoo-community.org/web?db=3147214-8-0-18f3a1-base

Steps to reproduce:
1. Create a sales order including a line with product "pvariant" (manufacture, make to order, stockable product, having attributes color and memory)
2. Confirm the sales order and procurement is correctly created
3. Confirm procurement 

Expected behavior:
.- Create an MO based on product template, having product configurator filled with values selected on Sales Order.

Obtained behavior:
.- Procurement goes to exception showing message: No BoM exists for this product!
Message is correct but BOM DOES exists for template
Procurement should look for template bom and the manufacturing order should be created 
Manufacturing  configurator should be filled with sales order line selected values.

**Comment by Daniel-CA** [comment]
Fixed in #1351
