### ISSUE TITLE
MRP Production manual close Question....About process

### ISSUE THREAD

**Issue by jaronemo** [odoomrp/odoomrp-wip#1246]
This module can not understand how can it help in practice business processes?
In China and Taiwan manufacturing industry developed business logic point of view, this module does not match the actual business processes.
Consider whether you want to fix this business logic?

Production Order qty 100 .....Produce 95   other 5 don't want produce..So..need manual close this production order ...set status is  done
So..this production order Product in Stock only 95  not 100...consume material is 95..not 100

**Comment by Daniel-CA** [comment]
I have a PR pending with this issue:

https://github.com/odoomrp/odoomrp-wip/pull/1160

**Comment by Daniel-CA** [comment]
Fixed in oca/manufacture#79
