### ISSUE TITLE
[8.0][sale_product_variant] How to update from  8.0.1.0 to 8.0.2.1.0

### ISSUE THREAD

**Issue by burnout75** [odoomrp/odoomrp-wip#1250]
I like to update the module to fix the issue about tre attributes traslation but the script  migrations/8.0.2.0.0/pre-migration.py return an error during db update and I need to restore from the previus version.
Need some steps more? All local modules (sale, wharehouse, purchase, etc etc) are to 8.0.1.x.

**Comment by pedrobaeza** [comment]
What error?

**Comment by burnout75** [comment]
From Configuration -> Local-Modules -> sale_product_variants -> Update the update not take effect.
From Configuration -> Updates -> Sale - Product variants 8.0.2.1.0 (8.0.1.0) the update take effect but when call Sale -> Product the error 
`2016-06-27 20:55:54,139 5804 ERROR dt_gestionale_new openerp.sql_db: Programming error: column product_product.product_id does not exist
LINE 1: ...uct"."write_uid","product_product"."default_code","product_p...
                                                             ^
, in query  SELECT "product_product"."manual_code","product_product"."ean13","product_product"."id","product_product"."product_tmpl_id","product_product"."write_date","product_product"."write_uid","product_product"."default_code","product_product"."product_id","product_product"."create_uid","product_product"."active","product_product"."name_template","product_product"."message_last_post","product_product"."create_date" FROM "product_product"
                        WHERE "product_product".id IN %s  ORDER BY "product_product"."default_code" ,"product_product"."name_template"`

or Sale -> Sale Order -> and try to open or create e new order:
`2016-06-27 20:58:29,987 5804 ERROR dt_gestionale_new openerp.addons.base.ir.ir_ui_view: Field`attribute`does not exist`

**Comment by pedrobaeza** [comment]
You have to restart your server and update.
