### ISSUE TITLE
[8.0][sale_product_variants][product_variants_no_automatic_creation] Extra price in sale order

### ISSUE THREAD

**Issue by burnout75** [odoomrp/odoomrp-wip#1266]
On the order line form the column with "Attribute Extra Price" is missing and the module not sum the costs for the extra attribute costs.

To reply from fresh installation or from runbot
- Create new BD with sample data
- Install Sale module
- Install sale_product_variants and relative dependencies
- Create or update a product with Attribute and relative values
- Create or update a sale order

Attribute Extra Price column is missiong from attributes table and the total price of product is wrong.

![cattura](https://cloud.githubusercontent.com/assets/4042055/16954228/557db35a-4dd0-11e6-9c15-4ff0c64b5d44.PNG)

It's a bug?

Check from http://3150705-8-0-f42815.runbot1.odoo-community.org/web/login?db=3150705-8-0-f42815-test

**Comment by burnout75** [comment]
With replacement of "mapped" function with standard cycles on "ProductConfigurator" and "ProductConfiguratorAttribute" classes the extra prices will be calculate again.

\product_variants_no_automatic_creation\models\product_configurator.py
@api.multi
    @api.depends('product_attribute_ids', 'product_attribute_ids.value_id')
    def _compute_price_extra(self):
        for record in self:
            for rec in record.product_attribute_ids:
                record.price_extra += rec

@api.multi
    @api.depends('value_id')
    def _compute_price_extra(self):
        for record in self:
            newrec = record.value_id.price_ids.filtered(
                    lambda x: (
                        x.product_tmpl_id == record.product_tmpl_id)
                )
            for rec in newrec:
                record.price_extra += rec.price_extra

Of course update_price_unit function on sale_product_variants still not working.
Some suggestion?

**Comment by anajuaristi** [comment]
@oihane @pedrobaeza
Please take a look to this.
Extra price for variants was properly working before the optimization. Maybe there is something missing from before.
@burnout75 thank you for contribution

**Comment by Daniel-CA** [comment]
Fixed in #1252
