### ISSUE TITLE
[v8] [purchase_secondary_unit] Does not allow to select product in purchase order

### ISSUE THREAD

**Issue by sandrafig** [odoomrp/odoomrp-wip#1289]
After the last commit, when I create a new purchase order, select the supplier and try to add a product, Odoo throws the following warning:

**ValueError
Mixing apples and oranges: 1 in account.tax(38,)** 

**Error log:**

> Traceback (most recent call last):
>   File "/opt/odoo/odoo-server/openerp/http.py", line 544, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 581, in dispatch
>     result = self._call_function(*_self.params)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 317, in _call_function
>     return checked_call(self.db, *args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
>     return f(dbname, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 314, in checked_call
>     return self.endpoint(_a, *_kw)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 810, in __call__
>     return self.method(_args, *_kw)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
>     response = f(_args, *_kw)
>   File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 944, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/api.py", line 399, in old_api
>     result = method(recs, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/models.py", line 5985, in onchange
>     record._onchange_eval(name, field_onchange[name], result)
>   File "/opt/odoo/odoo-server/openerp/models.py", line 5828, in _onchange_eval
>     method_res = method(self)
>   File "/opt/odoo/odoomrp-wip/purchase_secondary_unit/models/purchase_order.py", line 46, in onchange_price_unit
>     self.taxes_id)
>   File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/api.py", line 487, in new_api
>     result = method(self._model, cr, uid, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/addons/account/account.py", line 2175, in _fix_tax_included_price
>     incl_tax = [tax for tax in prod_taxes if tax.id not in line_taxes and tax.price_include]
>   File "/opt/odoo/odoo-server/openerp/models.py", line 5558, in __contains__
>     raise except_orm("ValueError", "Mixing apples and oranges: %s in %s" % (item, self))
> except_orm: ('ValueError', 'Mixing apples and oranges: 1 in account.tax(38,)')

**Comment by AntMoreno** [comment]
I confirm this issue. To reproduce it the purchase price of the product has to be different from zero.

**Comment by anajuaristi** [comment]
I also confirm it's happaning in our demo site.
@oihane could you take a look please?

**Comment by sandrafig** [comment]
Fixed in #1296
