### ISSUE TITLE
product_variants_no_automatic_creation - Variant Pricing not working

### ISSUE THREAD

**Issue by erwintwr2** [odoomrp/odoomrp-wip#1290]
hi there

i installed this module to an Odoo8 Version 8.0-20160829, on a clean DB.

when i create a product (with auto variant creation enabled), with variants and prices for variants, the correct variant price is not shown/calculated on the Product Variants tree view, or on the sales quotation.

please advise what i might be doing wrong?

thank you

erwin

**Comment by Daniel-CA** [comment]
Fixed in #1252
