### ISSUE TITLE
[8.0][sale_product_variants] product_tmpl_id not match if sale_stock module is active

### ISSUE THREAD

**Issue by burnout75** [odoomrp/odoomrp-wip#1303]
If sale_stock module is active
![cattura](https://cloud.githubusercontent.com/assets/4042055/19055239/3a324884-89c3-11e6-8d9a-3bd1b815ed2b.PNG)

the product_tmpl_id fields in sale.order.line table are not populate
![cattura](https://cloud.githubusercontent.com/assets/4042055/19055305/88207b74-89c3-11e6-8521-bb7ed3ef2ce4.PNG)

This is a know issue?

**Comment by pedrobaeza** [comment]
Install sale_stock_product_variants module.

**Comment by burnout75** [comment]
@pedrobaeza Maybe there are some other issue to fix.
![cattura](https://cloud.githubusercontent.com/assets/4042055/19132922/20b2417c-8b56-11e6-8dbb-924698b231b1.PNG)

This is a test from a blank installation with sample data. With a blank db I get the same result.
Where I can investigate?

**Comment by pedrobaeza** [comment]
No if you installed the mentioned module.

**Comment by burnout75** [comment]
This is the modules installed in the blank db:
product_variants_no_automatic_creation
sale_product_variants
sale_stock
sale_stock_product_variants
stock_product_variants
And in the checked option in sales setting is "Trigger delivery orders automatically from sales orders" (this install sale_stock)

Before to write I make the same test  sample data db and on a blank db too with same result.

Odoo and Wip modules installed are on the latest version.

**Comment by pedrobaeza** [comment]
Please try on runbot and you will see it's working: http://3155953-8-0-fd30e2.runbot1.odoo-community.org/web/login

**Comment by burnout75** [comment]
Thanks for your support.

Work on runbot.
Maybe something is wrong on installation but I didn't get any message during process.

If I check the sale.order.line db model and I didn't found sale_stock_product_variants in the list of moduls instead of runbot where is present:
![cattura](https://cloud.githubusercontent.com/assets/4042055/19134259/43755b8e-8b5d-11e6-822d-3d9009f9f174.PNG)

Folder and file ownership and permission are ok. There is some smart method to fix it?

**Comment by pedrobaeza** [comment]
It seems that he module is somehow not installed, but I can't say more.

**Comment by burnout75** [comment]
Solved by a my semi-mistake.
If you filter sale_stock_product_variants from Configuration -> Apps the system retrive only one result from https://github.com/BADEP/addons.git#8.0 and, of course, is not the same.

I upload the right one manually and now it's work.

Need to change module name?

Thanks  @pedrobaeza  for your support again.
