### ISSUE TITLE
[9.0] migrating 'procurement_service'

### ISSUE THREAD

**Issue by damdam-s** [odoomrp/odoomrp-wip#1350]
Hi there,

https://github.com/odoomrp/odoomrp-wip/tree/9.0/procurement_service

I plan to migrate this module to V9 but don't know what's your plans.
Do you mean to keep this module here or let it land on OCA repo ?

@pedrobaeza What do you prefer ?

Any advice welcomed :smile: 

Thanks

**Comment by pedrobaeza** [comment]
I prefer to move it to OCA, of course. The repo can be purchase-workflow, as it creates indirectly purchase orders.
