### ISSUE TITLE
[8.0][purchase_landed_cost] Generate accounting entries on action_done

### ISSUE THREAD

**Issue by livingmine** [odoomrp/odoomrp-wip#1361]
Are there any reasons why this module does not post the result of cost distribution as an accounting entry to the desired journal? My observation is, the stock_landed_cost module does this but leads to an extra entry when we pay the invoice of the landed cost i.e., "Freight Cost". On the opposite, this module rely only on the generated entry of the landed cost from supplier invoice, which i think it's the way to go. However, i think this module is missing the way to split the cost to different account, which i think it's not really hard to implement as it has already the cost computation when the calculate button is pressed.

IMO, if this functionality is enabled, moving the balance from landed cost account to each inventory account balance is going to be possible. Anyway, i'm not coming from an accounting background, but i think it's a logical thing to do as the company can have a detailed inventory account value to the product or product category level, and have them increased as the balance from the landed cost is transferred to each of those accounts.

**Comment by pedrobaeza** [comment]
It hasn't been implemented as it's not a requirement from none of our customers, so if you want to develop it, it will be welcome.

**Comment by livingmine** [comment]
Great! I'm curious on how you provide the solutions to the customers who want to know the profit/loss down to the level of product or product category. The only way i can think of know is to account revenue/cost to the level of product or product category and that's why i need to account landed cost down to that level. Are there any other solutions to solve this problem hence the reason this functionality has not been implemented yet?

**Comment by pedrobaeza** [comment]
They are simply using average price for their calculations.
