### ISSUE TITLE
  field "Manufacturer", Machine" and "Operation" - Material" are not editable

### ISSUE THREAD

**Issue by lappy123** [odoomrp/odoomrp-wip#1383]
please help
I couldnt see the editable box to put details for the above subjected heading.
![capture](https://user-images.githubusercontent.com/29672089/27506790-653d610a-58c9-11e7-9e99-c35eeba199e1.PNG)

**Comment by Daniel-CA** [comment]
You are not  correctly using the module, preventive operations are created from the assistant.
