### ISSUE TITLE
Volver a hacer PR de partner_risk

### ISSUE THREAD

**Issue by pedrobaeza** [odoomrp/odoomrp-wip#139]
@Daniel-CA, necesito que vuelvas a hacer el PR de partner_risk, ya que como estaba vinculado a la rama master, ahora no puedo acceder a él.

**Comment by Daniel-CA** [comment]
Actualizando el módulo a la nueva API, en cuanto esté hago un PR.

**Comment by oihane** [comment]
PR #152
