### ISSUE TITLE
11.0 branch

### ISSUE THREAD

**Issue by OpenCode** [odoomrp/odoomrp-wip#1406]
I need to port https://github.com/odoomrp/odoomrp-wip/tree/8.0/sale_order_line_dates to Odoo 11.0. It's possibile to have the branch 11.0? Thank you.

**Comment by pedrobaeza** [comment]
Better to move it to OCA

**Comment by pedrobaeza** [comment]
I think that there's now an OCA one for the same purpose...

**Comment by OpenCode** [comment]
@pedrobaeza this one https://github.com/OCA/sale-workflow/tree/8.0/sale_order_line_date?

**Comment by pedrobaeza** [comment]
Yeah, it seems so.

**Comment by OpenCode** [comment]
Ok. Thanks.
