### ISSUE TITLE
Is this project closed?

### ISSUE THREAD

**Issue by ska-ibees** [odoomrp/odoomrp-wip#1422]
Hi all,
I wanted to accomplish custom product manufacturing. mrp_product_variants module seems what i want. But it is not available for V11. 
Is this project closed or moved to somewhere else?

@pedrobaeza  Could you please advise? Thanks.

Regards

**Comment by pedrobaeza** [comment]
variant modules have been moved to OCA/product-variant and renamed, being the main one `product_variant_configurator`. For mrp, there's still not migration done, only this attempt in https://github.com/OCA/product-variant/pull/126

**Comment by ska-ibees** [comment]
Thanks for the response. Is there any documentation available?
As shown here https://www.youtube.com/watch?v=D8mUZ9hT7hE 
I am in a need to dynamically assign raw material based on product attributes. Is it possible with so far migrated modules at OCA/product-variant ?

Thanks again.

**Comment by pedrobaeza** [comment]
Sorry, but I don't know that PR. You should check by yourself.

**Comment by pedrobaeza** [comment]
@anajuaristi can tell you about another project for mrp variants any way.

**Comment by anajuaristi** [comment]
Yes
@mikelarre will update our https://github.com/avanzosc/mrp-addons with some modules we are working on. 
Not only migrating but refactoring. 
Most of them (wip) are still located on this branch
https://github.com/avanzosc/mrp-addons/tree/mikelarre-patch-1

**Comment by ska-ibees** [comment]
@pedrobaeza Thanks for the escalation to the concerned team.
@anajuaristi Thanks for the prompt response.
@mikelarre Can you please confirm ETA as when these modules will be available for V11?

I am struggling hard to accomplish an implementation where each manufacturing order is unique and custom products need to be produced each time. 
(Demo of MO with customize-able raw material (Concept of Templates for BoM and Products) as shown in this video looks promising... https://www.youtube.com/watch?v=D8mUZ9hT7hE )

Would appreciate if you please list names of modules that should be used to attain it.
Thanks again!

**Comment by SalahAdDin** [comment]
@go4site My PR is just for BoM: it enables to you to use the product configuration on Bill of Materials creation.
