### ISSUE TITLE
Tarifas de compra

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#146]
Copio pego la descripción de la tarea, en mi caso solo me aplica el punto 2.
Aun que en la tarea pone cargar tarifas, Ana definió que era una carga de precios de proveedor por lo que de momento está definido para que actualice los precios de los productos con los datos del archivo, si hay que enlazarlo con algún otro módulo a la hora de procesar las lineas expandir la definición aquí.
1. Módulo de extensión de tarifas en review. Ha sido migrado
2. Migrar  módulo de carga de tarifas de proveedor fichero base: Código producto,  descripción, precio, descuento1, descuento2, PVP, PDV1, PDV2. Coger módulo base muestra 6.1 --> Rama Avanzosc 6.1. Preguntar a Dani, coger el más genérico. Hay varias versiones del mismo módulo.
   1.    Automatismo de incremento de precio, no haría falta ya que se puede utilizar la carga para incrementar
   2.  Histórico de precios, módulo desarrollado en otra tarea. 

Oihane, mirar solo el punto 2. El resto están cerrados.

**Comment by anajuaristi** [comment]
@Daniel-CA Pregunta... ¿Como puede procesar el módulo de carga 4 precios diferentes, si en la ficha de producto hay solo 1 precio? 
Por otro lado, ¿como puede procesar correctamente, siendo precios de proveedor, si no aparece el proveedor por ningún sitio? ¿Qué hace el módulo? ¿Qué campo/s modifica?

Los precios de proveedor están en product.supplier.info ¿como esto lo puede hacer bien si no hay proveedor?

**Comment by Daniel-CA** [comment]
He añadido un campo para elegir el proveedor al que pertenece el archivo para que al procesar se asignen directamente y no desde el archivo.
El resto de precios no los he tratado ya que no se exactamente que hacer con ellos, se pueden añadir diferentes lineas de precios según cantidades, pero también deberían reflejarse en el archivo las cantidades, no se, lo que mejor os parezca.

**Comment by Daniel-CA** [comment]
Merged módule product_pricelist_import #147. Cierro.
