### ISSUE TITLE
Quality control put valid dependencia con quality extension

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#153]
quality control put valid, debería ser totalmente aislado e independiente, solo dependiente de quality control. 
Es necesario quitar dependencia.
Quality control extension, más que extension debería ser renombrado a "muestras", ya que lo que hace es crear N bloques de preguntas dentro de un test, en vez de una única, para el número de muestras epsecificado en la categoría o plantilla. 
2 tareas:
.-quitar dependencia
.- renombrar módulo quality extension  a lo que querais.

**Comment by pedrobaeza** [comment]
_quality_control_samples_ sería lo suyo.

**Comment by anajuaristi** [comment]
Quality_control_extension genera un bug/traceback al calcular datos de una orden de producción
Shows not found

**Comment by anajuaristi** [comment]
@alfredoavanzosc 
Me comentaste que esto estaba arreglado no? Si es así, porfa, indica PR en el que se subió el parche y cierra issue.

**Comment by alfredoavanzosc** [comment]
quality_control_samples en PR odoomrp-quality_control_samples
quality_control_put_valid en PR odoomrp-quality_control_put_valid

Yo no puedo cerrar el issue.
