### ISSUE TITLE
Asegurar en una ruta que existe una operación con check descarga

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#154]
Al asignar una ruta en una LM, verificar que la ruta tiene una operación con el check descarga marcado. Si no tiene --> Mostrar warning al usuario "ruta incorrecta: no tiene operación para producir"
Esto impedirá que se creen OFs sobre esta LM, que no tengan operación de "producir". 
@pedrobaeza valida
Si lo hacemos al grabar la ruta, mal, porque habrá un warning dando la lata al usuario. Hasta que se asigna la ruta a la LM, pueden estar montando la ruta pero no va a ningún lado. Si hacemos la verificación al asignar a la LM, queda bien y no molesta demasiado.

**Comment by pedrobaeza** [comment]
No me termina de convencer, porque tras asignar la ruta a la LdM, puede ser que cambies la ruta y se quite la operación de producción. La única opción segura es cuando se confirme la orden de producción, que ya ha volcado los datos de operaciones ( y se supone que el check debe estar también incorporado en esa copia de las operaciones). Entonces es donde se debe bloquear la producción si no hay ninguna operación con check.

Por cierto, ¿se hace una copia de las operaciones en la orden de producción, ¿no?

**Comment by anajuaristi** [comment]
Esto ya está también... 
El warning está causando problemas, ya que si por algún motivo la LM o la ruta no están bien configuradas para el producto, el scheduler al intentar confirmar la orden, no puede y falla. 
Esto se arreglará cuando se termine el tema de interceptar la confirmación de la OF de forma automática por lo que por mi parte :+1: y cierro issue
