### ISSUE TITLE
sale_variants (recálculo de precio en línea de pedido al seleccionar variantes)

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#156]
Al grabar la línea, una vez seleccionadas las variantes en el configurador, o bien con el botón recalcular precios, se debería tener en cuenta el incremento/decremento del precio variante. 
Actualmente no lo tiene en cuenta.

**Comment by oihane** [comment]
Cuando selecciona una variante (`product.product`) si esta tiene precio en la línea lo pone

y en el modo edición en el pedido de venta junto al TOTAL hay un enlace/botón `(actualizar)` que recalcula el valor de todas las líneas. También se ejecuta esto al guardar el pedido.

No entiendo a que te refieres

**Comment by anajuaristi** [comment]
En una plantilla hay un precio base y se permite un incremento/decremento de precio por variante. 
En la plantilla, hay un acceso al lado del árbol de productos específicos, a una tabla donde se pueden marcar esos incrementos decrementos.
Al crear productos específicos, el sistema tiene en cuenta estos incrementos/decrementos cuando se lleva el producto a la línea de venta, pero el configurador cuando seleccionamos template y opciones no. 
Actualizar precios, debería sumar precio base +-incremento por variante y asignar ese precio en cada línea, aunque no haya producto específico en ella. Si no, el comercial no tiene ni idea del precio correcto que tiene que dar para un producto con esas opciones.
Una posible mejora "visual" podría ser que al meter un valor de variante, en la tabla del configurador se muestre el precio que se aplicará, bien related, bien con campo si lo queremos hacer modificable (esto no lo han pedido, se me ocurre a mí ahora)

**Comment by oihane** [comment]
Creo que esto ya lo tienes para probar @anajuaristi

**Comment by anajuaristi** [comment]
Probado que:
1. Actualiza el precio variante directamente al asignar variantes en la línea
2. Cambiando tarifa en pedido, recalculate también calcula correcto en las líneas. 
Por mi parte :+1: cierro issue
