### ISSUE TITLE
[project_events_operations]

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#183]
Es un **warning** que muestra en el _log_

```
INFO openerp_template openerp.modules.loading: loading project_events_operations/wizard/events_date_modify_view.xml
WARNING openerp_template openerp.models: ir.actions.act_window.create() with unknown fields: key2
```

**Comment by pedrobaeza** [comment]
Sería quitar esa clave de la llamada.

**Comment by pedrobaeza** [comment]
¿Por qué lo cierras?

**Comment by oihane** [comment]
porque he quitado el key2

**Comment by pedrobaeza** [comment]
Vale, pues pon en el issue para histórico: resuelto en commit tal.

**Comment by oihane** [comment]
Solved on https://github.com/odoomrp/odoomrp-wip/commit/96565a39a04c7ff3c6cd5fcf0275d0bbf3409d23
