### ISSUE TITLE
product_manufacturer

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#184]
En la última sesión se vio la necesidad de un módulo que permita gestionar fabricantes de producto.
En versiones anteriores teniamos:
https://www.odoo.com/apps/product_manufacturer/
y
https://www.odoo.com/apps/7.0/product_brand/

El primero era oficial y el otro de comunidad. No encuentro en la instalación ninguno de los 2. Sería necesario incluir uno de ellos en la instalación.

**Comment by pedrobaeza** [comment]
El primero se ha eliminado de la distribución oficial, aunque lo único que hacía era colocar tres campos más en el producto. ¿Es eso lo que se quiere? ¿No puede ser más interesante manejarlo con etiquetas?

**Comment by anajuaristi** [comment]
Es que la etiqueta es algo tan genérico que luego no se puede operar con ella.
Necesitan el fabricante como tal porque posteriormente quieren usarlo en la homologación de productos (tener productos homologados para un fabricante y no para otro, para evitar comprarlo a ese, o indicar expresamente al proveedor que no quieren un producto de dicho fabricante. Hay paises que dan muy poca calidad y a veces les meten gato por liebre y es lo que quieren evitar)
Además PLSR, utilizará esto también en un específico, para calcular lo que viene de Austria y lo que viene de España. 
Voto por migrar el módulo standar.

**Comment by pedrobaeza** [comment]
Las etiquetas hacen el mismo funcionamiento que ese campo, porque ten en cuenta que ahora mismo la equivalencia es 1 producto = 1 fabricante con el módulo de la v7. No puedes establecer más de un fabricante, por lo que la funcionalidad de la homologación no se podría realizar de esa forma, pero ya hablamos que, por lo menos en DMC, se hacía por proveedor, que venía a ser equivalente para ellos.

**Comment by anajuaristi** [comment]
A mi no me gustan las etiquetas para estas cosas por ser demasiado genéricas.
¿Porqué no migrar manufacturers cambiando el many2one por un many2many contra fabricantes?

**Comment by anajuaristi** [comment]
@pedrobaeza Al final qué hacemos con esto? Migramos manufacturers o brand y lo mejoramos?

**Comment by pedrobaeza** [comment]
Como te dije por el chat, dime los requisitos de cliente y te digo cuál es la mejor opción.

**Comment by anajuaristi** [comment]
Requerimientos en CLM0080: Falta template y origen fabricante en homologación de proveedores. Te he enviado comentario. Cualquiera de las 2 opciones o hacer una tabla nueva valdría.

**Comment by pedrobaeza** [comment]
Ver https://github.com/OCA/product-attribute/pull/29

**Comment by anajuaristi** [comment]
¿Lo ponemos disponible en entorno demo para testeo funcional?

**Comment by pedrobaeza** [comment]
Tiene poco que probar, porque son tres campos en la ficha de producto, y luego una tabla de atributos que no tiene mucho sentido y que colisiona con el estándar, así que de momento no se puede instalar.

**Comment by pedrobaeza** [comment]
Esto habría que implementarlo entonces cambiando el enfoque many2one a many2many para producto > fabricante, y luego incluir ese fabricante en la línea del pedido de compra para validarlo contra las líneas de homologación.

**Comment by anajuaristi** [comment]
Esto, al final quedó en que cada EAN era un fabricante por lo que no aplicaba many2many. 
Creo que product_manufacturer ya ha sido migrado a V8 y está disponible en esta rama
https://github.com/OCA/product-attribute
@oihane en principio, si ponemos disponible el módulo en demo, lo probamos y si va... cerramos issue please.

**Comment by oihane** [comment]
Ups, lo he instalado en demo_noviembre2

**Comment by anajuaristi** [comment]
Pues bien... ¿Donde pues si no?

**Comment by oihane** [comment]
Te la quería solo poner disponible, no instalada, por si acaso

**Comment by anajuaristi** [comment]
Ahhh...no pasa nada.La tenía que instalar yo.
Cierro Issue entonces.
