### ISSUE TITLE
mrp_product_variants lo que falta para terminar

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#190]
Escribo lo que tenemos hasta ahora y lo que faltaría por hacer:

Cubrimos las siguientes casuisticas en el BOM: (BOM, ya está terminado)
BOM tipo NORMAL con líneas tipo NORMAL
1. Producto final específico (product_id) contiene componentes específicos (product_id) --> ESTANDAR ODOO
2. Producto final genérico (template_id) contiene componentes específicos (product_id) --> ESTANDAR ODOO
3. Producto final genérico (template_id) contiene componentes genéricos (template_id) --> OdooMRP

---

Casuística en OF (Líneas de componente en bom siendo de tipo Normal)
1. Se lanza producción por un product_id asociado a un bom específico --> Standar Odoo
2. Se lanza producción por un template_id que SOLO contiene products_específicos --> Standar Odoo (en principio, la selección de componentes se haría mediante las variantes del producto final y todos los productos específicos se meterían en el bom, indicando en el campo variante (de la derecha) la lista de variantes que definen ese producto específico, según el padre.
3. Se lanza producción por un template_id que contiene a su vez template_ids en sus componentes
A) Se muestra el configurador de producto en cabecera, para seleccionar los valores del padre (está hecho)
B) En la solapa productos planificados, al pulsar botón "calcular datos" (bom_explode) 
.- Si el producto de la línea del bom es product_id --> Funcionalidad estandar
.- Si es template_id: 
        \* Se carga en la línea el configurador y se intentan rellenar todos los valores posibles según hereda_de y valor por defecto cogidos de la configuración del propio atributo
        \* Al finalizar, se intenta encontrar un componente product_id que cumple todos los atributos asignados
        \* Si existe se asigna a línea de componente planificado
        \* Si no existe, se dejan los valores asignados (los que se puedan) pero product_id en blanco

Una OF no se podrá lanzar hasta que todos los componentes planificados, tengan asignado un product_id específico.

---

BOM tipo NORMAL con líneas de componente tipo Phantom --> Cuyo producto llevará asociado una lista de materiales tipo SET

Casuística en OF (Líneas de componente en bom siendo de tipo Phantom)
,. Es exactamente igual que en los de tipo normal, lo único que el componente de la lista, debe sustituirse por todos los componentes de su lista set, aplicando lo comentado arriba a cada uno de esos componentes. 
Es como si el producto phantom no existiese y se sustituya por los componentes definidos en su lista de materiales. 
Cuidado que esto puede ser recursivo, ya que una lista set puede a su vez llevar componentes phantom .
Cada componente phantom de una lista, sea esta de un template, o de un product, debe ser sustituida por sus componentes y estos ser añadidos al tratamiento normal, como si hubiesen estado en el bom original. El tratamiento a realizar a cada uno es exactamente el mismo que haríamos si estuviese cada uno de ellos en la lista original. 
Problema: El bom_explode original solo tiene en cuenta product_id para hacer la sustitución y no template_id. Según hemos visto esta tarde va a estar complicado utilizar la herencia y habrá que reescribir el bom_explode @pedrobaeza validar esto, a ver si se puede hacer de forma limpia, sin tener que reescribirlo.

**Comment by pedrobaeza** [comment]
Anoto aquí las cosas raras que he visto examinando el módulo más a fondo para rematarlo:
- En _mrp.production_, sigue habiendo dos onchange que buscan el product_id con código propio. ¿No se puede llamar a la función que hemos creado?
- Los domains que hay a nivel de mrp.bom.line son para los valores de los atributos, pero todos ahí como un batiburrillo, sin saber para qué atributo son. ¿Qué pasaría también si dos atributos tuvieran el mismo valor como posibilidad?
- Hay varios métodos en el que escribes hasta 5 veces valores en un registro. Recuerda que para esos casos, se hacen 5 consultas diferentes. Júntalos en un diccionario y haces al final un write para optimizar rendimiento.
- En _mrp.bom.line_, tienes un onchange nuevo a product_id que escribe product_template, y un onchange nuevo para product_template que modifica los atributos y puede llegar a modificar el product_id. Tienes que comprobar que no se cree un bucle infinito. ¿Hace falta el onchange del product_id?

**Comment by oihane** [comment]
1.- Si te refieres a la función `_product_find()` si, pero aún no lo había cambiado
2.- Si no me equivoco esos valores son del producto o variable de producto de la cabecera, y si no se pone el dominio, podrías poner cualquiera que exista, haciendo que parte del BoM sea innecesaria.
3.- Si te refieres a que hago varias veces `self.loquesea = loquesea` entendía que ahora se hacia así.
4.- Hasta ahora no me ha dado en ningún caso el bucle infinito ya que se supone que el `product_id` que se seleccione estará limitado al `product_template` que ya se ha dado. Aunque creo que tengo que eliminar la parte del configurador de las líneas, cosa que pidió en un principio @anajuaristi pero luego dijo que no era necesario y no está accesible en la vista :wink:.

**Comment by oihane** [comment]
@pedrobaeza creo que lo que comentas ya está hecho en el PR #197

**Comment by anajuaristi** [comment]
Si. Hay que eliminar el configurador de las líneas de componentes del bom. Definitivamente no tienen sentido ahí.

**Comment by anajuaristi** [comment]
@pedrobaeza cierro issue porque toda la funcionalidad requerida ya se ha incluido en mrp_product_variants.
Solo falta una cosilla que levanto nuevo issue porque según dice @oihane lo estaría produciendo operations_extension.
https://github.com/odoomrp/odoomrp-wip/issues/394
Cuando en el BOM existe una línea con un producto tipo phantom, en la OF se sustituye correctamente el producto por sus componentes pero los componentes no quedan linkados a la operación especificada para su producto origen en el bom.
