### ISSUE TITLE
[sale_product_variants] accessed before being computed

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#191]
Como en las OF y lista de materiales:

```
Field sale.order.line.attribute.possible_values is accessed before being computed
```

Al abrir una línea que ya existe.

**Comment by pedrobaeza** [comment]
Sí, esto está pendiente de que se resuelva el siguiente bug en el core:

https://github.com/odoo/odoo/issues/3205

Si mientras tanto te impide trabajar, comenta la correspondiente línea del domain.

**Comment by pedrobaeza** [comment]
Ya está solucionado en a5a37d441b5647d0f67922f916aaaf490688b32e para sale_product_variants. Paso a aplicarlo al resto de módulos que utilizan el mismo sistema.

**Comment by anajuaristi** [comment]
Jo que biennnnnn!!! :+1:
