### ISSUE TITLE
Nueva versión de calcular datos en boms con template, se pierde id de workorder

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#204]
Buenas... 
Hemos visto que el botón calcular datos, que asigna a los materiales workorder_id, pierde esta función cuando instalamos mrp_variants. 
Creo que se está sobreeescribiendo la función.
Lo suyo sería, dejar que calcule, normal, como hace sin el módulo e iniciar luego el tratamiento de líneas con template y sin producto.

**Comment by oihane** [comment]
El calculo NORMAL intenta buscar por product_id con lo cual si existen líneas que no lo tienen da un casque, por ello se reescribió la función ya que no se encontró otra forma de darle salida

**Comment by pedrobaeza** [comment]
Habrá que encontrar una forma de convivir los dos módulos. Luego le doy una vuelta.

**Comment by anajuaristi** [comment]
Es muy muy sencillo, porque no impactan uno con el otro.
El que hace operation_extension hay que hacerlo sí o sí.

Y posteriormente, la función de Oihane hace el tratamiento para las variantes, no llamando al botón calcular, sino simplemente recorriendo las líneas que ha hecho el botón calcular. 

No me explico pero lo que quiero decir es:
función1: operation_extension que llama a calcular datos y lo sobreescribe, es correcto.
función2: calcular variantes: que recorre las líneas que ha creado la función anterior y las "retoca" asignando valores a las variantes y buscando el id de producto si le toca.

Al final calcular datos tiene que llamar en orden a función1 y función2... 
Función 2 sólo debe tener en cuenta el workorder_id, en el caso de que se esté tratando una línea "phantom" del bom en cuyo caso, deberá hacer una sustitución de la línea por todos los ids de todos los componentes, pero a todas las líneas que se traiga tendrá que asignarles el mismo workorder_id que tuviese su padre. Ni siquiera en ese caso impactan las variantes en la función1.

**Comment by pedrobaeza** [comment]
Ana, no es tan sencillo como tú lo ves, porque no te va a devolver líneas, pero bueno, déjame que lo vea y ya está.

**Comment by anajuaristi** [comment]
Ayyy... ya veo lo que quiere decir Oihane... ya... si... 
En todo caso... si el módulo del operation_extension tuviese en cuenta que el bom puede llevar template_ids y asignase el workorder correctamente, ya estaría resuelto para la función2, no?
Porque ahí estamos sobreescribiendo seguro. Y el campo template_id, no lo añadimos nosotros, está en el standar, por lo que podría consultar el operation extensions si la línea lleva template o lleva product... no?

**Comment by oihane** [comment]
Resuelto, cierro
