### ISSUE TITLE
Renombrar módulo y subir a wip

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#207]
Buenas... 
Necesito tener disponible en el entorno wip, el módulo production_download_operation de alm

@pedrobaeza propone cambiar el nombre a 
mrp_dump

**Comment by pedrobaeza** [comment]
Es muy importante que en la descripción explique perfectamente qué hace y a qué tipo de industrias va dirigido.

**Comment by oihane** [comment]
Se ha cambiado e módulo de alm a wip, y se ha renombrado la carpeta (nombre técnico) a **mrp_dump**
La descripción no la he cambiado, pero no sabemos cual sería el **tipo de industria** a la que va dirigido

**Comment by anajuaristi** [comment]
Enfocado a industrias químicas, que realicen envasado de granel.

**Comment by mikelarre** [comment]
Para la descripción de mrp_dump

This module provides an association between the bulk product and the way it must be packaged at the end of the bulk product manufacturing.

**Comment by pedrobaeza** [comment]
Muy bien, me gusta la descripción. Añade luego: "Particularly suitable for chemical industries and others that produce liquid finished products." y marchando

**Comment by oihane** [comment]
PR #216

**Comment by anajuaristi** [comment]
No es por tocar las narices, pero creo que quedaría mejor "... that produce liquid bottled / packed products" 
;P

**Comment by pedrobaeza** [comment]
Sí, cierto, lo ponemos así.
