### ISSUE TITLE
  Edit New issue [FIX quality_control_between_dates] #206

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#217]
Si instalo este módulo e intento hacer uso de él metiendo fechas en las plantillas no se puede grabar. 
Da un warning que no se pueden meter 2 preguntas iguales en la misma fecha y es correcto pero el tema es que las 2 preguntas que estoy metiendo no son iguales.
Solo contempla las fechas y no la pregunta. 
Por tanto, he desinstalado el módulo.

**Comment by pedrobaeza** [comment]
Ana, acabo de probar y funciona perfectamente. Lo que no me gusta nada es el aspecto del módulo. Teníamos que haber partido del que yo hice para v7. Es más, estoy por cambiarlo, porque de verdad, ¡¡¿qué es eso de tener que definir una unidad de medida para poner una pregunta cualitativa?!! O los sinónimos que no valen para nada. O el tipo genérico o relacionado, que tampoco...

**Comment by anajuaristi** [comment]
En demo? pues esta mañana he tenido que desinstalar el módulo porque todo el rato me daba el warning. Debe ser que no estaba actualizado

En lo de que sobran campos tienes razón. Pero se migró el básico en su momento. Se quitan esos campos y marchando como dices, no? El resto de extensiones ya funcionan bien con esta versión.

**Comment by pedrobaeza** [comment]
No es sólo eso. También es un cambio de concepción de muchas cosas. Lo estudio y veo, porque al final la ventaja que me decías de los samples y demás se han puesto como módulos aparte.

Lo acabo de probar en local, no en demo, aunque se me acaba de ocurrir la razón y por eso no lo veías. Ya hay otra plantilla que tenga esa fecha para esa pregunta. ¿Esa condición debe ser así? Ahora lo pienso y te digo.

**Comment by pedrobaeza** [comment]
Sí, efectivamente es por eso. Habría que limitar la condición a la misma plantilla.

**Comment by pedrobaeza** [comment]
Reparado. No me gustan nada tampoco las pantallas definidas...

**Comment by anajuaristi** [comment]
@pedrobaeza 
Cuidado con el cambio de concepción. La funcionalidad del módulo ha sido validada por los clientes. Me parece correcto elimiinar los campos que has mencionado y que están de sobra pero el resto es correcto.
En cuanto a los campos que añade el samples, no quites ninguno que luego se usan en otros sitios, para mostrar one2manys en diversos puntos de la fabricación, albaranes y demás... 

Las pantallas están bien, ¿qué ves que no te guste? Hay cabecera y líneas. Está correcto.

**Comment by pedrobaeza** [comment]
No voy a cambiar de concepción, pero si de los nombres de variables (que la pregunta sea proof_id...). Las pantallas están feísimas, y es por la manía de seguir utilizando colspan y compañía.
