### ISSUE TITLE
product_last_price_info: La vista no se muestra.

### ISSUE THREAD

**Issue by Bilbonet** [odoomrp/odoomrp-wip#218]
Creo que hay algún problema en la vista "product_last_price_info / views / product_view.xml".
No se me muestra en la ficha del articulo. Todo lo demás me funciona bien.

Tengo poca experiencia con Odoo y no he conseguido ver el problema. Pero pongo un par de cosas que no entiendo por si ayuda.
1. Hay una etiqueta <data></data> en medio de la definición de la vista que no se si es para algo.
2. Todas las vistas que he visto en Odoo y heredan de la vista "product.product_template_form_view" utilizan el modelo [product.template]. Mientras que esta utiliza el modelo [product.product]. No se si esto se puede hacer?

Salu2.

**Comment by anajuaristi** [comment]
Los últimos precios aplican al producto en sí, no a la plantilla. 
Ve a la solapa variants y en el arbolito pequeño que aparece a la derecha del todo, navega al producto. La solapa está ahí.
No tendría sentido mostrar últimos precios en una plantilla ya que de ella pueden surgir N variantes y cada una es un producto específico. 
Gracias por reportarlo.

**Comment by Bilbonet** [comment]
Correcto :+1:  
Tus comentarios me han aclarado cosas que desconocía.
Gracias a ti.
