### ISSUE TITLE
sale_delivery_date duplicates standard feature

### ISSUE THREAD

**Issue by clonedagain** [odoomrp/odoomrp-wip#219]
From a quick glance at the code, I think the features of https://github.com/odoomrp/odoomrp-wip/tree/8.0/sale_delivery_date are already implemented in https://github.com/odoo/odoo/tree/8.0/addons/sale_order_dates.
I humbly suggest you migrate to the standard module, and maybe propose improvements to it if they are needed.

**Comment by pedrobaeza** [comment]
Thanks for the tip, Lionel. I will take a look and tell you, because I don't have now in mind the reason why we made it, but I think it's because a change in that module.

**Comment by clonedagain** [comment]
I hope so - I tried to push most community requirements upstream for a 
long time and it finally landed in v8.

**Comment by oihane** [comment]
We need those fields just for filling them with some info, no calculation is required, that's why we created this module.

**Comment by pedrobaeza** [comment]
@oihane, maybe _sale_order_dates_ standard module adds several of these fields, and you can only need to add the dependency. Can you check it?

**Comment by anajuaristi** [comment]
I don't think so.
Standar module is adding 3 data fields on sale order. All of them are
calculated depending on several parameters we don't really need.

I think is much easier, just install our module including 2 fields,
calculating nothing as demanded from our customers than trying to reuse and
inherit an standar module that we will need to touch anyway...
Customer could decide using standar or using ours or using both...

2014-10-30 11:53 GMT+01:00 Pedro M. Baeza notifications@github.com:

> @oihane https://github.com/oihane, maybe _sale_order_dates_ standard
> module adds several of these fields, and you can only need to add the
> dependency. Can you check it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/219#issuecomment-61074197.

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com soporte@avanzosc.com *

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
*_administracion@avanzosc.com
soporte@avanzosc.com *
_This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
soporte@avanzosc.com_

**Comment by oihane** [comment]
_sale_delivery_date_ creates three fields on sale.order, only one of them is of datetime type, others are functions. Maybe we can use this, but not sure if it will cause any problem in our other module.

**Comment by anajuaristi** [comment]
Revisado :+1: Cierro issue
