### ISSUE TITLE
[QUESTION] <project_events_copy> vs. <project_events_operations>

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#223]
Los modulos:
- project_events_copy
- project_events_operations

tiene la misma función de copiar, parece que el `_operations` es una extensión del `_copy`. Además tenemos un modulo en https://github.com/avanzosc/avanzosc que se llama `project_events` que creo que deberían usar como dependencia... cuando puedas lo revisas please @pedrobaeza

**Comment by pedrobaeza** [comment]
Respondido por chat.

**Comment by oihane** [comment]
No esto no me dijiste nada definitivo. Si dependen de ese modulo hay que pasarlos a la rama de avanzosc, pero el caso es que parece que el operations integra el copy

**Comment by pedrobaeza** [comment]
Te dije que los pasaras a la rama Avanzosc, eso es, y que uno es una extensión del otro.

**Comment by oihane** [comment]
El copy copia eventos
el operations, tiene la opcion de copiar eventos

**Comment by pedrobaeza** [comment]
Ya, pero los copiaba de forma distinta. No le demos muchas más vueltas y ya está. Son módulos accesorios.
