### ISSUE TITLE
Fechas de caducidad, constraint < en vez de <=

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#225]
En fechas de caducidad de los lotes, se ha incluido un constraint que no permite guardar el lote con las 4 fechas iguales
Field(s) `alert_date, removal_date, use_date, life_date` failed against a constraint: Dates must be: Alert Date < Removal Date< Best Before Date < Expiry Date

Hay que poner <= que el anterior, ya que si no, obliga a cambiar y es un follón. Pueden existir productos que se quiera controlar una única fecha y por tanto se ponga la misma en las cuatro, o 2 iguales, o lo que sea...

**Comment by anajuaristi** [comment]
No es <=, sino que los campos a rellenar en la ficha de producto están al revés... 
Hay que poner 120, 90, 60 y 30, en vez de 30, 60, 90. 120... 

No hay bug.. 

Ahora bien, en el lote, los campos están bastante desordenados. 
Habría que poner el form product_expiry.view_move_form_expiry así:

``` xml
<?xml version="1.0"?>
<xpath expr="//group[@name='main_group']" position="after">
                <group string="Dates">
                    <group>
                        <field name="alert_date"/>
                         <field name="removal_date"/>
                    </group>
                    <group>
                        <field name="use_date"/>
                        <field name="life_date"/>
                    </group>
                </group>
            </xpath> 
```

**Comment by oihane** [comment]
Related to #103

**Comment by oihane** [comment]
El módulo que dices de cambiar la vista no es el nuestro si no el de odoo

**Comment by anajuaristi** [comment]
Si. La vista estandar. Estan desordenados y no se entiende

**Comment by oihane** [comment]
PR #230
