### ISSUE TITLE
Añadir posibilidad de realizar asignación de lote manualmente en stock moves

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#227]
Se solicita poder realizar manualmente la asignación de un quant. 
Para ello, desde un movimiento de stock, se podrá lanzar un wizard que muestre los quants disponibles para ese producto, en la ubicación origen del movimiento y un check de selección
Domain: Quants filtrados por:
.- Producto del movimiento
.- Ubicación del quant = ubicación origen del movimiento o hija de ubicación origen del movimiento
.- No asignados
.- Con cantidad > 0

El usuario marcará manualmente los check que quiera (incluir "seleccionar todos") en la cabecera de la tabla y al pulsar confirmar, asignará los quants seleccionados al movimiento.

Validación a realizar antes de la asignación: La cantidad sumatorio de todas las unidades seleccionadas por el usuario deberá ser <= a la cantidad de producto indicada en el movimiento, en otro caso, mostrar warning: Cantidad seleccionada supera la requerida. 

@pedrobaeza validar enfoque

**Comment by pedrobaeza** [comment]
Tal como hemos dicho, no sería ubicación del quant igual a la del movimiento, sino ubicación del quant hija de ubicación origen del movimiento.

La validación de la cantidad total se hace en el propio asistente, no luego cuando la asignación, ya que una vez salgamos del asistente no podremos modificar esa lista.

**Comment by anajuaristi** [comment]
Me refería al pulsar el botón confirmar en el asistente (antes de la asignación) pero sí, estamos diciendo lo mismo.
Modifico lo de la ubicación. 
Listo para inciiar desarrollo
