### ISSUE TITLE
Visualizar fecha límite en tree de reclamaciones

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#229]
En reclamaciones se visualiza la fecha de creación pero no la fecha límite.
Se solicta hacer visible la fecha límite y meter agrupación por fecha límite en listado de reclamaciones.

**Comment by pedrobaeza** [comment]
Nota off-topic: En la v9 han metido el poder agrupar por cualquier campo, al igual que ya se hacía desde hace mucho con buscar por cualquier campo. ¡Por fin! No es fácil hacer un backport, pero dan ganas de ello. De esa forma, no haría falta estas solicitudes.

**Comment by oihane** [comment]
La agrupación por fecha límite ya existe
