### ISSUE TITLE
product_last_price_info should change data only when PO are approved

### ISSUE THREAD

**Issue by clonedagain** [odoomrp/odoomrp-wip#235]
Currently product_last_price_info changes the last purchase price and supplier as soon as you confirm the purchase, but it the supplier could refuse it or impose different prices.
It would be best to change only when the state is "aproved".

**Comment by pedrobaeza** [comment]
You are right.

@mikelarre, ¿puedes cambiar lo que dice Lionel? El flujo que tú has probado es sin pasar por aprobación, pero en muchos sitios se utiliza una aprobación intermedia. Para ello, tienes que marcar una opción en Configuración > Compras. Pruébalo y haces un PR con el cambio.

**Comment by anajuaristi** [comment]
Depende de si hay o no ese estado en el pedido.
Si al confirmar va a pasar a validación es correcto lo que dice Lionel.
Pero si no es necesario que pase por ahí, tiene que llevarse el precio en
la propia confirmación.

El 28 de octubre de 2014, 19:15, Pedro M. Baeza notifications@github.com
escribió:

> You are right.
> 
> @mikelarre https://github.com/mikelarre, ¿puedes cambiar lo que dice
> Lionel? El flujo que tú has probado es sin pasar por aprobación, pero en
> muchos sitios se utiliza una aprobación intermedia. Para ello, tienes que
> marcar una opción en Configuración > Compras. Pruébalo y haces un PR con el
> cambio.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/235#issuecomment-60804165.

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com soporte@avanzosc.com *

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
*_administracion@avanzosc.com
soporte@avanzosc.com *
_This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
soporte@avanzosc.com_

**Comment by pedrobaeza** [comment]
Ana, pero si no hay aprobación, también pasa por el mismo método. Entonces se puede poner en un solo sitio y que valga para los dos.

**Comment by oihane** [comment]
Change made, and PR merged, I close the issue
