### ISSUE TITLE
product_last_price_info overlaps with OCA's last_sale_price

### ISSUE THREAD

**Issue by clonedagain** [odoomrp/odoomrp-wip#238]
OCA has just adopted a module that does the sale part of product_last_price_info: 
   https://github.com/OCA/sale-workflow/tree/7.0/last_sale_price 
It does the job with function fields, which I think is a bit better than intercepting workflow changes because it immediately fills in the last prices on databases that are already populated, and updates the prices if an order is canceled.

To be consistent, I intend to write a module for purchases using the same technique, to compute the replenishment price (latest price from invoices or orders or quotations).

**Comment by oihane** [comment]
Thanks for the point @clonedagain. We will take a look, and let us know if you do the purchase part :wink:

**Comment by pedrobaeza** [comment]
See #321 for the work adapting standard module.

**Comment by oihane** [comment]
@pedrobaeza You are wrong the related issue fixed in #321 is #219

**Comment by pedrobaeza** [comment]
Sorry, I mispell the titles

**Comment by anajuaristi** [comment]
Entiendo que esto ya está arreglado con el merge de #336 por lo que cierro. :+1: 
@pedrobaeza si no es así, reopen
