### ISSUE TITLE
Traceback al iniciar orden de fabricación

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#244]
Ainara... 
Creo que es tu módulo de crear tareas desde fabricación (ejemplo en demo MO0062. Da un error Keycode, 

```
  File "/opt/odoo/v8/core/openerp/models.py", line 3965, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4103, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: ""duplicate key value violates unique constraint "project_task_unique_sequence"
DETAIL:  Key (code)=(T0007) already exists.
" while evaluating
u'action_start_working()'" while evaluating
u'action_in_production()'
```

**Comment by agaldona** [comment]
Resuelto en #251.

**Comment by oihane** [comment]
PR mergeado, cierro

**Comment by anajuaristi** [comment]
Si está resuelto en el PR que dice @agaldona , falta actualizar entorno ya que al iniciar una op de fabricación me ha vuelto a dar. (He verificado que el T0036 no existe en el entorno demo)

```
  File "/opt/odoo/v8/core/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3965, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4103, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "duplicate key value violates unique constraint "project_task_unique_sequence"
DETAIL:  Key (code)=(T0036) already exists.
" while evaluating
u'action_start_working()'
```

**Comment by agaldona** [comment]
@anajuaristi 
Acabo de iniciar la MO00062 y no me ha dado ningún error. ¿Estás segura que lo probaste en el entorno demo? Me dice @oihane, que ella no ha actualizado nada, por lo que entiendo que ayer seguía estando la misma versión que hoy arriba.
Si te sigue dando el error, especificame cual es la MO, por favor.
Eskerrik asko.

**Comment by anajuaristi** [comment]
inicio de OPERACION... o sea..WORKORDER, no la OF.

**Comment by agaldona** [comment]
@anajuaristi 
Acabo de iniciar una operación, y no me ha dado ningún problema tampoco. Dime cual es el que has intentado lanzar.

**Comment by anajuaristi** [comment]
Claroooo...porque desinstalé project_link para hacer pruebas. Instálalo...

**Comment by agaldona** [comment]
@anajuaristi  Ah vale, ya he visto. No está cogiendo la última versión, de hecho, incluso falta por cargar algunos campos que añadí en la última versión. Se lo he comentado a @oihane y me comenta que lo actualizará mañana a primera hora, ya que se ve que hay actividad en el servidor.

**Comment by oihane** [comment]
@agaldona puedes probar a ver si te permite hacer lo que debe, ya he actualizado esta mañana el server :wink:

**Comment by agaldona** [comment]
@oihane @anajuaristi 
Comprobado, he hecho un par de pruebas, el módulo mrp_project_link está instaldo y no da errores al iniciar una orden de fabricación, ni al inicial una workorder.
De todas formas, cuando puedas le echas un vistazo Ana.

**Comment by agaldona** [comment]
Creo que ahora si se puede cerrar, cualquier problema lo volvéis a abrir.
