### ISSUE TITLE
Odoomrp mrp production project estimated cost NUEVAS LINEAS de coste

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#247]
En los requerimientos, no está específicamente puestos en la tarea, pero los siguientes costes también deberían ser tenidos en cuenta como estimados:
.- Preparación de máquina:
En la ficha workcenter el campo Horas de preparación (pasado a entero) sería la cantidad de la línea
Los campos coste estimado, medio y demás... serían los del producto asociado a la preparación

.- Post producción de máquina:
En la ficha workcenter el campo Horas de post-producción (pasado a entero) sería la cantidad de la línea
Los campos coste estimado, medio y demás... serían los del producto asociado a la postproducción

El resto de campos de enlaces y demás... igual que en el resto de líneas. 

De momento, estos 2. No veo que nos falta ninguno más. Hay un pequeño lío con el estimado de los operadores, pero en principio, eso lo tengo que mirar/enfocar mejor.

**Comment by oihane** [comment]
#245

**Comment by pedrobaeza** [comment]
Tratar en otro PR distinto.

**Comment by alfredoavanzosc** [comment]
Realizardo, el nuevo issue es el 259.

**Comment by anajuaristi** [comment]
Realiza correctamente imputaciones pre y post producción en cada operación
Aunque no he probado con calculadora, a simple vista también veo que asigna correcto los precios y las cantidades en pre y post estimados, por lo que por mi parte
Probado  :+1:
Cierro issue
