### ISSUE TITLE
reparaciones cuando es No facturar

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#249]
El otro día detectamos unas cosas rarísimas cuando la reparación es NO facturar.

La cuestión es que cambia la tarifa y me pone una de distribuidor. O_o
Posteriormente, cuando vas a seleccionar un producto da un error de tarifa y no se puede añadir línea. 
No permite cambiar la tarifa porque es no editable. 
Si se pone como "a facturar" tanto antes como después de la reparación va bien.

No he probado en runbot. No sé si es que alguien ha puesto un default value en la tarifa o qué. Pero planta esa tarifa también en otros onchange... Descalabra todo el módulo de reparaciones. Habría que mirar si es sólo del entorno demo o se reproduce en más entornos.

**Comment by alfredoavanzosc** [comment]
Ana, yo he hecho una prueba en mi ordenador local, y he creado una reparación que es NO facturar, y no he tenido ningún problema de los que has tenido tu. Un saludo.

**Comment by anajuaristi** [comment]
Es muy curioso. 
¿Tienes una tarifa aparte de la pública que esté en el listado de tarifas por delante de la tarifa pública?
Porque he borrado la tarifa distribución, a saco y la siguiente que tengo es una en dólares tarifa 20% y ahora coge esa. 
Parece ser que si es no facturar, coge la primera tarifa de la lista de tarifas. Hasta que le pones el cliente. En ese caso, ya pone la tarifa correcta
También cuando se le pone "no facturar" permite añadir materiales pero no cargos por horas. No sé conceptualmente qué sentido tiene esto. 
@pedrobaeza ¿Qué hacemos? Es un bug? Simplemente se explica cómo está? 

Sabiéndolo, hay trucos. Pones la reparación para facturar, metes los cargos y luego le pones No facturar. Chapuza, pero lo hace bien
En cuanto a la tarifa, si es una reparación interna y no para cliente, sería poner como partner a la propia compañía. También es ir un poco por la calle de enmedio, pero ambos problemillas se pueden sortear de esa forma.

**Comment by anajuaristi** [comment]
@pedrobaeza ¿Qué hacemos? Cerramos esto dejándolo como está? Porque los problemas como digo en mi comentario anterior, se pueden sortear por configuración de la reparación. 
Ya dirás

**Comment by anajuaristi** [comment]
@pedrobaeza ¿Qué hacemos pues? Cierro directamente?

**Comment by pedrobaeza** [comment]
No lo cerremos. Vamos a darle una vuelta a nivel de core, y ponemos un issue con su PR para resolverlo vía warranty, y en OCB también podemos publicarlo.

**Comment by anajuaristi** [comment]
@pedrobaeza retomamos este tema, relacionado con otro issue que he abierto recientemente y asigno a @Daniel-CA

**Comment by anajuaristi** [comment]
Hecho. Cierro.
Si apareciese algo, ya lo reportamos en nuevo issue.
