### ISSUE TITLE
Listado extendido de trazabilidad-2

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#253]
Añado reclamación pendiente:

Necesitamos una gestión completa de la trazabilidad, es decir: 
- Para la trazabilidad hacia adelante, debemos conocer en que productos (acabados, intermedios, reprocesados, ...) ha intervenido una determinada materia prima y llegar hasta el detalle de los movimientos (documentos de venta, devoluciones, ...) de cada uno. 
- Para la trazabilidad hacia atrás, debemos conocer que materias primas han intervenido en la fabricación de un determinado producto (materia prima, producto intermedio, reprocesados, ...) y llegar hasta el detalle de los movimientos (documentos de entrada de dichas materias primas). 

Enfoque técnico: 
En el punto de "procesar" una orden de fabricación, al aceptar la pantalla donde se indican lotes de producto y de componentes, crear las líneas correspondientes en una nueva tabla con los siguientes campos:

Componente 
Nºlote componente 
Producto final 
Nºlote prod final 
Id orden de fabricación

---

Adicionalmente: 
En lotes, añadir botones "Trazabilidad total" --> Sacará un listado de todos los movimientos de stock, ordenados por fecha en los que el lote aparezca tanto en la parte izquierda como en la derecha de la tabla anteriormente creada. 

Permitir agrupar y filtrar el listado por tipo de picking, origen, fechas y otros campos tal cual se definió para movimientos de stock. De este listado puede obtenerse tanto la trazabilidad hacia atrás, como hacia adelante, simplemente filtrando por tipo de picking, ya que los pickings de recepción nos mostrarán el proveedor y el origen del material y los picking de salida nos mostrarán el cliente y el destino del material. 

Nota para Dani: 
De momento, el módulo que incluya sólo hacer la tabla e insertar el registro al pulsar el botón "aceptar" del wizard de "fabricar" en una orden de fabricación. El sistema solo tiene que crear línea en el caso de que el producto final sea trazable y solo para los componentes que sean trazables El informe de trazabilidad, lo haremos a posteriori, en otro módulo una vez funcione este.

**Comment by anajuaristi** [comment]
Pero que picking?en ese objeto no hay picking ninguno. Hay 5 campos y no has incluido ningun campo de busqueda ni agrupacion

**Comment by Daniel-CA** [comment]
Correcto, en el nuevo objeto no hay ninguna columna picking, por lo que entiendo que los filtros los querías en los movimientos (stock.move), pero me he fijado que los movimientos de producción no tienen ningún picking asignado por lo que el segundo parrafo del requerimiento no me queda claro:

"Permitir agrupar y filtrar el listado por tipo de picking, origen, fechas y otros campos tal cual se definió para movimientos de stock. De este listado puede obtenerse tanto la trazabilidad hacia atrás, como hacia adelante, simplemente filtrando por tipo de picking, ya que los pickings de recepción nos mostrarán el proveedor y el origen del material y los picking de salida nos mostrarán el cliente y el destino del material. "

Si a los filtros que te referías son añadirlos al nuevo objeto creado, no hay ningún problema.

**Comment by anajuaristi** [comment]
No te lies. Todavia no hemos empezado con el listado en si.
De base... Al Meter un menu sobre un objeto hay que poner busquedas y
agrupaciones

**Comment by Daniel-CA** [comment]
:+1:  Añado los filtros en el nuevo objeto.

**Comment by Daniel-CA** [comment]
Módulo añadido a la rama, cierro el issue.
