### ISSUE TITLE
Traceback estimated cost

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#257]
Pasos a seguir:
Definir un producto con abastecimiento contra pedido
Instalar Jit para la evaluación automática de abastecimientos
Indicar en el pedido una cuenta analítica
Confirmar --> La cuenta analítica no es arrastrada a la OF.

---

Hay varias cosas aquí: Si en el pedido de venta existen productos con abastecimiento a producir, contra pedido y el módulo de costes estimados de fabricación está instalado, la cuenta analítica en el pedido debería ser mandatory y arrastrarse a la OF. 

Por standar, al ejecutar un abastecimiento, si este crea una OF, el sistema lo confirma. IMHO esto es incorrecto. Esto debería ser exactamente igual que se hace con las órdenes de compra, que aunque son creadas nunca son confirmadas. Es un tema conceptual que debería ser revisado. ¿Realmente el sistema debe tomar la decisión de confirmar/lanzar una OF? Yo creo que no. En este caso, habría que "parar" la orden en su creación automática desde abastecimientos y no confirmarla, de tal forma que el botón confirmar será el que verifique si hay cuenta analítica o no en la OF y se podría poner en ese momento.

Otra concepción es que se deje tal cual y el sistema confirme Ofs, pero en este caso, se debería asignar una cuenta analítica por defecto en la OF (si viene de pedido y el campo está informado, está claro  que sería la que se informó en el pedido, pero si no está informada, podría ser la propia del producto que proporciona analytic defaults) 

@pedrobaeza verificar esto porfa, que es muy importante.  

En cualquier caso, lo dicho hasta el momento sería en la confirmación automática pero si se hace manual hay que capturar el traceback en un warning de aviso. Si al pulsar el botón confirmar OF no hay cuenta analítica y están instalados los módulos de costes de fabricación, hay que informar al usuario de que debe poner una y evitar el traceback. 

```
File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/mrp_production_project_estimated_cost/models/mrp_production.py", line 39, in action_confirm
    analytic_line_obj.create(vals)
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 3965, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/v8/core/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4103, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ValueError: "null value in column "account_id" violates not-null constraint
DETAIL:  Failing row contains (207, 2014-11-02 08:31:19.592516, null, 1, 2014-11-02 08:31:19.592516, 2014-11-02, 1, 1, MO00065-DMCEnvasado, 1, 0.00, 150, null, 1126, 11, null, null, 669, 1, null, null, null, null, null, 0.00, 0.00, 0.00, 0.00).
" while evaluating
u'action_confirm()'
```

**Comment by alfredoavanzosc** [comment]
He puesto el warning para que salte cuando no este definida una cuenta analítica en la OF. Esto esta comentado en un nuevo PR que solicitó Pedro que hiciera, el issue es https://github.com/odoomrp/odoomrp-wip/pull/259

**Comment by oihane** [comment]
Como el PR está aceptado cierro
