### ISSUE TITLE
Módulo carga Inventarios desde fichero CSV/ XLS

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#27]
Actualmente tenemos un módulo desarrollado para la 6.1 en el que definiendole un archivo csv te crea un inventario según los códigos de producto y cantidad.
Ahora teníamos pensado ampliarlo a archivos xls ademas de añadir un control en las lineas que se habían importado marcando las que se han importando correctamente y las que no.
Tenía pensado añadir un asistente para elegir el archivo y ampliar la vista de inventarios para que salga una nueva solapa al lado del "inventory Details" con el log de las lineas del archivo importadas.
Adicionalmente se puede añadir una 3 columna en el archivo que defina la ubicación del producto si es diferente a la que se define por defecto en el asistente.

**Comment by pedrobaeza** [comment]
No hace falta la compatibilidad con XLS. Cualquier paquete ofimático tiene exportación a CSV. Aunque es cierto que trabajar con el formato "nativo" ofrece ventajas, es complicar el desarrollo y obligar a utilizar una librería externa (xlwt o similar) para el parseo.

**Comment by pedrobaeza** [comment]
Por lo demás, adelante, pero debería ser al revés, que el asistente muestre y guarde en un archivo CSV las líneas NO importadas. Las importadas ya las verás en el propio inventario.

**Comment by Daniel-CA** [comment]
Bien, entonces se puede hacer que en el log salgan solo las lineas no importadas y que desde ahí mediante un botón de la opción de guardarlo en un nuevo archivo.

**Comment by anajuaristi** [comment]
Pedro, creo que Dani se refiere a las importadas desde el csv a la pantalla
de inventario.
Tenemos en 6.1 hecho una especie de modulo que podria ser generico (creo) y
que hemos utilizado en muchas cargas de datos diferentes para hacer
multiples cosas entre ellas primera carga de inventario proveniente de
otros sistemas o cargar excels con pedidos de venta y creacion de productos
desde ahi mismo.
La idea consiste en cargar el archivo venga como venga. Ahi pulsas
"procesar" (procedimiento en que haces todas las validaciones, creaciones y
actualizaciones que quieras) y el procesado devuelve Ok o Nok por cada
linea. Esto te evita los rollback completos y te permite ir capturando
pisibles errores de proceso, arreglarlo manualmente y reprocesar o cancelar
la linea
Esta chulo. Que te lo enseñe Dani si es caso y si es posible lo haria
generico.

**Comment by anajuaristi** [comment]
No he entendido ni torta de esto. Os estais empezando a liar.
Una cosa es el botom importar lineas de inventario en el propio objeto
inventario.
Otra cosa es importar lineas de inventario desde un archivo. Y en esta no
hay export ni log ni nada

**Comment by Daniel-CA** [comment]
Yo según le he entendido a Pedro quiere que a la hora de hacer la importanción en el log salgan solo las lineas que no se han importado correctamente y que de la opción de guardarlas en un nuevo archivo csv para poder modificarlas y volver a cargarlas.
Las lineas que se han cargado correctamente se verán ya en el inventario.

**Comment by pedrobaeza** [comment]
Efectivamente, eso justo es lo que quiero, Ana.

**Comment by anajuaristi** [comment]
Pero no tiene sentido. Una vez cargada la linea en el sistema, puedes
permitir editar los campos y reprocesar simplificando la operativz del
usuario. Y el cargar solo incorrectas te quita visibilidad sobre lo que ha
pasado en la carga
No st. Como veais. A mi cuanto menos arriba y abajo con archivos, mejor

**Comment by Daniel-CA** [comment]
Me parece bien, que con el botón en vez de guardar en un archivo  te vuelva a cargar las lineas erroneas directamente.

**Comment by anajuaristi** [comment]
Que no tiene que volver a cargar nada!!!

**Comment by Daniel-CA** [comment]
Si, me refería a que procesaría de nuevo las lineas que no se han cargado del archivo pero ya directamente desde el log.

**Comment by pedrobaeza** [comment]
Vale, @anajuaristi, ahora te entiendo. Lo que dices es como precargar las líneas en una pantalla, pero para corregirlas en la propia pantalla antes de cargarlas definitivamente. El único problema de este enfoque es que la corrección la tienes que hacer sí o sí en el momento antes de tener el inventario disponible. Sigue siendo un todo o un nada. Podrías eliminar las líneas conflictivas, pero luego no tendrías un archivo con sólo esas líneas erróneas. Por eso decía yo ambas cosas:
- Importar las correctas, y ya se podría trabajar con ellas mientras se arreglan las incorrectas. Parto del enfoque de que cada importación no crea un nuevo inventario, sino que añade líneas sobre el que estemos situados.
- Exportar a un archivo separado las incorrectas, para ir arreglándolas por otro lado.

¿Qué opinas?

**Comment by anajuaristi** [comment]
El proceso seria:
Carga lineas a modo informativo desde archivo a una tabla dummy nueva
Procesar lineas
Cada linea puede dar ok o error
Las ok yasta
Las error: lo corriges y reprocesas hasta que de ok

Tanto Alfredo como Aianara han utilizado esta base operativa para cargar
multitud de cosas incluso montar integraciones con otros sistemas. Como he
dicho antes el de carga de inventario es uno de los usos que se le pueden
dar. El problema en 6.1 es que tenemos ese mismo modulo copypasteado
harcideado para cada cosa a cargar
decia de intentar unificar y dejar un motor de carga unico si es posible

**Comment by pedrobaeza** [comment]
Eso es como diseñar otro _base_import_, en complejidad y en alcance. No merece la pena hacerlo genérico, porque son demasiadas cosas a tener en cuenta. El nuevo _base_import_ ya permite hacer eso. ¿Lo has probado?

**Comment by anajuaristi** [comment]
Si. Pero si no recuerdo mal base import no controla errores. Es todo o
nada. O sea si detecta algo mal hace rollback y no se puede reprocesar. Me
suena que era asi.
Pero ok. Igual es mas sencillo hacer diferentes modulos para cada cosa que
se necesite

**Comment by pedrobaeza** [comment]
En el nuevo te va indicando qué filas están incorrectas, aunque es cierto que hasta que no las corriges no puedes importar, pero todo se hace interactivo y visual. Échale un vistazo si no, a ver qué te parece, antes de seguir haciendo más trabajo. También podríamos ver si mejoramos el _base_import_ para permitir esa importación parcial.

**Comment by anajuaristi** [comment]
Eso estaria bien. Lo vemos el finde si te parece. Llego mañana por la noche
a casa

**Comment by anajuaristi** [comment]
Se deja aparcado por ahora hasta que haya una solicitud específica
