### ISSUE TITLE
mrp_bom_version traceback

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#271]
Si instalo el módulo mrp_bom_version en bbdd demo en demo.odoomrp.com, al intentar abrir una LM en modo formulario, se obtiene el error adjunto. Si desinstalo el módulo, no da el error.

Uncaught Error: QWeb2 - template['ListView.rows']: Runtime Error: Error: QWeb2 - template['ListView.row']: Runtime Error: Error: Campo desconocido state en el dominio [["state","=","historical"]]
http://demo.odoomrp.com/web/js/web.assets_common/ab75170:1020

**Comment by alfredoavanzosc** [comment]
He instalado el módulo en "demo.odoomrp.com", en la Bd demo, y para listas de materiales nuevas funciona perfectamente, te esta cascando porque este módulo mete un nuevo campo "state" en la listas de materiales, y lo que hace cascar son las listas de materiales viejas que tienen este campo vacio. Yo no puedo entrar a la Bd para dar valor a este campo.

**Comment by pedrobaeza** [comment]
Alfredo, para evitar estos casos en el futuro, puedes dar un valor por defecto a campos que requieran estar rellenos. Así, al instalarse en BDs con datos (que es lo habitual), no fallarán.

**Comment by anajuaristi** [comment]
Igualmente sigue siendo un bug.
El modulo al ser instalado deberia inicializa a un valor las listas
existentes.

**Comment by alfredoavanzosc** [comment]
En la definición del nuevo campo ya le tengo puesto el default, el campo esta definido de la siguiente manera:
    state = fields.Selection([('draft', 'Draft'),
                              ('active', 'Active'),
                              ('historical', 'Historical'),
                              ], string='Status', index=True, readonly=True,
                             default='draft', copy=False)

¿Donde debería de hacerlo aparte de aquí?

**Comment by pedrobaeza** [comment]
Sí, eso es correcto entonces, pero el traceback se debe deber a otra cosa entonces. De hecho, dice campo desconocido en domain. Ana, ¿puede ser que no estuviera actualizado el módulo?

**Comment by alfredoavanzosc** [comment]
no. He instadlo el módulo, he ido al objeto "mrp.bom", y se ve perfectamente el campo "state".

**Comment by alfredoavanzosc** [comment]
Se ha corregido el bug, nuevo PR en https://github.com/odoomrp/odoomrp-wip/pull/275

**Comment by oihane** [comment]
Merged
