### ISSUE TITLE
mrp_variants

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#272]
He creado MO00063, que incluye plantilla con un componente sobre plantilla y un proceso productivo.

Le incluyo un componente, asociado a plantilla, sin producto (earphones) que tiene variantes y otro que no los tiene
Determino color "hereda de" = true en la plantilla earphones.

Al pulsar el botón "calcular datos" de la OF, la línea de componente del bom que lleva asociada solo la plantilla, no la trae a la OF.

---

Intento meter a mano una línea a mano, sin producto para probar el configurador pero al meter template_id no aparece el configurador. Tampoco ejecuta onchange para traer la unidad de la plantilla.

---

Quiere decir que al final no he podido probar el módulo porque no consigo ejecutar el configurador y al no traer las líneas de la plantilla, tampoco veo si asigna correctamente los valores del hereda de. 
Revisar si se ha subido la última versión

**Comment by oihane** [comment]
![fireshot capture - productos - odoo_ - http___demo odoomrp com_web](https://cloud.githubusercontent.com/assets/2323616/4914759/04fe5b44-64c7-11e4-95c9-3940606edc7a.png)
¿Tiene algún sentido que se defina dos veces el ancho? Porque acabo de ver que el fallo al cargar los atributos (cuando dice que espera un singleton) se debe a esa configuración.

**Comment by pedrobaeza** [comment]
Yo no le veo ningún sentido, y es más, debería prohibirse como constraint.

**Comment by oihane** [comment]
## En el caso del MO00063.

En la lista de materiales de "ACABADO 1" se definen:
- caja envasado (sin product)
- skndsdislisd - skndsdislisd
- Pintura final - Pintura final
- Apple In-Ear Headphones (sin product)

```
            if not bom_line_id.product_id:
                bom_id = self._bom_find(
                    product_tmpl_id=bom_line_id.product_template.id,
                    properties=properties)
            else:
                bom_id = self._bom_find(product_id=bom_line_id.product_id.id,
                                        properties=properties)

            #  If BoM should not behave like PhantoM, just add the product,
            #  otherwise explode further
            if (bom_line_id.type != "phantom" and
                    (not bom_id or self.browse(bom_id).type != "phantom")):
```

La parte de buscar por **template** si no hay **product_id** es mía, el resto es copia del de _mrp_.

La cosa es que **Apple In-Ear Headphones** tiene un BoM de tipo _"phantom"_ que no tiene definido el producto que usar para la variante que nos correspondería, y por ello no pone nada en los productos planificados.
Es decir, en el if:
- bom_line_id.type != "phantom": True
- not bom_id: False
- self.browse(bom_id).type != "phantom": False

Aunque no le encuentro sentido, es como esta puesto.

**Comment by anajuaristi** [comment]
Joe.. vaya lío tienen montado. Eso no es así, es mucho más simple.

Debería ser algo como:

```
.- Si la línea es normal : 
     .- Si tiene product_id, coge product_id + template_id
     .- Si no coge template_id

.- Si la línea es phantom:
     .- Busca bom tipo set --> Si lo tiene sustituye product_id o template_id por sus componentes
        Si no lo tiene --> Error, una línea phantom debe tener un bom tipo set 
asignado, o bien se asigna el producto o template como tal, sin hacer sustitución 
para que alguien lo corrija
```

Y ya esta... no hay tanto lío de true/falses ni nada...

**Comment by anajuaristi** [comment]
Veo que se han arreglado la mayoría de las cosas.

Hay algunos matices que paso a detallar:

A. ONCHANGE product_id en OF

.- Creo una nueva OF con un template que tiene una LM asociada, normal
.- Salta el configurador de producto final pero al asignar "variant" porque el producto específico ya existe, ejecuta un onchange y se "pierde" la lista de materiales. Queda el campo vacío. 
Aquí el onchange correcto debería ser: Si al asignar producto existe una LM específica para dicho producto, la asigno, pero si no, dejo la del template. Actualmente busca y si no encuentra ninguna elimina la del template dejando el campo vacío.
En la misma línea, si elimino el producto del combo y dejo el campo vacío, elimina el dato de los campos LM y Template.  Lo mismo, si tengo template asignado, no debería vaciarlo nunca.

---

B. Botón calcular datos

Si la lista de materiales tiene una línea phantom con variantes no he conseguido que traiga el componente correspondiente a la variante, aunque la asignación el hereda de, la hace bien, solo sustituye el componente fantasma por los componentes de su lista que no están limitados a variantes del padre. 

---

C. Los componentes sustituidos por la lista fantasma, se quedan sin asignación de workorder. Tendrían que llevar todos el mismo workorder que el componente al que sustituyen, es decir, se consumirán todos en la misma operación que muestra el componente sustitudo en la lista de materiales

Por lo demás, está OK mrp_variants. :+1:

**Comment by oihane** [comment]
Has probado el punto **C** sin el modulo `mrp_product_variants`??
Ya que eso es parte del modulo `mrp_operations_extension`

**Comment by anajuaristi** [comment]
Cierro ya que el issue mencionado ya ha sido abierto aparte como bug en #394
