### ISSUE TITLE
Onchange incorrecto en product_id en la OF mrp_product_variants

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#273]
Aparte del configurador encuentro estas cosas:

Onchange incorrecto en product_id en la OF
1. Asigno plantilla y el onchange se trae LM y proceso productivo. OK
2. Incluyo valores en tabla y encuentra un producto... parece ser que hay un onchange en product_id, que busca una LM asociada al producto específico y al ejecutarlo "limpia" el valor asignado en LM y proceso. --> BUG
Modificar onchange en product_id para que sólo modifique valor de LM, en caso de que encuentre una LM específica para el producto, si no, no. No es bloqueante ni crítica ya que permite volver a seleccionar la LM de la plantilla manualmente pero se puede evitar.

**Comment by anajuaristi** [comment]
creo que he duplicado esto en un comentario aquí
 https://github.com/odoomrp/odoomrp-wip/issues/272 
porque me ha vuelto a pasar

**Comment by anajuaristi** [comment]
@oihane pone merged pero sigue pasando por favor, revisa. 

El on_change en product_id, en caso de tener que existir debería hacer lo siguiente:
.- Buscar un BOM específico para ese product_id, si existe lo asigna en bom, si no existe, si el campo BOM está vacío, busca el bom de la plantilla y si está asignado ya, no hace nada. (No deja el bom en blanco, deja el que estuviese)

En todos los casos, podriamos pulsar el botón "recalcular datos" para regenerar de nuevo la lista de componentes de esta nueva selección.
.- Pulsar el botón recalcular datos.

Esto sería lo correcto. Ahora mismo, limpia el campo y es necesario seleccionarlo el bom de nuevo a mano.

**Comment by anajuaristi** [comment]
@oihane, está mejor pero no está niquelado. Acabamos de actualizar el entorno

En demo, prueba el template "PruebaVariantName"

Al cambiar el template, no trae la lista de materiales. Si se la pongo manualmente, al seleccionar un producto, ahí sí que ya no ejecuta limpiar la lista de materiales. Deja la que había.

Solo faltaría el onchange en el template.

**Comment by anajuaristi** [comment]
@oihane, esto sigue pasando. 
@pedrobaeza ¿Podeis echarle un vistazo a los onchange de template y producto en la OF? 

Tiene que ser: 
1. En el onchange de template_id --> Si solo hay una LM asociada al template la trae. Si hay más de una, trae la última versión (la que tenga secuencia más alta)
1. En el onchangede product_id --> Si existe LM específica para product_id, se modifica LM, Si no, se deja la que haya. En ningún caso, se limpia el campo (ahora cuando seleccionas un producto "se pierde" el que hubiese seleccionado anteriormente y hay que volver a ponerlo)
2. En el onchange de LM --> Asignar la ruta de ese LM
3. Combo de ruta, tiene que tener domain. No se puede poner cualquiera.Solo puede asignarse la que tenga asociada la LM seleccionada.

A nivel usabilidad, se pierde bastante tener que volver a meter la LM, si ya tenía una puesta.

**Comment by oihane** [comment]
Creo que esto estaba también arreglándolo en #587

Cual es exactamente el domain, que hay otro issue #515 pero no he sido capaz de entenderlo. He entendido que falta y algunas otras cosas que nos aconseja Eva, pero no he terminado de tener claro el dominio

**Comment by anajuaristi** [comment]
El domain es en el campo ruta de la OF.
Solo puede seleccionarse la ruta que esté asignada en la LM que haya sido seleccionada. O sea, justo la que asigna en el onchange de la LM. Y no se podría/debería cambiar.

**Comment by oihane** [comment]
Donde era ya sabia :wink:, voy a ello

**Comment by anajuaristi** [comment]
Functional review :+1: 
Cierro. GRACIAS!!!
