### ISSUE TITLE
Smartbutton Pedidos Venta/Compra ultimos precios

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#277]
Crear boton en pedido de compra y oferta de venta que muestre los ultimos precios de los articulos incluidos

En pedidos de venta añadir un smartbutton que al ser pulsado muestre líneas del resto de pedido de venta filtrando que se muestren únicamente los productos que se han incluido en el pedido de venta. En pedidos de compra añadir un smartbutton que al ser pulsado muestre líneas de pedido de compra filtrando que se muestren únicamente los productos que se han incluido en el pedido de compra.

**Comment by Daniel-CA** [comment]
No sería conveniente añadir algún tipo de limitación de los productos a mostrar? Por ejemplo de las compras/ventas de solo el último mes o dos meses, por que al final en cuanto se tenga cierto volumen de datos las lineas que se muestren serán bastantes y la mayoría inútiles.
Que os parece, @anajuaristi  @pedrobaeza?

**Comment by pedrobaeza** [comment]
Eso ya lo hace solo el sistema: te muestra los 80 primeros. Tú lo que te tienes que preocupar es que el dominio sea correcto. Si hay más, que pagine.

**Comment by Daniel-CA** [comment]
Ya bueno, yo lo decía para no recargar a lo tonto el postgres, al final no es lo mismo recorrer los últimos pedidos de compra/venta que todos los pedidos de compra/venta.

**Comment by pedrobaeza** [comment]
No lo recargas. El posgres ya es consultado con el LIMIT correspondiente. Lo que tienes que preocuparte es que el order sea el adecuado para lo que quieres mostrar (por fecha como dices o lo que sea).

**Comment by Daniel-CA** [comment]
Validado el módulo, cierro issue.
