### ISSUE TITLE
Bug en assets 

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#286]
Parece ser que hay un bug en assets, en el base de Odoo. No sé si sería lo suyo reportarlo en la rama de Odoo.
Cuando se realiza una factura, con una línea asociada a categoría de asset, pero con cantidad >1, el sistema genera un único asset, poniendo en el campo valor bruto, el subtotal de la línea.
Debería generar un asset diferente por cada unidad, incluyendo en valor bruto, el precio unitario de la línea.
@pedrobaeza ¿Lo reportamos a odoo a ver qué dicen? Puede ser que el requerimiento legal de tener que crear un asset por unidad, no aplique a otros paises, en cuyo caso, habría que solucionar el tema en l10n_es, pero si es requerimiento legal general, debería aplicarse en odoo core.
Ya dirás.

**Comment by pedrobaeza** [comment]
Como dices, podría ser algo específico de la localización española. Tendré que investigar luego.

**Comment by anajuaristi** [comment]
Es que el traceback salta al instalar el módulo asset base de Odoo en ALM
En wip está todo instalado y no puedo probar. 
Cierro este issue y te lo abro en la rama que toca,  no vaya a ser algo puntual del entorno. 
En runbot no puedo probar tampoco porque también está instalado.

**Comment by anajuaristi** [comment]
@pedrobaeza parece ser mirando ahora el error más en detalle que da al insertar el registro de prueba de datos demo. He posteado el traceback en el nuevo issue
#179 de ALM
