### ISSUE TITLE
quality_control_between_dates traceback

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#287]
Si tengo este módulo instalado e intento crear un test desde plantilla, da este error. Si lo desinstalo no da.
Impacta en la creación de test desde fabricación también. Las operaciones que implican la creación de un test, no se pueden iniciar por el mismo traceback.

```
AttributeError: 'qc.test' object has no attribute 'env'

```

**Comment by alfredoavanzosc** [comment]
Se ha corregido el error y se ha hecho un nuevo PR, https://github.com/odoomrp/odoomrp-wip/pull/308

**Comment by alfredoavanzosc** [comment]
Ana... Pedro ya me ha hecho el MERGE de este módulo, ahora habrá que actualizarlo en el entorno correspondiente. Un saludo.

**Comment by anajuaristi** [comment]
Probado con varias casuisticas de fechas en la plantilla, trae bien las líneas
:+1: Cierro issue
