### ISSUE TITLE
mpr_bom_version no se pueden duplicar listas

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#290]
Hay 2 errores funcionales en el módulo
Por una parte, se ha duplicado el campo revisión, que ya existe uno "secuencia" que podía haberse utilizado para versionar las listas y se ha añadido un nuevo campo "revisión", que no haría falta.

independientemente de eso, se produce una problemática de que si intentamos duplicar una lista, por defecto le da número de revisión = 0 y si esta revisión existe previamente, no deja duplicar.
El caso que me ha sucedido es que he duplicado una, le he dado nuevo número y he historificado la de revisión 0. Al existir ya una con revisión cero, no permite grabar otra con la misma revisión. Al estar en histórica, tampoco permite modificarle el campo por lo que la lista "patas", no se puede duplicar nunca más.

**Comment by alfredoavanzosc** [comment]
Se ha quitado el campo "review", y se utiliza ahora el campo "sequence". Se ha hecho que al duplicar una lista de materiales, se le asigne automáticamente el número de secuencia que le corresponda, a la nueva lista de materiales resultante. Se ha hecho un nuevo PR, en: https://github.com/odoomrp/odoomrp-wip/pull/291

**Comment by oihane** [comment]
Merged
