### ISSUE TITLE
CLM0084 Mejora de referencia interna (product_variant_default_code)

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#296]
Varias cosillas en este módulo:

Lo que se pide es crear automáticamente la referencia de los productos que se crean desde una plantilla, concatenando en su código de referencia, el código de la plantilla y los valores de las variantes.
1. En las plantillasno se ve por defecto el campo default_code, sigue limitado a no tener atributos para verse.
2. Aunque lo hago visible por pantalla y asigno un valor, el campo default_code de los productos, sigue vacío. 

Revisar el módulo.

**Comment by alfredoavanzosc** [comment]
Después de hablar con Ana, he modificado el módulo y he hecho un nuevo PR, está en el issue https://github.com/odoomrp/odoomrp-wip/pull/312

**Comment by alfredoavanzosc** [comment]
Pedro ya me ha hecho el merge, así que habría que actualizar el módulo en el entorno correspondiente.

**Comment by anajuaristi** [comment]
Probado el módulo funciona correctamente.
Una pequeña cosa... es que si el valor de variante tiene el campo código nulo, evidentemente la concatenación coge el campo vacio

En el ejemplo, he dejado a posta el código vacío en el color negro y he asignado BL en el blanco

```
TclApple/2,4    Teclado inalámbrico Apple  Color: Negro, Red inalámbrica: 2.4 GHz  
TclApple/3,6    Teclado inalámbrico Apple  Color: Negro, Red inalámbrica: 3.6GHz   

TclApple/Bl/2,4 Teclado inalámbrico Apple  Color: Blanco, Red inalámbrica: 2.4 GHz 
TclApple/Bl/3,6 Teclado inalámbrico Apple  Color: Blanco, Red inalámbrica: 3.6GHz
```

Creo que si está vacío, podríamos coger las 2 primeras letras del nombre de variante, por ejemplo, así será raro que coincidan 2 diferentes. 
Otra opción es que al crear el valor de variante, por defecto ya se asignen al código las 2 primeras letras. 
@alfredoavanzosc @pedrobaeza  ¿Como lo veis?

**Comment by pedrobaeza** [comment]
Es que esa posibilidad no debería darse por dos mecanismos que pusimos: el campo required y que coja automáticamente para ese campo las dos primeras letras. No sé por qué no está funcionando. ¿Puedes revisarlo, @alfredoavanzosc?

**Comment by alfredoavanzosc** [comment]
Hola, buenos días a los dos. Yo creo que es esto lo que está pasando. Para empezar el campo "attribute_code", NO es un campo requerido, lo que si hay es un onchange que se ejecuta cuando se cambia el nombre del valor del atributo, y automáticamente se cogen las 2 primeras posiciones de este nombre/descripción, y se las pasa al nuevo campo que le pusimos "attribute_code".
Todo esto me hace pensar que ya había atributos grabados en la BD antes de instalar este módulo.
Para solucionar esto, con los datos que hay actualmente, se podría poner un default al campo "attribute_code", ya me diríais que cogería este default.

**Comment by anajuaristi** [comment]
Si. Estamos en una bbdd con datos de prueba.
No veo sencillo poner un default porque no interesa tener el mismo valor en
todos los atributos
el default como tal serian las 2 primeras letras y si esto ya esta en el
onchage y se informa al crear nuevos atributos por mi parte ok. Cerraria
issue

**Comment by anajuaristi** [comment]
El bug sigue existiendo ya que aunque ahora sí que asigna valor de código, cuando se da de alta desde la ficha de producto, pero solo coge una única letra/digíto y no 2 como estaba pedido.
Es decir para el valor AB, le asigna solo A

Además, si se renombra un código de variante directamente en la tabla de valores, el código de los productos asociados no se renombra, queda con el valor antiguo.

Ejemplos con el código substring de 1 único carácter:
    PDC/3/A PruebaDefaultCode   Nuevo1: 330, Nuevo1: AB 
    PDC/3/B PruebaDefaultCode   Nuevo1: 330, Nuevo1: BC 
    PDC/3/C PruebaDefaultCode   Nuevo1: 330, Nuevo1: CD

**Comment by alfredoavanzosc** [comment]
Ok, ya he hecho para que coja 2 dígitos en vez de 1. Pero ahora tengo un problema con el tema de que al renombrar un codigo de variante, el código de los productos asociadosno se renombra. El problema es el siguiente:
1.- En la tabla "product.product" existe el campo attribute_value_ids, que es un many2many al objeto product.attribute. value
2.- En la tabla "product.attribute.value" existe el campo "product_ids", que también es una many2many a product.product, pero el problema es que en este campo no quedan asociados los productos, esta vacio.
¿Como lo hago, me recorro todos los productos?

**Comment by pedrobaeza** [comment]
Recorrer no, simplemente buscar aquellos que tenga ese atributo, y regenerar la correspondiente referencia. Yo creo que nos va a tener más cuenta ponerlo como campo calculado y que dependa de cualquier de los campos que forman parte de esa referencia, y así lo haría automático.

**Comment by anajuaristi** [comment]
Esto sigue pasando. 
Al modificar el prefijo (ahora máscara) del template y grabar sí que modificar el código de los productos afectados pero si modifico un código de atributo, no hace nada 

Igualmente, sigue cogiendo un único dígito en el código de atributo y no 2. El entorno ha sido actualizado hoy.

**Comment by alfredoavanzosc** [comment]
Realizado, el PR es el https://github.com/odoomrp/odoomrp-wip/pull/576

**Comment by anajuaristi** [comment]
:+1: Cierro
