### ISSUE TITLE
Listado extendido de trazabilidad

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#31]
Esta tarea la tengo como pendiente también, la añado aquí para que no se nos pase.

Necesitamos una gestión completa de la trazabilidad, es decir:
- Para la trazabilidad hacia adelante, debemos conocer en que productos (acabados, intermedios, reprocesados, ...) ha intervenido una determinada materia prima y llegar hasta el detalle de los movimientos (documentos de venta, devoluciones, ...) de cada uno.
- Para la trazabilidad hacia atrás, debemos conocer que materias primas han intervenido en la fabricación de un determinado producto (materia prima, producto intermedio, reprocesados, ...) y llegar hasta el detalle de los movimientos (documentos de entrada de dichas materias primas).
  Enfoque técnico:
  En el punto de "procesar" una orden de fabricación, al aceptar la pantalla donde se indican lotes de producto y de componentes, crear las líneas correspondientes en una nueva tabla con los siguientes campos:
  Componente
  Nºlote componente
  Producto final
  Nºlote prod final
  Id orden de fabricación
  Necesitamos esta tabla relación (que se creó también para Fagor, creo, algo similar) De momento, el módulo que incluya sólo hacer la tabla e insertar el registro al pulsar el botón "aceptar" del wizard de "fabricar" en una orden de fabricación.

El sistema solo tiene que crear línea en el caso de que el producto final sea trazable y solo para los componentes que sean trazables
El informe de trazabilidad, lo haremos a posteriori, en otro módulo una vez funcione este.

**Comment by pedrobaeza** [comment]
@Daniel-CA , indica en qué PR lo solucionas antes de cerrarlo.

**Comment by Daniel-CA** [comment]
El módulo es mrp_production_traceability, no encuentro el PR.

**Comment by anajuaristi** [comment]
Pues aquí está el lío que comentaba Oihane que hay 2 módulos que se llaman
igual.
Cuidado con esto.
El de Dani, hace una relación entre los lotes consumidos y producidos
(guarda esa relación cada vez que se consume o produce en la OF), el de
Oihane, asigna un lote automáticamente al producto "producido" asignándole
el mismo número que tiene la propia OF.
Ambos dos han sido solicitados y están en los requerimientos. Cuidado no se
pierda ninguno.

Cambiar el nombre a uno de los dos.

**Comment by anajuaristi** [comment]
Por otro lado, no puede ser que no haya PR, Quizás es de los primeros módulos que se hizo al principio  del proyecto cuando no se utilizaba la metodología actual, pero ahora no tiene sentido que haya ningún módulo sin PR por lo que si no hay, crea uno y súbelo de la manera correcta antes de cerrar la solicitud.
Te la reabro.

**Comment by oihane** [comment]
El PR #32 está aprobado y es el módulo de @Daniel-CA el otro no se cual es, pero no lo he encontrado con ese nombre.

**Comment by anajuaristi** [comment]
@Daniel-CA tu módulo no crea ningún menú, ni ninguna vista en el objeto por lo que no puedo validar que esté correcto o incorrecto.
Por favor, incluye un menú y al menos una vista tree con los campos básicos que guardas en tu tabla en el nuevo objeto de trazabilidad en fabricación.

@oihane Me suena que el otro módulo que comentais es uno que actualmente está haciendo @alfredoavanzosc que asigna automáticamente un número de lote al producto final
Ponerle un nombre que no sea  mrp_production_traceability
El de @alfredoavanzosc podría ser mrp_assing_automatic_lot o algo así.

**Comment by Daniel-CA** [comment]
Creados menus en Warehouse -> Traceability PR #270

**Comment by anajuaristi** [comment]
Se ha incluido el menú y los campos incluidos son correctos pero no hay ningún campo de filtro ni agrupación sobre ellos por lo que cuando haya volumen será complicado intentar sacar algo de ahí. 

Reabro con la solicitud para añadir filtro y agrupación sobre los 5 campos de la tabla

**Comment by Daniel-CA** [comment]
Cierro esta issue y seguimos en #253
