### ISSUE TITLE
estimated cost, crea líneas analíticas sin enlace a of y workorder

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#313]
Verificando las líneas analíticas que crea el estimated_cost, he visto que las líneas que se crean, no llevan el id de la of, ni de la ot inicializados, por lo tanto, al intentar agrupar por estos campos no se puede porque están indefinidos en todas las líneas.

**Comment by alfredoavanzosc** [comment]
Modificado el módulo, y subido en PR https://github.com/odoomrp/odoomrp-wip/pull/328

**Comment by alfredoavanzosc** [comment]
Ana... ya esta hecho el merge, puedes descargar e instalar el módulo en el entorno que corresponda.

**Comment by anajuaristi** [comment]
Solucionado error :+1:  cierro issue
