### ISSUE TITLE
Nombre de diarios estimated cost

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#314]
A fin de facilitar luego la comparación de los costes estimados y reales, creo que los diarios analíticos que crea el estimated cost, no deberían llevar el nombre Estimated, sino solo Materiales, Maquinas y Operarios... 
De esta forma, independientemente si el coste es estimado o real, se podrá seleccionar el mismo diario y en la agrupación se ve perfectamente el sumatorio y la comparativa. 
Si le dejamos estimated en el nombre, es probable que imputen costes reales contra otro diario por lo que al agrupar, la comparativa no se ve de forma tan clara. 

Se solicita, cambiar el nombre a los diarios.

**Comment by alfredoavanzosc** [comment]
Se ha modificado el nombre de los diarios, el PR  es el https://github.com/odoomrp/odoomrp-wip/pull/327

**Comment by anajuaristi** [comment]
Verificado cambio :+1: Cierro
