### ISSUE TITLE
CLM0042: Filtrar por Día y Semana los Pedidos de Venta Mejora extensión sale_delivery_date

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#317]
En Ventas
Pedidos de Ventas
Crear un filtro (Agrupación) para que muestre los pedidos en función de la Fecha de Salida por Día y por Semana (Debe aparecer la Fecha de Entrega).

---

Enfoque técnico:
Añadir en pedidos de venta agrupación por semana y día basado en "fecha salida"
Añadir al tree de pedidos, los campos fecha salida y fecha estimada de entrega 
Modificar directamente el módulo sale_delivery_date de wip

**Comment by oihane** [comment]
Esta es la que te acaba de comentar @anajuaristi

**Comment by alfredoavanzosc** [comment]
Ya esta el módulo subido y a pasado los controles de "travis", esta pendiente del MERGE. Para que Ana lo pueda probar, se ha subido este módulo al servidor de Avanzosc.

**Comment by anajuaristi** [comment]
@alfredoavanzosc :+1: 

Una pequeña cosilla --> El campo validity_date del módulo sale_delivery_date se ha traducido como "fecha de caducidad", sería "fecha de validez". Se ve en la cabecera de pedido y da lugar a confusión. Cuando podáis, lo cambiáis en el módulo.

Por lo demás, está correcto por lo que cierro issue.
