### ISSUE TITLE
Asignación de cuenta analítica del pedido a la OF (Enlaces1)

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#318]
Probando abastecimientos contra pedido --> No se puede generar OF, porque la cuenta analítica en la OF es requerida, pero no se arrastra desde el pedido según parece.

Por lo tanto, al intentar guardar la OF, le falta la cuenta y hace rollback de todo.

Posibles soluciones: 
1. Dejar como está, arrastrar cuenta a la OF desde el pedido resolviendo el bug
2. Quitar la cuenta obligatoria en la OF pero no permitir confirmarla si no tiene cuenta asignada.
3. Quitar cuenta obligatoria en OF y permitir confirmar OF, pero si no hay cuenta, no imputar costes estimados y reales a la OF porque no es posible sin cuenta. 
@pedrobaeza @agaldona ¿Cual os parece la mejor?

**Comment by pedrobaeza** [comment]
La 1 cuando se instala el módulo de costes, porque si no quieres cuenta analítica, no la pones en el pedido.

**Comment by agaldona** [comment]
En principio, la cuenta se arrastra, ¿me podéis decir cual es el ejemplo que habéis utilizado? También veo necesario quitar la obligatoriedad del campo cuenta analítica en OF, ya que si no se especifica en pedidos, no se cargara en OF.
