### ISSUE TITLE
mrp_procurements_plan No consigo hacerlo funcionar

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#319]
La verdad no entiendo el funcionamiento de este módulo.
He probado de todas formas, con jit, sin jit, definiendo abastecmiento contra pedido, contra stock, con regla mínima, sin ella... 
No hay forma que genere ni compras, ni ofs.

Aparte de que cuando lo lanzas una única vez ya se queda muerto. No deja hacer nada más, aunque salga un error y no acabe de ejecutarse, ya no hace nada. El plan se queda bloqueado. Para volver a regenerar o poder volver a lanzar el plan, hay que borrarlo y crear uno nuevo. 

Hay algún fallo de diseño o algo y no hace lo que tiene que hacer que es... simplemente lanzar el scheduler para las líneas incluidas en él y mostrar los pedidos de compra y Ofs que se vayan creando. 
No debe hacer nada más.
@alfredoavanzosc @pedrobaeza ya direis.

**Comment by anajuaristi** [comment]
Y acabo de ver lo de la cancelación de los moves en salida, que sigue ahí. 
Se supone que el merge con esto arreglado es de hace días, por lo que debería estar ejecutando la última versión, pero no sé. Quizás basta con una nueva actualización del entorno por si acaso no estoy viendo los últimos merges.
De momento desinstalo el módulo hasta que le deis una vuelta.

**Comment by alfredoavanzosc** [comment]
Ana... sobre esto que me estas comentado, no se que decirte, los MERGE están hechos, pero no creo que tienes actualizado el sistema, ya que el tema de la cancelación de los stock.move no está, y yo haciendo pruebas en mi local no tengo los problemas que tienes tú.
La prueba que yo ha realizado ha sido la siguiente:
1.- He creado un pedido de venta con un producto a producir
2.- He creado un plan, al cuál he incluido los 2 abastecimientos creados por este pedido de venta.
3.- Ejecuto los abastecimientos desde el plan, y me genera lo siguiente:
3.1.- Me crea una OF con el plan asociado.
3..2.- Me crea 2 abastecimientos nuevos por el producto a consumir en la OF, estos 2 abastecimientos quedan linkados al plan.
3.3.- Me crea el pedido de compra del producto a consumir en la OF, este pedido de compra queda asociado al plan.
Pues Ana... esto es lo que me hace a mi en mi local, no sé si tendrás actualizados los módulos donde tu estas haciendo las pruebas.
Comentarte también que son 2 módulos: "procurement_plan", y "mrp_procurement_plan".
Un saludo.

**Comment by anajuaristi** [comment]
Retomamos lo del plan, pero rehaciendo parte.Asigno a @agaldona 
No sé si deberiamos cerrar este issue que ya no aplica y abrir uno nuevo o nos vale con este mismo
@pedrobaeza

**Comment by agaldona** [comment]
PR subido en #589

**Comment by anajuaristi** [comment]
Cierro ya no aplica por haberse rehecho el plan entero
