### ISSUE TITLE
procurements_plan

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#323]
Puntos de mejora
1. Borrar registros antes de ejecutar wizard importar
2. Tree editable para desenlazar procurement con plan

**Comment by alfredoavanzosc** [comment]
Realizado, el PR esta en https://github.com/odoomrp/odoomrp-wip/pull/325

**Comment by alfredoavanzosc** [comment]
Ana, Pedro ya me ha hecho el merge, por lo que puedes descargar y actualizar el módulo en el entorno que corresponda.

**Comment by pedrobaeza** [comment]
Esto ya no aplica. Cierro.
