### ISSUE TITLE
[TRAVIS] ERROR no bloqueante

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#326]
Al ejecutar cualquiera de los travis, se ve que aparece en el server:

```
ERROR openerp_template openerp.modules.graph: module stock_invoicing_type: Unmet dependencies: sale_journal
```

Resulta que los de **Odoo** lo han puesto como `installable: False` :smile:

**Comment by pedrobaeza** [comment]
Y por qué depende de ese módulo? Mira a ver si se puede quitar la dependencia.

**Comment by oihane** [comment]
Es un modulo hecho por @mikelarre y @agaldona que no se que hace ni para que sirve.

Se lo asigno a @agaldona por ser la última que lo ha modificado, y entiendo que sabrá de que va...

Please, begiratu Ainara

**Comment by agaldona** [comment]
@oihane @mikelarre @pedrobaeza @anajuaristi
Espero que me explique bien, ya que he estado buscando, pero no encuentro las especificaciones.
Había un requerimiento, donde decían que en un cliente podías especificar un tipo de facturación, donde se decía, si se facturaba, factura en factura o en grupos. Luego ese dato se cargaba en pedidos de venta y así se trasladaba hasta los albaranes para que luego al facturar, se tuviese ese campo en cuenta.
El módulo sale_journal, ya creaba ese objeto e implementaba la mayor parte de los requisitos que se pedían, si no recuerdo mal, solo añadí algunas cosillas que se pedían.
No se si me he explicado.

**Comment by pedrobaeza** [comment]
Ya recuerdo, pues habrá que esperar a ver qué hace Odoo con ese módulo y si lo rescatamos nosotros o qué. Por el momento, @oihane, ponlo en exclude en el Travis con commit para que no fastidie el resto de PRs.

**Comment by oihane** [comment]
La verdad es que solo dice "unmet" y sigue adelante, pero lo pongo :wink:

**Comment by pedrobaeza** [comment]
Ah, vale, si no da rojo Travis, entonces déjalo.

**Comment by oihane** [comment]
:worried: ya lo he cambiado

**Comment by oihane** [comment]
`sale_journal` otra vez instalable :wink:
