### ISSUE TITLE
No genera test

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#33]
Prueba:
incluir un rango de muestra genérico
Crear presupuesto compra
Recepcionar todo 
Ir a solapa test calidad: No se visualiza ningún test

Si se hace mediante la pantalla de código de barras, se crea test. Pero todos los campos relación quedan vacíos:
Producto, movimiento, categoría.. etc. lo cual luego impide buscar

**Comment by oihane** [comment]
Corregido en #28
