### ISSUE TITLE
Expected singleton al hacer split en transfer de entrada

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#334]
Albarán de entrada con X cantidades
Botón transfer
Split la línea en 2
Asignar un lote a cada línea 
procesas el albarán y da este error

```

ValueError

Expected singleton: stock.production.lot(102, 103)
```

**Comment by agaldona** [comment]
@anajuaristi No se si has desisntalado algún módulo o he hecho yo algo mal. Pero en la base de datos demo, el albarán  WH/OUT/00005 me lo ha procesado bien. He hecho split, y le he asignado un lote distinto a cada línea.

**Comment by anajuaristi** [comment]
Creo que fue un error puntual de alguna revisión. En BBDD nueva no he conseguido reproducirlo. De momento cierro issue
