### ISSUE TITLE
landed cost: solicitan visualizar producto y cantidad en tree purchase.cost.distribution.line

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#335]
Lo dicho en el título
Mostrar producto y cantidad en el tree de ese objeto (están en el form)

**Comment by pedrobaeza** [comment]
Justo los dos campos que dan problemas con los datos calculados... Por eso están quitados.

Intentaré ver cómo resolverlos.

**Comment by pedrobaeza** [comment]
Ya los he añadido utilizando campos calculados en lugar de related, que eran los que daban problemas.
