### ISSUE TITLE
Enlace a Product Variants

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#344]
Igual que en el módulo de ventas hay un MENU a 'productos' y otro a 'product variant', se debería añadir ambos menús en los módulos de compras y de almacén. 
Además, habría que cambiarle las etiquetas ya que producen confusión, creo que lo más lógico sería que producto se etiquetara 'template' y que product variant, se etiquetara como 'productos'. He revisado los módulos de compras y almacén y en el caso del módulo de almacén, el enlace aparece bajo el menú 'configuración' además, está duplicado el enlace a producto (en el menú producto y en el menú configuración).

---

Ana: 10oct2014 
Enfoque técnico: Añadir tanto en compras como en almacén, los menús de entrada que falten. Desde ambos se debería tener acceso a producto y plantilla y traducir correctamente.

**Comment by pedrobaeza** [comment]
En almacén es absurdo tenerlo. Ya se tiene productos. Alguien con perfil de almacén no va a manejar esa variantes.

Igualmente en compras.
