### ISSUE TITLE
Vista de "productos a enviar"

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#345]
En compras existe una entrada "productos a recibir" que filtra líneas de movimiento (con menos campos que la vista de movimientos normal) que no existe en ventas. Se solicita que se monte una entrada de menú similar en Ventas que muestre los movimientos en albaranes de salida, que aún no se han realizado, con un número de campos reducido como en el listado de productos a recibir de compras.
@anajuaristi , @pedrobaeza 
Algo que añadir?

**Comment by pedrobaeza** [comment]
Tampoco tiene sentido en el mismo momento en que tu política de envío sea Pick + Pack, o la de tres movimientos. ¿Qué consideras para enviar? Por eso se ha eliminado, por una buena razón y debe seguir así.

No hay que tratar de replicar la funcionalidad de la v6.1/v7, porque con el nuevo WMS hay cosas que cambian.

:-1:

**Comment by anajuaristi** [comment]
Pedro... Eso que dices no tiene sentido. Pick y pack son albaranes internos y exactamemte igual puedes tener una recepcion en 3 pasos. Pero el albaran de salida como tal o el de entrada son solo uno haya los pasos que haya.
No es replicar funcionalidad de 6.1. Es que hay cosas incoherentes. Si pones una funcionalidad necesaria en compras porque no en ventas?

**Comment by pedrobaeza** [comment]
Es que para eso ya tienes el panel de almacén. En ventas no pinta nada. En compras tiene sentido porque se puede facturar desde ahí.

**Comment by anajuaristi** [comment]
Esta vista, si se hace, debería ir también al nuevo repo de utilidades. 
Sigo pensando que es necesaria. ya que te da a un vistazo y con los campos mínimos los productos que le "debes" a los clientes, al igual que la de compras te da los que te deben los proveedores. 

En movimientos de almacén, se puede sacar la información pero estamos en la de siempre, si un comercial necesita ver esta información, filtraday rápidamente, necesitaría tener también permisos de almacén.
Ya direis.

**Comment by anajuaristi** [comment]
Al final no se hace. Cierro
