### ISSUE TITLE
Mejora para test cualitativos

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#35]
En plantilla de test, en opciones de valores cualitativos, añadir un checkbox 
Los valores "buenos" serán marcados y los "malos" se quedarán sin marcar.

Por defecto, al crear el test, en valores cualitativos el check Ok, nok será inicializado a false (actualmente le pone true, cuando aún no se ha evaluado)
Posteriormente, en el propio test, al seleccionar un valor cualitativo, se trae el valor que tenga en el check en la configuración. 
El check, basta con ponerlo en la tabla opciones, no es necesario modificar el many2many de prof/opciones. Si una misma opción es válida en un test y no válida en otro test, que creen 2 opciones diferentes, seleccionen el que corresponda en la plantilla y listo. No hace falta cambiar estructura de modelo

**Comment by anajuaristi** [comment]
@alfredoavanzosc 
Alfredo, recupero esta solicitud de mejora en los test de calidad para preguntas de tipo cualitativo. Es una mejora pequeñita pero que permite poner en el listado de valores "buenos" y "malos"
Actualmente, solo se pueden poner valores buenos, y hay un ok por defecto. De esta forma, si se selecciona uno malo, le pone nok y si se coge uno bueno le pone ok, lo cual da mucha más flexibilidad.

**Comment by pedrobaeza** [comment]
Yo no lo veo. Lo que habría que hacer es que no ponga el OK cuando no tiene ningún valor (sea bueno o malo). Pero un no ok te lo da el que no hayas seleccionado una de las respuestas admitidas.

**Comment by anajuaristi** [comment]
@pedrobaeza 
Si, eso es... no ok cuando no hay respuesta o la respuesta es "mala".
Ahora no hay opción a poner respuestas "malas", si respondes, ya te da ok directamente. Ese es el cambio que hay que hacer.

**Comment by pedrobaeza** [comment]
¿Seguro que no hay la posibilidad de respuestas válidas? Es que ya me confundo con el módulo de v7 que adapté yo. Habría que haber partido de ése...

**Comment by anajuaristi** [comment]
No, no hay.
Cogimos el de 6.1 porque tenía una extensión bastante grande para el tema de las muestras por rangos de cantidad. El quality_extension

**Comment by pedrobaeza** [comment]
Habría que quitar ese nombre y poner _quality_control_samples_ o algo así. Extension nunca.

Entonces sí, hay que ampliarlo para tener los valores válidos. El problema de ser con un check es que hay que poner una tabla one2many nueva... Otra opción es con many2many tags.

**Comment by anajuaristi** [comment]
No.. no hace falta que el check esté en la relación pregunta / respuesta. Solo se añade en la opción "respuesta", se añade un campo ahí y listo. 
Si un mismo válor es válido en un test e inválido en el otro, que seleccionen el que corresponda en la plantilla del test

**Comment by pedrobaeza** [comment]
Pues a eso me refiero, que hace falta un one2many con:
- Boolean de válido o no.
- Many2one a respuesta.

**Comment by anajuaristi** [comment]
No... pero no hace falta eso.
O sea, en la tabla "respuestas", en vez de un único campo pones 2 campos.
La relación pregunta/respuesta en plantilla no cambia
La relación test/pregunta en plantilla no cambia

En el nombre de la respuesta pones algo que lo diferencie rojo (check ok) y rojo \* (check nok) 

Luego tanto en la pregunta en la plantilla seleccionas la que le toque de las dos. 
Y al hacer el test, cuando mete la respuesta, en la propia tabla de la respuesta seleccionada tiene el ok o nok. No hace falta más que añadir un campo en la respuesta.

**Comment by pedrobaeza** [comment]
Pues a esa tabla me refiero, Ana, que ahora mismo es un many2many a secas.

**Comment by anajuaristi** [comment]
Es que no veo que no tenga que seguir siendo un many2many a secas. ¿qué se me escapa?

**Comment by anajuaristi** [comment]
en el combo de respuestas tienes
verde, rojo_, azul, morado_, morado.... 
Seleccionas uno de ellos y para verificar si es ok o nok, miras en su tabla. ¿qué cambia?

**Comment by pedrobaeza** [comment]
Déjalo, Ana. Luego lo implementamos y ya está.

**Comment by anajuaristi** [comment]
Pero no te líes a meter un one2many a un nuevo objeto con 
check
many2one a respuesta porque NO hace falta para esto.

**Comment by pedrobaeza** [comment]
Es que para algunas preguntas, "rojo" será correcto, y para otras, "rojo" no será correcto. Tal como estaba, las respuestas se pueden compartir. De ahí el one2many.

**Comment by anajuaristi** [comment]
Yaaa... pero que para 2 únicos valores OK, Nok, no hace falta esta relación. 
Se crean las 2 respuestas una con OK y otra con Nok en la tabla y ya está. De ahí el tema de marcar el nombre con y sin \* para que el usuario diferencie. O puede ser rojo bueno y rojo malo... como ellos vean. 
Y cubre perfectametne y no tocamos ninguna estructura.

**Comment by pedrobaeza** [comment]
Uf, la gente se va a confundir. Creo que lo que deberíamos hacer es que las respuestas no se compartan entre preguntas, y así, además reducimos la lista a seleccionar, porque cuando haya muchas preguntas y respuestas, es inmanejable.

**Comment by anajuaristi** [comment]
No, no, no. no hagamos eso. Que obligas a configurar respuestas duplicadas y es más lío aún.
Y lo de las respuestas, que si se les explica, no es tan complicado. No tienen porqué liarse. Queda super-sencillo, no tocas nada y cubres el requerimiento, sin más.

**Comment by pedrobaeza** [comment]
Ana, es súper rápido introducir posibles valores. Mejor que elegir entre una lista de 200 mil respuestas. Vamos a probar de esta manera y ya verás como es mejor.

**Comment by anajuaristi** [comment]
Pedro... Coste beneficio.
Lo k dices es xambiar enfoque y estructura. No ganamos nada y se
desnormaliza el matenimiento de respuestas.
Lo k digo yo no rompe nada, no cambia nada y en 5m esta cubierto el
requerimiento.
Minimo producto viable. Para la criticidad que tiene y siendo mejora no
bug, de momento suficiente.

**Comment by pedrobaeza** [comment]
Ana, eso lo implemento en 5 min yo también. No desnormaliza nada. Lo otro, follón auténtico para el usuario. Lo dicho, déjame hacerlo para que lo veas.

**Comment by anajuaristi** [comment]
Como veas . Pero veras que lo tuyo tiene lio. Intenta meter en una
plantilla la misma pregunta con diferentes respuestas en cada plantilla.
Con un many2many como ahora es trivial. Con un one2many el lio esta montado.
No me parece mejora sino paso atras. Casi igual dejarlo como esta es hasta
mejor que eso

**Comment by anajuaristi** [comment]
Cierro esto que ya está hecho
