### ISSUE TITLE
Cuenta analítica y proyecto

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#350]
Hay varios puntos del sistema que está mostrando los campos cuenta analítica y proyecto.
En la mayoría de ellos se ha marcado obligatoria la cuenta analíca por lo que el primer impulso es crear la cuenta y luego rellenar proyecto, incluso está antes el campo cuenta que el de proyecto por lo que se llama al error ya que esto puede causar inconsistencias de integridad

Propongo no mostrar nunca la cuenta analítica, sino el proyecto. Hacer este campo obligatorio y en el onchange de este campo, si es necesario que estén los 2 asignar la cuenta analítica de forma oculta haciendo invisible el campo y evitando las posibles inconsistencias.
Puntos donde pasa esto, que yo haya visto, aunque pueden haber más:
.- Pedido de venta
.- Orden de fabricación
.- Orden de reparación, aparece solo cuenta... deberiamos unificar y mostrar proyecto tambien.

@pedrobaeza opinion?

**Comment by pedrobaeza** [comment]
Si algo está ahí en el estándar, hay que dejarlo, se llame cuenta o se llame proyecto. Se explica que son equivalentes y ya está, o a las malas se cambia esa traducción para el que no lo quiera así. Si un campo que añadamos nosotros es redundante, entonces sí que no hay que añadirlo.

**Comment by anajuaristi** [comment]
Si, dejarlo sí, pero podemos ponerlo no editable y hacer que cuando
seleccionen el proyecto, se informe automáticamente la cuenta del objecto,
con la del proyecto asignado para evitar inconsistencias. A esto me refería.
Hay puntos que es mejor meter proyecto, ya que si creamos cuenta analítica
y después proyecto, la cuenta del proyecto vuelve a crearse y la
inconsistencia viene sola.

El 21 de noviembre de 2014, 10:03, Pedro M. Baeza notifications@github.com
escribió:

> Si algo está ahí en el estándar, hay que dejarlo, se llame cuenta o se
> llame proyecto. Se explica que son equivalentes y ya está, o a las malas se
> cambia esa traducción para el que no lo quiera así. Si un campo que
> añadamos nosotros es redundante, entonces sí que no hay que añadirlo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/350#issuecomment-63942647.

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com soporte@avanzosc.com *

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
*_administracion@avanzosc.com
soporte@avanzosc.com *
_This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
soporte@avanzosc.com_

**Comment by pedrobaeza** [comment]
Ah, vale, si lo que apunta es a project.project, entonces sí.

**Comment by oihane** [comment]
A ver... por lo que veo, en el caso de las ordenes de fabricación, el módulo `mrp_project_link`
Añade dos campos `project_id` y `account_analytic_id` (este segundo requerido en la vista)
Si el proyecto no se asigna, busca el que le corresponde a la cuenta analitica o si no existe lo crea, enlazándolo a la cuenta analítica. Entiendo que si lo que se quiere es eliminar o esconder la cuenta analítica de la orden todo este proceso es innecesario, pero eso haría que fuese obligatorio seleccionar un proyecto, no?

**Comment by anajuaristi** [comment]
Si, exactamente.
La idea es unificar la forma de asignar un proyecto/cuenta analítica. 
Lo que asignas a una OF siempre tiene que ser un proyecto. La cuenta analítica puede quedar oculta.

La cosa esa rara que se hace, no es necesario. El standar, cuando creas un poryecto ya te crea una cuenta analítica. Utilicemos esto. 
Ahora bien, en el onchange del proyecto, sí hay que asignar la cuenta analítica a la OF, aunque sea de forma invisible.

**Comment by anajuaristi** [comment]
Perfecto
Solo se ve el proyecto en ventas y fabricación.
Al crear una orden contra pedido, arrastra el proyecto desde el pedido a la OF.
Muestra en SO0061, que ha generado OF MO00102
Cierro :+1:
