### ISSUE TITLE
Evaluación de opciones inmediata, onchange en test de calidad

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#36]
Pedro: Valorar si merece la pena o no hacer esto

Actualmente, se evalúan todos los valores metidos al grabar el test. Propongo que se evalúe cada opción, asignando ok, nok en el onchange del valor de la línea.

Además, sería muy visual si el OK fuese verde por ejemplo y el NOK rojo. Las que aún no se han evaluado (no tienen valor en los campos Qt o Ql, pueden quedarse en negro.

**Comment by pedrobaeza** [comment]
Lo suyo sería eso, evaluar cada uno por separado, con un campo function boolean. Después, la evaluación global sería tan sencilla como recorrer ese campo para todos los registros. Sobre los colores, no está mal, aunque el rojo y el verde quedan siempre muy chillones. Se puede probar a ver.

**Comment by oihane** [comment]
Actualmente funciona de la siguiente manera
Cada línea tiene un campo booleano denominado 'success', es un campo calculado que es True cuando el campo Qt o Ql es correcto según lo que se haya establecido. Si una línea no ha sido procesada o no es correcta este campo es False.
Cada test a su vez tiene un campo 'success' que cambia a True cuando todas sus líneas tienen el campo 'success' a True (antes se ponía a True cuando no tenía líneas pero esto ya esta solucionado)

Por lo tanto, no existe un campo que sea 'no OK', los test tienen también un estado que se cambia al confirmar y ejecutar y es cuando se distingue si un test es correcto o no realmente.

**Comment by pedrobaeza** [comment]
Un campo no OK no haría falta, ya que es si el valor es False. Sí que habría que distinguir cuándo está procesada de cuándo no. Se podría determinar sin necesidad de un campo si la respuesta es vacía, ¿no?

**Comment by oihane** [comment]
Si se puede, ya que hay dos campos que si no tienen valor es que no han sido procesados, pero a la hora de dar color, se podría hacer?

**Comment by anajuaristi** [comment]
correcto que no hace falta.
Lo que yo decía es que ahora, la evaluación de cada línea la está haciendo
al grabar el registro. Es decir que cuando introduces un valor, no evalua
si es ok, nok
La modificación sería que grabar, evalúe el estado global del test, pero
meter un onchange en cada línea para ver su evaluación individual online,
no a posteriori. No sé si me explico.
Por defecto, no se ha realizado cuando no hay valor ni en Ql ni en Qt. Si
hay un valor en alguno de los 2, es que sí que se ha hecho el test de línea.

El 27 de agosto de 2014, 10:42, Pedro M. Baeza notifications@github.com
escribió:

> Un campo no OK no haría falta, ya que es si el valor es False. Sí que
> habría que distinguir cuándo está procesada de cuándo no. Se podría
> determinar sin necesidad de un campo si la respuesta es vacía, ¿no?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/36#issuecomment-53541669.

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com soporte@avanzosc.com *

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
*_administracion@avanzosc.com
soporte@avanzosc.com *
_This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
soporte@avanzosc.com_

**Comment by pedrobaeza** [comment]
Ah, entendido. Buena idea. No sé si con los onchange de la nueva API valdría, o recurrir al onchange tradicional en el campo.

**Comment by anajuaristi** [comment]
Reasigno a @alfredoavanzosc ya que está tocando todo el tema de los test de calidad.
Alfredo: El tema es meter un on_change en los campos Qt y Ql, de tal forma que evalúe si la línea es Ok o Nok, en el momento que el usuario introduce un valor. Si es correcto pone la línea en verde, si no, la pone en rojo.
Sin más.

**Comment by anajuaristi** [comment]
@alfredoavanzosc 
Ya que hay que tocar los test de calidad para lo de los valores cualitativos, aprovechamos y metemos el onchange, que veo que aún no está incluido.

**Comment by anajuaristi** [comment]
Cierro esto que ya está hecho hace bastante :+1:
