### ISSUE TITLE
mrp_dump_production_create_wizard varios temas a tener en cuenta y modificar

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#360]
Acordado con Pedro vamos a hacer a este módulo las siguientes mejoras de usabilidad y cambios de enfoque:
1. En atributos de producto, añadiremos otro nuevo "tipo de atributo" que se denomine "envasado"
   A ese tipo de atributo, se le podrá asociar un "producto" en este caso, sería asociarle el producto que sea el envase vacío.
2. En la solapa de Download de la OF
   Meteremos un botón, que rellene la tabla de cantidades/envases/productos de la siguiente forma:
   .- (A) Buscamos todas las listas de materiales en las que el "granel" o producto base, sea componente (debe existir función en el sistema, ya que hay una entrada de menú "bom components" que muestra exactamente eso. En qué listas de materiales está presente el producto.
   .- Hay que eliminar campos que están de sobra y se dejan únicamente
   Producto, envase, cantidad, fill
   La tabla debe ser editable botton para poder modificar directamente el campo "cantidad" el resto serán NO editables y no se permitirá añadir líneas. Sí se permite borrar.
   Se creará en la tabla una línea cogiendo el producto final, de todas las listas de materiales encontradas en el punto (A) 
   Envase: Tomará el valor de la variante producto final
   Cantidad: rellena el usuario
   Fill: Calcula la cantidad de granel/base que se consume en función de la cantidad indicada (campo function) CUIDADO, cambiar el cálculo, para que en vez de coger cantidad de UL como hasta ahora, coja del campo numérico del atributo. 

Con esto, quedaría acabado el tema de indicar cuántos envases de cada tipo quiero obtener desde esa orden de granel/base

---

En la creación de las OFs, de envasado:
.- Con este nuevo enfoque estamos obligando a que en la lista de materiales del producto final, exista la relación con su granel/base, por tanto, hay que cambiar un poco el tratamiento de la línea de granel ya que no hay que volver a insertarlo, sino, solo calcular la cantidad que le corresponde consumir. 
Por tanto... la forma correcta sería:

Paso1: Crear OF
La cabecera de la orden, debe crearse con 
.- el "producto", indicado en la tabla del punto anterior. 
.- La cantidad será calculada de la siguiente forma:
    Si la unidad de producto final (en ficha de producto) es igual que la del granel --> Campo FILL
    Si la unidad de producto final es otra --> Campo Cantidad (asumimos que la unidad del producto final será unidad) Todo... Contemplar otras conversiones de unidad

Paso2: Calcular datos --> Permitir que el sistema traiga lo que haya en la lista de materiales de forma standar

Paso3: Insertar líneas de productos existentes en atributos --> 
NUEVA FUNCION que será añadida al "Calcular datos" --> Haremos una función que recorra todos los atributos del producto final, y para cada atributo que encuentre, que tenga un producto asociado, insertaremos una línea nueva en "productos planificados"
CUIDADO aquí... la cantidad de envases siempre es el campo "cantidad" del producto final, nunca el FILL
Y en cuanto a la operación a asignar, SIEMPRE Asignaremos la primera del proceso de la lista.

Paso4; Modificar cantidad del granel --> Asignar campo FILL 

Con esto, queda "supergenérico" y con muy poca configuración que deba hacer el usuario. Solo tiene que tener en cuenta asignar el producto envase vacío y rellenar correctamente la cantidad en la variante

@pedrobaeza, si estás de acuerdo lo paso a desarrollo tal cual

**Comment by pedrobaeza** [comment]
Bueno, pásalo, aunque ya sabes mis pegas.

**Comment by mikelarre** [comment]
Una pregunta para calcular el fill no es mejor que rellenen la cantidad en el bom del producto final que en el campo numerico del atributo?

**Comment by pedrobaeza** [comment]
Esa cantidad sería la capacidad del envase, por lo que no es lo mismo que la cantidad de envases que van a hacer.

**Comment by anajuaristi** [comment]
No no... precisamente... el granel lo pones en el BOM del template. Ahí no
sabes qué cantidad necesita cada envasado.
Si lo tuviésemos que hacer como dices (que es como lo tienen el 100% de los
ERPs actuales) estarías obligado a definiri una LM especifica por cada tipo
de envasado en cada producto final envasado
Y es lo que tratamos de evitar porque ese dato NO es necesario hasta lanzar
la OF y se puede calcular con una simple multiplicación, teniendo en cuenta
el envase requerido para envasar.

Este es uno de los puntos de infinita mejora en cuanto a la necesidad de
tener que definir LMs que no son necesarias, aparte de las LM template
contra template.

**Comment by anajuaristi** [comment]
Exactamente...
Y en la OF de granel indicas cantidad de envases a hacer y como el producto
final ya lleva qué cantidad necesita, el cálculo está hecho ya directamente

Ejemplo
Productos finales: Champu A 330, Champu A 500, Champu A 750

Todos llevan el mismo granel Champú A G --> Cuya lista de materiales
contiene, alcohol, aromas...etc... normal.. es igual para todos ellos.

La LM se definiría una única vez en Champú A que contiene Champú G y si
tuviese más cosas, como tapones, etiquetas y demás.. lo que tenga.

Por tanto la LM en este caso SOLO contempla la relación del producto final
plantilla con el granel.

Y ya está, no hace falta más. Con una única lista, evitas 3 en este caso,
pero evitas otros 3 en otro caso y N en otro caso.. evitas montón de listas
de materiales.

Luego al crear la OF de envasado la lanzas por
Champu A 300, 40 botes
Champú A 500, 20 botes... Así.

Qué lanza?????
Champú A 300, 40 en cabecera y luego en componentes a consumir:
     40 bote 300
     1200 Champu A granel
Perfecto y correctísimo...

**Comment by anajuaristi** [comment]
@mikelarre 
Cuidado que hemos modificado y generalizado el enfoque de paso 3, que ahora pasa a ser este:

Paso3: Insertar líneas de productos existentes en atributos --> 
NUEVA FUNCION que será añadida al "Calcular datos" --> Haremos una función que recorra todos los atributos del producto final, y para cada atributo que encuentre, que tenga un producto asociado, insertaremos una línea nueva en "productos planificados"
CUIDADO aquí... la cantidad de envases siempre es el campo "cantidad" del producto final, nunca el FILL
Y en cuanto a la operación a asignar, SIEMPRE Asignaremos la primera del proceso de la lista.
