### ISSUE TITLE
mrp_operations_extension : impossible to confirm a manufacturing order without no routing 

### ISSUE THREAD

**Issue by gaultp** [odoomrp/odoomrp-wip#364]
I cannot confirm any Manufacturing Order if there is no because of constraint: "At least one operation must have checked "Move produced quantity to stock"field"
Is it possible to disable this constraint in the case you don't need it?

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting.

You need to mark this check at operation level to indicate in which one final products are produced, because if there is no operation marked, produce move is not done. We should discuss internally if we can expand requirements to assume that if no operation is checked, the produce move is done at the end. I don't remember now if we reject this for some reason... What do you say, @anajuaristi?

**Comment by gaultp** [comment]
I understand the purpose. But in the case that there is no routing, there is no operation neither. So it is not possible to check at operation level, neither to confirm your manufacturing order.

**Comment by pedrobaeza** [comment]
Then, for what do you need _mrp_operations_extension_?

**Comment by gaultp** [comment]
Well, some MO have routing because I need to track operations, other MO don't need routing because I just transform my product without tracking operations.

**Comment by pedrobaeza** [comment]
OK, I get it. We are going to check this condition. Thanks for reporting.

**Comment by anajuaristi** [comment]
I agree with Gaultp
If one bom has no routing assigned, condition should not be considered.

Someone could want make MOs in standar way even if in some cases they want
to make MO by operations. I think we should accept it as bug and correct.

Thank you for reporting!!

**Comment by pedrobaeza** [comment]
@Daniel-CA, tienes que revisar esta incidencia. El problema es que cuando no se define ruta, no deja confirmar la OF. Hay ciertas OFs que pueden ir sin ruta, y en esos casos, no debe ser necesario revisar si alguna de las operaciones (que no habrá ninguna) tiene marcado el check de producir. ¿Entendido?

**Comment by gaultp** [comment]
Another suggestion, why don't you allow users to define the last operation by default in the routing configuration or to check directly in the MO form view what operation will be the last one.
These are just suggestions. Maybe it is going against the original purpose of your module?

**Comment by anajuaristi** [comment]
Purpose is that de operation moving final products to stock or any other location, could not be the last operation.
Maybe you need cleaning the machine or execute some quality test after production and MO could be not finished but final product has been moved.

There is a kind of operations that would have the "move product to stock" check marked, so in any route where that operation is used, will be the one to "move product to stock". 
Maybe check should be included on route or at less we should make it visible on route with a related field 
@pedrobaeza opinion?

**Comment by pedrobaeza** [comment]
The issue is solved is https://github.com/odoomrp/odoomrp-wip/commit/72653ca16a0ce9ea3b82e9a08a9eb69f877e3a4a
