### ISSUE TITLE
Edicion Productos a Consumir

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#370]
Enfoque técnico:
Módulo1: 
Añadir campo lote en "materiales planificados" en la OF. Al confirmar la OF, preasignar el lote indicado por el usuario, al movimiento correspondiente, siempre y cuando haya stock de dicho lote, en otro caso, dejar vacío. 

Módulo2: 
En "materiales planificados", añadir un check "adición" que significa "componente añadido una vez iniciada la orden" En la solapa "materiales planificados" añadir un botón "añadir material adicional" El botón sólo se mostrará en el caso de que la orden haya sido iniciada, en otro caso no. Al ser pulsado, mostrar un wizard, en el que el usuario pueda incluir un material, una cantidad ( en caso de que Modulo1 esté instalado, también mostrará un campo lote). Cuando el usuario pulse aceptar en el wizard: 1. La línea será añadida a "materiales planificados", con el check "añadido post-inicio orden" clickado. 2. La línea de movimiento será creada, de la misma forma que se realiza al confirmar una OF, sólo para la línea añadida por el usuario y se verificará su disponibidad. 

Módulo3: 
Módulo dependiente de operations_extension y de módulo2. En workorders, añadir un botón "añadir material adicional" que lanzaría un wizard similar al definido en el módulo2, a diferencia de que el campo workorder estára inicializado por sí mismo. En el wizard si se lanza desde "materiales planificados", permitir indicar la workorder a la que aplica. El procedimiento al aceptar el wizard, sería exactamente igual que el definido en el punto2. Con estos 3 módulos, el procedimiento sería "calidad, añade los materiales a agregar", por tanto ejecuta los wizard y los operadores consumen los materiales indicados de forma adicional, bien en la OF o en la workorder que haya indicado Calidad.

---

Comentarios Pedro:
Módulo 1: No se debe permitir validar la OF si no existe disponibilidad del material para ese lote. El usuario debe ser consciente que no se está cogiendo ese lote. Si desea continuar con otro, que elimine ese dato, pero no se puede eliminar silenciosamente un dato que el usuario espera tener.

Módulo 2: El botón debe estar en 'Productos a consumir', no en 'Materiales planificados', ya que la pestaña de control ahora es ésa.

**Comment by anajuaristi** [comment]
@pedrobaeza 
Sobre tu comentario 

Módulo 2: El botón debe estar en 'Productos a consumir', no en 'Materiales planificados', ya que la pestaña de control ahora es ésa --> Tiene una pega y es que los movimientos en sí, en principio no están asociados a una workorder y los productos planificados sí lo están.

Entonces, dijimos de meterlos en productos planificados y que los que se añadan a posteriori de iniciarse la OF, queden marcados con un check "adición". 

También habría un proceso que haga  lo que hace confirmar la orden (aplicado sólo a los productos de adición para crear automaticamente el moviento)

Si te refieres únicamente a que el botón que lanza el wizard esté en la solapa de consumir datos, no me parece mal, pero al tener que añadirse el producto en "materiales planificados" por eso lo pusimos ahí.

Por otro lado... ¿No sería mejor que estos botones de acciones estén todos arriba donde los botones de proceso en la OF en vez de en solapas ocultas?

**Comment by pedrobaeza** [comment]
Tal como acordamos anoche, el botón se puede quedar en la pestaña "Productos a consumir", aunque esa acción también tenga como efecto el añadir una línea en "Materiales planificados" con el check de "Añadido posteriormente".

El pasar los botones arriba se ha decidido de momento que no, para no confundir al usuario con su efecto principal.

**Comment by Daniel-CA** [comment]
Módulo 1: Una duda sobre el control del material del lote. 
Solo se podrán asignar lotes que tengan material disponible que se encuentre en la misma localización de la orden de producción desde el campo Raw Materials Location. Es decir si tengo lotes disponibles en otra localización que no es la definida en la orden de producción será como si no tuviera material disponible para ese lote. Eso es correcto?

**Comment by pedrobaeza** [comment]
Más que de disponibilidad en la ubicación de producción, sería en la ubicación origen (que en principio, si se selecciona la ubicación padre, sería en cualquiera). Después, cuando se hagan los stock.move de preparación, hay que hacer que ese lote se mueve ya a la ubicación de producción.

**Comment by anajuaristi** [comment]
Seria en la ubicacion de materias primas que esta definida en la propia
orden.
En principio todod los movimientos se crean con esa ubicacion origen

**Comment by Daniel-CA** [comment]
En las especificaciones del módulo 3 sería una vez la Work Order ha sido iniciada? Por que ahora mismo ya existe la opción de añadir productos a la misma, lo único que no se crea linea de movimiento ni de producto planificado.

**Comment by Daniel-CA** [comment]
Módulos en repositorio, cierro issue.
