### ISSUE TITLE
mrp_production_real_costs error en inicialización de campo

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#374]
Buenas... 

Al imputar una línea analítica, este módulo está informando los campos de costes estimados de la línea con coste_medio y coste_standar. 
Cuando se imputan tiempos reales, el valor en esos 2 campos debe ser cero siempre. Ya que si no se desvirtúan los datos, incrementando los costes estimados de la OF

**Comment by agaldona** [comment]
PR #386
He cambiado para que en el create de la línea, me cargue a cero esos campos.
De todas formas, he podido ver que en el módulo de costes estimados, hay un onchange, que al cambiar la cantidad te carga valores en ese campo. He pensado cambiarlo, pero no he sabido como diferencias una línea analítica de gastos reales, de otro tipo de líneas.
¿Alguna idea?  @anajuaristi @pedrobaeza

**Comment by anajuaristi** [comment]
Una linea de estimado tendria los campos de gasto real a cero y los
estimados con importe diferente de cero
y una linea de Gasto real tendria los campos estimados a cero e importe
diferente de cero.

Solo en el caso de que un estimado se quiera llevar tambien a real llevaria
importe real pero un gasto real nunca debe llevar los estimados diferentes
de cero.
¿Porque existe un onchange en producto para meter  estimados? Solo tendria
que coger el valor del campo e imputar estimados al confirmar la of pero no
veo necesidad de un onchange ahi.
Ya direis

**Comment by agaldona** [comment]
En el producto no, el onchange es de la línea analítica. 
De todas formas, con lo que me dices tampoco puedo asegurar cuales son las líneas reales y cuales no, quiero decir, el problema esta en que mete los gastos estimados en reales, y para evitar eso, no me puedo basar en los campos de gastos estimados. Y si me dices, que existe la posibilidad que se cargue el gasto real, en una línea de estimados, tampoco me puedo basar en eso. Ahí es donde tengo el problema.

**Comment by anajuaristi** [comment]
A ver... el módulo de costes reales, SIEMPRE los valores de la línea en costes estimados deben llevar cero. 
Y en la línea analítica NO DEBE HABER ningún onchange en ningún sitio. El módulo de costes estimados, al insertar la línea debe coger los 2 campos estimados de la ficha e insertar la línea, pero sin más. No veo la necesidad del onchange
Por otro lado, SOLO el módulo de costes estimados debe insertar líneas con costes estimados. Pero debe coger el valor puntualmente de la ficha al meter la línea en analítica. No cada vez que se meta una línea en analítica.

¿Se entiende?

**Comment by agaldona** [comment]
PR #387
He eliminado el código del onchange donde carga los valores estimados. He visto que en la creación de las líneas estimadas, ya les asigna valor.
