### ISSUE TITLE
Cierre de operación con test pendientes

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#378]
@alfredoavanzosc 

Hace tiempo ya se comentó que aunque una operación tuviese tests que no fuesen válidos, si estaban en estado incorrecto o correcto, la operación se podía cerrar.
Lo que no se permitía era que hubiese tests en borrador o pendientes de aprobación para cerrar. Había que realizarlos o borrarlos/cancelarlos.

El mensaje es :
Finalization Operation Error!
The Operation has quality test withoutQUALITY SUCCESS state

Sería más correcto: The operation has got a quality test in draft or aproval pending status please finish or cancel them.

**Comment by pedrobaeza** [comment]
Mejor: `There are quality tests in draft or approval pending state for this operation. Please finish or cancel them.`

**Comment by anajuaristi** [comment]
:+1: Mismamente...

**Comment by anajuaristi** [comment]
@pedrobaeza 
Con la nueva versión de calidad este issue ya no aplicaría pero... 
¿Como sería ahora para meter un test en una operación de calidad? Veo un disparador al finalizar OF, pero no veo la creación desde una OT o relacionado con una OT. 
¿Qué estoy haciendo mal? ¿Qué me falta?

**Comment by pedrobaeza** [comment]
Esto es algo a implementar, ya que yo no he tocado el módulo _mrp_operation_with_quality_test_. ¿Quién hizo este módulo originalmente? De todas formas, no puede ir a nivel de producto o categoría, ya que si se da en medio de una fabricación, todavía no se puede considerar es producto. Debe configurarse a nivel de ruta.

**Comment by anajuaristi** [comment]
Cierro este issue ya que con la nueva versión ya no aplica
