### ISSUE TITLE
Botón "crear test" en operación, crea test pero no lo enlaza a la OF ni a la op

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#380]
Aquí hay algo raro.
Si pulso el botón "crear test" en una op de calidad, crea perfectamente el test manualmente aplicando la plantilla.
El test, se visualiza bien en la pantalla, pero... si lo abro, los campos OF y OT no quedan enganchados, no se ven ni en el tree, ni en el form.
¿Como puede ser esto? Que en el tree de la workorder vea el test, pero en cambio el campo op del test no esté informado?

**Comment by alfredoavanzosc** [comment]
Faltaba por mover el ID de la producción, pero otra cosa.. .en el tree de test o en el formulario, no existe campo OT.

**Comment by anajuaristi** [comment]
Cierto que no está visible en el tree y en el form. Quizás sí debería estar visible.
Pero existir sí que tiene que existir porque en las workorders hay un one2many a test y se ven perfectamente asociados, por lo que no es posible que no exista el campo en el test.
Si se crea un test manualmente desde un workorder, dicha workorder pertenece a una OF, por lo que el campo debería ser informado automáticamente en el test. 

Activando el modo debug, el objeto al que a nivel usuario llamamos workorder, en el sistema sería  mrp.production.workcenter.line

En cualquier caso, los enlaces de cabecera del test cuando es creado manualmente no funcionan bien.
1. Si el usuario manualmente asigna el test a un movimiento cualquiera, automáticamente se debería informar el producto con el del movimiento.
Si el movimiento pertenece a un picking, el picking debería ser informado 
Si el movimiento pertenece a una OF, la OF debería ser informada
2. El campo categoría en el test, sobra
3. Si manualmente asigno un lote, el campo producto debería ser informado automáticamente
4. Si se asigna una OF, el producto debería ser informado automáticamente.
1. Los campos de enlaces, deberían estar en una solapa aparte y no en cabecera porque ocupan mucho y obligan a hacer scroll vertical.

@pedrobaeza --> ¿Opinión?

**Comment by anajuaristi** [comment]
Cierro. Ya no aplica
