### ISSUE TITLE
Complicado realizar el test cuando lo abro desde operaciones

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#381]
Creo que esto, mejor que el one2many sería mejor tener un shorcut al test.
La cosa es que los test que están en los one2many de las Ofs y los que están en operaciones, si hago click encima, al salir la pantalla emergente, se hace muy complicado meter datos. Salen muchos scroll y se "montan" unos campos sobre otros, sobre todo si hay preguntas cualitativas.

Me pregunto, si no sería mejor quitar los one2many y sustituirlos por unos shorcuts. De esta forma, podría clickar en el shorcut y me abriría la lista de tests asociados bien a la OF, si voy desde el shorcut de la OF , o bien los tests asociados a una operación, si voy desde la operación. 

De esta forma, el test se me abre en pantalla completa y lo puedo realizar sin mayor problema.
¿Como lo veis?

**Comment by alfredoavanzosc** [comment]
Como vosotros digáiis

**Comment by pedrobaeza** [comment]
Vale, pero el shorcut no va a inhibir que cuando se pulse sobre el resto de la línea se abra el formulario...

**Comment by anajuaristi** [comment]
Ya bueno. Eso si. Pero es una vez he navegado al test.
Habria que ponerle edit bottom a la linea de plantilla

**Comment by anajuaristi** [comment]
Comentando con la gente de OdooMRP hoy, les ha gustado la idea de poner shorcuts y quitar los one2manys tanto de la OF como de Operaciones

El tema quedaría como sigue:
1. En OF : Actualmente hay 4 shorcuts que muestran los realizados, creados... etc... Habría que poner un solo shorcut con toda esa información en el mismo botón.
2. HAY un bug en algún sitio con los Ids. En principio, los test de calidad deberían tener un id interno a la OF (para test generales que no estén asociados a operaciones) y un id a workorder (para los que son creados por operaciones). 
   Me da que algo hay mal con los ids de enlaces, porque los test creados por operaciones no se ven desde los shorcuts de la OF. No se enteran. 
3. Hay que añadir el mismo shorcut en operación. Se solicita que se muestre el test específico de esa operación y los generales de la OF, que no correspondan a otra workorder de calidad.

Con estas 3 cosas quedaría acabado
1. Adicionalmente, lo que comentamos de la usabilidad de plantillas de test... las líneas debería crearse mediante un edit bottom y no mostrar un form al meter nuevas líneas.

**Comment by anajuaristi** [comment]
Cierro también. Ya no aplica. Es un issue referente a la antigua versión
