### ISSUE TITLE
Checks de "éxito" editables en módulo de tolerancias (Quality)

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#382]
He visto lo siguiente:
En un test con tolerancias, ya realiza correctamente el cálculo de las líneas y el combo. 
Sale la línea en azul si está en el rango optimo y gold si está en rango admisible... ahora bien, al clickar el check para marcar si la línea es válida o no manualmente, no graba el valor. Graba inválido siempre. 

En cualquier caso, pienso que se puede volver a poner no editable.  Por defecto siempre no ok si la línea no es verde (entre min y max) y no permitir cambiarlo. 

Si se instala el módulo "put_valid" (a este hay que cambiarle el nombre sí o sí) ya marcamos que el test es válido, en principio, no haría falta que cada check de cada línea se marque de forma individual. Ahora el combo de estados da mucha más información que antes y creo que con la validación manual global del test bastaría. ¿Opinion?

En cuanto al put_valid, esta misma mañana funcionaba perfectamente. Es decir, si marco el check valid, al confirmar el test y validarlo, pasa a estado correcto y si no, depende los cheks de las líneas. Pues ya no lo hace. Pasa a incorrecto aunque el chek valid esté clickado. 

Por último, la columna "respuestas" que muestra el listado de valores cualitativos está de sobra, porque ya me sale el combo para elegir valores en el campo que toca. Este campo lo quitaría. Ocupa espacio, muestra los valores en un recuadro "raro" y quita bastante usabilidad.

**Comment by alfredoavanzosc** [comment]
Ana... ponte en contacto conmigo, porque el check de ok/no ok en mi sistema no esta editable, no entiendo nada de nada.

**Comment by anajuaristi** [comment]
@alfredoavanzosc ... yo sí que a veces no entiendo nada. 
Mira aquí https://github.com/odoomrp/odoomrp-wip/pull/237

Hace pocos días que hemos tenido esa conversación. No me puedo creer que no te acuerdes. 

La cuestión... que al final tiene razón en lo que dice @pedrobaeza que no es necesario que se especifique ok/nok en cada línea, sino que es suficiente con que se marque válido el test entero
Y esto lo hace el módulo put_valid 

O sea que habría que dejar de nuevo los checks de línea no editables y hacer que funcione put_valid porque ahora mismo siempre todos los test se van a error, si existe alguna línea en Nok.

**Comment by pedrobaeza** [comment]
Esto no aplica ya con la nueva refactorización.
