### ISSUE TITLE
Duplicar tareas da error de clave única

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#389]
Buenas... 
El módulo de asignar secuencia a tareas de proyecto impide poder duplicar tareas y también está impactando en la delegación de tareas del standar, ya que esta funcionalidad utiliza a su vez la de duplicar. 
Da un error de restricción de clave única.
Gracias.

**Comment by pedrobaeza** [comment]
Ese módulo está en la rama de Avanzosc (https://github.com/avanzosc/avanzosc/tree/master/project_task_code), así que mueve el issue allí.

**Comment by anajuaristi** [comment]
Y no es mejor pasr el modulo a wip?
La numeracion de tareas me parece una funcionalidad supergenerica para que
no este en wip. Ya diras.

**Comment by pedrobaeza** [comment]
Es una tarea que no tiene nada que ver con MRP. No debería estar aquí, aparte de por lo pequeño de su funcionalidad.

**Comment by oihane** [comment]
https://github.com/avanzosc/avanzosc/pull/5
