### ISSUE TITLE
Acciones correctivas de no conformidades no se ven

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#39]
Corrective Actions no es corrective actions, sino que es un número de no conformidad. La secuencia es un número de no conformidad.
Esta no conformidad, incluye varias acciones de solución, con un estado, responsable y demás.
Al abrir la no conformidad (para la que la secuencia se crea bien y todo), el one2many de las acciones correctivas no se visualiza en el form de la no conformidad.

El tree y menú de corrective actions, sí que está, pero en el form, no muestra ni el claim, ni la no conformidad, por lo que no se pueden asignar correctamente. No tiene sentido tener acciones correctivas "sueltas" que no pertenecen a una no conformidad, y por ende a una reclamación.

Premisas funcionales:
Pueden exisitr reclamaciones, para las que no se genere una no conformidad, pero nunca al revés. una no conformidad, siempre se crea desde una reclamación.
Las no conformidades deben estar numeradas en orden, sin huecos y deben constar las acciones correctivas que se llevaron a cabo para solucionar el problema, indicando responsable y fecha en la que se realizó la acción.
No está migrado completo, aunque casi.

**Comment by oihane** [comment]
El modulo que esta en nuestro repositorio es lo que he pasado, a no ser que tenga otro modulo adicional, eso que dices que no está migrado completo no lo entiendo.

**Comment by anajuaristi** [comment]
Al meter el one2many en la acción correctiva, ahora se ve la tabla de acciones, pero, al crearse la acción correctiva, debería "copiar" de la acción introducida, las acciones correctoras por defecto asociadas a esa acción en la tabla. 
Esto no lo hace. 

Si en el sistema se ha establecido que el problema ha sido provocado por una causa y se ha "predefinido" que dicha causa se soluciona mediante ciertas acciones correctoras, estas deberían ser copiadas de base, aunque luego se permita meter más, o eliminar o definir manualmente las que haga falta en la acción correctiva. 
Me mosquea que esto no lo haga porque el requerimiento de desarrollo para 6.1 era así.

**Comment by oihane** [comment]
Relacionado con PR #29

**Comment by anajuaristi** [comment]
Cierro... se arregló hace tiempo ya.
