### ISSUE TITLE
procurements_plan

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#392]
Importar abastecimientos no hace nada.
Está mal el filtro. 

Propuesta, quitar el filtro y traer todos los abastecimientos entre las 2 fechas del plan que no estén asignados previamente a ningún plan. Sin más.

---

Segundo problema, al pulsar el botón ejecutar, se queda colgado. No hace nada.

---

Tercero, 

En principio, un abastecimiento, crea una única orden de fabricación (este Id se muestra en la solapa info-extra del propio abastecimiento) , por lo tanto, si la OF, ha sido creada por un abastecimiento incluido en el plan
.- Al crearse la OF, habría que asociarle el Id del plan
.- Asociarle también el proyecto del plan
.- Asociarle la cuenta del proyecto del plan

No he podido llegar a probar esto porque el botón ejecutar no funciona.

---

En cuanto a las compras creadas, el módulo muestra un one2many a compras, pero no es posible que sea un one2many ya que 2 abastecimientos diferentes pueden estar linkados a una misma compra.
Por lo tanto, y puesto que no es posible asociar un único plan a una compra, no es posible tampoco asociarle un Id de plan, por lo que veo más correcto que en vez de una solapa con un one2many exista un shorcut en el plan, que me lleve al tree de compras, pero filtradas únicamente las que están relacionadas con los abastecimientos incluidos en el plan.

Al igual que en las OFs, cuando un abastecimiento crea un pedido de compra o bien incluye cantidades o modifica uno existente, este pedido de compra se muestra en la solapa info-extra del abastecimiento por lo que el filtro del shorcut habría que montarlo sobre este campo.

**Comment by anajuaristi** [comment]
@pedrobaeza necesitaría que le eches un vistazo al tema del plan.
Hoy comentando en la sesión y explicando los problemas que tiene, me han comentado que aun así sigue siendo útil como una herramienta de agrupación de abastecimientos y planificación semanal, por lo que he pensado darle otra vueltilla y acabar ya con ello.

La diferencia estaría en que el botón ejectutar, ejecuta planificadores. Y el plan como tal sería un "aglutinador" de procurements. O sea, es como agruparlos en bloques semanales sean del tipo que sean.

**Comment by pedrobaeza** [comment]
Entiendo que esto tampoco aplica con los últimos cambios de Ainara/Mikel. Si no es así, se vuelve a abrir.
