### ISSUE TITLE
Crear repositorio odoomrp-utils

### ISSUE THREAD

**Issue by pedrobaeza** [odoomrp/odoomrp-wip#393]
Para albergar todos los módulos con alguna pequeña funcionalidad, cambios en el interfaz, etc, y mover a ese repositorio varios de los módulos actuales, junto con varios PRs así indicados. Tareas:
- [x] Crear repositorio odoomrp-utils.
- [x] Poner Travis y demás.
- [x] Indicar en el README de odoomrp-wip la existencia de ese otro repositorio y su uso.
- [ ] Mover módulos ya puestos en odoomrp-wip a ese otro repositorio. El criterio para moverlos ya debes saber cuál es, pero si dudas en alguno, dímelo.
- [x] Mover PRs de módulos que cumplan también el criterio a ese otro repositorio.

**Comment by oihane** [comment]
#399

**Comment by oihane** [comment]
Listado de módulos a mover:
- [x] purchase_products_sc
- [ ] base_partner_references
- [ ] crm_claim_corrective
- [ ] crm_claim_links
- [ ] mrp_bom_catch_product_code
- [ ] mrp_bom_component_change
- [ ] mrp_bom_notes
- [ ] mrp_bom_version
- [ ] mrp_product_variants_types
- [ ] mrp_production_editable_scheduled_products
- [ ] mrp_production_notes
- [x] mrp_stock_quant_shortcut
- [ ] mrp_wizard_filter_task
- [ ] mrp_workcenter_workers
- [ ] partner_control_fields_view
- [ ] product_attribute_types_views
- [ ] product_attribute_views
- [ ] product_category_in_header
- [ ] product_last_mrp_info
- [ ] product_last_price_info
- [ ] product_m2mcategories
- [ ] product_packaging_views
- [ ] product_price_history
- [ ] product_pricelist_import
- [ ] product_supplierinfo_for_customer
- [ ] product_suppliers_from_category
- [ ] product_type
- [ ] product_variant_default_code
- [ ] purchase_last_price_info
- [ ] purchase_order_last_prices
- [ ] purchase_requisition_display_order_line
- [x] purchase_stock_quant_shortcut
- [ ] sale_delivery_date
- [ ] sale_documents_comments
- [ ] sale_last_price_info
- [ ] sale_order_last_prices
- [ ] sale_order_line_dates
- [ ] sale_order_line_view
- [ ] sale_proforma_report
- [x] sale_stock_quant_shortcut
- [x] stock_lot_notes
- [x] stock_picking_visible_scheduled_date
- [x] stock_quants_shortcuts
