### ISSUE TITLE
operations_extension y boms con componentes phantom

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#394]
Cuando en el BOM existe una línea con un producto tipo phantom, en la OF se sustituye correctamente el producto por sus componentes pero los componentes no quedan linkados a la operación especificada para su producto origen en el bom.

Ejemplo:
Producto prueba variante contiene una línea PC ensamblado SC234, de tipo phantom y lleva asociado "operación 4" de la ruta
A su vez PC ensamblado SC234 tiene asociado un BOM tipo phantom con una serie de componentes

Al crear una OF, y pulsar calcular datos, la línea PC ensamblado SC234, es sustituida por todos sus componentes, pero no quedan asociados a la operación4, sino que el campo operación queda vacío.

**Comment by oihane** [comment]
Esto lo tienes listo para testear

**Comment by anajuaristi** [comment]
Cierro esto. Resuelto en principio hace tiempo.
