### ISSUE TITLE
Campo nombre en numeración de workorders

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#395]
Actualmente las workorders, al crearse se nombran
"nombre operación" - "secuencia" 

Siguiendo convenciones, sería más correcto nombrar "secuencia" - "nombre operación"
Lo ha comentado ALM en el issue CLM0056 Cambiar orden en nombre Orden de Trabajo

Ahora sale Pintar - 1, Soldar - 2 y solicitan que sea 1-pintar, 2-soldar 
@pedrobaeza ¿Cambiamos la forma que se crea el nombre en operation_extension? Creo que lo que dicen tiene más lógica, aunque en el fondo es lo mismo pero creo que se ve más claro, sobre todo si el nombre de operación es un poco largo.

**Comment by pedrobaeza** [comment]
Me parece correcto.

**Comment by oihane** [comment]
En realidad es una cosa de Alm... cierro
