### ISSUE TITLE
Creación automática de reclamaciones desde test erroneo

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#396]
Al aprobar un test de calidad, si es OK, se va a calidad correcta y si es NOK se va a calidad incorrecta.

Se solicita que si un test tiene líneas incorrectas, automáticamente se generen las reclamaciones correspondientes para dichas líneas (una reclamación por cada línea incorrecta, azules, gold o rojas), siempre que la plantilla en la que esté basada, lleve clickado "incidencias automáticas"

---

Requerimiento de cliente:

1--MAPA Control de Calidad...Plantillas de Test...Plantilla del Test
     Se solicita un Campo Check para definir si una Plantilla de Test genera o no una incidencia (IDI/NC)

2--MAPA Control de Calidad...Tests...Tests
     Generación IDI/NC
     Se genera IDI cuando la línea esté en colores  Azúl o GOLD.
     Se genera NC cuando la línea esté en color Rojo

Siendo IDI y NC, categorías de reclamación.

---

Enfoque técnico: 
Añadir a plantillas de test el campo "incidencias automaticas": check

Al aprobar test --> 
   .- Si el test tiene líneas en estado diferente de Ok --> generar reclamación
   .- Si la línea es amarilla o azul --> reclamación categoría IDI.
   .- Si la línea es roja --> reclamación categoría NC y además crear NC asociada a la reclamación

@pedrobaeza lo subo a wip porque la creación de incidencias para los test incorrectos era lo que faltaba para cerrar el ciclo de calidad y se pidió también algo similar en wip por lo que creo que debería ser genérico. El nombre del módulo podría ser quality_claim_link, aunque a tí se te dan mejor los nombres.

Asigno a @alfredoavanzosc para su vuelta

**Comment by pedrobaeza** [comment]
Ana, sobre esta reclamación, pregúntame luego por chat.

**Comment by alfredoavanzosc** [comment]
Para cubrir este requerimiento se han realizado los módulos "quality_claim_link", "quality_line_claim_link", y "crm_claim_corrective_nc". El PR es el https://github.com/odoomrp/odoomrp-wip/pull/551

**Comment by anajuaristi** [comment]
Cierro... ya se ha mergeado
