### ISSUE TITLE
[Calidad] Sobre a qué tener efecto los tests

### ISSUE THREAD

**Issue by pedrobaeza** [odoomrp/odoomrp-wip#40]
En las plantillas de test, sólo se puede seleccionar un producto y/o una categoría.

Primero, habría que aclarar bien en pantalla (directamente con un texto de párrafo en la vista), diciendo que si selecciona un producto y una categoría, se hará el test para ambas cosas (y si éste no es el comportamiento, debería serlo).

Además, deberían cambiarse los campos a un many2many, para poder decir que un test se puede hacer a más de un producto/categoría. Un escenario típico es realizar un test a una categoría y unos pocos productos de otra categoría.

**Comment by anajuaristi** [comment]
Pues justamente eso han pedido hoy en la sesión y les he dicho que no, de
momento, que era complicado incluirlo en el alcance para diciembre, que
teniamos cosas más urgentes que esta por hacer pero sí, sería interesante.
¿Mismo proyecto o fase2?
Ya dirás

El 27 de agosto de 2014, 10:27, Pedro M. Baeza notifications@github.com
escribió:

> En las plantillas de test, sólo se puede seleccionar un producto y/o una
> categoría.
> 
> Primero, habría que aclarar bien en pantalla (directamente con un texto de
> párrafo en la vista), diciendo que si selecciona un producto y una
> categoría, se hará el test para ambas cosas (y si éste no es el
> comportamiento, debería serlo).
> 
> Además, deberían cambiarse los campos a un many2many, para poder decir que
> un test se puede hacer a más de un producto/categoría. Un escenario típico
> es realizar un test a una categoría y unos pocos productos de otra
> categoría.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/40.

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com soporte@avanzosc.com *

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
*_administracion@avanzosc.com
soporte@avanzosc.com *
_This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
soporte@avanzosc.com_

**Comment by pedrobaeza** [comment]
No es complicado de hacer, y lo veo básico. Cambiar dos tipos en los campos, y luego cambiar el search para buscar si afecta. Un = por un IN. Deberíamos hacerlo. Luego le dices que al final hemos sido buenos y lo hemos puesto :stuck_out_tongue:

**Comment by anajuaristi** [comment]
@alfredoavanzosc 
Otra solicitud de los módulos de calidad... Habría que modificar el many2one a producto y a categoría de las plantillas del test por un many2many.

Luego cuidado porque el módulo de muestras, tendría que buscar entre esos many2many. La búsqueda ya no sería directa.
ANTES de programar esto, ver impacto en la creación automática de tests. Creo que sólo afecta al módulo de muestreo y no a los test que se crean desde las operaciones de la OF, pero Alfredo  mira a ver si es así. Ante cualquier duda de romper otras cosas... no tocar que de momento no es prioritario, se puede hacer más tarde.

**Comment by pedrobaeza** [comment]
La búsqueda se hace igual sobre many2many que sobre many2one, así que no debería haber demasiados problemas. Eso sí, no sé si el operador '=' valdría o habría que poner el operador 'in' (aunque resulte la expresión al revés - `('products', 'in', product_id)`).

Ahora que hablas de many2many, habría que aprovechar para colocar en la ficha de producto esa tabla many2many con los tests que se hayan asignado, o un botón controlador de los nuevos de v8, indicando el nº de tests y que al pulsarlo, te lleve a ellos (esta opción casi me gusta más, para no saturar las pantallas).

**Comment by anajuaristi** [comment]
Cierro esto, que en la nueva versión de los módulos de calidad ya se puede utilizar el mismo test para diferentes categorías, templates o productos
