### ISSUE TITLE
CLM0117 Duplicacion de productos/plantillas en lineas de pedido

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#406]
@oihane 

Al duplicar una línea de pedido que sea un artículo proveniente de una plantilla, debería de mostrar el configurador de producto para poder cambiar valores en los atributos. 
En el desarrollo actual no muestra el configurador de producto al entrar en la línea del producto duplicado.

**Comment by oihane** [comment]
Resulta que en su momento puse el atributo "copyable" pero parece que o me equivoque o lo han cambiado a "copy", se ha hecho el cambio en sale, purchase y mrp

**Comment by oihane** [comment]
Cierro, aún esta en el sistema de gestión
