### ISSUE TITLE
Actualizar precio quant en purchase_landed_cost

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#410]
Se solicita que al modificar el precio medio del producto en su ficha, se modifique también el precio medio del quant que crea la línea de movimiento para evitar inconsistencias en ambos puntos.

**Comment by pedrobaeza** [comment]
Solucionado y mejorado en https://github.com/odoomrp/odoomrp-wip/commit/afb89d0cdc54773d6e68c1e4a1d1b77c3f4aa7b0.

_ADVERTENCIA:_ Para que el precio de coste del producto se actualice, hay que tener precio medio puesto (como es lógico). Antes, se machacaba el valor sin más.

**Comment by anajuaristi** [comment]
Sobre esto y segun vimos con dsn... En V8 se incorpora en core un nuevo
metodo de calculo en la ficha de producto y es el calculo real.
La diferencia es que el precio medio actua sobre todos los quants
existentes del producto asignando el precio medio a todos igual.
Si el metodo seleccionado es real solo modifica el quant afectado
No se como impactaria esto en el modulo landed cost, ni siquiera si
impactaria pero lo apunto para que le demos una vuelta al realizar las
pruebas.

**Comment by pedrobaeza** [comment]
No tiene nada que ver. El cálculo del precio medio/real sólo afecta al campo standard_price, no a los quants.

**Comment by anajuaristi** [comment]
Si. Si que afecta. Lo que valora inventario es el quant y al realizar
movimiento de entrada se valora el quant en funcion del metodo elegido en
el producto.
Y como digo si es a medio se modifican todos y si es a real solo el quant
afectado.
Verificado con dsn hace unos dias que tuvimos que probar por un tema suyo

**Comment by pedrobaeza** [comment]
No, cada quant entra con su valor de price_unit del stock.move o del producto en caso de que no exista éste.

**Comment by anajuaristi** [comment]
Si es real si pero si es a medio se recalcula el valor de todos los quants
existentes
Al menos con productos trazables funciona asi.

**Comment by anajuaristi** [comment]
De todas formas no tiene sentido discutir. Dejame mañana probar todos los
casos en runbot y a partir de eso vemos si hace falta retocar algo o no

**Comment by pedrobaeza** [comment]
Bueno, no hace eso, mira:
- Éste es el código que se llama para actualizar el precio del quant:
  https://github.com/odoo/odoo/blob/8.0/addons/stock_account/stock_account.py#L77
  A este mismo método lo llamo yo, por lo que cualquier cosa que haga éste o heredados, lo replico.
- Este método actualiza el precio del producto:
  https://github.com/odoo/odoo/blob/8.0/addons/stock_account/stock_account.py#L291
  Que sólo actúa sobre el campo standard_price y cuando el método es precio medio
- Y por último, éste es el que actualiza el precio del movimiento cuando el método es real:
  https://github.com/odoo/odoo/blob/8.0/addons/stock_account/stock_account.py#L315

**Comment by nestoravalos** [comment]
Hola a todos, a ver si me pueden orientar con el siguiente detalle con la actualización del campo "Precio coste (standard_price)".

Mi configuración es la siguiente:
1. Valoración del inventario en tiempo real.
2. Método de coste: Precio medio.

Pero esté último nunca se actualiza durante las compras, lo que hace que todos los movimientos de contabilidad los haga con el Precio Coste que se le indique. Si se deja en 0 todos los movimientos de venta salen a costo cero. 

En el Quant si se actualiza el campo 'Precio de coste (variante) ' de forma correcta, pero el registro contable no lo hace con esté lo hace con el Precio Coste del Producto.

No sé si tenga que actualizar algún módulo, porque ya realice muchas configuraciones y ninguna hace de forma el cálculo de Valoración del Inventario con Método de Coste Promedio.

Espero me puedan orientar, de antemano gracias.

Saludos.

**Comment by pedrobaeza** [comment]
Este módulo no contempla por el momento la actualización contable, ya que en España no se hace. Habría que ampliar desarrollo para cubrirlo, lo que por el momento no está planeado.

**Comment by nestoravalos** [comment]
Ok gracias Pedro.

Me pudieras orientas sobre cuales objetos o módulos se debe trabajar para que haga la actualización en la contabilidad?

De antemano gracias.

Saludos.

**Comment by nestoravalos** [comment]
Otra pregunta, porqué cuando el Método de Coste es Precio Real si actualiza el Precio Coste (standard_price), por lo cual la contabilidad queda correcta.

Creo que si me pudieras orientar con el objeto que utilizan para realizar estás actualizaciones, sólo tendriamos que agregar el código para actualizar el Precio Coste cuando el Método de Coste es Precio Real, cómo ves Pedro?

Quedo a tu órdenes para cualquier comentario.

Saludos.

**Comment by pedrobaeza** [comment]
Hay que actualizar este módulo, pero es una cuestión de observar el código del módulo stock_account y cambiar este código en consecuencia.

**Comment by nestoravalos** [comment]
Ya realice los cambios Pedro, pero me surgio otra pregunta, porque cuando es una DEVOLUCIÓN DE COMPRA no  se actualiza el campo 'cost_price' del Quant, yo puedo tener una operación de compras/ventas sin devoluciones y esté campo se actualiza correctamente, pero al momento de realizar una devolución de compra, no lo actualiza, a ver si pudieras orientarme un poco con está parte. Saludos y gracias de antemano.

**Comment by pedrobaeza** [comment]
Esa duda la tendrás que plantear con Odoo, ya que es cosa del estándar.

**Comment by nestoravalos** [comment]
Ok gracias Pedro, saludos!
