### ISSUE TITLE
purchase_requisition_auto_rfq disponible en entornos

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#415]
He eliminado order generator de demo y la ofi. En alm no lo tienen instalado, por lo que podríamos proceder a instalar el de la comunidad (purchase_requisition_auto_rfq) + el nuevo purchase_requisition_display_order_line #361

@oihane Solicito por favor, que pongáis disponible el módulo purchase_requisition_auto_rfq en todos los entornos ya que aún no he podido probarlo, ni por tanto, tampoco la extensión nueva.
En cuanto a #356 ya lo he cerrado para que no moleste.

**Comment by oihane** [comment]
En el entorno de la Ofi ya estaba

**Comment by oihane** [comment]
@anajuaristi has comprobado si ya está? creo que ya lo incluí en todos, si no dime que entorno que lo pongo :wink:
En caso afirmativo, cerrar el issue

**Comment by anajuaristi** [comment]
Si. He  visto que ya está en demo. 
Cierro issue
