### ISSUE TITLE
Extensión LM para control por operaciones

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#42]
Buenas... 
Remito esta tarea que aún estando en mi cabeza parece que no estuviese escrita en las tareas de fabricación.

Continuando con el tema de maestro de operaciones y rutas requerimos:

**En el listado de materiales a consumir: un many2one a línea de ruta**

Adicionalmente como extensión del módulo by products lo mismo, en el listado de productos adicionales a producir: un many2one a línea de ruta.

---

En la OF, requerimos el mismo many2one en los siguientes puntos:
- Listado de productos planificados
- Listado de productos a consumir / consumidos
- Listado de productos a producir/producidos

Al crear la orden, se inicializarían las ops desde lista de materiales en la solapa lista de productos planificados.
Al confirmar la orden, cuando se crea el listado de productos a consumir y los de a producir, se inicializa la operación con la que marcase el listado de productos planificados.

**Comment by Daniel-CA** [comment]
He visto que la tarea de Maestros: Operaciones esta en diseño pero no en desarrollo, pego aquí lo que tiene definido y comentamos.

Se requiere un maestro de operaciones.
Cada operación deberá tener al menos un código y una descripción.

## Las operaciones podrán ser utilizadas para ser incluidas en un orden determinado en un proceso o ruta de fabricación o de proyectos.

Tareas a realizar:
Crear una tabla maestra con los siguientes campos:

```
Codigo
Descripción
Pasos relevantes
Asociación many2many con "etapas" 
Campo entero "Número personas", inicializado a Cero
```

Objetos relacionados con el maestro de operaciones:

```
Tareas: incluir un many2one a maestro de operaciones
Linea de rutas de producción: incluir un many2one a maestro de operaciones 
Máquinas: incluir un many2many a maestro de máquinas
```

**Comment by Daniel-CA** [comment]
Tengo una duda a la hora de relacionar las Operaciones en las rutas.
Una misma operación se puede hacer en una misma ruta en diferente secuencia?
Es decir si yo tengo las operaciones OP1 - OP2 y los Work Center WC1 - WC2 - WC3 se puede dar el caso que en la ruta sea:
1. OP1 - WC1
2. OP2 - WC2
3. OP1 - WC3 (o en el WC1 por rizar más el rizo)

Si esto es así como relaciono las Work Orders con los Scheduled products.

Relacion de objetos:
OP - mrp.routing.workcenter
WC - mrp.workcenter
Work Order - mrp.production.workcenter.line
Scheduled products - mrp.production.product.line

**Comment by pedrobaeza** [comment]
Sí, se debería poder permitir. El tema es que la referencia en Scheduled products no es al workcenter en si, si no a _mrp.production.workcenter.line_.

**Comment by Daniel-CA** [comment]
Correcto, el tema es que hay una función cuando hace el calculo en la  OF que se llama bom_explode-
En esta función me calcula las lineas de producción de producto por un lado (mrp.production.product.line) y las Work Orders (mrp.production.workcenter.line).
Como se a que Work Order pertenece cada linea de producto a producir si la única referencia que tengo a la operación viene en el nombre de la Work Order ( Nombre Operacion + Nombre producto a producir).

**Comment by pedrobaeza** [comment]
En la LdM hay que poner la referencia a lo que tengas en _mrp.routing.workcenter_. Si ahí se han duplicado los workcenters, de esa forma se sabrá. Tú tienes el id de ese registro de _mrp.routing.workcenter_, además de los datos que dices (nombre y código), y así es como debes hacer el matching. Cualquier otra forma no es la adecuada.

**Comment by Daniel-CA** [comment]
Ok, sabemos cada linea de Produccíon de producto (mrp.production.product.line) que mrp.routing.workcenter le corresponde según el producto que se va a consumir, el problema es relacionar esa linea de producción de producto con la Work Order (mrp.production.workcenter.line), ya que no tengo una referencia especifica en este objeto.
La Work Order no tiene una referencia clara a mrp.routing.workcenter, como digo solo tiene la referencia que viene en el nombre, y veo un poco chapuza ponerme a cortar strings.

**Comment by anajuaristi** [comment]
Paramos un poco aquí a darle una pensada.
Este era un problema gordo en OpenMRP.

Premisas.
- Maestro de operaciones --> operation_id con link many2many a máquinas.
  Implica que una operación que puede estar en varias rutas es posible
  hacerlo en varias máquinas.
- En una ruta, una línea de operación SOLO me deja especificar una única
  máquina --> bippppp... error porque no cuadra el maestro con lo que luego
  hacemos en la ruta. Si quisiéramos configurar esto con lo que hay ahora
  tendríamos que tener una combinatoria de rutas y máquinas duplicando rutas
  y sería inmanejable. Fijaos que los parámetros de coste y tiempos pueden
  variar en función de la máquina en que se haga la tarea.
- Lío montado,  si intentamos linkar la workorder a una línea de la ruta

Modificaciones propuestas (a validar)
- Montamos un módulo extensión: permitir rutas con varias máquinas. El
  standar SOLO permite una máquina y listo. Todos los parámetros de coste y
  todo se pueden llevar a la ruta para esa máquina.
- En el nuevo módulo: Ocultamos el campo máquina de la línea de ruta y
  montamos un one2many a "posibles máquinas" con los siguientes campos:

Maquina: many2one a work centers (maestro)
Campos de coste: ciclos, horas... etc,etc... (los varios campos que hay en
la propia máquina en la solapa extra-info)
Por defecto o secuencia: La secuencia marcaría la máquina prioritaria o si
ponemos un check, marcaría qué máquina es por defecto.
- En el onchange de la operación, al seleccionar una operación en la
  línea, traemos del maestro al nuevo one2many todas las máquinas posibles
  con sus parámetros de coste inicial, tiempos y demás.

Listo... punto de configuración arreglado.

Ahora, vamos a la operativa

Al confirmar una orden de fabricación, en la workorder hay un link a
máquina directo.
Solo hay que inicializar este valor con el id de la máquina que se haya
marcado por defecto en la línea o bien, el que tenga secuencia 1.
No hay desarrollo.
Al hacer el cálculo de costes, se puede acceder a todos los campos para
llegar a los valores indicados en el maestro, ya que tenemos Operación y
máquina. Al estar "suelta" la máquina podriamos elegir otra. Por tanto
- Si se quiere cambiar la máquina en el workorder: SOLO hay que limitar
  el domain a las que están en el listado en la línea de la ruta. Se puede
  llegar desde workorder.OF.BOM.RUTA o bien directamente Workorder.OF.RUTA
  seleccionando por id_operación e id_maquina.
- Si queremos evitar tanto lío, podriamos añadir un link directamente en
  el workorder a línea de máquina dentro de la ruta  en vez de directo a
  máquina(maestro global).
- Igual este es el punto porque en realidad los costes de máquina están
  linkados a una ruta, los del maestro global no valen para nada.

Es más, creo que esto debería ser la solución standar, incluso cuando hay
una única máquina y nos evitaría duplicar los campos de coste en la línea
de ruta por campos. Con el one2many a máquinas, solucionamos ambos casos y
se unifica la forma de calcular los costes.
En todo momento en la orden solo puede haber una línea asignada a cada
workorder, de entre todas las posibles e inicialmente se asigna la de "por
defecto" o la que tenga secuencia menor.

¿como lo veis?

**Comment by anajuaristi** [comment]
Se solucionó hace bastante tiempo. Cierro issue.
