### ISSUE TITLE
Purchase Requisition botón cambiar cantidad en líneas

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#423]
Al pulsar este botón y cambiar la cantidad, te lo hace en el campo "cantidad licitada" del one2many de líneas de compra.
No tiene sentido ya que la cantidad licitada está arriba y cuando se confirma la licitación, no se cambia. El wizard debería cambiar la cantidad de la línea de compra y no la cantidad licitada.

**Comment by alfredoavanzosc** [comment]
Se ha realizado lo solicitado, el PR es el https://github.com/odoomrp/odoomrp-wip/pull/432

**Comment by anajuaristi** [comment]
Igualmente, el issue sigue existiendo. Habría que cambiarlo en nuestro módulo purchase_requisition_display_order_line tal y como está ahora no vale para mucho el botón de cambiar la cantidad

**Comment by pedrobaeza** [comment]
@alfredoavanzosc, revísalo por favor de nuevo cambiando ese módulo.

**Comment by alfredoavanzosc** [comment]
Como me ha solicitado Ana, el módulo que se ha modificado ha sido el "purchase_requisition_display_order_line", el PR es el https://github.com/odoomrp/odoomrp-wip/pull/591

**Comment by anajuaristi** [comment]
Funcionalmente :+1: 
Cierro issue
