### ISSUE TITLE
stock_quant_manual_assign Pequeñas mejoras funcionales

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#425]
Buenas... he pensado que podriamos meter estas 2 mejorillas funcionales en el módulo de asignación manual de stock:
1. En el tree, de lotes a seleccionar, añadir sumatorio abajo, para saber qué cantidad total llevo asignada en todos los lotes seleccionados
2. Abajo del tree, mostrar a modo informativo y no editable la cantidad que requiere el movimiento
3. Adicionalmente al clickar el check "selección" del lote, poner cantidad total disponible del lote en el campo cantidad, de tal forma que el usuario no tenga que teclear la cantidad. De hecho, la fórmula correcta sería algo así:

qty= cantidad requerida (la del punto 2) - cantidad asignada (la del punto1)
Si  qty > cantidad disponible del lote entonces, asignar cantidad disponible del lote, y si no asignar qty

@pedrobaeza ¿Como lo ves?

**Comment by anajuaristi** [comment]
:+1: RTM
probado en server ofi

**Comment by oihane** [comment]
@anajuaristi esto es un issue, no un pull request. Por lo que creo que ya esta mergeado, si lo puedes comprobar y cerrar el issue, estaría bien limpiar los issues

**Comment by anajuaristi** [comment]
Hecho. Cierro
