### ISSUE TITLE
Envasado dependiente de costes

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#429]
Cuando están instalados el módulo mpr_packaging de envasados y el de costes estimados y reales, que hacen obligatoria la cuenta analítica en la OF, al crearse las OFs de envasado, habría que asignarles a todas ellas, la misma cuenta analítica que la de granel. 
Actualmente se crean con la cuenta vacía y hay que ponérsela manualmente a cada una.

**Comment by anajuaristi** [comment]
Asigno a @agaldona por los módulos de costes, pero no sé si debería asignarse a @oihane por el de envasados...
Como veais.

**Comment by anajuaristi** [comment]
Según último cambio que acaba de hacer @oihane esto cambia y lo que hay que asignarles a las OF de envasado es el proyecto (que a su vez, en el onchange ya se asignará la cuenta)

**Comment by oihane** [comment]
los módulos serian:
- mrp_packaging
- mrp_project_link

y con los cambios aún por mergear, hay que tener en cuenta que se le asigna proyecto y la cuenta analitica de este

**Comment by anajuaristi** [comment]
@oihane ARREGLADO.

Funciona, siempre y cuando uno se instale el módulo ;P

:+1:  Cierro

**Comment by oihane** [comment]
Esta instalado, `mrp_packaging_project_link`?

Por que estos autoinstall no se instalan al hacer update=all
