### ISSUE TITLE
Extensión para captura de tiempos en workorders

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#43]
A fin del control posterior de costes de fabricación, se requiere:

.- Crear una nueva tabla con los campos
Fecha/hora inicio
Fecha/hora fin
Operación
Tiempo 

Cuando en una operación se pulsa el botón "iniciar" o "reanudar", se genera una nueva línea donde fecha/hora inicio, es la que se ha pulsado el botón.
Cuando se pulsan los botones parar/finalizar, se actualiza la fecha hora fin y se calcula/actualiza 
       tiempo = fechahorafin-fechahorainicio

Esto nos va a permitir conocer el tiempo que una operación/máquina ha estado en marcha y por tanto, calcular fácilmente sus costes, realizando las imputaciones en analítica que se vean necesarias.

**Comment by anajuaristi** [comment]
Mikel, no lo veo instalado en el servidor de la ofi, no tengo el nombre del módulo, no tengo info para testearlo y lo vi funcionando el viernes. 
Por favor escribe aquí el nombre del módulo, instálamelo en la ofi y añade enlaces para que pueda probarlo.
REPITO: LEEROS EL MAIL DE LA METODOLOGIA que os envié. Vamos a intentar seguir los pasos.
Gracias

**Comment by mikelarre** [comment]
Esta subido e instalado, el modulo es "operation_time_control"

PR #75

**Comment by anajuaristi** [comment]
Cierro issue. Está hecho e instalado hace tiempo ya.
