### ISSUE TITLE
Columna duplicada en "Productos consumidos" al instalar <mrp_lot_reserve>

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#434]
En las ordenes de producción, en la pestaña de productos consumidos, a la derecha se muestran la lista de movimientos que equivalen a los productos consumidos, si instalas el modulo <mrp_lot_reserve> se duplica la columna de lotes, ya que la vista del modulo <mrp> ya contiene esa columna aunque está oculta con los permisos.
No sé que opinará @pedrobaeza pero tal vez habría que tener en cuenta esto y aquellas columnas nuevas ponerlas con el grupo de "lotes" (`stock.group_production_lot`) y quitar esta duplicidad.

Asigno a @Daniel-CA por que es quien ha hecho en un principio el módulo

**Comment by Daniel-CA** [comment]
Yo creo que eso sería lo correcto si, añadir la otra columna de lote al grupo y quitar la que duplico.
