### ISSUE TITLE
No puedo confirmar OF

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#435]
Buenas...
Tengo un caso "raro" en el server de la ofi demo_noviembre2, donde una Of creada automáticamente desde abastecimientos, no me permite confirmar. No da ningún warning, ni traceback pero se queda ahí. 
¿podeis mirar si hay algún error en el log?
MO00106

He visto que la of se crea sin que tenga asignado el template del producto, pero en principio, no haría falta y tampoco el producto vea que tenga nada raro, ni variantes, ni nada.

**Comment by oihane** [comment]
Pues, aunque no lo puedo asegurar, (a mi me falla solamente al intentar abrir un MO) hay que repasar los módulos que heredan quality_control, como por ejemplo `mrp_operations_with_quality_test`
ya que el `mrp_operations_time_control` lo usa y `mrp_production_real_cost` a su vez hereda el time_control.

**Comment by oihane** [comment]
En el log no da ningún error, pero tienes razón, no lo deja confirmar parece algún problema al ejecutar el workflow

**Comment by anajuaristi** [comment]
Me ha vuelto a pasar.
MO00121 demo_noviembre, server ofi

Es una OF creada desde un abastecimiento a fabricar. Por si puede servir de pista. Se ha quedado igual que la otra sin poderla confirmar. Sería cuestión de ver directamente en BBDD qué campos/relaciones tienen diferentes de las que se ejecutan correctamente, o si es tema de la configuración del producto/LM/proceso como tal. Intento sacar más pistas.

**Comment by anajuaristi** [comment]
Definitivo, las ofs que se crean desde abastecimiento, son las que se quedan. He visto 2 cosas:
1. que se crean sin tener asociado template
2. que si el producto es un producto como tal (variante), al abrir la OF, no se ve el configurador. 

No sé si puede estar relacionado con esto, que no tenga asignado valor en las variantes o algo. Pero en principio, si el producto está informado, no debería necesitar nada más

**Comment by oihane** [comment]
Arreglado, y mergeado, cierro

Si te da en algún sitio dime, que lo actualizo el la DB
