### ISSUE TITLE
mrp_subcontracting Duplica abastecimientos de producto subcon

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#436]
Al confirmar una OF, con una operación de subcontratación, genera varios abastecimientos del producto a subcontratar. Debe generar únicamente 1 abastecimiento, con la cantidad que marque la orden.
Ejemplos en ordenes a partir de 104 en entorno ofi
Revisar

**Comment by anajuaristi** [comment]
Probado el ciclo completo de las 2 formas de abastecimiento (creando albarán de salida y sin crearlo), este es el único problema detectado por lo que en cuanto esté solucionado:

RTM :+1: funcionalmente OK

**Comment by alfredoavanzosc** [comment]
Había un bug por crear mas de 1 abastecimiento, subido el módulo a nuestro server para pruebas de Ana.

**Comment by anajuaristi** [comment]
Cierro
