### ISSUE TITLE
Proyecto interno, duplicar meetings (URGENTE)

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#44]
Necesitamos un procedimiento automático que realice la duplicación de un calendario de proyecto, en otro proyecto. Es decir, que duplique todos sus meetings

Propuesta:
Montar una acción en meetings, que me permita seleccionar uno o varios, que al pulsar muestre un wizard con los siguientes campos:
.- Combo de selección proyectos (requerido)
.- Fecha inicio sesiones del proyecto (no requerido)

Al pulsar aceptar realiza las siguientes acciones:
 .- De cada meeting guardar: Fecha del primer meeting del proyecto al que pertenecen. (Fecha inicio Proy Origen), Fecha meeting origen
.- Duplicar meeting
.- Asignar al meeting creado el ID de proyecto seleccionado en el combo
.- Asignar como fecha meeting = fecha meeting origen - (Fecha inicio proyecto/el del wizard) - Fecha inicio proy origen) Es decir, si digo que el proyecto se inicia el 10 de septiembre de 2014 en el wizard y tengo que el primer meeting del proyecto al que pertenece fue el 10 de Julio de 2014, entonces sería (10 de septiembre - 10 de Julio) = 2 meses = 60 días, por ejemplo. Pues a cada fecha de meeting nuevo que cree, le sumo esos 60 días. Esto me permite luego, ajustar los días de forma visual en el mes que corresponda, por si cae en sábado y cosas así, pero más o menos me ubica los meetigns nuevos de forma tratable. 
Y creo que es todo.

**Comment by anajuaristi** [comment]
@mikelarre... necesito esto ANTES de lo del tiempo de los workorders.
Porfa, mañana cuando llegues ponte con ello.
Marcamos 2 fases de entrega:
1. copiar meetings de un proyecto en otro --> En cuanto lo tengas inmediatamente me lo instalais en odoomrp.
2. Lo de las fechas.

**Comment by anajuaristi** [comment]
Lo de las fechas de los meetings no funciona, bien porque la fórmula que yo puse no hace lo que creí que tenía que hacer, bien porque se ha programado de forma incorrecta.

Necesito un par de asistentes más para precisamente arreglar esto, por si nos equivocamos a la hora de meter los datos al Wizard de duplicar

Igual que se ha hecho este wizard, necesito otro, en el mismo objeto que muestre una pantalla con los campos:
Adelantar/retrasar: combo selección con los valores "adelantar/retrasar"
Cantidad: Número entero
Medida: Días, meses

Al confirmar, modificará la fecha de los meetings seleccionados. Si se selecciona adelantar, restará a la fecha el número de días/meses indicados. Si se selecciona retrasar, sumará a la fecha del meeting el número de días/meses indicados. 

Y necesito otro asistente diferente "unificar horarios", que al pulsar mostrará los siguientes campos:
Hora inicio: Formato "hora"
Duración en horas: numérico
Al confirmar, asignará a los meetings seleccionados:
  hora inicio = hora de inicio marcada en el wizard, respetando la fecha que tenga
  hora fin = hora inicio + duración marcada, respetando la fecha que tenga.

**Comment by mikelarre** [comment]
esta hecho, he cambiado el nombre del modulo a "project_events_operations"

**Comment by anajuaristi** [comment]
Viendo con Ibone la gestión de los asistentes al curso técnico, necesitamos la siguiente ampliación (nuevo módulo dependiente de event_subscription)
1. En proyectos, añadir un many2many a partner, sin ninguna restricción de domain ni nada. 
2. En events/meetings añadir un nuevo asistente, además de los que ya se han hecho, que funcione de la siguiente forma:
Para cada meeting:
.- Si el meeting no tiene proyecto asignado, no hacer nada.
.- Si tiene proyecto asignado:
        \* Crear una línea en el objeto event.registration por cada partner existente en el many2many del punto 1 
         \* Coger la lista de partners del proyecto asociado al meeting
         \* Ver que ese partner no esté ya metido en event.registration para ese meeting.

Lo que se pretende es crear automáticamente las invitaciones a reunión de todos los clientes de un proyecto. Así, por ejemplo si tengo el proyecto "curso tecnico" y le meto 5 partners en el many2many, necesito que los 5 se registren en todos los meetings/sesiones del curso.

Para ello, iré a meetings, filtro los que sean del curso tecnico y ejecuto el asistente, al finalizar debe existir UN UNICO registro que contenga el mismo partner_id, event_id en la tabla event.registration. 
Podría ejecutar el asistente varias veces, ya que un partner se puede dar de alta más tarde, o cambiar de opinión. Es decir, al empezar tener por ejemplo 5 clientes en un proyecto y que luego se me apunten más clientes a los que también tendré que invitar a la sesión.

Al crear el registro nuevo asignar los siguientes valores en los campos:
Event_id: el del meeting que se está tratando en el bucle
Partner_id: el del partner que se está cogiendo del many2many
Nombre, email, teléfono: Los que tenga asociado en su ficha el partner que se está cogiendo
message_followers_ids: Partner_id, y el que esté marcado como responsable del proyecto al que pertenece el meeting.

Creo que con esto sería suficiente. 
Gracias!!

**Comment by anajuaristi** [comment]
:+1: RFM 
No os podéis hacer una idea de lo que nos va a mejorar este módulo la planificación interna de proyectos. A Ibone le va a encantar. 
He creado y planificado un curso técnico fantasma en noviembre en un plis

**Comment by pedrobaeza** [comment]
Cierro el issue por tanto.
