### ISSUE TITLE
stock_quant_expiry_state_color no coge colores correctos

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#445]
stock_quant_expiry_state_color #433

Probado en server ofi, no trae los colores del quant. 
Lote 0005 está en amarillo, y el quant relacionado aparece en verde
El campo state del quant aparece 2 veces en el tree y no se muestra en el form.

**Comment by oihane** [comment]
Ese modulo se quito, se ha hecho en `product_expiry_ext`

**Comment by oihane** [comment]
@anajuaristi da visto bueno tras comprobar que el modulo product_expiry_ext hace lo que se requeria
