### ISSUE TITLE
sale variants onchange de product_id borra la descripción construida por el configurador

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#466]
Buenas.. 
He visto en ventas, que mientras vas seleccionando las variantes, la descripción se va montando correctamente. 
Pero al final del todo, cuando encuentra el producto, se borra todo lo construido y se trae código y nombre, dejando la descripción limpia, como al principio. 
Debería controlarse que si el producto tiene variantes, al final, el onchange del producto, no resetee la descripción. Como mucho, quizás concatenar lo que tenga el producto específico.

**Comment by pedrobaeza** [comment]
Se solucionará en #477
