### ISSUE TITLE
expected singleton al crear nuevo presupuesto de venta

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#467]
En demo_noviembre2 al abrir cualquier presupuesto de venta da el error:
ValueError
Expected singleton: sale.order()

**Comment by pedrobaeza** [comment]
Ya está solucionado. El problema es que el self.ensure_one(), también detecta cuando hay 0 registros, y usándose en un onchange al crear, ese caso ocurre. Haciendo antes un escape `if not self: return {}` evitas ese chequeo.

**Comment by anajuaristi** [comment]
Gracias Pedro
