### ISSUE TITLE
Shorcuts a reglas tarifarias desde producto y desde template

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#468]
Buenas... 
En la última sesión donde se trataron tarifas en moneda extranjera, vimos que la configuración standar de tarifas cubría lo requerido pero sí era complicado saber qué precios y en qué moneda se habían definido para el producto, ya que no hay navegación directa desde producto o template a reglas tarifarias.

Se solicita extender nuestro módulo odoomrp sale_pricelist_rules (mismo módulo donde se crean los menús a reglas tarifarias) que incluya lo siguiente:
En product.product --> nuevo shorcut a reglas tarifarias filtradas directamente por el producto desde el que se navega
En product.template --> nuevo shorcut a reglas tarifarias filtradas por el template desde el que se navega. 

Además, se solicita hacer visible el campo price_surcharge en el tree de reglas tarifarias

**Comment by Daniel-CA** [comment]
Merge realizado en #469, se puede cerrar.
