### ISSUE TITLE
Taxes breakdown no tiene en cuenta impuestos de precio fijo

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#471]
Configurando el punto verde, como impuesto fijo ( es decir debe calcular un precio fijo por unidad vendida/comprada y no por porcentaje), hemos visto que el standar lo hace correctamente pero taxes breakdown está aplicando siempre el impuesto en porcentaje. 

Mirar pedido SO063 en demo, donde subtotal del pedido está correcto calculado (el punto verde es 0,02) pero en breakdown taxes aparece punto verde 20, que sería el % sobre el importe y sería incorrecto.

**Comment by pedrobaeza** [comment]
Rehecho el módulo completamente en https://github.com/odoomrp/odoomrp-wip/commit/2da279d078c7637dcd8e75f033c23bda033efbb3 y dividido en dos: _sale_order_taxes_ y _stock_picking_taxes_ para modularizar cada área.

**IMPORTANTE**: Hay que desinstalar el anterior antes de actualizar el repositorio.
