### ISSUE TITLE
Restricción cambio unidades de medida en productos

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#474]
Este warning sale cuando has grabado un producto en una unidad y le quieres cambiar a posteriori. El warning debería únicamente saltar si existen movimientos de almacén de dicho producto. En otro caso no.

Es bastante molesto y hace trabajar absurdamente inactivando productos y volviéndolos a crear... debería quitarse la restricción general e incluirla únicamente si existen movimientos. Incluso en ese caso, con cambiar la unidad correspondiente a todos los movimientos, creo que no habría efecto lateral, pero en principio, valdría con el warning.
@pedrobaeza asigno a Oihane. Tenemos un módulo en 6.1 que directamente quita la constraint pero me parece un poco heavy hacerlo así.

¡Categorías de las unidades de medida no coincidentes!

La nueva unidad de medida 'kg' debe pertenecer a la misma categoría 'Unidad' que la antigua unidad de medida 'Unidad(es)'. Si necesita cambiar la unidad de medida, debe desactivar este producto desde la pestaña 'Aprovisionamientos' y crear uno nuevo.

**Comment by pedrobaeza** [comment]
Pero eso es un bug a nivel de core, y habría que publicarlo ahí. Pasa además desde hace varias versiones (creo que desde la 6.1). Públicalo con el warranty en odoo.

Cierro este issue.

**Comment by anajuaristi** [comment]
Hay este fix https://github.com/odoo/odoo/pull/3441 pero aún no han hecho merge

**Comment by pedrobaeza** [comment]
Dale entonces también tu visto bueno como he hecho yo.

**Comment by pedrobaeza** [comment]
Y aún así, lo reportaría como un issue con el warranty, apuntando a que el PR es la solución.

**Comment by anajuaristi** [comment]
Ya. El problema es que ya lo han puesto como enhancement y lo llevan sólo al trunk. No lo van a mergear en V8 :(

**Comment by pedrobaeza** [comment]
Echa mano del warranty a ver y si no, al OCB.
