### ISSUE TITLE
Cambiar código de variante  no modifica código de producto específico

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#475]
Siguiendo esta línea:
1. Crear producto nuevo
2. Crear nueva variante
3. Crear valores (el sistema sigue cogiendo un único carácter como código de atributo, se dijo mínimo 2)
4. Crear productos --> crea los códigos de artículo según la concatenación de prefijo y códigos de variante. 
   Si modifico el prefijo en el template, actualiza los códigos de producto correctamente, pero si únicamente cambio el valor de código de atributo, no actualiza nada.

Debería actualizar los códigos de producto específico que lleven el código de atributo modificado.

@pedrobaeza --> Esto como lo ves?

**Comment by pedrobaeza** [comment]
Con la nueva máscara esto tampoco aplica. Cierro.
