### ISSUE TITLE
En lista de valores de atributo no se puede buscar por atributo

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#476]
En el listado de valores de atributo, entrada desde menú, no se ha incluido ningún filtro ni agrupación.

Al menos debería poderse buscar por atributo y poderse agrupar por atributo y tipo
Modificar directamente en módulo que añade los menús de atributos.

**Comment by oihane** [comment]
No se puede modificar directamente el modulo, es el módulo:
**product**

**Comment by anajuaristi** [comment]
¿Cual es el módulo que añadimos los menús nuevos de atributos? Pues en ese

**Comment by pedrobaeza** [comment]
Se soluciona en #477
