### ISSUE TITLE
mrp_bom_catch_product_code no informa correctamente la referencia de la LM

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#478]
En la descripción pone:
When the product template is selected, the internal code is brought to the reference in BoM list.

No lo hace. Lo deja en blanco
Tener en cuenta que ahora el código de plantilla cuando ésta tiene variantes, está en el campo Prefijo de la referencia y no en default_code. Mirar a ver si es esto.

**Comment by alfredoavanzosc** [comment]
Ya esta hecho el merge
