### ISSUE TITLE
Botón producir de operación cicla con productos trazables

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#479]
En una operación con move products to stock marcado, debería hacer lo mismo que el botón "fabricar" de la OF es decir:
- Si la operación es de mover a stock, debería realizar el movimiento de producción y si el producto es trazable, funcionaría de la forma standar. 
- Si el usuario asigna un lote manualmente, crearía un quant con dicho lote
- Si el usuario no asigna un lote --> mostraría el aviso que muestra actualmente.

---

En el caso de que el módulo mrp_final_product_lot esté instalado, debería hacer lo mismo si lanzo el wizard desde una operación de producción, que si la lanzo desde la orden en general. 

---

En el entorno que estoy probando demo_noviembre2, no deja producir desde una operación ya que si no pongo lote muestra el mensaje pero si lo pongo a mano, no realiza el movimiento. Se queda como estaba.

**Comment by mikelarre** [comment]
me he fijado y aunque le de a fabricar sale el botón de consumir (el check de move products to stock esta activo). He mirado las vistas y aunque hay actions diferentes una de ellas no tiene una referencia explicita a la vista de producir. Este puede ser el error que en realidad no esta fabricando. ¿Me lo confirmas?

**Comment by anajuaristi** [comment]
Muy probable que sea eso. Ya que si hay 2 vistas y ambos botones llaman a la misma, al aceptar el wizard no estaría ejecutando el action correcto y por tanto cicla.
El aceptar del botón producir debería llamar al mismo action que ejecuta el movimiento de producción y funcionar de la misma manera que en la propia OF como tal.

**Comment by anajuaristi** [comment]
@mikelarre este issue puede estar de alguna forma relacionado con el que acabas de comentar?
https://github.com/odoomrp/odoomrp-wip/issues/615#issuecomment-72044699

**Comment by anajuaristi** [comment]
Cierro. Ya se ha hecho merge del fix
