### ISSUE TITLE
Cálculo de cantidades de materiales a consumir en la orden de envasado

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#480]
Hay un bug tanto en las órdenes de envasado que vayan en unidades como en las que van en kg.

Hay 2 cosas que verificar 
1. La cabecera de la orden: Si la unidad de la orden de envasado es igual que la de granel coger Fill, sino, coger quantity --> ESTO ESTA CORRECTO
1. Líneas al planificar la orden de envasado --> Si la unidad de la línea en el BOM es igual que la del granel coger FILL, sino, coger quantity --> Esto está incorrecto

No hace distinción sobre la unidad de la línea, le pone lo mismo a todo y no es correcto. Es decir si en el bom tengo
Granel en kg
envase en unidades

Tiene que descontar FILL para el granel y Quantity para el envase. Descuenta lo mismo en ambos. 

Conclusión hay que verificar las unidades de las líneas de la lista de materiales. Si son iguales que la unidad de la orden hay que coger el campo Fill. Si son diferentes hay que coger el campo quantity.

---

Adicionalmente, duplica la línea con el número de envases a consumir N veces. Ejemplo, demo_noviembre2 orden número MO00083

Corrijo la primera orden de envasado número PK00001, dejándola como tiene que quedar, eliminando los envases de más y cambiando la cantidad de granel. 
El resto dejo incorrectas para que se vea el error.

**Comment by oihane** [comment]
Mergeado, para que lo revise @anajuaristi

**Comment by anajuaristi** [comment]
Cierro. Esto ya se arregló
