### ISSUE TITLE
Costes estimados de empleado

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#481]
Tenemos una pequeña cosa que nos falta para terminar de definir los costes estimados de una orden y es el coste estimado de los operadores que realizarán la fabricación.

Conceptualmente tenemos el número de personas que realizan habitualmente una operación (en el maestro de operaciones)
Y también tenemos el concepto en la relación línea de ruta / workcenter --> podemos poner cuántas personas realizan una operación cuando usas una máquina concreta en una ruta concreta. Nos falta el importe asociado.

En el workcenter tenemos el listado de usuarios que se permite que manejen la máquina, independientemente de la ruta en que se use. 
Se solicita AMPLIAR el módulo de creación de costes estimados en analítica para que realice también lo siguiente:
Para cada OT:
1. Obtener el importe coste medio operador del workcenter asignado, haciendo la  media de todos los operadores asignados y sus productos asociados. Operador está asociado a empleado y en empleado está el coste/hora. Hay que hacer media de todos los productos coste de la ficha de empleado, de los usuarios asignados al workcenter,  Si la lista de operadores está vacía, el coste será cero. Para evitar esto, añadiremos un CAMPO NUEVO en la ficha de compañía (many2one a producto) "coste medio operadores" y si la lista está vacía cogeremos como coste el valor de coste que tenga el producto asignado en dicho campo nuevo.
2. Insertar nueva línea de coste estimado, poniendo
- Cantidad, el número de operadores marcado en la ruta para dicho workcenter
- Producto el asignado en la ficha de compañía
- Importe, el calculado en el punto1. 
- Diario, el de operadores que da de alta el propio módulo de costes estimados.

@alfredoavanzosc te asigno a tí. Porfa, lee detalladamente lo que se pide antes de ponerte a ello y si no se entiende algo, me preguntas directamente a mí.

**Comment by pedrobaeza** [comment]
Todo correcto salvo que en compañía no se pondría un many2one a producto, si no directamente el coste como un float, ya que no aporta nada poner un producto "Coste medio de trabajador".

**Comment by anajuaristi** [comment]
Es que el producto en analítica es requerido y he pensado que no era mala idea cogerlo de ahí.

**Comment by pedrobaeza** [comment]
Qué va, no es requerido. Se puede rellenar (como en contabilidad general), pero no obligatorio.

**Comment by anajuaristi** [comment]
O sea, me refiero a que en todo el resto de costes estimados que imputamos ponemos un producto, que luego vale para agrupar / categorizar esos costes. Al mismo precio prefiero que vaya con producto. No nos molesta ponerlo en la compañía y creo que da más juego. 
Como veas.

**Comment by pedrobaeza** [comment]
Pues yo casi prefiero sin producto, y así también se sabe que es porque no había ningún trabajador asignado en el workcenter.

**Comment by oihane** [comment]
Por si acaso... la parte del BUG, ya la hemos solucionado

**Comment by anajuaristi** [comment]
Eliminada del texto la parte de bug para no liar.

**Comment by oihane** [comment]
Esta mergeado y listo para review

**Comment by anajuaristi** [comment]
Pequenos bugs en este PR
Al generar la línea de analítica de operador, está calculando correctamente "coste estándar estimado" pero 
.- deja a cero el campo cantidad (debería poner la cantidad de operadores)
.- deja a cero el campo "coste standar manual"/stim_standar_cost (debería poner la misma que coste estándar estimado"/stim_avg_cost)

Arregladas esas 2 asignaciones, validación funcional OK :+1:

**Comment by alfredoavanzosc** [comment]
Ana... ya están solucionados los 2 BUGs, junto con el nuevo requisito de las OFs, ficticias. El merge esta hecho, se puede cerrar este issue.

**Comment by anajuaristi** [comment]
Correcto. Se puede cerrar issue. Funcionalmente validado :+1: 
Cierro. Gracias
