### ISSUE TITLE
Ambit on the machine: What does this mean

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#488]

**Comment by pedrobaeza** [comment]
What module? What screen or model?

**Comment by ybofr** [comment]
Machinery manager, Machines, Analysis Information, Additional Details

**Comment by pedrobaeza** [comment]
I see that it's a selection between Local, National and International, but now I don't know what is the purpose.

@anajuaristi, do you know it?

**Comment by anajuaristi** [comment]
No. I think it should be something specific coming from fleet manager. Remember that machine form has been inherited from vehicles form so, in a vehicle makes more sense having ambit local/national/international.
Maybe we should erase or make invisible that field. I don't think it makes any sense on manufacturing machines.

**Comment by ybofr** [comment]
it's not so relevant. I will close the issue
