### ISSUE TITLE
Manufacture details

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#489]
The field manufacturer of the machine should be there also.

**Comment by pedrobaeza** [comment]
What module? What screen or model?

**Comment by ybofr** [comment]
Machinery manager
Machines

Analysis Information
Additional Details
Manufacture Details

**Comment by pedrobaeza** [comment]
Yeah, it can be included.

These are instructions to our developer:
@Daniel-CA, introduce por favor un campo fabricante (manufacturer) en el modelo machinery y ponlo en la ruta que indica este hombre.

Ahora que he visto el modelo, me doy cuenta que has puesto mal el nombre, y debería ser `machinery.machine`, ya que por convención todo debe llevar un mismo padre que indique el área (por eso por ejemplo tienes account.account). Eleva el nº de versión del módulo para indicar que ha habido un cambio grande.

**Comment by anajuaristi** [comment]
@pedrobaeza 
Sorry but I think we could make this requirement a little bit more generic.

We have got pending the task of migrating/including product_manufacturer or product_brand (we could reactivate this theme) so, I think it could be used here. 
One machine is related to a product and the product will be related to a manufacturer so we can cover both requirements without modifying machine form

**Comment by pedrobaeza** [comment]
You're right, but we should completed creating a related field that shows the manufacturer at machine level.

**Comment by anajuaristi** [comment]
@pedrobaeza +1.
Manufacturer could be shown related to product on machine. Good point. 

About product_manufacturer or product_brand modules. Did we decide wich of them will be migrated?

@ybofr do you know any of them from previous version? Do you have any preference about selecting one or the other?

**Comment by pedrobaeza** [comment]
There is a WIP for porting product_manufacturer here: https://github.com/OCA/product-attribute/pull/29. We can go this direction.

**Comment by ybofr** [comment]
@anajuaristi I do not have the knowledge of it, so unfortunately, I cannot express any opinion. Thanks for asking.

**Comment by anajuaristi** [comment]
Module product_manufacturere has been migrated to V8 inside project  OCA/product-attribute, so I procceed closing the issue.
