### ISSUE TITLE
Preventive maintenance: very unclear

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#491]
Hello,

It's very unclear what is meant with the cycles and how it works.

Please provide some explanation for proper testing.

**Comment by anajuaristi** [comment]
Preventive maintenance in this versions makes nothing. 

We took the machine form from old openerp version and migrated master data to odoo, There is still 3-4 more modules on that old version covering full preventive maintenance cycle for machines, but it was not in our project first phase scope migrating them so, we just did not erase those fields but it's true they are just informative, no operative on machine form.

**Comment by pedrobaeza** [comment]
Ana, is there any link to old modules in case anyone is interested in migrating them?

**Comment by anajuaristi** [comment]
Yes of course. They are published in our old launchpad repository on avanzosc branch

If you want to see functionality you can take a look to this small screencast
http://www.openerpsite.com/wp-content/uploads/Preventive_Maintenance.htm

The modules are all published here:
http://bazaar.launchpad.net/~avanzosc/avanzosc/addons-6.1

And I should verify but I think the one related to preventive in mrp machines should be this one:
http://bazaar.launchpad.net/~avanzosc/avanzosc/addons-6.1/files/head:/avanzosc_preventive_mrp/

**Comment by pedrobaeza** [comment]
Ah, OK, then you can give new GitHub references:
- https://github.com/avanzosc/odoo-addons/tree/6.1
- https://github.com/avanzosc/odoo-addons/tree/6.1/avanzosc_preventive_mrp
