### ISSUE TITLE
Bill of material

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#493]
1. Field in active should be: inactive (in one word)
2. When pressing this field, a confirmation should appear
3. What is the difference between the field "active" and setting inactive?
4. The sequence number is valid, even if a BOM is historical. This is unclear for the user. If the sequence number should be unique, than it should appear on the header.
5. Manufacturing efficiency should not be on the BOM. It is generally in the production order as it depends from both the routing and the BOM. If there is an element that links both, then it would be best placed there.

**Comment by pedrobaeza** [comment]
Please, when creating issues, refer to installed modules that affects the corresponding issue.

**Comment by ybofr** [comment]
Hello Pedro,

As I am testing on the machine given to me by Ana and I do not know what is installed, I will not be able to answer this exactly. But I will do my best to be more descriptive and simplify your work.
At the moment, I am working on odoomrp, using the database noviembre2. If this can help.

And I am not a developer... ;-) So nothing technical coming from my side.

**Comment by pedrobaeza** [comment]
Ah, OK, I didn't know about that. By the way, what is your name to refer to you properly?

**Comment by ybofr** [comment]
Hi Pedro, my name is Eva.

To the point one concerning in Active. I guess, this is just a translation issue. In english, you will probably have "activate" to say that the draft BOM will be active from now on.

**Comment by anajuaristi** [comment]
Yes.. @ybofr (eva) is reporting here several improvements on BOM version module that it's still WIP (as a few other modules) 

We included the workflow and needed fields on bom, but... there is a pending task where we will link active field with status field.

By default bom will be created inactive. It will be activated (check active marked) when pushing button activate, and it will be set inactive on pushing "historify". 

It's very simple change but it's true it has not been done by now.

**Comment by anajuaristi** [comment]
About questions 3 and 5
1. Inactive boms could not be possible to be selected for manufacturing. That is Draft and historical boms will be not allowed to be used on manufacturing
2. Eficiency factor is standar field provided by odoo itself. We did no changes about it.

**Comment by ybofr** [comment]
Hi Ana,

There is some confusion about the field active and the status (draft, historical). It's probably from Odoo, but it is confusing for the user. But, if you use the activate workflow, it makes it clearer for the user.

Thanks for the answers.

**Comment by alfredoavanzosc** [comment]
Ya he modificado el módulo "mrp_bom_version", ha pasado travis, y hay que hacer el merge.

**Comment by alfredoavanzosc** [comment]
El PR se encuentra en https://github.com/odoomrp/odoomrp-wip/pull/536

**Comment by pedrobaeza** [comment]
Done in https://github.com/odoomrp/odoomrp-wip/commit/5f11c8597f36823b9466d38b9f8fb3e4763a1c1c
