### ISSUE TITLE
QTY to consume: Field is not clear

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#494]
Bill of Material/ Create / header

The field QTY to consume is unclear, especially as it is read only field.

**Comment by anajuaristi** [comment]
Yes.. this field is specific for chemical companies. It shows the sum of components quantities and allows user to know if formula is right or not.
In chemical companies bill of materials is a formula where each component is a % quantity based on 100.

this is you will have 80% water, 10% component A, 10% component B
If you click the check produce by percentaje you will see that standar quantity field will dissapair and you will not be able of saving the BOM if the sum of quantities of all components is not 100. 

As I said is a very specific tool that you only will see if specific module is installed.
