### ISSUE TITLE
BOM: Inconsistency in the unit of measure

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#495]
Bill of Material / Create / Components

When I enter a component, the unit of measure is not changed. In my example, I have a product that is in g and I can save the quantity in units, even, if there is nowhere a definition how to go from unit to g for my specific product.

I believe, it should automatically take the basic unit of measure of the component and always use this throughout the production. If using alternative units of measure, then these should be defined somewhere in the material master data.

**Comment by anajuaristi** [comment]
The onchange when selecting template_id on components list is not taking the right unit.
It's working properly when selecting product_id. 

It's a bug. Just assigned to be repared.
Thank you for reporting.

**Comment by oihane** [comment]
There is now a domain in UoM, so that it is only possible to select one depending on product variant or on product, if variant is not set
