### ISSUE TITLE
BOM: Manufacturing efficiency

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#496]
Bill of Material / Create / Components

There is the possibility to add the efficiency to the component. I do not understand what it is used for.
Is it used to say that I will get back a certain percentage of the component I have been using?

Thank you for your answer. This is not a Bug, but more a problem of understanding from my side.

**Comment by pedrobaeza** [comment]
I think the original purpose for this is to express that some raw material is wasted in the manufacturing process, but I'm not sure if this field is being taken into account. @anajuaristi, do you know it?

**Comment by anajuaristi** [comment]
Yes, it's a field (that we don't usually use) where you can specify more materials to be consumed when you launch the manufacturing order based on this bom.

As we never use, we didn't test (it's an standar field not added in our project) but I feel that setting efficiency less than 1 would plan more materials to be consumed. As I said, not sure about it.

**Comment by pedrobaeza** [comment]
OK, we can check it later then.
