### ISSUE TITLE
Workcenter: Pre- & Post-operation costs

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#499]
I do not understand why Pre Operation Cost and Post Operation Cost is linked to a material. What is the idea behind it?

**Comment by anajuaristi** [comment]
Preoperation and postoperation time are provided from Odoo standar mrp module. Cost/product fields has been added in odoomrp project.

There is 2 ways of controlling that kind of operations
1. Considering them as part of the route, so they will have got by theirselves all functionality related to an operation in an MO (that is, start, stop, take times, put cost... and so on) On this case, for sure those fields on operation itself have nosense.
2. Considering them as a fixed time before and after begining of finishing one operation. Example:
   prepare machine with paints: 30m
   paint itself: XXXm
   clean machine after painting: 30m

On this case we will not have 3 operations on route but only one (paint itself) and we will stablish a time to pre-operation and another for post-operation. About product fields, they can be used to specify a different cost for each one of the task I need to do. Supose you expend 10€ to prepare, 20€ to clean and 15€/h during the time machine is working.

That's the idea. After that, when you launch MO, the product will be used to be assigned on analytic line + take its unitary cost. Time will be the number of units. 
Take in mind that product can be also a service. Not always is a material. In this case there will never be a related stock.move but product will be only used to fix the cost of something

**Comment by ybofr** [comment]
Hi Ana,

Pre and post time is a standard concept and it's great to have it there.

My question was related to the product that I have to link as cost. In standard manufacturing language, when you speak about cost, you do not speak about a material. So, this is confusing. 

If I understand it properly, you want to assign a product in order to make the link in the costing as there is no other way. In this case, I would write: "costing product", so that people understand that whatever they have in analytic accounting with that product  will be used for costing.

In order to also have this separated, I will add something in the product to say that it can be used for costing purposes. This way, it would be easier for the user to understand and separate the different usages of a product.

**Comment by anajuaristi** [comment]
Hi:
The use of product to costing purposes is also standar behavior from Odoo. 
Employée hour/cost is added using a product, also is used on employées expenses and even machine cost itself. 
It don't think so, it's necesary adding a new check on product to mark it. We usually configure cost product as not to sale, no to purchase, service, to_order. That's all. 
@pedrobaeza opinion?

**Comment by pedrobaeza** [comment]
I agree to label this as "Costing product", but enable another check more on product is too much for only this use.

**Comment by ybofr** [comment]
For me it is ok, just changing the on screen description.

Thanks

**Comment by pedrobaeza** [comment]
Renamed in https://github.com/odoomrp/odoomrp-wip/commit/8876d9ba2d3cb653eef34dec09aec3c48748d8d6
