### ISSUE TITLE
Work center: unit of measure for the capacity is missing

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#501]
Work center / General information

There is no unit of measure for the capacity. So, it is difficult to know, what this field represents. In some example, it is 200....of what? liter, hours, kg?

I believe there should be a unit of measure. It can be at the work center level, after efficiency factor.

Thanks

**Comment by anajuaristi** [comment]
Final product defines the uom.
Otherwise it would be complicated. On same workcenter you could mix/process units, kg, L depending on product you are producing
Imho uom is not needed on workcenter

**Comment by ybofr** [comment]
Then there is a conceptional problem with that. What does it mean, when I put in my work center a capacity of 200?

Does it mean that for product 1, it is 200 l and for product 2, 200 kg?

**Comment by anajuaristi** [comment]
Yes. 
Take cost/configuration parameters on workcenter form as a kind of default values that usually should be changed on every route/Bom. We mantained those fields on that point just because standar Odoo included there but capacity and other parameters will depend totally on final product to produce. 

Imagine different kind of workcenters
1. Printer: It will print units per hour, depending on what kind or paper that capacity could increase or decrease
2. Liquid mixing recipe: Unit probably will be L independent from final produced product
3. Powder mixing recipe: Unit probably will be kg independent from final produced product
4. General machinery as making holes or assembly will be units.

So... I still think that including units on workcenter would be something to make it more complex and not more simple.

**Comment by ybofr** [comment]
Hello Ana,

When someone defines a capacity for a machine, he must know what type of capacity he defines. if you have an amount, then you need a unit of measure. It cannot depend on the final product and be on the work center. The two concepts do not seem to make sense together.

When you give the capacity of a printer, you define the number of pages of a specific format that he can print. So you would say 20 A4 pages in black and white, or 40 A4 pages in color.

If you have a container for mixing liquid, you will say how much liter you can mix in the container

If you have any mechanical machine, you will specify the reference for a capacity.

I believe, it is not understandable for a user to have a capacity without any other specifications. If you produce 2 different products on the same work center, it really does not make any sense.

From my point of you, a capacity unit of measure, even if only informative, should appear on the same screen.

But we can wait for other feedbacks to see how other users/testers  feel about the capacity management.

**Comment by pedrobaeza** [comment]
I think you both are right. It depends on the kind of abstraction you made over workcenters.

If you think on a workcenter like a machine, Eva is right about the constraint on unit. A reference UoM is needed on workcenter, and should be propagated (and can be changed) to any other UoM from the same UoM type.

But if you think on a workcenter like a production area or a group of workers (line 1, painters), the UoM can change depending on the product that is produced.

We can parametrize all these things at workcenter level, but does it deserve the effort?

**Comment by anajuaristi** [comment]
I vote not to make the effort and close directly the issue. IMHO by the moment we have got other things to fix/improve much more important than this one.

**Comment by ybofr** [comment]
My point was, you can have the unit of measure as an information for the work center capacity. A capacity without any UoM does not make a lot of sense and is not usual in the producing environment. 

Most people use the capacity to plan the production, so to give them one without the other will probably be a point most people won't understand. I will discus the point with my friend, who is production manager next week and come back to you with his point of view. So you will have two opinions from different view points. What do you think?

**Comment by pedrobaeza** [comment]
Great, and you have made a point: or both or none.

**Comment by ybofr** [comment]
Hello,

What is the decision on that point?

**Comment by pedrobaeza** [comment]
Hi, Eva,

Talking with Ana, we can't afford now a change of this size in the project, although it's interesting. Maybe for a second round.

I keep this open for knowing that it's there.
