### ISSUE TITLE
Work center for subcontracting: The field external should be part of it

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#502]
Normally, in order to correctly plan my workers, I need to know, if a task will be done internally or externally. This is perfectly represented in the operation, but unfortunately, if the user forgets to select external in the operation, it will be considered as internal.

I suggest that we add a field "external" in the work center that will be copied to the operation, if selected as default in the routing.

Tell me your thoughts

**Comment by anajuaristi** [comment]
When we defined functional behavior on subcontracting operations, we thought very much about it and even with our customers and decided that the operation on route was the best place to set it.

Functionally you have got external operations in a route and in this case, there is no workcenter/machine to make the operation. Is independant, so we think is better setting in routing. I close the issue.
