### ISSUE TITLE
Draft and historical BOM can be selected when creating a MO

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#504]
Manufacturing/Manufacturing orders/create

I have created 3 BOMs

One is active, the other is draft and the third is historical.

All three appear and can be selected in the MO.

**Comment by anajuaristi** [comment]
Yes. As I told you before there is still a task pending about BOM versions.
They will be created in draft (inactive), when user push activate they would be really activated and again inactivated when they are historical 
when tasks is done the issue will be solved.
I close duplicated.

**Comment by pedrobaeza** [comment]
If you close this issue as duplicated, please refer to the original one for reference.

**Comment by anajuaristi** [comment]
Yes. You are right
It's this one assigned to @Daniel-CA https://github.com/odoomrp/odoomrp-wip/issues/493
