### ISSUE TITLE
Manufacturing order: unit of measure for the product

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#505]
In order to have no problems with manufacturing orders, the unit of measure of the product should be taken either from the base unit of measure in the material master or from the unit of measure in the BOM.

At the moment, I can choose any unit of measure in the manufacturing order.

**Comment by anajuaristi** [comment]
UOM/UOS on MO are taken from product form when on_change the template and product. 
If user changes it manually system does not control it.

This is an standard Odoo behavior (enhancement) that should be reported to Odoo. It's out of our scope.

**Comment by ybofr** [comment]
There is still an issue coming from the OpenMRP. In standard Odoo, the product is mandatory, in OpenMRP, the product is NOT mandatory. So, in your case, you can just choose a BOM. And not check will be done vs the unit of measure in the material.

**Comment by anajuaristi** [comment]
Product should be mandatory to confirm the MO. I think system would not allow you to lauch the order before the product is created on the moment you use the configurator. It's possible to save it but not confirm it i think. It's made like that.
