### ISSUE TITLE
Capacity warning during creation of a MO, even if the UOM is not yet entered

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#507]
Manufacturing/Manufacturing order/ create

I receive a capacity message after I entered the quantity, even without entering the UOM. This does not seem correct.

![manufacturing_orders_-_odoo](https://cloud.githubusercontent.com/assets/7601880/5606129/16833798-9417-11e4-8d2a-942c429d7d06.png)

**Comment by anajuaristi** [comment]
Yes. It's totally correct.

Let's see if you set a workcenter on route with "limits routing capacity" and verify min and max capacity of that workcenter.
System is advising you that your MO qty is not between both ranges but you could launch the order anyway.

**Comment by pedrobaeza** [comment]
This depends on the decission on #501, so I leave it open.

**Comment by anajuaristi** [comment]
@pedrobaeza 
18 days without comment, I propose closing this one

**Comment by pedrobaeza** [comment]
Yeah, I think so.
