### ISSUE TITLE
Move final product to stock is only on "standard operations"

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#508]
Manufacturing/Routings/create

When an operation is defined in the configuration, there is a field allowing to define if the operation will put the product into stock.

This is not available in the routing, so that any manually defined operation cannot be "Move Final Product to Stock". 

Of course this can be overcome with creating a standard operation called "Move Final Product to Stock" that the user can include in all routings. The only issue with this is that the number of people for the task is defined in the standard operation and cannot be changed in the routing.

Any Idea?

**Comment by anajuaristi** [comment]
You can have a single operation "move final product to stock" for all routings like you say or, if there is different configuration for same operation in different routings, you can create as many final operations like you need.

**Comment by ybofr** [comment]
So, what do you do with the number of persons?

**Comment by anajuaristi** [comment]
What do you mean? I see no problem on that. Please explain a little bit.

**Comment by ybofr** [comment]
You have a field called "numero de persona" that is defined in the standard operations. I thought this field would be used for planning (I'm not there yet with testing due to short dumps). So, I was wondering, what happens with this field, if you set it to a specific value, but need another value, depending on the product you are producing.

**Comment by anajuaristi** [comment]
It's possible changing the number of people value on routing/workcenter lines, so even if you set a default value in operation it can be modified on route, for each workcenter

**Comment by ybofr** [comment]
It's ok. I checked it. In this case, it is only training for the user. I think it's a very good solution.
