### ISSUE TITLE
Manufacturing order: the attribute value cannot be selected

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#509]
Hello,

I have a BOM, and a routing and I try to confirm a production. As the material is not mandatory, I have left it blank.
The system ask for a value of the attribute, but I cannot select any

Picture is included
![manufacturing_orders_attribute values](https://cloud.githubusercontent.com/assets/7601880/5606249/e6d1c026-941d-11e4-97ad-881dd765ef52.png)

**Comment by anajuaristi** [comment]
i reviewed the MO00089 and there were a couple of errors there.
First, there was no selected final product. I selected one
Second, one of the planned materials "water" was liters on bom but kg on planned materials (someone changed it manually) so, i corrected and could confirm the order without specify memory.
