### ISSUE TITLE
Product unit of measure in the BOM

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#510]
Products/BOM
It is possible to choose any unit of measure when adding a BOM component. The problem comes when confirming the manufacturing order. 

When selecting the component, the system should automatically change the unit of measure to the base unit of measure of the product. This will prevent many mistakes.

![manufacturing_confirm](https://cloud.githubusercontent.com/assets/7601880/5606279/79c1126e-941f-11e4-9738-bc0add70eea7.png)

**Comment by anajuaristi** [comment]
As I said before. This is a standar behavior on Odoo. It should be reported to be enhanced / controlled on Odoo core. It's not in our scope. 
I close duplicated

**Comment by ybofr** [comment]
I just checked in with the master and there seem to be an update bug in your version. In runbot.odoo.com, when I enter the product, then the unit of measure changes in the line. In noviembre2, the unit of measure is not taken from the product. If it is taken from the product, then there is no problem as the user will not manually change it for no reason.

Can you please check it again?

Thanks

**Comment by anajuaristi** [comment]
In standar there is no template on bom components, just product_id

I think you are reporting same issue we accepted here: https://github.com/odoomrp/odoomrp-wip/issues/495
So, it has been assigned by now to be repared so we will review.

**Comment by ybofr** [comment]
I will close this issue, as it is related to the 495.

Thanks
