### ISSUE TITLE
Capacity warning should not appear in the MO

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#513]
To have the capacity warning when creating the manufacturing order is by far too specific. For instance, in mechanical industry, this would not be well accepted, as you can produce in batches and move the batches one by one into stock until the total MO quantity is reached.

So, what i would prefer is to have a warning as a configuration for the module manufacturing, so that other industries can use the module.

**Comment by anajuaristi** [comment]
It's configurable. You will not have the warning if you don't set any workcenter as "limits route capacity". 
On the other side, it's added by a module that can be avoided / not installed if not needed. 

It's usefull on chemical industries where there is mixing recipes limiting full route capacity, setting quantity by cicle.
