### ISSUE TITLE
Errores en la creación del test desde producción

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#514]
Ejemplo en la inspección Inspection QC-000008
1. El sistema ha creado 27 bloques de inspección, a pesar de que en las muestras para ese test tiene puestas 2 muestras entre las cantidades 1-999. Tendría que haber creado 6 líneas
2. El campo OF de la inspección, aparece vacío a pesar de que se ha creado desde una OF  
3. No hay acceso al test desde la OF, tampoco da ningún aviso ni nada de que se haya creado por lo que puede pasar desapercibido al usuario que lo tiene que rellenar. 
   Sería necesario poner un shorcut desde la OF  a todos los test creados.

**Comment by pedrobaeza** [comment]
Solucionados en https://github.com/odoomrp/odoomrp-wip/commit/814d6819f27967acbf84d73e10dfcf11771314f7
