### ISSUE TITLE
Incorrect labels: don't create variants, do create and create variants do not create

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#516]
i think new labels are incorrectly set on product form
If you select Don't create them automatically, variants are created and if you select create them automatically, variants are not created.

**Comment by pedrobaeza** [comment]
You're right. Corrected in https://github.com/odoomrp/odoomrp-wip/commit/aa469a03fc5e1070a67cfee65e87618d9239c6cd.
