### ISSUE TITLE
[QUALITY_MRP] Smartbutton position

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#519]
![quality_mo](https://cloud.githubusercontent.com/assets/2323616/5611272/d693dd6e-94c4-11e4-8e92-94b639841145.png)

@pedrobaeza he visto que has hecho alguna modificación con esto, y he observado la vista que adjunto al issue.

**Comment by pedrobaeza** [comment]
Buenas, aquí tenemos el mismo caso de otros módulos que añaden la caja de smart-button por su cuenta. Habría que crear una vista común que declararan ambos y heredaran de ella. ¿Puedes por favor hacerlo tú?

**Comment by oihane** [comment]
Hecho, cierro
