### ISSUE TITLE
quality control tolerances small improvements

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#520]
Buenas, analizando el módulo quality_control_tolerances y comentado con @pedrobaeza en hangouts, hemos pensado hacerle las siguiente mejoras de usabilidad:
1. En el template añadir 2 campos calculados (no editables) que muestren:
   Min_value - tolerance_below Y
   Max_value + tolerance_above
2. En la inspección / Inspection line / valid values, mostraremos únicamente el valor que marca el límite de tolerancia, simplificando el string que se enseña.
   (2,5) 3 - 5 (5.5) por ejemplo.

**Comment by oihane** [comment]
Mergeado, cierro
