### ISSUE TITLE
BOM: Create BOM Field Product twice in the line

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#525]
The field product appears twice in the line.

**Comment by oihane** [comment]
The point is that there are two fields with the same string. One of them is linked to _product.product_ and the other is linked to _product.template_
As odoo considers _product.template_ to be **product** that field has that name.

P.D: sorry for my English

**Comment by pedrobaeza** [comment]
@oihane, please rename the product.product one to 'Variant'.

**Comment by oihane** [comment]
Done
