### ISSUE TITLE
BOM: Activation workflow should warn about missing routing

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#527]
Due to the fact that the BOM cannot be changed after becoming active, the activation workflow should give a warning when no routing has been assigned. This is due to the fact that the link between BOM and Routing is done in the BOM and that no change is allowed once the BOM has been activated.

The rule of not being allowed to change anything in the BOM after the activation is very strong. I'm not sure, it is comfortable for the users. A slight mistake in the BOM before activation and then a new BOM MUST be created.

**Comment by pedrobaeza** [comment]
@anajuaristi, se ha prohibido modificar las LdMs una vez activadas? Si es así, Eva lleva razón aquí.

**Comment by anajuaristi** [comment]
Yes. This was a requierement aproved for all customers on our funding. 
They don't want allowing changes once BOM has been activated. You can always make a copy and  delete the old bom if you don't need it. It's not restricted and system will allow you deleting if it has not been used. 
But I see correct having a warning advicing that after activated changes will not be allowed.

**Comment by pedrobaeza** [comment]
Odoo doesn't allow to warn, but to raise an Exception that avoids to "activate" it.

**Comment by anajuaristi** [comment]
Ok. I agree with that.

@ybofr question is that if you want to just use your bom in draft status, having the possibility of modifying like you want. There is no problem since you can have "active" button allowed.
If you don't want people use draft boms but only "active" boms, restricting changes once Bom has been aproved, just activate it. 
So both aproches are covered.
1. Allow changing during use --> Draft Boms + active
2. Dont allow changing during use --> Draft Boms + Inactive and Active Boms
3. Historify in both cases --> draft --> active --> Historify

**Comment by anajuaristi** [comment]
@pedrobaeza 

So.. to fix this issue the solution would be:
.- Advice when activating bom: "Bom without routing is going to be activated" Accept  Cancel
.- Advice when historifying bom: "Bom is going to be historyfied" are you sure? Accept Cancel

Both advices will be includen in Bom version module.
Agree?

**Comment by anajuaristi** [comment]
@alfredoavanzosc 

Es necesario hacer los siguientes cambios en el módulo bom_version
1. Al activar un bom desde borrador, si el bom no tiene una ruta asignada se muestra una ventana con el siguiente aviso 
   "Va a activar la LdM. Si no ha puesto ruta, no podrá ya ponerla. ¿Está seguro de que desea proceder?"  
2. Al historificar un bom desde activo --> Se muestra una ventana con el siguiente aviso: 
   "Va a historificar una LM. Si lo hace, no podrá volver a activarla a no ser que saque una copia ¿Está seguro de que desea proceder? 
3. Meter un parámetro de configuración en el área de producción "NO permitir volver a editar la LdM".  será un check, que por defecto está a FALSE. 
4. Permitir pasar de activo a borrador, de tal forma que en borrador se pueda modificar y volver luego a activar --> Si el parámetro de configuración del punto 3 está a TRUE, no se permitirá esta vuelta atrás, o sea, quedaría el workflow como está ahora mismo.
5. cambiar el nombre del módulo a mrp_bom_state, que refleja mejor lo que hace.

**Comment by pedrobaeza** [comment]
Un par de apuntes:
- No sería "reactivar la LdM", ya que se supone que el estado es Activo y es pasar a borrador. Mejor "Permitir volver a editar la LdM".
- Hay que cambiar el nombre del módulo a _mrp_bom_state_, que refleja mejor lo que hace.

**Comment by anajuaristi** [comment]
Al final queda pues así:
Es necesario hacer los siguientes cambios en el módulo bom_version
1. Al activar un bom desde borrador, si el bom no tiene una ruta asignada se muestra una ventana con el siguiente aviso 
   "Va a activar la LdM. Si no ha puesto ruta, no podrá ya ponerla. ¿Está seguro de que desea proceder?"  
2. Al historificar un bom desde activo --> Se muestra una ventana con el siguiente aviso: 
   "Va a historificar una LM. Si lo hace, no podrá volver a activarla a no ser que saque una copia ¿Está seguro de que desea proceder? 
3. Meter un parámetro de configuración en el área de producción "Permitir volver a editar la LdM".  será un check, que por defecto está a True. 
4. Permitir pasar de activo a borrador, de tal forma que en borrador se pueda modificar y volver luego a activar --> Si el parámetro de configuración del punto 3 está a TRUE, se permitirá esta vuelta atrás, pero si está a FALSE quedaría el workflow como está ahora mismo y NO permitiría volver a borrador un bom activo
5. cambiar el nombre del módulo a mrp_bom_state, que refleja mejor lo que hace.

**Comment by anajuaristi** [comment]
@ybofr we just published a new version of bom_version, now renamed to bom_state, where we included several of your suggestions.

Now it's posible navigating from active to draft and active again, and it will show a warning when historifying + another when activating bom without routing

So, I close the issue as it's made. 

Thank you!!!

**Comment by anajuaristi** [comment]
[DEL mrp_bom_version, NEW mrp_bom_state] #595
