### ISSUE TITLE
Field product should be automatically filled when a BOM is chosen

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#531]
At the moment, it is possible to choose only a BOM causing many problems as the field product can stay empty. As each BOM is related to a product, entering a BOM should automatically fill the field product with the related value. This would prevent the short dump I get when trying to confirm the order without a product.

**Comment by oihane** [comment]
Could you please copy and paste here the dump you are talking about? Thanks in advance

**Comment by oihane** [comment]
Done
