### ISSUE TITLE
CLM0135 Alta de almacén de producción muestra mensaje de error

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#545]
Nuevo almacén
Indicar check de producción
Salta warning, segun pantallazo adjunto y no deja grabar el almacén.

![almacen_produccion](https://cloud.githubusercontent.com/assets/2323616/5703171/30b89e8a-9a63-11e4-8dbb-8a815dd98923.png)

---

La tarea sería averiguar porqué salta el error, qué está intentando buscar y ver si es del core de Odoo. 
En runbot no se reproduce. Quizás es un error anterior y al actualizar se arregle

**Comment by anajuaristi** [comment]
@pedrobaeza ¿Alguna idea de esto?

**Comment by pedrobaeza** [comment]
Lo dicho, ¿cuál es el warning o el pantallazo?

**Comment by anajuaristi** [comment]
Creo que puede estar adjunto en el claim. He hecho copy paste del texto durante la sesion sin ver el contenido. Te miro luego.

**Comment by oihane** [comment]
El código que hace que salte este warning es:

```
try:
    manufacture_route_id = data_obj.get_object_reference(cr, uid, 'stock', 'route_warehouse0_manufacture')[1]
except:
    manufacture_route_id = route_obj.search(cr, uid, [('name', 'like', _('Manufacture'))], context=context)
    manufacture_route_id = manufacture_route_id and manufacture_route_id[0] or False
```

**Comment by oihane** [comment]
Lo curioso es que busca una ruta con el nombre **traducido** de 'Manufacture' pero resulta que el campo se define así:
`'name': fields.char('Route Name', required=True),`

¿Has probado a crear el almacén poniendo el idioma del usuario en Inglés? Esta parte de código pertenece al modulo **mrp** de Odoo

La ruta se crea con el código:

``` xml
<record id="route_warehouse0_manufacture" model='stock.location.route'>
    <field name="name">Manufacture</field>
    <field name="sequence">5</field>
</record>
```

**Comment by anajuaristi** [comment]
En inglés va bien, si.
Por esto no podía reproducir el error en runbot. 
Esto habría que reportarlo allí también.

**Comment by pedrobaeza** [comment]
Mergeado el módulo que lo corrige mientras llega el parche oficial. Ana, ¿lo reportas en Odoo?

**Comment by oihane** [comment]
ya lo ha hecho https://github.com/odoo/odoo/issues/4697
