### ISSUE TITLE
'purchase_pricelist_rules' incompatible con purchase_discount

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#55]
Al instalar el módulo da este error:
Intenta instalar el módulo 'purchase_pricelist_rules' que depende del módulo 'purchase_discount'.
Este último módulo no está disponible en su sistema.

y en la descripción del módulo pone:
This module allows to apply product_pricelist_rules extended features to purchase order lines and gets the best pricelist rule automatically.

Warning: This module requires product_pricelist_rules that is incompatible with product_visible_discount

Warning: The required module purchase_discount is available at: https://github.com/OCA/purchase-workflow

**Comment by pedrobaeza** [comment]
Ana, es incompatible con _product_visible_discount_, no con _purchase_discount_.

**Comment by anajuaristi** [comment]
Ahh, juer, tienes razón.
pues cambio el issue que sería: no tenemos purchase_discount disponible en el entorno para hacer las pruebas funcionales del nuevo módulo.

**Comment by pedrobaeza** [comment]
Pues cambia el título entonces, con el botón edit de arriba :wink:
