### ISSUE TITLE
Unificar "autor" en todos los módulos de OdooMRP

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#56]
En algunos está puesto OdooMRP
En otros OdooMRP Team y en otros OdooMRP team por lo que al agrupar por autor, aparecen 3 autores. Esto es un problema de visibilidad en apps cuando publiquemos.

Igual con los de Avanzosc. Dijimos que la convención de nombre para todos los módulos Avanzosc, sería Avanzosc, S.L. Exactamente así, con puntos y todo. Revisad todos los que tenemos subidos para Odoo y ponerlo bien.

**Comment by Daniel-CA** [comment]
Se decide usar OdooMRP team al ser la que más número de apariciones tiene.

**Comment by oihane** [comment]
El nombre Avanzosc, S.L. se usa en aquellos módulos que están en la rama https://github.com/avanzosc/avanzosc
