### ISSUE TITLE
Traceback al pulsar botón de crear un test de calidad en operación

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#560]
He actualizado el módulo quality_control_mrp_operations en demo pero al pulsar el botón de crear el test manualmente desde una operación, me da este error.
No sé si está la última versión en el servidor porque sé que habeis estado con este módulo pero por si acaso, levanto el bug para que no se olvide.
Si cuando actualiceis se ha solucionado lo cerramos directo

```
Traceback (most recent call last):
  File "/opt/odoo/v8/core/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/core/openerp/http.py", line 538, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/core/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/http.py", line 291, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 754, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/core/openerp/http.py", line 387, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 875, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/v8/core/addons/web/controllers/main.py", line 896, in do_search_read
    request.context)
  File "/opt/odoo/v8/core/openerp/http.py", line 856, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 5046, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 1642, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4556, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/opt/odoo/v8/core/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4379, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/opt/odoo/v8/core/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/opt/odoo/v8/core/openerp/osv/expression.py", line 812, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'workcenter_line_id' in leaf "<osv.ExtendedLeaf: ('workcenter_line_id', '=', 490) on qc_test (ctx: )>"
```

**Comment by alfredoavanzosc** [comment]
Imposible reproducir el error. ¿Me puedes decir por favor en que Bd estás haciendo las pruebas, y que OF es la que te da el problema?. Gracias.

**Comment by oihane** [comment]
OF no, workorder

**Comment by alfredoavanzosc** [comment]
Bueno.... la workorder estará en una OF, no?

**Comment by anajuaristi** [comment]
En cualquier workorder de cualquier OF en demo_noviembre 2 pulsando el
botón test, como ya se dice en la descripción

2015-01-14 13:42 GMT+01:00 alfredoavanzosc notifications@github.com:

> Bueno.... la workorder estará en una OF, no?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/560#issuecomment-69910695.

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com soporte@avanzosc.com *

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
*_administracion@avanzosc.com
soporte@avanzosc.com *
_This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
soporte@avanzosc.com_

**Comment by alfredoavanzosc** [comment]
OK. El caso es que Pedro ha modicado el módulo "quality_control_mrp_operations", y se hace referencia a la función "set_test_template" del objeto "qc.inspection", y esta función no existe en ningún módulo. Estoy intentando ponerme en contacto con él, pero no le veo conectado. Mañana intento ponerme en contacto con él, a ver que me cuenta.

**Comment by anajuaristi** [comment]
Pero para qué necesitas a Pedro aquí?
¿Qué tiene que hacer el botón? Sin más... es un shorcut a tests de calidad. Por tanto, no tiene que hacer nada más que navegar a los tests asociados a esa workorder y listo.

**Comment by alfredoavanzosc** [comment]
Ana... no me vuelvas loco por favor. En el issue decías "al pulsar el botón de crear el test manualmente desde una operación, me da este error".
He traido la bd demo_noviembre2 a mi local, he hecho la prueba de crear un test pulsando el botón desde la operación, y me da este error:
  File "/home/alfredo/OdooMRPOficina/quality_control_mrp_operations/models/mrp.py", line 140, in create_quality_test
    test.set_test_template(self.qtemplate_id.id)
AttributeError: 'qc.inspection' object has no attribute 'set_test_template'

Entonces... a que viene ahora lo del shorcut a tests de calidad?. No entiendo nada de nada, la verdad.

**Comment by anajuaristi** [comment]
Bueno pues el shorcut a tests de calidad en operaciones en demo_noviembre2 también da traceback.
En cuanto al error, te digo que no necesitas aquí a Pedro para nada. Que simplemente arreglas el módulo y ya está.
Tiene que hacer lo mismo que hacía antes con la versión anterior de calidad. En los mismos puntos y momentos pero utilizando los objetos y variables de la versión nueva.
Te comenté esto el otro día y me dijiste que estaba cambiado pero parece que no del todo. Eso es lo que hay que arreglar y para esto no necesitas a @pedrobaeza  para nada. Ya te validará el código cuando hagas el PR del arreglo.

**Comment by anajuaristi** [comment]
Esta mañana @oihane ha actualizado la rama wip y ha ejecutado update=all por lo que he vuelto a probar y verifico que se siguen reproduciendo ambos errores:

```
.- Al crear el test desde el botón: 
  File "/opt/odoo/v8/odoomrp-wip/quality_control_mrp_operations/models/mrp.py", line 140, in create_quality_test
    test.set_test_template(self.qtemplate_id.id)
AttributeError: 'qc.inspection' object has no attribute 'set_test_template'
```

Al pulsar el shorcut

```
  return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/core/openerp/models.py", line 4379, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/opt/odoo/v8/core/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/opt/odoo/v8/core/openerp/osv/expression.py", line 812, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'workcenter_line_id' in leaf "<osv.ExtendedLeaf: ('workcenter_line_id', '=', 44) on qc_test (ctx: )>"
```

Hay que arreglar los 2

De momento desistalo módulo en el entorno porque creo que dará igualmente cuando en una ruta hay una operación de calidad y haya que crear el test automáticamente al iniciar la operación.

**Comment by alfredoavanzosc** [comment]
Ya están solucionados los 2 errores, el PR es el https://github.com/odoomrp/odoomrp-wip/pull/570

**Comment by pedrobaeza** [comment]
Mergeado.
