### ISSUE TITLE
No permite marcar un almacén para "producir"

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#561]
En almacenes hay un check comprar y otro producir. 
Si se marca producir y se intenta grabar sale el warning y no deja.
Pasa también en el entorno de Dsn

No se puede encontrar ningún proceso productivo genérico.

En cambio en runbot no lo he podido reproducir. Este error se da desde hace tiempo, antes de navidades y creo que ya lo reporté, pero sigue pasando. ¿Podriais mirar por favor qué es lo que causa el warning?

**Comment by oihane** [comment]
duplicado en el Issue #545
