### ISSUE TITLE
Faltan On_changes en tarifas

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#563]
Buenas... 
En compras --> 
.- Al cambiar el producto no cambia la regla tarifaria
.- Reglas tarifarias no tienen domain contra tarifa/versión

En ventas y compras --> 
.- Al cambiar la regla tarifaria no recalcula el precio

Al crear una nueva regla tarifaria directamente desde dentro de versión, no coge la tarifa y versión por defecto
Al crear una nueva regla desde cualquier sitio, si pones la versión no coge la tarifa, deja el campo en blanco.
.

**Comment by oihane** [comment]
Pero los dos últimos puntos aunque no lo muestra si que lo guarda correctamente no?
Me suena que no pude hacer que los mostrase pero que si que lo guardaba como debía, por favor compruebalo.

**Comment by anajuaristi** [comment]
No. No guarda. Porque da un error de estos de integridad al intentar grabar y si le pones al tarifa a mano ya graba bien.

**Comment by anajuaristi** [comment]
Hau berriro begiratzeko moduan?
Upssss... ( en castellano... ¿Está para mirar otra vez?)

**Comment by oihane** [comment]
Si
por eso te he puesto 4review :wink:

**Comment by anajuaristi** [comment]
Nop... no va
Integrity Error

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: price_version_id - price.version.id]

Si ocultas tarifa y versión de la regla, ya no se puede dar de alta una nueva, si no es desde dicha tarifa y versión

**Comment by oihane** [comment]
Exactamente desde donde has entrado?

**Comment by anajuaristi** [comment]
Era un tema de permisos de usuario. Fallo mío. el último comentario.

Realizado nuevo Review, en principio la última versión mergeada está :+1: 
Cierro
