### ISSUE TITLE
Picking taxes BUG

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#565]
Al confirmar el pedido de venta, al albarán está arrastrando el precio coste de la línea y no el precio de venta (en ventas)

**Comment by anajuaristi** [comment]
@pedrobaeza Me dice Gzlo de Dsn que porfa, cuando esto esté arreglado que le avises.

**Comment by pedrobaeza** [comment]
Cuando esté arreglado el qué?

**Comment by anajuaristi** [comment]
El bug:
Al confirmar el pedido de venta, al albarán está arrastrando el precio coste de la línea y no el precio de venta (en ventas)
En LA TABLA DE IMPUESTOS nueva.
Al calcular, está cogiendo como base (en el picking) el precio de coste, de la línea del pedido de venta y no el precio de venta y entiendo que esto es porque el dato se arrastra mal desde el pedido.

**Comment by pedrobaeza** [comment]
Solucionado
