### ISSUE TITLE
mrp_operations_extensions blocks MO when routing contains no operation

### ISSUE THREAD

**Issue by clonedagain** [odoomrp/odoomrp-wip#567]
mrp_operations_extensions adds a new object "operation" but does not make it required on routing lines. 
However if I enter a routing where the field "operation" is blank in all lines, I cannot confirm a manufacturing order and I get this message: `At least one operation must have checked "Move produced quantity to stock"field`.

**Comment by pedrobaeza** [comment]
But why are you putting a routing if the routing doesn't contain any operation? I think that doesn't have any sense, don't you think?

**Comment by clonedagain** [comment]
I actually recorded a routing with 4 steps, each with a name, workcenter 
etc, but the field "operation" is empty as you can see on the screenshot.

**Comment by clonedagain** [comment]
Huh except that the screenshot was not pulled from my email by github. Here it is : 
![operation](https://cloud.githubusercontent.com/assets/391953/5760117/bddc9a84-9cd2-11e4-8c01-b7872d2a9e02.png)

**Comment by pedrobaeza** [comment]
Hi, Lionel,

I have changed in https://github.com/odoomrp/odoomrp-wip/commit/9e5928731ad1f4bafdcbcd63de07a0fce0e89d02 the location for the check "Produce here" from operation to routing workcenter line, so that you don't need anymore to put an operation. I'm going to debate also the convenience of the model "Operation" with Ana afterwards.

Please check and let me know any problem. I close this for now.

**Comment by clonedagain** [comment]
Gracias, ahora parece mejor integrado en el estándar.
`operation` quizás sera útil en nuestro proyecto, ya no sé, estoy estudiando diferentes maneras de entrar las datos. Tenemos mucho productos que producimos quasi de la misma manera, ya no estoy seguro si reutilizar la ruta basta, o si necesitamos varios rutas con modelos de operaciones.

**Comment by pedrobaeza** [comment]
Sí, hablando con Ana, habla de que las operaciones sean una plantilla, y de momento vamos a dejarlo así. Su uso de todas formas es opcional.

**Comment by clonedagain** [comment]
@pedrobaeza todavía hay un problema: tengo el error cada vez porque le test es sobre los workcenters del MO pero esos workcenters no existen si no se ha llamado super() antes.
Pienso que https://github.com/odoomrp/odoomrp-wip/pull/659 le corrige.

**Comment by pedrobaeza** [comment]
@clonedagain llevas toda la razón. Yo siempre probaba pulsando primero en el botón "Calcular datos", pero si no se pulsa, el action_confirm() simula esa pulsación, y aparece el error que comentas. Gracias por reportarlo.
