### ISSUE TITLE
BOM: Bill of material structure is empty

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#568]
manufacturing/products/bill of material then menu more Bill of material structure.

The list is empty as in the picture. system Noviembre2, BOM "Poudre de perlimpimpim draft (copy)"

(https://cloud.githubusercontent.com/assets/7601880/5745430/b117814a-9c20-11e4-9c3a-a147706715d0.png)

**Comment by pedrobaeza** [comment]
That it's because product variant it's not informed. Maybe we can add also template to this view.
@oihane, can you check it?

**Comment by oihane** [comment]
Yes @pedrobaeza is right, thanks for the point @ybofr

**Comment by oihane** [comment]
Done
