### ISSUE TITLE
Módulo de Carlos Tipos de pedido no está completo.

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#57]
La tarea no está terminada del todo.
En los tipos de pedido faltan los siguientes campos, que no sé si se habrán incluido en otro módulo. Igual sería lo suyo separarlo.

diario facturacion: many2one a diarios factura
diario rectificativa: many2one a diarios facturas rectificativas.

Por lo tanto, no puedo probar la siguiente funcionalidad:
Albaran incluir campo relacionado tipo de pedido por pedido. 
Al generar factura desde albarán, asignar por defecto el diario marcado en tipo de pedido desde el que proviene el albarán.

La funcionalidad que SI se ha hecho en el módulo funciona correctamente por lo que lo doy por validado funcionalmente.

**Comment by anajuaristi** [comment]
Me habeis puesto la tarea en review pero no veo los cambios. Requeriría que mergeaseis el PR para probarlo. 
Paso la tarea otra vez a desarrollo

**Comment by pedrobaeza** [comment]
Está en principio completado. Revisar en el server.
