### ISSUE TITLE
instalar en entorno currency_date_update

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#573]
Se solicita instalar en el entorno demo y pasar el link de donde se encuentra el módulo currency_rate_update de la  comunidad a GZl y Jm
Asigno a Oihane para que reparta a quien corresponda.

CLM0173 instalar módulo currency_rate_update

**Comment by pedrobaeza** [comment]
Ese módulo está en account-financial-tools.

**Comment by oihane** [comment]
Modulo ya disponible en entorno de demo, cierro
