### ISSUE TITLE
Conveniencia de instalar stock_cancel y sale_set_to_draft

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#575]
Buenas:

@pedrobaeza  
Existen estos módulos de comunidad que permiten cancelar albaranes y pedidos de tirón y volver albaranes al estado inicial.
https://www.odoo.com/apps/modules/7.0/stock_cancel/
https://www.odoo.com/apps/modules/7.0/sale_set_to_draft/
¿conveniencia o inconveniencia de "adoptarlos" y traerlos a la 8? 
¿Sabes si existe en OCA algo similar para 8?

**Comment by pedrobaeza** [comment]
stock_cancel está propuesto aquí: https://github.com/OCA/stock-logistics-workflow/pull/46

El otro no.

**Comment by anajuaristi** [comment]
Ponemos pues stock_cancel? Asigno la tarea?

**Comment by pedrobaeza** [comment]
Primero hay que probarlo y hacer el review para que pase a ser oficial. Asigna esa tarea de revisión.

**Comment by anajuaristi** [comment]
¿A qué te refieres? A que se revise el código y se incluya un :+1:  en OCA para que lo mergeeen?
Si es eso, pues asigno a Oihane pero que lo mire también @mikelarre a ver si le ven alguna cosa. 
Supongo que les van a pedir el CLA para contribuir? O pueden sin más dar feedback positivo sin CLA? sabes como va?

**Comment by pedrobaeza** [comment]
Sí, pero que mire que realmente funciona para lo que queremos.

**Comment by anajuaristi** [comment]
No lo necesitamos para nada en concreto pero es una funcionalidad interesante. Sobre todo si permite poner el movimiento en estado "nuevo", lo cual podrías borrarlo o reiniciar el ciclo. Tampoco lo veo crítico porque se puede vivir sin ello con otros trucos, pero es más limpio poder cancelar y volver a iniciar el workflow en el movimiento y/o Albarán.

**Comment by pedrobaeza** [comment]
Que alguien lo pruebe entonces y lo tenemos como comodín.

**Comment by pedrobaeza** [comment]
Ya he mergeado y revisado yo el módulo. Es limpio y da una utilidad interesante. Se puede instalar en los entornos que lo requieran.

**Comment by santiarg** [comment]
@pedrobaeza @anajuaristi Ya lo he comentado en el pull request pero por si consideráis usar stock_cancel en producción advertiros de que no se debe usar en absoluto ese módulo tal como está en V8.0 porque al no cambiar los quants el stock quedará totalmente descuadrado.

**Comment by pedrobaeza** [comment]
Gracias por avisar, Santi. La verdad es que en mi review no me di cuenta de esa parte, que efectivamente supone el gran cambio en el WMS de la v8. Habrá que revisar el módulo y ver si los quants son deshacibles.
