### ISSUE TITLE
MPS pequeño bug

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#577]
Buenas... 
Hemos visto que al importar líneas de pedido con el wizard del MTS, trae siempre el cliente. 
SOLO debería traer el cliente, en caso de que sea seleccionado en el wizard, en otro caso no.
Ya que si no, se desvirtúa el listado, al diferenciar las cantidades por cliente, cosa que en la mayoría de los casos no es necesario.

Es decir, si yo digo importar desde tal fecha a tal fecha, simplemente haría el sumatorio de producto cantidad e importaría esto a la línea del MTS
En cambio, si digo importar desde tal fecha a tal fecha del cliente pepito, entonces sí me importaría pepito, sumatorio de sus productos , cantidad. 

¿Se entiende? 
El resto, funcionalmente :+1:

**Comment by agaldona** [comment]
Entendido, el lunes me pongo con ello.

**Comment by oihane** [comment]
Mergeada solución, cierro
