### ISSUE TITLE
packaging.operation no tiene grupo de permisos

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#579]
Este objeto no tiene grupo de permisos por lo que al acceder desde multicompañía o con un usuario no admin da error de acceso
AccessError

Lo siento, no está autorizado para acceder a este documento. Por favor, contacte con el administrador del sistema si piensa que esto es un error.

(Modelo de documento: packaging.operation)

**Comment by anajuaristi** [comment]
@mikelarre retomamos esto?

**Comment by oihane** [comment]
Hecho en https://github.com/odoomrp/odoomrp-wip/commit/2e09c674fd3ed23d7d914bdf82b1b8aa62c5a54c
