### ISSUE TITLE
Pequeño bug en CRM. Campos canal, origen y campaña

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#580]
Acabo de ver que hay una cosa rara con los campos canal, campaña y origen (básicos por otro lado para poder hacer segmentaciones o sacar informes de los casos de CRM

```
                    <field name="medium_id"/>
                    <field name="campaign_id"/>
                    <field name="source_id"/>

```

Están incluidos por defecto en las agrupaciones de las vistas tree, lo cual es correcto, pero en el tree y form como tal, se ven parte y no se pueden informar en el form porque están invisibles o no están.

Solicito que los 3 campos sean visibles tanto en el form como en el tree de iniciativas y oportunidades.

Ya están en agrupaciones pero deberían ser también incluidos en filtros 
Esto sería un pequeño módulo de usabilidad, No prioritario.

**Comment by anajuaristi** [comment]
@alfredoavanzosc me puedes mirar esto porfa, que me lo han vuelto a comentar hoy... y lo teniamos ahí sin asignar.

**Comment by alfredoavanzosc** [comment]
Subido módulo en PR https://github.com/odoomrp/odoomrp-utils/pull/25

**Comment by anajuaristi** [comment]
Gracias!!
