### ISSUE TITLE
Al menos una órden de trabajo debe tener marcada 'Producir aquí' impide fabricar en OF sin proceso

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#588]
Este mensaje debe salir sólo en aquellas OFs, que tengan asignado proceso productivo.
En una fabircación donde no hay operaciones, no tiene sentido controlarlo ya que se fabricará en general por el medio estándar.

**Comment by pedrobaeza** [comment]
Corregido en https://github.com/odoomrp/odoomrp-wip/commit/437435157a7eca8a34bdec4a03807e4708461aa5.
