### ISSUE TITLE
Mejoras en el product_pricelist_rules

### ISSUE THREAD

**Issue by pedrobaeza** [odoomrp/odoomrp-wip#593]
- No mostrar el botón de pricelist rules en producto si no se tiene el permiso de "Usar tarifas para adaptar los precios..."
- Poner al usuario admin con ese permiso al instalar el módulo.

**Comment by pedrobaeza** [comment]
Añado:
- No mostrar campo descuento en la tarifa si tampoco se tiene esa opción marcada.

**Comment by oihane** [comment]
perdon? campo descuento en la tarifa???

**Comment by pedrobaeza** [comment]
Claro, hay dos campos descuento en la línea de tarifa que añade precisamente este módulo. Esos campos sólo deben verse si está activada la opción correspondiente de ver descuentos.

**Comment by oihane** [comment]
pero cual es esa opcion, ya que por ejemplo en compras no hay grupo y siempre se ve

**Comment by oihane** [comment]
No encuentro el permiso: **Gestionar múltiples precios a través de tarifas**

**Comment by pedrobaeza** [comment]
Está dentro de Ventas, y me he equivocado el nombre, pero ya lo he renombrado. Lo que tendríamos que activar es a nivel de usuario la opción " Tarifas de venta".

**Comment by pedrobaeza** [comment]
El de los descuentos se llama "Descuentos en líneas"

**Comment by oihane** [comment]
"Descuentos en líneas"  = `sale.group_discount_per_so_line`
Hay "Tarifas de venta" y "Tarifas de compra", lo pongo para ambos?

**Comment by pedrobaeza** [comment]
De acuerdo

**Comment by pedrobaeza** [comment]
Aunque cada uno en su correspondiente sale_ y purchase_

**Comment by oihane** [comment]
El grupo de ventas es del modulo product, el otro... no me acuerdo :wink:

**Comment by oihane** [comment]
Ahm...
- [x]  Usar tarifas para adaptar los precios a cada cliente = Tarifas de venta
- [x]  Gestionar tarifas por proveedor = Tarifas de compra

Lo que no he conseguido es averiguar como hacer que se activen en la configuración, voy a poner que el admin tenga esos grupos

**Comment by pedrobaeza** [comment]
Eso sería justamente. Puedes ver ejemplos de esos en sale, purchase, etc, que añade automáticamente al admin como responsable.

**Comment by oihane** [comment]
Esto ya está hecho, lo cierro
