### ISSUE TITLE
OFs por defecto ACTIVE = TRUE

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#606]
Las Ofs simuladas siguen creándose con Active = False, cuando lo normal será que se creen OFs activas.
No sé si es porque no se ha actualizado. Por si acaso lo apunto para que no se olvide.

**Comment by alfredoavanzosc** [comment]
Ana... el tema lo entendí de la siguiente manera: Las OFs normales, cuando se crean desde la opción de menú, se crean con active=True. Las OFs simuladas, se crean con active=False.
¿Esto así es correcto?. Si esto es correcto, y el viernes no te lo hacía así, entonces entiendo que es porque no tienes la última versión. Un saludo.

**Comment by anajuaristi** [comment]
Desde cualquier sitio que creas una OF se crea con active false y sería casi mejor que se cree con active true. 
No sé si es por una actualización o porque no esté actualizado. Te digo lo que veo ahora.

**Comment by alfredoavanzosc** [comment]
ok, entendido entendido, no te refieres a cuando la creas desde formulario, sino cuando haces una create desde programación. Ahora cambio el módulo.

**Comment by anajuaristi** [comment]
En cualquier punto del sistema default es false. Debería ser true siempre. Tendría que ser false únicamente si se lanza desde el nuevo menú. En otro caso, siempre true.

**Comment by anajuaristi** [comment]
Cierro solucionada
