### ISSUE TITLE
Costes estimados (Ultimos ajustes) 

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#607]
Punto1.
En la versión instalada de simulación de costes de Of me falta aún el shorcut a apuntes analíticos desde la OF, pero ya que sigue aún pendiente, habría que adecuar un poquito el árbol de apuntes a la información necesaria de la OF.

De base, el shorcut navegaría a líneas analíticas, que pertenezcan a esa OF.
Y en el tree correspondiente:
1. Quitar campos "facturable" y cuenta financiera --> los apuntes de una OF, estos datos no nos interesan.
2. Cuando se lance la vista, que salga por defecto agrupada por 
OF
Operacion
Diario
Producto

Estos cambios se harían directamente en el módulo de costes estimados... no hace falta otro módulo

---

Punto2:
Expediente X:
El menú Órdenes de producción ficiticias para estimar costes, no sale aunque refresco el interfaz.
He metido el menú original en el grupos producción/usuarios manualmente pero tampoco
Le he cambiado el padre a mano a otro sitio y tampoco.
Ahora... voy a menús y lo duplico y se visualiza bien  O_o (le he cambiado el nombre y le he puesto Simulación costes OF para diferenciarlo del original)

---

Punto3:
Al igual que sucedía con las imputaciones de Operador(ya arreglado), he visto que los costes de máquina en cuanto a ciclos y horas dejan a cero el campo estim_standar_cost, debería ponerle el mismo que en estim_average_cost

---

Punto4:
El cálculo de horas en la OF, está sumando
.- De la máquina: horas preoperacion, horas postoperacion y coste hora máquina
.- De la ruta routing.workorder.line: coste hora máquina

Por tanto, está duplicando el coste hora máquina. SOLO debería coger el de la ruta. 

En cuanto al de máquina, puesto que los tiempos y coste de pre y post, ya se imputan independientemente de la máquina, yo los quitaría de la suma de horas, si no, también estamos duplicando su coste.

**Comment by pedrobaeza** [comment]
Yo no cambiaría la vista estándar de cuentas analíticas, aunque esa información no valga en ese tema, pero tampoco molesta.

**Comment by anajuaristi** [comment]
Molesta porque el campo cuenta hace que la línea baje bastante (el texto es largo) y se ve hueco entre líneas. Es por eso.

**Comment by pedrobaeza** [comment]
No sé si vamos a ganar mucho, pero puestos así, mejor utilizar la vista tree (la de tipo tree, lo del plan de cuentas) para mostrarlo.

**Comment by anajuaristi** [comment]
No es mala esa... Como la que hemos puesto en los históricos de costes de en líneas de pedido? que se muestre onthefly directamente desde la OF dices? 
Estaría chulo eso no?
y la vista normal, la que usamos ahora, sigue estando disponible en apuntes analíticos, sin tocarla.

+1 :)

**Comment by anajuaristi** [comment]
:+1: probado funcionalmente cierro
