### ISSUE TITLE
Creación de cuenta al confirmar OF y también al "calcular datos"?

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#608]
@pedrobaeza 
@agaldona 
@alfredoavanzosc 

Según última mejora subida, al confirmar una OF, si no tiene proyecto le creamos uno, pero... ¿Tendriamos que creárselo también al calcular datos? 
Anteriormente, sólo se calculaba estructura de costes al confirmar OF, pero ahora con las Ofs simuladas, al calcular datos, calcula también costes... ¿Deberiamos crearle el proyecto también aquí?
Actualmente se advierte al usuario de que debe poner un proyecto y sería correcto como está.
Opinion?

**Comment by pedrobaeza** [comment]
Sí, buena cuestión. Entiendo también que habría que crearlo, trasladando el código que hace esa creación desde la confirmación al calcular datos, pero además, habría que añadir que el proyecto se elimine cuando se elimine la OF (sólo si se ha creado, por lo que habría que añadir una marca de algún tipo que indique que el proyecto se ha creado automáticamente).

**Comment by agaldona** [comment]
Entiendo que si se crea el proyecto al dar a calcular datos, no tiene sentido que se crea también al confirmar, al final, siempre tendrá un proyecto asignado.

**Comment by pedrobaeza** [comment]
Sí, eso es. Lee de nuevo mi último comentario que digo exactamente lo que hay que hacer.

**Comment by agaldona** [comment]
Ok, perdona. Y todo esto, ¿en que módulo habría que hacer?

**Comment by pedrobaeza** [comment]
En el de costes estimados, claro.
