### ISSUE TITLE
[V8] mrp_operations_extension, error wizard do_consume_produce

### ISSUE THREAD

**Issue by ccarly** [odoomrp/odoomrp-wip#615]
En la vista "Ordenes de Trabajo",  boton "Producir", da un error de cantidad, al fijarme en el codigo de la accion, veo que la llamada es con caltidad "False" y a la accion en MRP le llega cantidad 0.

Por lo tanto emite una ventana que resa 
"¡Aviso!
Por favor introduzca una cantidad adecuada."

mrp_operations_extension/wizard/mrp_product_produce.py

```
    def do_consume_produce(self, cr, uid, ids, context=None):
        work_line = self.pool['mrp.production.workcenter.line'].browse(
            cr, uid, context.get("active_id"), context=context)
        production_id = work_line.production_id.id
        assert production_id
        data = self.browse(cr, uid, ids[0], context=context)
        self.pool['mrp.production'].action_produce(cr, uid, production_id, False, 'consume_produce', data, context=context)
        return {}
```

**Comment by pedrobaeza** [comment]
@mikelarre, puedes echarle un vistazo?

**Comment by mikelarre** [comment]
Ese False es porque la información que necesita esta el data ya que se esta ejecutando desde el wizard. Voy a mirar lo del error

**Comment by ccarly** [comment]
@mikelarre, si requieres mas información me cuentas, te adelanto que en la vista "Ordenes de Produccion", si permite fabricar parcial o totalmente.

**Comment by mikelarre** [comment]
Pues estaba equivocado. Cuando se consume si que se coge del data pero al producir hay que pasarle el qty donde está el False. Ya he hecho las pruebas y el PR. Gracias @ccarly !!

**Comment by pedrobaeza** [comment]
¿Dónde está el PR?

**Comment by anajuaristi** [comment]
@mikelarre ¿el PR?

**Comment by pedrobaeza** [comment]
Ya lo veo #619. @mikelarre, si cuando haces un PR, en el commit pones el nº de issue con la almohadilla, automáticamente los relaciona y además se cierra el issue en el momento en el que se hace el merge.

**Comment by mikelarre** [comment]
Perdonad me he despistado ya esta el PR
