### ISSUE TITLE
Can not install mrp_production_project_estimated_cost

### ISSUE THREAD

**Issue by mcassuto** [odoomrp/odoomrp-wip#618]
Hi Team,

on a fresh DB installed from github repositories (OCB and   odoomrp-wip), I got the following mistake when trying to install the module mrp_production_project_estimated_cost:

<pre>
  raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: mrp.mrp_production_buttons" while parsing
/git/odoomrp-wip/mrp_production_project_estimated_cost/views/mrp_production_view.xml:31,
 near

``` xml
<record model="ir.ui.view" id="mrp_production_buttons_inh_estimatedcost">
            <field name="name">mrp.production.buttons.inh.estimatedcost</field>
            <field name="model">mrp.production</field>
            <field name="inherit_id" ref="mrp.mrp_production_buttons"/>
            <field name="arch" type="xml">
                <div name="buttons" position="inside">
                    <button class="oe_inline oe_stat_button" type="action" name="%(action_estimated_costs_per_production)d" icon="fa-bookmark-o">
                        <field name="created_estimated_cost" widget="statinfo" string="Estimated costs"/>
                    </button>
                </div>
            </field>
        </record>
```

**Comment by pedrobaeza** [comment]
Hi, @mcassuto, thanks for reporting the problem. It's fixed in https://github.com/odoomrp/odoomrp-wip/commit/0e8e0c20432a0b99e0d2ff09a7150569cfb8a6b9
