### ISSUE TITLE
[V8] mrp_operations_extension field limited_production_capacity

### ISSUE THREAD

**Issue by ccarly** [odoomrp/odoomrp-wip#621]
El campo limited_production_capacity no existe para el modelo 'mrp.routing.workcenter' y emite su error

  File "/mrp_operations_extension/models/mrp_bom.py", line 57, in _get_workorder_operations
    if wc.limited_production_capacity and not cycle.is_integer():

En realidad el codigo no dice mucho, pero pensaria que sobra la comparacion a este campo

```
            ...
            cycle = factor / wc.cycle_nbr
            if wc.limited_production_capacity and not cycle.is_integer():
                cycle = int(cycle) + 1
            hour = wc.hour_nbr * cycle
            ...
```

Propuesta de codigo

```
            ...
            if not cycle.is_integer():
                cycle = int(cycle) + 1
            ...
```

**Comment by pedrobaeza** [comment]
Buenas, Genaro,

He aportado un parche más elegante al problema en https://github.com/odoomrp/odoomrp-wip/commit/dcb3f1d814f7ee3c4b5fc18f798ffd9fdf581c22.

Un saludo.
