### ISSUE TITLE
[V8] mrp_operations_extension vista mrp_routing_view.xml

### ISSUE THREAD

**Issue by ccarly** [odoomrp/odoomrp-wip#622]
En la vista mrp_routing_workcenter_form_view_inh, esta desabilitado el campo workcenter_id
(mrp_operations_extension/views/mrp_routing_view.xml)

Esto no tiene dificultad alguna cuando se instala el modulo y ya existen las rutas de producción, pero en el momento de crearlas desde cero, al momento de grabarlas siempre protesta por la ruta de producción, pensaría que no debería estar invisible el campo workcenter_id

**Comment by pedrobaeza** [comment]
Buenas, Genaro, esto se ha hecho así a propósito para que el workcenter se coja de la línea de operación por defecto. Si no se define ninguna línea de operación, no debe funcionar. Aunque el mensaje podría mejorarse, el comportamiento es el adecuado.

**Comment by ccarly** [comment]
Regresando

En el momento de crear las Operaciones del Centro de Produccion, el 1er campo "Operación", debería ser obligatorio, así como en la vista Oparaciones, tener al menos un Centro de Produccion. esto eliminaría cualquier tipo de dudas.

**Comment by pedrobaeza** [comment]
Genaro, la operación no es obligatoria porque tú puedes definir una línea sin ese dato. Piensa la operación como la plantilla de la que se copian los datos maestros, que luego se pueden cambiar.

Sobre el otro tema, he puesto que si no hay líneas en las operaciones, aparezca el campo de centro de trabajo.
