### ISSUE TITLE
[V8] mrp_operations_extension accion action_confirm

### ISSUE THREAD

**Issue by ccarly** [odoomrp/odoomrp-wip#623]
Independientemente que las rutas de producción entran o no una al menos que habilite el 'Producir aqui', la accion no las encuentra, debido a que  la variable workcenter_lines en el modulo mrp.production siempre esta vacia.

mrp_operations_extension/models/mrp_production.py Linea 26

Codigo

```
   ...
    def action_confirm(self):
        print "*" * 50
        if (self.routing_id and
                not any([x.do_production for x in self.workcenter_lines])):
            raise exceptions.Warning(
                _("At least one work order must have checked 'Produce here'"))
        return super(MrpProduction, self).action_confirm()
   ...
```

Sin embargo en la ruta si esta la información que se requiere.

Propuesta

```
   ...
    def action_confirm(self):
        print "*" * 50
        if (self.routing_id and
                not any([x.do_production for x in self.routing_id.workcenter_lines])):
            raise exceptions.Warning(
                _("At least one work order must have checked 'Produce here'"))
        return super(MrpProduction, self).action_confirm()
   ...
```

**Comment by pedrobaeza** [comment]
Genaro, debes revisar el estado de tus datos, porque el flag se traspasa a las líneas de la orden de producción justo aquí: https://github.com/odoomrp/odoomrp-wip/blob/8.0/mrp_operations_extension/models/mrp_bom.py#L66

Por lo que la condición es correcta. Tal vez estás trabajando con una OP antigua antes de que hiciéramos algunos cambios, y por eso los datos que contiene no son los adecuados. Pulsando el botón de _Calcular datos_ debería ser también suficiente para volver a traer ese valor.

Un saludo.

**Comment by ccarly** [comment]
Hola Pedro

El tema esta en any([x.do_production for x in self.workcenter_lines]), siempre da false, o sea no encuentra ningún centro de echo esa variable esta vacia.
Por eso propuse any([x.do_production for x in self.routing_id.workcenter_lines]), que si tiene las rutas

**Comment by pedrobaeza** [comment]
Lo siento, no consigo reproducir el problema que comentas. Ya te digo que debes tener datos antiguos.

**Comment by ccarly** [comment]
Hola Pedro

Volviendo al tema, intentare recreartelo.

1.- Creo una ruta de producción con dos operaciones y una de ellas le habilito "Producir aqui"
2.- Creo una LdM, para un producto X con materias primas Y1 (Operacion 1) y Y2 (Operacion 2), cuyo Proceso productivo, es la ruta creada anteriormente.
3.- Creo una orden de producción del Producto X
4.- Confirmar Produccion.

Odoo Warning: Al menos una órden de trabajo debe tener marcada 'Producir aquí'

Es todo, por eso se propuso la solución inicial.

**Comment by pedrobaeza** [comment]
Ya sé lo que ocurría, Genaro. El tema es que no pulsabas "Calcular datos" y yo sí. Por eso no lo reproducía. La comprobación era correcta, pero se tenía que hacer después de llamar al super para que si no lo habías pulsado, se simule su pulsación.

Ya está corregido en la última versión.

**Comment by ccarly** [comment]
Corroborado
