### ISSUE TITLE
machine_manager Terminología confusa

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#624]
La clase MachineModel tiene dos campos: name y model_type, que se etiquetan como 'Name' y 'Type', respectivamente. Pero el campo asociado en la clase Machinery (model_type) también se etiqueta como 'Type' y lo que muestra es el campo name del MachineModel.
A su vez, tenemos que "Modelo máquina" no se relaciona con el campo model de la clase Machinery, lo cual puede tener sentido pero resulta confuso al irse repitiendo términos que luego no tienen relación.

Espero haberme explicado bien.

**Comment by Daniel-CA** [comment]
El campo `model_type` que se relaciona con la clase `MachineModel` es un modelo de máquina genérico, como puede ser fresadoras o electro-erosión, mientras que el campo de texto `model` sería algo mas concreto como Fresadora Yasda YBM o Danobat Ni-750.

**Comment by anajuaristi** [comment]
Contestado. Cierro
