### ISSUE TITLE
machinery manager/create machine: manufacturer is missing

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#626]
Manufacturer is missing in the view. It should appear before the model
![machines_-_odoo](https://cloud.githubusercontent.com/assets/7601880/6014419/724de0fe-ab5b-11e4-8b3c-dfca9d0c56fa.png)

**Comment by pedrobaeza** [comment]
Done in https://github.com/odoomrp/odoomrp-wip/commit/59ea85dbe09f6183069c44e700e53bd219fbd625

**Comment by anajuaristi** [comment]
@pedrobaeza I don't understand very well the change. 
This claim was opened before and we closed because a machine is related to a product that can be related to a manufacturer (including product_manufacturer OCA module) 
So... if you include many2one directly to manufacturer it could be inconsistent.

If manufacturer should be shown on machine it should be related to associated product and machine manager module would became product_manufacturer dependant.

**Comment by ybofr** [comment]
If the machine needs to be linked to a product, then the product should be mandatory or at least an explanation should appear to explain where the manufacturer comes from.
As a user, I do not understand why I need to create a product in order to create a machine, so I would have the tendency to not create the product. Unless there is a need for it….
Regards

---

Eva P.

Get free Odoo training in our youtube channel http://www.youtube.com/user/ybofr

**Comment by anajuaristi** [comment]
You don't have a machine unless you buy it
If you buy you need a product, so if machine is coming from a purchase record will be automatically created. 
Product it's not mandatory at all. You can have machines that you don't buy and... manufacturer is neither mandatory. 
IMHO It's right like it is now.

**Comment by ybofr** [comment]
Ok, let’s say, I already have all the machines when I start Odoo mrp. I will need to create manually a product for each machine, in order to have a manufacturer in it, even, if the manufacturer is only an information field, in my opinion on the machine.

The effort of creating all the products just to had the manufacturer will have almost everyone changing the screen the very first day they will use it.  As to have the machine model without the manufacturer does not make sense. 
What I see is that, due to the ease with which you can add fields in Odoo, there will be many people adding this missing field, not understanding that they need to create a product in order to put the manufacturer in the product and then, there will be incompatibility with the data from the product master.

I maybe seeing things a little bit black, but this is my experience. End users are very creative and they do not think like programmers.

---

Eva P.

Get free Odoo training in our youtube channel http://www.youtube.com/user/ybofr
