### ISSUE TITLE
Machinery manager/create machine/preventive maintenance cycles and meters incompatible

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#628]
When I change the primary meter to calendar, there is no space to indicate after how many days I need to do a maintenance. I should not be checking the number of cycles, if I want to have the maintenance after a specific period.

![machines_-_odoo](https://cloud.githubusercontent.com/assets/7601880/6014449/f58063a2-ab5b-11e4-81c9-088493486a18.png)

**Comment by pedrobaeza** [comment]
@anajuaristi, please check this one

**Comment by anajuaristi** [comment]
Those fields are not operative on this machine manager version. They are just informative fields about the way the maintenance should be done.

If someday we migrate or refactor full preventive maintenance module, this fields will have "operative" master data and we will be able to configure alarms and operations to be done to machines by calendar or cicles. 
I propose mantaining like that until we afford the task (not on our roadmap by now)

**Comment by ybofr** [comment]
Hi Ana,

The view I have on the module is not a technical, but a functional only. For the user, when a field is there, it should have some logic otherwise, he will be asking. So maybe, the fields could be set in a way that people do not believe that it should be working somehow or maybe the selection for the type of maintenance should be taken away and only the cycle maintenance should be left, as an information.

The more unfinished you have in a system, the more frustration you have from the users.

My 2 cents

---

Eva P.

Get free Odoo training in our youtube channel http://www.youtube.com/user/ybofr

**Comment by anajuaristi** [comment]
But on this case fields are valid. I say... if you buy for example a second hand machine and you want to set how many cicles it has got by now... you can do it. 
You could also set the type of maintenance and even record manually each X month the actual cicles of the machine.
i would not take off. Just explain... if you need use it, if not, don't use. that's all. It's a master table, for sure user will not use 100% of Odoo standar master fields but we don't want erasing / making invisible just because he can change his mind a few days/hours after. Double work.

**Comment by anajuaristi** [comment]
Sorry but this case is not about technical or functional.
It's conceptual.
Everybody understands that one product could be produced by a manufacturer
so it's correct that manufacturer is linked to product
On the other side one machine could be or not related to a product /
manufacturer.
If you allow direct link on machine user could configure one
product/manufacturer and different manufacturer on machine so you would
have an integrity error. To solve or deny this case you need coding more
controls or automatisms that make more complex module so more expensive
maintenance and they are not necesary at all
Just showing manufacturer as related to product and including good help tip
should be enough to guide user. If you open a way where end user can
introduce a manual error... Be sure he will do.

**Comment by ybofr** [comment]
Hello Ana,

totally agree with you. If you include a good inline help explaining the usage of the fields.
In this case, I suggeyt to make the field manufacturer “read only” and to add an explanation telling that the manufacturer is to be maintained  in the associated product. This way, it is clear and less development work.

regards

---

Eva P.

Get free Odoo training in our youtube channel http://www.youtube.com/user/ybofr

**Comment by anajuaristi** [comment]
@ybofr I'm closing this issue since we migrated by now the preventive_maintenance module from previous version.
It's published just on this branch
