### ISSUE TITLE
Create BOM: components: Suggestion: Do not allow the inline editing of the routing steps

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#631]
It is best practice to edit the routing separately. This way, the user has full visibility over what he is doing. Whilst the inline editing of routing steps when creating a BOM seems to be a practical short cut, the user has too many risks to change the routing. So, I suggest to take the edit function of the routing steps away from the component adding.

**Comment by pedrobaeza** [comment]
Well tought!

Done in https://github.com/odoomrp/odoomrp-wip/commit/98a3dcab0497cd5e9fab64d11f66e18d05138b1f
