### ISSUE TITLE
Create routing header: produce here is not understandable by the user

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#632]
The field title "produce here" is not understandable. Please change it to "Stock delivery" or "Goods to Stock".

![odoo](https://cloud.githubusercontent.com/assets/7601880/6014622/af4e1c7c-ab5f-11e4-8b82-d7cd5e2a825e.png)

**Comment by pedrobaeza** [comment]
Well, personally I prefer this term, but I can put it as a help text what you are suggesting.

**Comment by ybofr** [comment]
It is not about loving the term. It is that this is not a term that is understandable  as it is not about the production at that stage, but about the fact that this is a delivery step. Our goal should always be to make it simple for the user. At least this is what I believe.

Sent from my Samsung Mobile on O2

<div>-------- Original message --------</div><div>From: "Pedro M. Baeza" notifications@github.com </div><div>Date:04/02/2015  20:24  (GMT+00:00) </div><div>To: odoomrp/odoomrp-wip odoomrp-wip@noreply.github.com </div><div>Cc: ybofr epinter@openit.ch </div><div>Subject: Re: [odoomrp-wip] Create routing header: produce here is not
  understandable by the user (#632) </div><div>
</div>Well, personally I prefer this term, but I can put it as a help text what you are suggesting.

**Comment by anajuaristi** [comment]
This is not objective but subjective opinion. 
I think it could not be considered even an issue, so if you both agree I'm closing
