### ISSUE TITLE
mrp_production_capacity / i18n Traducción incorrecta

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#633]
En el es.po, en las líneas 19 y 24, se traduce 2 veces el campo capacity_per_cycle_min y el mensaje de ayuda que se muestra queda incorrecto.

![traducc](https://cloud.githubusercontent.com/assets/8233008/6039548/5b3752a2-ac68-11e4-94a5-1a8c71774a84.png)

Además, en la ayuda del campo capacity_per_cycle coge la ayuda del campo que está sobreescribiendo.

![traducc1](https://cloud.githubusercontent.com/assets/8233008/6039613/ebeb60ae-ac68-11e4-98c0-ecb7dfb6e6b2.png)

**Comment by anajuaristi** [comment]
Aquí el tema es que el estándar tiene un único campo capacidad, que indica la máxima y nosotros hemos añadido otro que indica la mínima.
Se han mezclado los labels y las traducciones de ambos campos. 
Gracias por reportar. Lo asigno.

**Comment by alfredoavanzosc** [comment]
Este es el pr https://github.com/odoomrp/odoomrp-wip/pull/634
