### ISSUE TITLE
alm_commercial_information

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#636]
La tarea era
1) Añadir en la ficha de Cliente, un check "Prospección". Al crear el cliente, por defecto estará activado. Al hacerle la primera factura, se le desa ctivará.
2) Añadir en la ficha del cliente, un check "Distribuidor". Se utilizará al asignar los lotes del pedido, para comprobar la caducidad de producto.

---

Se subió el módulo alm_commercial_information y los campos se han definido en el módulo. Están ahí, pero creo que hay un bug en la vista porque no se visualizan en la ficha del producto y tampoco encuentro la vista cargada para poderla modificar a mano y ver lo que pasa

**Comment by anajuaristi** [comment]
@alfredoavanzosc ayer detecté este bug, cuando puedas le echas un vistazo? A ver qué está pasando con la vista almetac_commercial_information?

**Comment by alfredoavanzosc** [comment]
Realizado, este es el PR https://github.com/odoomrp/odoomrp-almetac/pull/232

**Comment by pedrobaeza** [comment]
@anajuaristi cuidado, que lo has publicado en el general con nombre de empresa.

**Comment by anajuaristi** [comment]
Vaya... qué lío llevo encima. Tienes razón. Pero... ya no es evitable no?

**Comment by pedrobaeza** [comment]
No, no se puede evitar ya, pero bueno, lo dejamos ahí cerrado
