### ISSUE TITLE
Pequeño bug de visibilidad y usabilidad en supplierinfo

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#638]
buenas... 

Hay varias cosillas inconsistentes en el tree product.supplierinfo

Se puede acceder al tree desde ventas o desde compras
Desde ventas, la relación es cliente/producto en caso de que se tenga instalado el módulo extensión pero en principio, desde compras sigue siendo proveedor /template

La inconsistencia: En el tree en ambos casos se muestra product_id y en caso de que el registro sea de tipo proveedor, el campo siempre está vacío. Debería mostrar template_id en este caso

Por otro lado, la agrupación en todos los casos es por template_id, y en caso de clientes debería incluirse también agrupación por product_id

**Comment by oihane** [comment]
Vista tree accedida desde menu en compras:
![image](https://cloud.githubusercontent.com/assets/2323616/6150354/20dda370-b20f-11e4-936b-c39358635252.png)

Vista tree desde producto (product.template)
![image](https://cloud.githubusercontent.com/assets/2323616/6150368/4649e9de-b20f-11e4-9b95-b3dc1af700b1.png)

**Comment by oihane** [comment]
Por cierto en los módulos de WIP no hay enlace directo entre `product.product` y `product.supplierinfo`

**Comment by anajuaristi** [comment]
Eso está pedido en una reclamación. Lo comentaron el otro día.

**Comment by anajuaristi** [comment]
Cierro esto
