### ISSUE TITLE
quality control Traceback al crear claim desde test

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#640]
Supongo que el traceback es provocado por el módulo que genera claims automáticamente cuando falla un test o una línea de test
quality_control_claim

```
  result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/odoomrp-wip/quality_control_claim/models/qc_inspection.py", line 47, in action_approve
    self.object_id.name)
AttributeError: 'bool' object has no attribute 'name'

```

**Comment by pedrobaeza** [comment]
Eso es por que no ese test no tiene referencia a ningún objeto (creado a mano). Habría que controlar esa condición, Alfredo.

**Comment by alfredoavanzosc** [comment]
Corregido, el PR es el https://github.com/odoomrp/odoomrp-wip/pull/641
