### ISSUE TITLE
purchase_product_price_history no veo cambios en el entorno

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#642]
Según este PR
https://github.com/odoomrp/odoomrp-wip/pull/331

En el tree histórico de costes debería verse product_id en vez de template_id
No se ve, por lo que no se puede probar lo que debería hacer el módulo.

**Comment by oihane** [comment]
Este modulo añade únicamente un menu en compras

**Comment by anajuaristi** [comment]
Entonces no entiendo. Que modulo es el que da la funcionalidad que se
solicita en el issue?

**Comment by oihane** [comment]
No he leído el pr pero supongo que el product_price_history, que tiene una vista donde se muestran template y product

**Comment by anajuaristi** [comment]
@oihane Revisa porfa y si no está hecho, hay que terminar el módulo incluyendo lo que falta y lo que se pide en el issue.

**Comment by oihane** [comment]
![image](https://cloud.githubusercontent.com/assets/2323616/6102968/b5edae1a-b03e-11e4-8345-befca1c9fc9a.png)

Teniendo en cuenta que se muestran ambos no sé por que dices que hay un bug. Además como se historifican también los cambios en el template, se deben mostrar ambos.

**Comment by anajuaristi** [comment]
Es que la semana pasada no se veían los 2. Solo se veía template.

**Comment by anajuaristi** [comment]
Funciona pero... hay que darle un poco más de usabilidad en la ficha de producto
En el producto se ven los campos de coste de plantilla y de producto (este último sin etiqueta ni nada). Deberían ser visibles en ficha de producto solo el del producto y en ficha de plantilla solo el campo de plantilla.

Además, hay otro issue, que al incluirse los campos nuevos de costes se mueven de sitio en el form y queda raro. Hay que organizar mejor el grupo de campos en el form. Pongo el issue relacionado aquí
https://github.com/odoomrp/odoomrp-wip/issues/638
