### ISSUE TITLE
account_treasury_forecast Botón "Get Data"

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#652]
Al crear una previsión de tesorería, hay un botón en la parte inferior que indica "Get Data", pero al pulsarlo lo único que hace es eliminar todas las líneas, no se ve otra funcionalidad o por lo menos por pantalla no genera ninguna información. ¿Eso es lo que debería ocurrir?

**Comment by agaldona** [comment]
Buenas tardes,
El botón get_data de la previsión, se divide en tres pasos o funcionalidades.

Por una parte, elimina todas las líneas que tengamos de antes. Por lo que veo, esto os hace bien.

La segunda fase o funcionalidad consta en traer las facturas correspondientes a la previsión, hay varios factores que condicionan la carga de las facturas. Uno de ellos es la fecha, es decir, la fecha de la factura a cargar, debe estar entre las dos fechas de la previsión, debe ser mayor que la fecha inicio  y menor que la fecha fin. Y por último, se aplican los check de borrador, abierto y proforma. Es decir, solo nos va a traer las facturas que estén en los estados que tengamos marcados. Si no hay ningún estado marcado, no nos va a traer ninguna factura, y si no hay facturas que coincidan con las condiciones que comento, tampoco.

La tercera funcionalidad y la última consiste en traer las líneas de la plantilla de la previsión. Como veis en la cabecera, asignar una plantilla es requerido. El sistema, nos trae las líneas desde la plantilla dependiendo también de las fechas, las que no tienen fecha, o las que tienen la fecha mayor que la fecha inicio y menor que la fecha fin de la previsión. Además de eso, la línea no puede estar marcada como facturada/pagada. Entendemos que si una línea esta pagada, no tendría sentido meterla en una previsión, si por lo contrario esta facturada, ya se nos habrá cargado en el paso previo.

Espero haber resuelto vuestras dudas. 
Cualquier otra duda que os surja, no dudéis en preguntárnoslo.
Un saludo,
Ainara.

**Comment by pedrobaeza** [comment]
Ainara, estaría bien que todo esto que comentas aquí, lo pongas en un asistente que lo abra ese botón, y así el usuario lo sepa, y además decida si continúa o no.

**Comment by ghost** [comment]
Muchas gracias por la explicación, todo aclarado y funcionando.

Por nuestra parte cerraríamos el issue.

**Comment by pedrobaeza** [comment]
Lo dejamos abierto para que Ainara haga lo otro que he comentado, que servirá de bastante.

**Comment by agaldona** [comment]
Ok! :+1:

**Comment by anajuaristi** [comment]
@agaldona esta es una de las que se pueden cerrar ya... 
A continuación, igual que este, te iré pasando recordatorio de temas para cerrar, que me has comentado hoy.

**Comment by pedrobaeza** [comment]
Se han hecho los cambios de textos pedidos?

**Comment by anajuaristi** [comment]
veo que sí esta hecho @pedrobaeza o sea que cierro
@agaldona
