### ISSUE TITLE
Sugerencia mrp_operations_extension models: mrp_workcenter.py

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#656]
Podría ser útil añadir dos campos para el "Coste pre-operación" y el "Coste post-operación" que muestren por pantalla los valores de esos costes (¿y se puedan modificar?), al igual que lo hace el campo costs_hour para el "Coste por hora"

**Comment by anajuaristi** [comment]
En principio. se hizo así porque consideramos que el dato de tiempo pre-operación y post-operación es más inherente a la máquina que a la ruta... pero sí. Podría ser una extensión perfectamente aceptable porque pueden existir casos en los que dichos tiempos sean inherentes al proceso de producción en que esté la máquina.

¿Os animais a hacernos un PR?
Ahora mismo nosotros vamos a tope de trabajo y esto no nos lo ha pedido aún ninguno de nuestros clientes por lo que lo abordaríamos a medio incluso largo plazo.
Ya nos decís...

**Comment by ghost** [comment]
En este momento también está nuestro equipo técnico hasta los topes, pero intentaré que alguno le eche un ojo.

Tampoco me parece algo ni urgente ni "importante" (mientras nadie lo reclame), pero informativamente parece razonable que aparezca por pantalla sin tener que entrar en el Producto asociado.

**Comment by anajuaristi** [comment]
@pedrobaeza  Cierro pues el issue. 
Si en algún momento abordais el desarrollo, nos haceis un PR @erc-anubia
