### ISSUE TITLE
[CLM0215] Asignar los test para que sean visibles solo a cierta gente por dpto

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#662]
Para cubrir este requerimiento surgido en la última sesión, la propuesta es simplemente relacionar dpto del usuario asignado en las inspecciones de calidad. De esta forma se podrían replicar los mismos mecanismos de permisos que tienen otros objetos en el sistema como oportunidades o claims en el CRM.

El enfoque técnico sería:

Nuevo módulo **quality_control_hr**
- Añadir dpto en tree inspección, related a user asignado.
- Incluir campo dpto en filtro, agrupación y búsqueda (en tree) 
- Crear 3 grupos de permisos para establecer tres niveles de seguridad: ver sus inspecciones, ver las del departamento, y verlas todas (manager).

**Comment by oihane** [comment]
@pedrobaeza y @anajuaristi tengo varias dudas, que me han surgido al revisar los modulos de quality_control para preparar lo que se pide.
- Por lo que he podido ver el objeto `qc.inspection` no tiene usuario asignado, por lo que la duda es si debo añadirlo en el modulo **quality_control** o en este nuevo modulo que voy a crear yo. Y supongo que como mencionas, debe ser usuario y no empleado.
- El modulo **quality_control** crea dos grupos, _manager_ y _user_, debo dar por hecho que he de sustituir el _user_ por los dos mencionados en el requerimiento?

**Comment by oihane** [comment]
Y por cierto, un `res.users` puede pertenecer a varios `hr.employee`, por lo que el `qc.inspection` podría pertenecer a varios `hr.department`.

**Comment by pedrobaeza** [comment]
Asumimos el primero de los empleados encontrados.

**Comment by pedrobaeza** [comment]
A la segunda cuestión que queda por contestar es eso, se crean tres grupos en lugar de dos. El user se puede considerar el básico.

**Comment by oihane** [comment]
He creado 4 grupos:
- See own inspections = user (renonmbrado)
- See department inspections
- See all inspections (tendrá permisos para acceder a inspections pero no a tests)
- Manager

**Comment by pedrobaeza** [comment]
No sé si el tercero tiene mucha utilidad, pero bueno, no viene mal.

**Comment by anajuaristi** [comment]
Y si ponemos manager que pueda definir plantillas y configurar rangos y eso? Y el resto que sean las restricciones sobre las inspecciones? 
#my2cents

**Comment by pedrobaeza** [comment]
Eso se supone que ya está, Ana.

**Comment by anajuaristi** [comment]
ok.

**Comment by oihane** [comment]
Pregunta... los grupos con restricción a los tests (qc.test) que serían todos menos manager.. tienen que poder acceder a las líneas de inspecciones? porque estas no tienen departamento y entiendo que deberían de estar limitadas igual que las inspecciones.

**Comment by pedrobaeza** [comment]
Sí, pon un related y le aplicas las mismas normas.
