### ISSUE TITLE
modificaciones en mrp_production_traceability

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#664]
Este issue incluye la reparación del módulo (actualmente no registra nada en mrp.track.lot ) y un par de mejoras.

Modificaciones a realizar:
1. En el wizard mrp.product,produce cada vez que se pulse do_produce, se registrará una línea en la tabla por cada tupla, número de lote producto final que se muestra en cabecera y los números de lote seleccionados en los componentes.
Se inserta una línea por cada lotefinal-loteconsumido
2. En el wizard work.order.product cada vez que se pulse do_consume se registrará una línea en la tabla por cada componente para el que se haya especificado un lote, con padre "vacío"
3. En el wizard work.order.product cada vez que se pulse do_consume_produce:
   .- Se crean las líneas para consumo, igual que se hace en el punto 2.
   .- Se verifica si existen líneas en la tabla para esa OF con parent vacío y si las hay, se les pone el lote de PF que se haya indicado en el wizard.

Además:
.- Incluir one2many a esta tabla en las operaciones de producción y en la propia OF 
(Creo que valdría con un shorcut, en cada una. Desde la OF o desde las operaciones de produccion. Como veias. Daría igual en este caso)

@pedrobaeza validar enfoque
@alfredoavanzosc si hay alguna duda preguntar.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by anajuaristi** [comment]
Ahhhh... una pequeña cosa

Quizás harían falta 2 módulos.
El punto1, funcionaría sólo con dependencia MRP. ES decir, alguien que no fabrique por operaciones podría usar este módulo tranquilamente. 

Los puntos 2 y 3 deberían tener dependencia con mrp_operations_extension. 

Quizás deberiamos tener mrp_production_traceability y mrp_production_traceability_by_operations o algo así.

**Comment by pedrobaeza** [comment]
Vaya tela con los nombres... cuándo vais a coger la regla de nombrarlos: `mrp_operations_traceability`

**Comment by anajuaristi** [comment]
Ahhh.. pues genial

mrp_production_traceability 
y
mrp_operations_traceability

Así queda pues. 
P.D: Pedro... lo de los nombres... a mí también se me hace complicado de atinar con el correcto!!!

**Comment by pedrobaeza** [comment]
No, si por ti lo digo. Pero ya con la de módulos de operaciones que llevamos que han sido mrp_operations_lo_que_sea...

**Comment by anajuaristi** [comment]
okokokokokokokok

**Comment by alfredoavanzosc** [comment]
"mrp_production_traceability" modificado, PR https://github.com/odoomrp/odoomrp-wip/pull/655
