### ISSUE TITLE
sale_packaging_info campos incorrectos en tree y form

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#666]
Tal y como hemos comentado en la solicitud, en el tree se mostrarían solo cantidades y en el form cantidad y tipo de envase. Se han metido justo al revés
En el tree se ven
Nº de env. 1 
Env. 1 
Nº de env.2
Env. 2 

Y en el form solo los Nº

Por otro lado, las etiquetas siguen sin gustarme. Siguen ocupando demasiado. En la línea quedan tropecientos campos largos. Propongo.
# Pq1

Pq1 
# Pq2

Pq2

**Comment by pedrobaeza** [comment]
Esa nomenclatura no la entiende nadie, Ana. Aunque tenga que ser un poco más largo, lo adecuado es: `Env. 1`, `Ctd. env. 1`, `Env. 2` y `Ctd. env. 2`.

**Comment by anajuaristi** [comment]
Y que tal sin espacios? 
Env.1,  NºEnv.1, Env.2 y NºEnv.2.

Se entiende igual y ocupa menos. Pero bueno, como veais. Si al final los tipos solo aparecen en el form, estamos hablando de un par de caracteres más en el tree. El problema es el tree, en el form puede ser el nombre tan largo como uno quiera

**Comment by pedrobaeza** [comment]
Entre el punto y el número puede valer, pero entre º y E queda muy raro.

**Comment by anajuaristi** [comment]
jajaja... vale. Aceptamos barco.
Env.1, Nº Env.1, Env.2 y Nº Env.2.
