### ISSUE TITLE
crm_claim_ref_search no funciona

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#669]
instalado en demo_noviembre2

Aunque existen claims donde se ha asignado algo en el campo referencia, en la vista tree aparece vacío tanto el campo modelo, como el id del objeto en sí.
La búsqueda por id en el omnisearch tampoco funciona.

**Comment by alfredoavanzosc** [comment]
Como me ha dicho Pedro, he desinstalado el módulo, lo he vuelto a instalar, y ya han cogido valores los campos.

**Comment by anajuaristi** [comment]
Perfecto
 Ya funciona!!
Cierro
