### ISSUE TITLE
sale_order_allowed_product no ejecuta el filtro ni en compra ni en venta

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#671]
Siempre carga todos los productos. Pasa de si el check del pedido está clickado o no está. 
No está montando bien el domain en el combo de productos

Es posible que se esté pegando con los domains que monta @oihane en el configurador
O bien que se esté intentando filtrar por producto cuando es plantilla, o al revés. 
Pero en demo_noviembre2 no hace nada el módulo. Solo añade los checks en partner y en pedidos.

**Comment by pedrobaeza** [comment]
Ana, el _sale_order_allowed_products_ no está pensado para convivir con todos los desarrollos de variantes (sale_order_product_variants y demás), y por eso el campo nuevo que añade este módulo (el de plantilla) no restringe nada. En cambio, el de producto sí que aparece restringido.

Habría que hacer un módulo puente, o expresar su incompatibilidad.

**Comment by anajuaristi** [comment]
Ya. Me imaginaba que fuese eso ya que al establecer una plantilla se monta el domain sobre el campo product en funcion de dicha plantilla

El modulo puente tendria que montar un filtro sobre el campo template. No se. Como veas. Yo creo que si merece la pena contemplarlo. Pero si va a ser complejo lo dejamos como To-do... Para mas adelante. A

**Comment by alfredoavanzosc** [comment]
Ana tu dirás porque me dices que hay un BUG, yo defino clientes, voy a un producto, le meto un cliente, y en los PV solo veo los productos de ese cliente.
Si hay un BUG, es por otros módulos instalados, así que tu dirás, porque los módulos tanto de compra como de venta, para mostrar productos permitidos, funciona perfectamente.

**Comment by pedrobaeza** [comment]
Alfredo, yo he explicado el por qué (los otros módulos instalados), que añaden el campo template. Ese campo no aparece pre-filtrado.

**Comment by anajuaristi** [comment]
@pedrobaeza 
Se me ocurre que una forma sencilla sería meter un domain en el campo template_id de la línea de pedido de venta que incluya todos los diferentes templates de los productos asociados al cliente en supplierinfo.

De esta forma funcionarían las 2 cosas. 
Los módulos de @alfredoavanzosc para el caso de productos sin más (para order.lines sin template, ni configurador, solo productos) y este que montaríamos nuevo, dependiente del configurador de @oihane que añada el domain en template_id
Así funcionaría en ambos casos.

Ya direis.

**Comment by alfredoavanzosc** [comment]
Hice 2 módulos nuevos para tener en cuenta las plantillas, falta que los revise Pedro, el PR es el https://github.com/odoomrp/odoomrp-wip/pull/690.

**Comment by alfredoavanzosc** [comment]
Ana.... esto ya esta hecho, y Pedro ya ha realizado el merge. Para solucionar este problema tanto en compras, como en ventas, se han realizado los módulos "sale_order_allowed_product_template", y "purchase_order_allowed_product_template"

**Comment by pedrobaeza** [comment]
Sí, Ana, lo que planteabas no terminaba de verlo, así que hemos seguido con este enfoque. Cierro.
