### ISSUE TITLE
mrp_production_project_estimated_cost Cálculo del coste operario

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#677]
Para realizar la estimación de coste de los operarios en una orden de fabricación se utiliza el siguiente código:

![image](https://cloud.githubusercontent.com/assets/8233008/6249866/72a4e206-b78a-11e4-9c5f-125d25bc532a.png)

En la línea 229 se establece que el coste por operario será la multiplicación del nº de operarios asignados a la operación (op_number) por el coste medio por operario (op_avg_cost), pero en ningún momento se tiene en cuenta el tiempo dedicado en la operación, es decir, da igual que dure 1 minuto que 9 horas, el coste asociado a la parte de Operators será el mismo. ¿Es esto correcto?
En caso afirmativo, ¿cuál es la "unidad de medida" del campo op_avg_cost?¿se debería indicar directamente en el campo op_avg_cost de cada operación el coste por operario que se va a imputar?

**Comment by pedrobaeza** [comment]
Efectivamente, no es lo correcto. @agaldona, puedes echarle un vistazo?

**Comment by agaldona** [comment]
Buenas tardes,
Por una parte, están los costes estimados de una orden de fabricación, y por otra, los costes reales.
Las imputaciones exactas de un operario se tienen en cuenta en la segunda parte, puesto que en la primera todavía no sabemos cual es el tiempo que va a pasar en una operación en concreto.
La parte de las imputaciones reales, se hacen desde tareas, manteniendo la operativa general de la parte de proyectos de Odoo, en ese caso, el producto de coste que se tiene en cuenta es la del usuario que hace la imputación.
Cuando se hace el cálculo de los costes estimados, que es lo que vemos en esta parte del código, al no saber cual va a ser el tiempo exacto, especificamos un coste medio estimado del operario para una línea de ruta en concreto. Así, aunque no sea un dato exacto, nos permite ver con algo más de precisión los costes que podemos tener en una orden de fabricación en concreto.
Cualquier duda, me comentáis.
Saludos,
Ainara.

**Comment by anajuaristi** [comment]
Si, pero tiene razón @ingenieriaanubia en este caso ya que NO estamos teniendo en cuenta el tiempo de operación. por operario. 
Si hay 3 operadores y su coste es X, está haciendo 3*X pero si la operación dura 2 horas tiene que hacer 2 \* 3 *X

Nos falta de meter eso en la fórmula de costes estimados. Sí que sería un bug a arreglar.

**Comment by anajuaristi** [comment]
@agaldona 
Bueno... la solución sería que cuando metemos la línea analítica el campo cantidad de la línea debería ser el número de horas ya que en el campo importe metemos el valor número de operadores \* Coste unitario

**Comment by pedrobaeza** [comment]
Aún así, @agaldona y @anajuaristi, hay que multiplicar el importe por la cantidad, ya que el campo cantidad es sólo informativo en el apunte analítico.

**Comment by anajuaristi** [comment]
@pedrobaeza correcto también. Si. Es una pena que apuntes analíticos no tenga un campo coste "unitario" como en todo el resto de sitios. Siempre me olvido de eso.

**Comment by ghost** [comment]
Después de echarle una pensada el fin de semana, el planteamiento inicial (sin tener en cuenta el tiempo dedicado por el operador) podría ser válido en un caso como el siguiente: un operador inicia varias operaciones que se realizan en máquinas automáticas y simplemente hace una "tarea" de supervisión y control sobre dichas máquinas. En este caso no se le podría imputar al operador todo el tiempo de la operación pues no es real, sino que lo más conveniente podría ser imputar un "coste aproximado", tal y como estaba la fórmula inicial.

De todas maneras, casos como este deberían ser los menos, pero debía transmitiros lo que se me ocurrió. Si consideráis que para resolver un caso como este se podría poner un coste por hora más bajo en la operación, como si fuese un coste de control, distinto al coste del operario, el caso estaría "resuelto".

Ya se que no se debería pensar en estas cosas el fin de semana, pero en fin...

**Comment by pedrobaeza** [comment]
Ya, puede haber muchos casos diferentes de paralelismos, pero no deben ser los generales. Eso, cuando algún cliente los subvencione, pensamos cómo implementarlos :wink:

**Comment by ghost** [comment]
Ok! ¿cierro el issue entonces?

**Comment by pedrobaeza** [comment]
Sí, lo cerramos
