### ISSUE TITLE
Error al calcular costes reales porque no tiene cuenta analitica asociada.

### ISSUE THREAD

**Issue by agaldona** [odoomrp/odoomrp-wip#688]
Hoy nos ha dado error al crear los costes reales de una OF porque no tenía el proyecto asociado.
Cambiamos el control de si una OF tenía proyecto o no, para que cuando se calculaban los costes estimados, si no tenía ninguno asociado, creara uno, y se lo asociara.
Pero hemos visto, que si produces sin haber calculado los costes estimados, y sin asignar el proyecto, da error al crear las líneas analíticas.
Añadimos un raise? o hacemos el mismo proceso que los costes estimados?
Que opinais @pedrobaeza @anajuaristi ??

**Comment by pedrobaeza** [comment]
Sí, debería ser lo mismo, pero, ¿no deberían crearse los estimados al confirmar la OF? Si es así, no haría falta el control, ya que lo haría el de costes estimados.

**Comment by agaldona** [comment]
Tienes razón. He ido a hacer de nuevo la prueba, y he visto que no tenemos la última versión. Por lo que este issue, no aplica. Gracias!
