### ISSUE TITLE
Campos de paquetes añadidos a los quants. Hay que quitarlos de la vista general.

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#696]
Buenas... 
He visto que los campos retaled a un pack, se han añadido a un quant. No tendría sentido. Hay que quitarlos de las vistas tree y form del quant cuando se abre desde menú!! SOLO DEL MENU, o ponerlas al final del todo... porque es bastante molesto que salgan en todas las vistas.

Weight
Peso total 
Net Weight
Total peso neto 
Volume
Total volumen 

La vista quant que está dentro del paquete está correcta. 

Propongo hacer una vista especial para quants, que solo se muestre en la vista del paquete. En el resto de sitios (asignación del quant a albaranes,tree de quants... etc... molestan bastante los campos)

**Comment by anajuaristi** [comment]
De paso, comentar un problema que he visto en el cálculo de pesos y volúmenes...

Total peso bruto estimado 44,00
Total peso neto estimado 38,80
Volumen permitido 1200000,00
Volumen total carga  0,00 ---> DA CERO cuando los productos sí que tienen volumen

Sumatorios de los productos: ESTAN CORRECTOS
Peso total bruto    12,00
Peso total neto     9,40  
Volumen                  81,00  

Total peso bruto estimado sería la suma del peso de paquete vacío + suma de pesos brutos de todos los productos + suma de los pesos de subpaquetes que contiene.
 No sé de dónde sale el 44, ya que el paquete vacío pesa 20,00 y no hay otros paquetes, solo productos.
Revisar fórmula

---

otro problema que he encontrado es que en los pesos reales se inicializa con el valor del peso y volumen del paquete vacío, sin tener en cuenta lo que pesa el contenido.

---

Por último, en el onchange del paquete se recalculan algunas de las variables , pero igualmente no se tiene en cuenta los valores sumatorio de los productos.

**Comment by alfredoavanzosc** [comment]
Realizado, el PR es el https://github.com/odoomrp/odoomrp-wip/pull/698
