### ISSUE TITLE
product_variants_no_automatic_creation Bug al asignar variantes de producto en BOM

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#699]
Revisando un bug que ha reportado Ana en los BOM he encontrado otro a la hora de asignar una variante de producto en los componentes del BOM.
La vista de las lineas del BOM coge las variantes segun los `product.product` creados para ese producto, por lo que al limitar la creación de los `product.product` no asigna correctamente las variantes disponibles.
Voy a crear un módulo llamado mrp_product_variants_no_automatic_creation que se autoinstale si mrp y el otro están instalados y que permita seleccionar las variantes directamente del `product.template`.

**Comment by Daniel-CA** [comment]
Si no veis ningun problema me pongo con ello. @anajuaristi , @pedrobaeza

**Comment by pedrobaeza** [comment]
Dani, es que si no hay variantes creadas, no hay product.product. No entiendo qué quieres hacer. Poner atributos y valores?

**Comment by Daniel-CA** [comment]
Correcto, a la hora de elegir los componentes que pueda elegir las variantes del producto a producir si dicho componente es especifico para esa variante, pero sin tener que definir el `product.product` de esa plantilla de producto.

**Comment by pedrobaeza** [comment]
Uf, eso es bastante trabajo y luego hay que cambiar todo el bom_explode. Creo que de momento no lo vamos a hacer, ya que no es un requisito de ningún cliente.

**Comment by Daniel-CA** [comment]
Ok, lo dejamos pendiente y sigo con el que estaba.
