### ISSUE TITLE
Planificación de la producción por capacidad finita

### ISSUE THREAD

**Issue by JordiBForgeFlow** [odoomrp/odoomrp-wip#706]
Hola! Estoy buscando una herramienta para programar las órdenes de fabricación teniendo en cuenta las limitaciones impuestas por la capacidad de los recursos / niveles de stock, y por la carga impuesta por órdenes de fabricación ya planificadas. Es decir, planificación de la producción por capacidad finita. Hasta qué punto llega OdooMRP a implementar este tipo de requerimiento?  Tenéis pensado incorporar algo al respecto?

Revisando los módulos me ha parecido que implementáis un warning cuando la orden supera la capacidad del centro.

Por otro lado veo que frePPLe (http://frepple.com/docs/2.3/extension-modules/odoo-connector.html) propone un conector hacia una herramienta externa de planificación de la producción. Tiene bastante buena pinta!

**Comment by anajuaristi** [comment]
Hola Jordi:
No está implementado.
El warning solo avisa de que una máquina de la ruta marca el número máximo de unidades que puedes lanzar en una única orden de fabricación. Por ejemplo, una cuba en una fabricación de granel pero hasta ahí llegamos.

Lo de frepple, vi en directo la demo el año pasado en Bélgica y según mi opinión está muy bien pero no lo recomiendo para nada. 
El asunto es que para poder hacer una buena planificación a capacidad finita entran en juego demasiadas variables (abastecimientos, compras, subórdenes, tareas, fechas de recepción, entregas, disponibilidad de máquinas, operadores... otros que me olvido) y sin tener en cuenta todas las variables, la planificación no vale de nada. 
Cada vez que lances una planificación hay que exportar los datos de casi todo el ERP, realizar el cálculo externamente y volverlo a importar. En ese tiempo probablemente las condiciones iniciales habrán cambiado por lo que lo calculado no sirve de mucho.
La planificación debe ser calculada por Odoo directamente. Habría que tirar más por intentar encontrar un algoritmo de cálculo, donde se vean todas las variables a tener en cuenta y "traducirlo" a Odoo/python. Sea el de frepple o el de otra herramienta. Eso sí.

Ya nos dices porque evidentemente nosotros también estamos sumamente interesados en el tema. 
Saludos!!

**Comment by JordiBForgeFlow** [comment]
Hola Ana, segun leo en la página de frepple, los datos se leen en Odoo directamente, se computa en Frepple la planificación y se escribe directamente en Odoo. Parece que frepple es, entonces, un motor de cálculo para Odoo.

Por otro lado yo he comenzado a usar TaskJuggler como motor de calculo de planificacion de tareas en proyectos, y del mismo modo el numero de variables a integrar es grande, pero cuando le das a programar se envian las variables, se computa en TJ y se devuelven los resultados al instante. Los resultados son prometedores. 

Con integraciones al instante solamente te preocupas de adaptar el modelo de información. Los sistemas ya se habla entre sí. Da igual si en la caja negra hay dos, tres o cuatro sistemas.

Saludos,
Jordi.

**Comment by anajuaristi** [comment]
Jordi.. como tú mejor veas pero yo después de haber lidiado con conectores durante varios años, directamente los odio.
Eso de que "coge los datos directamente" ... no me lo creo. Si no, sería un interfaz contra Odoo y eso no es. Tiene sus propios datos maestros y es un sistema independiente por lo que existe un conector sí o sí.
Pruébalo y nos cuentas. 
Yo por mi parte, creo que no es el camino pero evidentemente no tengo la verdad absoluta y puedo equivocarme.

**Comment by JordiBForgeFlow** [comment]
Voy a echar un vistazo y os digo.. Y te doy la razon 100% que integrar bases de datos con modelos de datos diferentes es morir.....   

Gracias!!!
Un besote

**Comment by clonedagain** [comment]
Just my 2 cents: last year the authors of Frepple said they may eventually consider making a library out of the Frepple scheduling engine, that could be used directly in Odoo instead of using a connector.

**Comment by JordiBForgeFlow** [comment]
@clonedagain It makes sense, because Frepple seems to be designed as a substitute of traditional excel spreadsheets used by manufacturing managers. And how you produce this 'spreadsheet', either dynamically from an external system such as Odoo or a XLS file is irrelevant. 

I'm finding something similar with the TaskJuggler integration.

In contrast to separate systems requiring connectors and replications, using external opensource libaries is way better. And I'd say even better and re-doing from scratch in Odoo. At the end mono-cultures can be very bad.

I also think that it is of the interest of Frepple to build such library, because people start to use the tool, and can easily jump into additional value-added services.

@jdetaeye, perhaps you can help us here! :)

**Comment by jdetaeye** [comment]
As author of frePPLe (and therefore not completely unbiased...), here are my comments:
- @anajuaristi: Since the presentation on the odoo opendays last year, the connector has been refactored. 
  At that point the connector copied the data into the frePPLe database, then frePPLe runs the plan and exports the results into its database, and in a final step the results are brought to odoo.
  
  As described by @jbeficent, In the new design the frePPLe planning engine connects LIVE to odoo to pull the data, and posts its results DIRECTLY into odoo.  So, you can generate a plan without replicating the data to the frePPLe database at all.    An odoo module is used to prepare the data in XML format for frePPLe.
- For the frePPLe - Odoo integration to deliver added value, the Odoo functionality in the manufacturing domain needs to be sufficiently complete.  The standard Odoo isn't strong and complete enough, which makes implementations too complex. Hence my interest in odoomrp, and the OCA MRP intiative started by Maxime Chambreuil.  (And to be honest, I'm a bit disappointed in the slow progress and lack of consensus among the community, OCA, and Odoo company... )

**Comment by JordiBForgeFlow** [comment]
Thanks @jdetaeye!
