### ISSUE TITLE
CLM0246 No permite cambiar la unidad de medida en el producto

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#707]
Eliminar la constraint en el producto, siempre y cuando NO EXISTAN movimientos de stock relacionados con dicho producto.
Si existen, es correcto que no deje cambiar la unidad de medida.

**Comment by oihane** [comment]
Hecho en https://github.com/odoomrp/odoomrp-utils/commit/a08240f22cd7f5a19addf7299f6f9cb00ae4c3eb
