### ISSUE TITLE
almetac_supplierinfo debería ser de OdooMRP

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#71]
Existe requerimiento para añadir producto/cliente en OdooMRP por lo que este módulo creo que debería ser genérico tanto en nombre técnico como en descripción y ser incluido en OdooMRP en vez de en el proyecto de Almetac.

**Comment by anajuaristi** [comment]
Mejor dicho, debería partirse en 2
Ya que la funcionalidad de añadir precios por volumen para clientes, al igual que para proveedores la pidieron en OdooMRP, pero en la tabla relación hay bastantes campos que son solo de almetac y no aplicarían en ningún sitio mas. 
Propongo tener un supplierinfo con lo básico y su extensión almetac_supplierinfo
Las fechas en la linea de descuento por volumen las dejaría como genérico, ya que puede venir bien si se quiere aplicar un precio a partir de cierta fecha o dar de baja un precio que ya no aplica pero manteniendo el histórico.
De hecho, esta tabla se podría utilizar para guardar el histórico de precios si fuese necesario. Valorar si los 2 campos tienen suficiente entidad propia para sacarlos de supplierinfo y ser añadidos por un módulo que se llame "historical_pricing" o algo así. 
Con los 2 campos en ese punto podriamos generar un registro "caducado" en esa tabla desde cualquier punto que sea necesario. No se necesitarían nuevas estructuras. Ya direis.

**Comment by anajuaristi** [comment]
La creación del menú para acceso directo a product_supplierinfo debería estar en el módulo general y no en el de Almetac.
Por otro lado, hoy en el servidor de la ofi he visto que los domains en los objetos siguen sin estar muy católicos. Debería ser que cuando marco customer, aparezcan solo partners cliente y cuando marco proveedor solo proveedores. Actualmente enseña cosas diferentes en función del sitio desde el que entro y sigue sin estar muy fino del todo.

**Comment by anajuaristi** [comment]
@oihane Te vuelvo a poner. Porque lo de los domains lo tienes tu y cambiar el menú de un módulo al otro, tampoco es complejo.
En pirincipio, que se pueda entrar a producto/cliente desde menú y que se visualice el one2many también en la ficha de cliente, lo pondría en el general.
El resto de cosas en el de almetac. Es copy paste de un módulo al otro y este creo que de todos los que hay es el que más urge porque es de lo primero que para ellos es super-critico y lo veremos mañana o el martes que viene. Creo que les puedo aguantar el tirón hasta el martes.

**Comment by oihane** [comment]
Estaba asignado @pedrobaeza para que respondiese

**Comment by anajuaristi** [comment]
Pero si no tiene nada!!!
O sea sacar el menú es super-genérico y vale para todo el mundo, igual que
mostrar la lista de productos en la ficha del cliente/proveedor. Es un paso
en usabilidad.
Solo dejamos en Almetac lo que sea de almetac

Y los domainsa que están mal, es un bug que hay que arreglar o sea que
también es genérico.
Por lo que no veo que lo tenga que tener Pedro asignado.

En marcha ;P para antes de ayer... GO GO GO!!! viento en popa a toda vela
!!!

El 18 de septiembre de 2014, 10:41, oihane notifications@github.com
escribió:

> Estaba asignado @pedrobaeza https://github.com/pedrobaeza para que
> respondiese
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/71#issuecomment-56010742.

## 

CEO Avanzosc, S.L http://www.avanzosc.es : Office phone / Tfono oficina:
(+34) 943 02 69 02
Ana Juaristi Olalde http://www.anajuaristi.com/: Personal phone: 677 93
42 59. User/usuario skype: Avanzosc
www.openerpsite.com

*El contenido de esta comunicación y de toda su documentación anexa es
confidencial y se dirige exclusivamente a su destinatario. El uso no
autorizado de esta información está prohibido por la legislación vigente.
Si usted no es el destinatario le rogamos nos lo indique, no comunique su
contenido a terceros y proceda a su destrucción. Disculpe las molestias que
le haya ocasionado la recepción indebida de este e-mail. Sus datos figuran
en un fichero cuyo titular es Avanzosc, S.L., a quien usted puede dirigirse
para ejercer sus derechos de acceso, rectificación, cancelación y oposición
en Julio Urkijo, 32, 20720, Azkoitia (Gipuzkoa), Tef. 943 02 69 02 -
administracion@avanzosc.com soporte@avanzosc.com *

_Komunikazio honen edukia eta dokumentazio erantsia konfidentziala da eta
hartzaileak bakarrik jaso beharko luke. Indarrean dagoen legeriak debekatu
egiten du bertan eskainitako informazioa baimenik gabe erabiltzea.
Komunikazioa zuri iritsi bazaizu, baina zu ez bazara hartzailea, mesedez,
guri jakinarazi, eta jasotako informazioa ez inori jakinarazi eta suntsitu.
Barkatu okerreko email hau jasotzeak eragindako eragozpenak. Zure datuak
Avanzosc, S.L. enpresaren fitxategietan sartuta daude. Zure datuak atzitzea
eska dezakezu, bai eta, datuak zuzentzea, ezereztea eta tratamenduari aurka
egitea ere. Horretarako, enpresara jo dezakezu, helbide honetan: Julio
Urkijo, 32, 20720, Azkoitia (Gipuzkoa), telefonoa: 943 02 69 02 -
*_administracion@avanzosc.com
soporte@avanzosc.com *
_This message and all documents attached to it are confidential and
intended only for the person or entity to which it is addressed. Any use of
this information by unauthorised persons is prohibited under current
legislation. If you received this message by error, please advise us,
destroy it and refrain from communicating its contents to third parties. We
apologise for any inconvenience receiving this email improperly may cause
to you. Your personal data are included in a file owned by Avanzosc, S.L.
If you want to exercise your rights of access, correction, erasure and
objection you can contact the Controller at Julio Urkijo, 32, 20720,
Azkoitia (Gipuzkoa), T: 943 02 69 02 – administracion@avanzosc.com
soporte@avanzosc.com_

**Comment by oihane** [comment]
@anajuaristi mergeado, cierro issue
