### ISSUE TITLE
Install MRP - stock location route fix Module --create new warehouse failed

### ISSUE THREAD

**Issue by jaronemo** [odoomrp/odoomrp-wip#710]
Install this module 
when create warehouse failed ....
Language is Chinese type ..

**Comment by anajuaristi** [comment]
Sorry @jaronemo, could you please explain a little bit more what you mean or what is this issue?

We deleted the module since issue has been fixed in Odoo Core.

Thank you:

Ana
cc: @pedrobaeza

**Comment by pedrobaeza** [comment]
This module is no longer valid, because Odoo has fixed the issue. Please remove this module and update your installation.
