### ISSUE TITLE
CLM0134 (ALM) Eliminar acceso al botón Forzar Disponibilidad

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#714]
Esta también la posteo aquí porque es una solicitud que aunque no nos la han registrado como issue sí que me lo han comentado varios, varias veces.

El botón "forzar disponibilidad" debería estar restringido únicamente a perfiles concretos, administradores o managers de fabricación o logística. Un usuario "normal" no debería poder pulsar el botón, incluso debería estar oculto.

Se solicita que se pueda restringir el botón por permisos.

**Comment by oihane** [comment]
Hecho en https://github.com/odoomrp/odoomrp-utils/pull/33
Mergeado en https://github.com/odoomrp/odoomrp-utils/commit/b8052fcc5c64b0d55f0e338f1e86350b8f90ddf0

Cierro
