### ISSUE TITLE
Nuevo módulo enlace stock_picking_package_preparation con picking Wave

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#718]
Buenas... 

El módulo stock_picking_package_preparation permite meter todos los productos de N pickings en un único paquete, en un único paso. Lo que hace es crear el nuevo packing y asignarlo en la tabla operaciones.

Se solicita una extensión de ese módulo que enlace con waves. Para ello, se añade un botón que se denomine "send to wave" ( @pedrobaeza needed new name ;P)

Al pulsar se muestra un wizard que contenga un many2one contra waves. De esta forma, se permitiría añadir los albaranes a un wave existente o crear un wave nuevo desde ahí. (solo muestra waves en estado diferente de cancelado o realizado)

Al confirmar el wizard --> copiar todos los albaranes de la "preparación" al wave, es decir, asignar a todos los albaranes el wave id seleccionado, bien sea nuevo, bien sea existente anteriormente.

@pedrobaeza validar enfoque
@alfredoavanzosc te asigno para acabar de completar el tema de paquetería y bultos.

**Comment by pedrobaeza** [comment]
Me parece bien. Sólo que lo llamamos "Add to wave" como el estándar.

**Comment by alfredoavanzosc** [comment]
Nuevo módulo realizado y subido

**Comment by alfredoavanzosc** [comment]
El PR es el https://github.com/odoomrp/odoomrp-utils/pull/42

**Comment by anajuaristi** [comment]
Hola @pedrobaeza 
Para instalar estos módulos que tienen dependencia con el stock_picking_package_preparation, necesito que se instale este en el server demo.
Gracias!!

**Comment by anajuaristi** [comment]
Esto está hecho, probado y funcionando en producción.
Cierro
