### ISSUE TITLE
stock_quant_merge problema permiso eliminación

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#719]
Buenas... 
Cuando un usuario (No admin) desasigna un quant y por tanto se ejecuta la eliminacion del quant fusionado, salta un error de permisos, que que el usuario no tiene permiso para eliminar el quant

El error es fácilmente subsanable por pantalla activando el permiso de eliminación en stock.quant pero esto abre una vía a tener un agujero en el sistema ya que en un caso enrevesado se les podría ocurrir borrar un quant de verdad. 

Voto por incluir en el módulo algún tipo de control para evitar el error, sin tener que tocar los permisos de los usuarios, que es correcto que no puedan eliminar quants.  

@pedrobaeza 
@oihane te asigno.

**Comment by pedrobaeza** [comment]
Simplemente hay que hacer la operación ésa en concreto con `.sudo()`.
