### ISSUE TITLE
Extensión ajustes de inventario

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#72]
Caso:
Utilizando la pantalla de inventario "vacía" para leer con código de barras, la pantalla desaparece al pulsar start.
Los códigos que no se han podido mapear en el sistema no se ven, no se da feedback al usuario. Deberían mostrarse los que sí se pueden mapear en verde y los que no en rojo, por ejemplo y que la solapa no quede invisible ya que da información superválida al cliente, sobre productos mal etiquetados, por ejemplo. 
Esto es una mejora no es un bug

**Comment by anajuaristi** [comment]
@oihane ¿Porqué se asigna a Pedro a esta tarea?

Entiendo que el objeto / tabla donde se capturan los códigos en la ficha de inventario, es un objeto normal, no es un wizard ni nada. Entonces... ¿porque no hacer un write normal y no ocultar la solapa? Sin más, los productos que se consigan mapear, Ok, Los que no se pueden mapear, ya verá el usuario qué hacer con ellos, si los da de alta o ha sido una mala lectura o qué es.

Tampoco es super-prioritario hacer esto. Se puede dejar para dentro de unos días pero lo veo sencillo. ¿qué opinas @pedrobaeza ?

**Comment by anajuaristi** [comment]
Esto se puede compaginar perfectamente con el de carga de inventario de @Daniel-CA 
Es decir, tanto si se importan las líneas mediante archivo, como si se capturan por código de barras línea a línea... el proceso debería ser el mismo.
Capturar y procesar. 
El check de "lista vacía" debería mostrar como hace ahora, la lista vacía y el procesar una vez capturadas las líneas debería ser exactamente el mismo proceso que el que hace el de procesar líneas una vez cargado un archivo.
@pedrobaeza ¿Estas de acuerdo? Mejoramos la opción de "lista vacía"... ya dirás.

**Comment by pedrobaeza** [comment]
Bueno, tal como está ahora mismo, son dos cosas aparte. Se podría utilizar el mismo asistente para una entrada manual con código de barras o por carga de CSV. El tema es que en su momento @oihane dijo que querías tener la lista ahí guardada con el inventario.

**Comment by anajuaristi** [comment]
@pedrobaeza Si, por eso digo. Por lo que vi en la carga desde archivo, también se graban todas las líneas y se marca en rojo las que no se pueden mapear y en verde las que entran bien.
Sería el mismo tratamiento en ambos y el listado donde se carga tanto por archivo como manualmente también quedaría el mismo. Simplificamos código no?

**Comment by anajuaristi** [comment]
@pedrobaeza ¿Qué haremos con esto abierto desde hace tiempo?

**Comment by pedrobaeza** [comment]
Es una información que yo no la veo tan útil una vez iniciado el inventario. Mientras se está llenando la lista, pues sí, pero luego, no lo quieres para nada.

Además, vas a marcar en rojo algo que luego puede cambiar. Por ejemplo, un código de barras que no tienes puesto en un producto. Lo pones, pero eso seguirá ahí en rojo.

Pero vamos, si quieres hacerlo...

**Comment by anajuaristi** [comment]
creo que lo dejamos como está. Además, nadie ha pedido funcionalidad adicional al respecto, ni hay claim asociado por lo que cierro. Si necesitan más ya lo pedirán.
