### ISSUE TITLE
Control de calidad antes del movimiento de almacén.

### ISSUE THREAD

**Issue by cuijartija** [odoomrp/odoomrp-wip#720]
Estimados todos los colaboradores y seguidores de este proyecto, gracias por la labor.

¿Existe algún módulo o configuración para poder forzar a realizar el test antes que de el producto llegue a almacén?

O en su defecto, ¿Es posible deshacer el movimiento si el control de calidad falló?

O como ustedes manejan los test fallidos, teórícamente so no pasa el control de calidad se debería hacer algo con esos productos ¿no?

Muchas gracias.

**Comment by anajuaristi** [comment]
Activa el almacén para que recepción sea realizada en 2 pasos. De esta forma recepcionas la mercancía en una ubicación. Si está correcto pasará a la siguiente, si no está correcto la devuelves a proveedor.

Requeriríais un poco de formación en la configuración de logística.
Cierro issue, ya que no es tal. Es más bien una duda funcional.

Cordiales saludos!
