### ISSUE TITLE
How to configure advanced routes for manufacturing?

### ISSUE THREAD

**Issue by RamiTHelal** [odoomrp/odoomrp-wip#724]
I want to create a warehouse route, that picks the BOM components of product A (let's say these components are B, C, and D) from the raw materials warehouse RWH, to the manufacturing warehouse MWH to begin the manufacturing of product A.

I tried the pull rule and it gets the desired flow but it picks the finished product itself not its components!

Any help will be highly appreciated.

**Comment by pedrobaeza** [comment]
This query is out of the scope of the project. Please post it on help.odoo.com.
