### ISSUE TITLE
Clarification needed on MPA and sale plans

### ISSUE THREAD

**Issue by clonedagain** [odoomrp/odoomrp-wip#728]
@anajuaristi, @pedrobaeza 
I'm trying to understand how the planning features are implemented in OdooMRP, because there is a pressing requirement for production forcecasting from my users.

On one hand there is a sales forecast, which can generate procurements based on past sales, right?

On the other hand there is a group of modules to group procurements in procurement plans, but it's not connected to the sales forcast and I can't seem to enter data manually in it, only import existing data.
What is the point of this, would you be kind enough to elaborate about the use case it serves please ?

Depending on the features offered, I'll probably base my own development on one of those, and of course contribute them back either to OdooMRP or OCA.

**Comment by pedrobaeza** [comment]
Hi, @clonedagain,

The procurement plan is a quick and dirty solution that I don't like too much, but Ana proposed for solving one existing problem: all procurements are solved in the moment without time frame or any planning date consideration. This leads that orders planned in a year are inmediately procured.

With this "plan", you can group the procurements manually to avoid the execution of them.

**Comment by anajuaristi** [comment]
The plan module changed so much from march that I think we could close this issue.

@clonedagain please try again. It has been heavily improved. 
You can also test the new stock_planning module. Both are complementary. If I can take some time during next weeks I will make a new video to show how both modules work together

Thank you
