### ISSUE TITLE
stock quant merge y manual quants

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#737]
Buenas... 

Un par de cosillas que hemos detectado con estos 2 módulos instalados.

stock quant merge SOLO se ejecuta si pulsas la acción do_unreserve. 
Si pulsas manual quants, asignas a mano y vuelves a pulsar seleccionando otros quants, los anteriores no se mergean.

Para evitar el tema, creo que al pulsar manual quants debería ejecutarse do_unreserve a fin de que los quants antiguos vuelvan a juntarse y se parta de una situación "limpia".

Problema de esto es que si pulsan manual quants y vuelven a pulsar lo que hubiesen hecho anteriormente no se mantiene, pero creo que es mal menor porque ahora tampoco aparecen pulsadas las casillas anteriores ni nada. Simplemente aparecen los quants "partidos" y hay que  volverlos a coger igualmente

Relacionado con esto CLM0151 Eliminar División de Lotes reportado por ALM

**Comment by oihane** [comment]
Si cuando seleccionas el quant de forma manual no seleccionas la cantidad completa tendrás que volver a seleccionar, por lo que si hicieses el unreserve, todo lo que ya hubieses seleccionado se deshace. Lo que pasa al seleccionar el quant manualmente, es que lo divide cuando se asigna, es decir es un error que comete el usuario. No sería más correcto que mergease aquellos quants que ha asignado? Siempre que se quiera reducir el número de quants. Yo creo que es mejor opción que hacer el unreserve cada vez que ejecutes el manual, porque cuando haces el automatico tampoco hace el unreserve.

**Comment by anajuaristi** [comment]
Si por eso, se deshace pero no lo veo problema porque ahora tampoco te deja seleccionados los quants que había, sino que les tienes que volver a dar click otra vez en el asistente.

Ejemplo: tienes un quant "1" de 20 unidades y un quant "2" de 20 unidades, necesitas 25 unidades

Tanto manual como automáticamente supongamos que asignas los 20 del "1" y 5 del "2", si vuelves a pulsar manual quants... ves
quant 1 20 unidades
quant2 15 unidades
quant2 5 unidades
pero NINGUNO está clickado por lo que el usuario tiene 3 quants para elegir en vez de dos y si vuelve a elegir el de 20 y el de 15, la siguiente vez que entra ve un "cachito" más... y otra vez sin clickar esta vez verá.
quant 1 20 unidades
quant2 10 unidades
quant2 5 unidades
quant2 5 unidades

Por lo que veo mucho más correcto que cada vez que pulse manual quant el usuario vea
quant 1 20 unidades
quant2 20 unidades

Y ahora que has dicho lo de asignación automática, creo que ese también debería llamar al unreserve igualmente para que se haga el merge de los lotes/quants que se reasignan, por si acaso.
O sea, creo que CADA VEZ que se "desasigna un quant", sea como sea, bien sea porque lo hacemos con manual quant, bien sea porque damos al botón do_unreserve, bien sea porque se asigna otro automáticamente al comprobar disponibilidad... debería de ejecutar el merge quant para los que se quitan de la asignación.

**Comment by pedrobaeza** [comment]
Sin profundizar demasiado, como norma general diría que hacer un unreserve automático es MALA IDEA.

**Comment by anajuaristi** [comment]
@oihane @pedrobaeza cierro esto
Al final, hay otro PR por ahí que nos mantiene los quants previamente asignados. Aparte de que esto también ha habido que tocarlo varias veces desde marzo por el tema ese del do_prepare_partial.
Ya no aplica el issue
