### ISSUE TITLE
Mejora en los módulos de packaging

### ISSUE THREAD

**Issue by pedrobaeza** [odoomrp/odoomrp-wip#738]
@alfredoavanzosc, estoy viendo un método de ORM llamado `read_group`, que permite obtener datos agregados por cualquier agrupación. Creo que eso puede ser mejor solución para obtener los totales de los paquetes y demás. ¿Lo miras?

**Comment by anajuaristi** [comment]
@alfredoavanzosc @pedrobaeza 
Esto también ya se hizo hace varias semanas. 
Cierro
