### ISSUE TITLE
Mejora de usabilidad en Abastecimientos en excepción

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#742]
Actualmente si un abastecimiento está en excepción y se "arregla" el problema que causa la excepción, es necesario ir manualmente y uno a uno "ejecutando" el resto de abastecimientos que se encuentran en la misma situación

Ejemplo --> Un producto no tiene proveedor, lo vendo, se crea abastecimiento que al ser ejecutado va a excepción. Así, lo vendo 10 veces, se crean 10 abastecimientos en excepción.
Para repararlo cojo uno cualquiera, le pongo proveedor y reejecuto. Ya va correcto pero... tengo que ir a los otro 9 y pulsar el botón de reejecutar.

Para arreglar esto, sería suficiente con 
- Al pulsar "ejecutar" de un abastecimiento que esté en excepción --> 
     .- Buscar si existe otro abastecimiento en excepción que cumpla las siguietnes condiciones: Mismo producto,almacén, ubicación, regla 
     .- Si existe, reejecutar

@pedrobaeza valida enfoque porfa
@alfredoavanzosc te asigno tal y como hemos hablado

Creo que el módulo iría a utils.

**Comment by pedrobaeza** [comment]
Se supone que cuando lanzas de nuevo el planificador, revisa esos abastecimientos en excepción. De todas formas, es tan fácil como seleccionar todas las excepciones desde la vista lista y darle a volver a ejecutar. No le veo utilidad a eso que propones.

**Comment by anajuaristi** [comment]
Es que no hace ni uno ni otro.
Es decir... en la vista de lista no puedes reejecutar, tienes que ir uno a uno y el planificador no recalcula. Es decir, el planificador pasa olímpicamente de las órdenes en excepción. Se quedan ahí.

**Comment by pedrobaeza** [comment]
Pues veo más lógico entonces tener la acción a nivel de vista que hacer esa operación oculta al usuario.

**Comment by anajuaristi** [comment]
@pedrobaeza 
Comentando con Alfredo... igual de la misma deberiamos añadir en menú esas 3 acciones, para que se pueda seleccionar y ejecutar dicha acción con los abastecimientos seleccionados:

.- Ejecutar (pasa de confirmado a en ejecución)
.- Cancelar
.- Volver a confirmado

Sería quizás lo más sencillo, crear las 3 acciones desde menú.

**Comment by pedrobaeza** [comment]
OK

**Comment by anajuaristi** [comment]
@alfredoavanzosc adelante con ello pues.
@pedrobaeza va a utils? O lo ves con enjundia suficiente para wip?

**Comment by pedrobaeza** [comment]
utils de cabeza

**Comment by alfredoavanzosc** [comment]
El PR  es el https://github.com/odoomrp/odoomrp-utils/pull/36#issuecomment-88016587

**Comment by alfredoavanzosc** [comment]
Esto ya está realizado, Pedro ya realizó el merge en su día, el módulo se llama "procurement_manager", y se encuentra en odoomrp-utils
