### ISSUE TITLE
Translations of forms and views

### ISSUE THREAD

**Issue by lmurta** [odoomrp/odoomrp-wip#743]
I created and translated a .po file for my language (pt_BR).
After importing the .po file some terms are translate and other not:
![screenshot from 2015-03-30 11 47 40](https://cloud.githubusercontent.com/assets/605261/6898807/a0bcbf58-d6d2-11e4-82e1-b91616251c1b.png)

**Comment by pedrobaeza** [comment]
Maybe you haven't overwritten correctly the terms, but this is not something about OdooMRP itself, but Odoo. Please export again pot file and import on a fresh DB, or choose to load language overwriting translations.
