### ISSUE TITLE
Product variant sales: Button copy does not respect the status of the order

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#752]
The new button right from the product on the sales order line allows copying a position.

The problems are:
1. When an order is confirmed, the button should not be active. It is, so I can continue to duplicate lines that are created in the status draft, even if the order has the status confirmed.
2. When not in edit mode, the button should not be active. I can just press the button, even if I am not editing. This is a problem, as someone can just come on the button and press it, believing nothing will happen as he is not in edit mode. I believe this button should only be active in edit mode, and if the status of the sales order allows changes.

Regards

**Comment by anajuaristi** [comment]
About point 1: I agree... it's a bug and should be solved
About point2: I'm not so sure because you may want duplicate the line and open to change something. I don't see big issue on it and even I consider it may help user to avoid edit/save buttons sometimes.

anyway @pedrobaeza opinion?

**Comment by ybofr** [comment]
Ana,

The issue I have is that, only the sales order gets changed, no other document. So, if I press the duplicate button, I change the sales order, but the delivery order is not changed and I do not notice that there is a discrepancy between sales order/delivery order/invoice. 
As long as the order is NOT confirmed, i find it cool to just press the button without going to edit. But as soon as it is confirmed, I have an issue.

What do you think?

By the way, great module that you developed. It changes totally the usage of the variant and it makes it really GREAT.

**Comment by pedrobaeza** [comment]
First point is fixed.

About second point, I agree with Ana: we may want to click in edit or view mode. Indeed, this is just as the regular buttons in the header.

**Comment by ybofr** [comment]
Thanks Pedro for the quick fix.

**Comment by ybofr** [comment]
We tested it and it still copies when I have confirmed the order.

**Comment by pedrobaeza** [comment]
Sorry, I have discovered that state field on lines is not the same as state field for the header.

It's amended here: https://github.com/odoomrp/odoomrp-wip/commit/ca0c0bac4d90367908b50ba561e15af03d2d64c6.
