### ISSUE TITLE
CLM0272  Chequeo de valor válido en atributos tipo Rango en la OF

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#754]
En una OF con configurador, al introducir los valores de los atributos, en los tipo rango NO comprueba que el valor introducido esté dentro del rango y No da ningún aviso.

**Comment by pedrobaeza** [comment]
Esto debería tener un constraint, sí, porque si no, ¿qué sentido tiene el rango?

**Comment by oihane** [comment]
Creo que esto se hizo para ventas pero no para compras y para fabricación. @anajuaristi lo tienes probado en compras?

**Comment by oihane** [comment]
veo que lo que pides estaría hecho, puedes decirme donde has visto que no lo hace, porque parece que no se haya instalado el modulo mrp_product_variants_types

**Comment by anajuaristi** [comment]
Ahhh... aquí ya sé lo que está pasando.
El valor del atributo se está evaluando al grabar el pedido. ¿No debería ser en el onchange del campo custom en el configurador? Si no, da la sensación de que no evalúa. El otro día no llegamos a grabar el dato, creo. Simplemente anduvimos "jugando" con diferentes valores del configurador.

Ya direis si cambiamos la evaluación de la constraint o sabiéndolo se queda donde está. 
Como veais.
@pedrobaeza @oihane

**Comment by pedrobaeza** [comment]
Sí, es cierto que la advertencia sale demasiado tarde. La forma de hacerla "instantánea" es con el onchange del valor, que lance un raise exceptions.Warning en caso de que no sea correcta, o devolver el warning simplemente en el onchange, porque no sé si lo primero causaría alguna inconsistencia (en principio, creo que no).

**Comment by oihane** [comment]
Entonces... se lo pongo?

**Comment by pedrobaeza** [comment]
Sí
