### ISSUE TITLE
CLM0273  En OF con configurador, error "unidad de medida incorrecta"

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#755]
Cuando se seleccionan valores en el configurador pero no existe producto creado ( es decir, el campo product_id queda vacío todavía) No permite grabar la OF por "unidad de medida incorrecta". El campo UDM queda sin informar. 

Si el parámetro de configuración "varias unidades de medida" no está activado, el campo no se ve en la OF y por tanto puede confundir al usuario porque no se puede informar ni siquiera a mano.

El error se solucionaría si al seleccionar un template_id en una OF, el onchange informase el campo UDM y no solo se informase en el onchange del product_id

**Comment by pedrobaeza** [comment]
Justamente es ése el problema.

**Comment by oihane** [comment]
Uhm... parece que con lo que dice Ana no se soluciona, https://github.com/odoomrp/odoomrp-wip/blob/8.0/mrp_product_variants/models/mrp_production.py#L106

**Comment by pedrobaeza** [comment]
Resuelto en https://github.com/odoomrp/odoomrp-wip/commit/aca051f935e51606f4043e91234eb4a2bc5cba53.

@oihane, acostúmbrate por favor a dos cosas:
- Incluir el nombre del módulo en cada commit. Así, me ha sido difícil localizarlo. No sirve de nada que en el commit inicial lo pongas, porque luego en la lista de commits eso no se ve.
- Incluir en uno de los commits (normalmente el inicial), el texto "Fixes #num_incidencia" o "Closes..." para que se cierre automáticamente la incidencia al mergear.
