### ISSUE TITLE
Error de Travis

### ISSUE THREAD

**Issue by pedrobaeza** [odoomrp/odoomrp-wip#756]
El error se debe a una búsqueda, domain o similar que se hace en algún módulo con un campo x2many (one2many o many2many), que no está soportado por el actual estándar.

Este PR (https://github.com/odoo/odoo/pull/5898) lo arregla para el estándar, y éste para OCB (https://github.com/OCA/OCB/pull/181), pero mientras no lo integren, va a seguir dando error.

Hay dos opciones:
- Localizar dónde está ese dominio y buscar otra forma de ponerlo.
- Esperar a que integren el parche.

**Comment by oihane** [comment]
Arreglado cierro
