### ISSUE TITLE
The internal reference is created for the first variant and added to the product template

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#761]
Hello,

I created the following: 1 product template, 1 sales order based on the product template.
Then, I confirmed the sales order and the product variants were created. Then, the field internal reference was set on the product template, using the mask. This is wrong. I do not want to have an internal reference, that refers to the first variant, saved in the product template.
Then, I created a second variant, but the product template still had the wrong internal reference.

Thanks for the correction

**Comment by pedrobaeza** [comment]
I think this is part of the standard behaviour to write back the internal reference to the template, but @anajuaristi should confirm it

**Comment by ybofr** [comment]
I do not think so. I have used internal reference for other customers and it would not write it back to the template.

Regards
Eva P.
