### ISSUE TITLE
Product attributes were deleted when changing the quantity in the sales order

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#762]
I created a sales order with the quantity one. Before saving it, I decided to change the quantity. Suddenly, many attributes were deleted and then, the system would of course not allow to confirm because attributes were missing.

This is a mistake that was on the last version. We reversed to an earlier version and this bug was not present.

Regards

**Comment by pedrobaeza** [comment]
We cannot reproduce the problem in our installations. Can you provide the installed module list and a step by step flow that gets to the error?

**Comment by ybofr** [comment]
Hi Pedro,

We rolled back the update of the module as we had to go live with the system, so I do not have the possibility to reproduce or inform further about it. You may close the issue and we will check later, if this happens again.

## thanks

Eva P.

Affordable high quality training on Odoo-training.com http://odoo-training.com/
