### ISSUE TITLE
purchase landed cost not update cost

### ISSUE THREAD

**Issue by spadae22** [odoomrp/odoomrp-wip#763]
Helllo,
I set up the product with ave cost and created a new PO, DO. Then used added the landed cost. The calculation is correct, but the update product cost does not update?

**Comment by spadae22** [comment]
OK, I really like this module. The issue in _product_price_update I see is when qty <=0, it sets the price to move.price_unit which is the cost on the PO. Not the landed cost. If existing stock moves exist, then the calculation is correct since it used the other calculation. 

The calculation works if: 
if product_avail <= 0:
                new_std_price = new_price

I am not sure if the cancel will be an issue. But if I cancel, update, the cost is corrected.

**Comment by anajuaristi** [comment]
@spadae22 
Could you test again please? 
I think we solved all the possible issues related to this module so, if it still happens, please reopen the issue. 
Thank you

**Comment by spadae22** [comment]
Fixed in 8af8799
