### ISSUE TITLE
Issue con la Fecha final de las Órdenes de Trabajo

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#774]
Hola.

A ver si me explico correctamente.

Fijándome en cómo gestiona Odoo la programación de Órdenes de trabajo me he encontrado con que al generar una Orden de producción y elegir su "Fecha programada", Odoo calcula la "Fecha final" (date_planned_end) de la Orden ignorando la parte de los minutos y segundos. Me explico: 
- Tengo un Producto para fabricar y su Ruta de producción con dos Operaciones: Operación A dura 4 horas y Operación B dura 1,5 hora; realizadas cada una en un Centro de producción distinto.
- Creo una Orden de producción del Producto con "Fecha programada" = 17/04/2015 11:24:32.
- Inicio la producción, por tanto la primera Orden de trabajo generada comienza a la misma hora: "Fecha programada" = 17/04/2015 11:24:32.
- Aquí viene el problema: El campo de la Orden que indica "Fecha final" no se calcula correctamente. Muestra por pantalla "17/04/2015 15:00:00" en vez de ser la suma de "Fecha programada" + "Horas" de la operación (en este caso, 4 horas) = 17/04/2015 15:24:32. Además, este valor de la "Fecha final" será el que use para dar comienzo a las siguientes Órdenes de trabajo, con lo cual se va arrastrando el error. Conclusión (visto un poco el código de Odoo en el módulo "mrp_operations"): Primero ignora los minutos y segundos de la "Fecha programada" y después le suma las "Horas" de la Operación.

Ignorar los segundos parece razonable, pero no los minutos. No es lo mismo acabar una Orden a las 09:00:00 que a las 09:59:59.

He reportado este issue a Odoo: https://github.com/odoo/odoo/issues/6348

Pero quería saber si lo habíais ya contemplado con algún módulo o es algo parecido a lo que pasa con https://github.com/odoomrp/odoomrp-wip/issues/750

**Comment by pedrobaeza** [comment]
Buenas, Eduardo, efectivamente, ese comportamiento es erróneo, pero hay que corregirlo en el propio Odoo, y es por lo que hay que luchar. Voy a suscribirme al issue para seguirlo.

Cierro aquí.

**Comment by pedrobaeza** [comment]
Aclaro que no es lo mismo que #750, porque lo otro tiene que ver directamente con la gestión de operaciones.

**Comment by ghost** [comment]
Correcto correcto, no es lo mismo. Me refería a que también es un comportamiento erróneo del core.
