### ISSUE TITLE
mrp_packaging al comprobar disponibilidad debería coger lote del padre

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#789]
Hemos detectado lo siguiente:

Orden de fabricación de producto base
Crear órdenes de envasado
Confirmar orden de envasado

Si en el movimiento del producto base (producido en el padre) hay más lotes creados por otras OFs, o restos que no se hayan utilizado, al comprobar disponibilidad le asigna esos lotes
En este caso, SOLO debería asignar el lote del "padre" en las órdenes de envasado hijas.

Es necesario incluir esta restricción en la selección de lotes del movimiento cuyo producto es igual que el producto de la OF padre, tanto en el botón "comprobar disponiblidad" como en el botón "manual quants"

**Comment by oihane** [comment]
Resuelto en https://github.com/odoomrp/odoomrp-wip/commit/12746d8f7aeb24744d9c729815877f746236d028 pendiente de validar por @anajuaristi

**Comment by anajuaristi** [comment]
Cierro pues
