### ISSUE TITLE
When Opening a Inspection Test from Work Order on Manufacturing order Can not edit Question Values

### ISSUE THREAD

**Issue by slevenhagen** [odoomrp/odoomrp-wip#798]
I have set Manufacturing Order to edit mode, then clicked on Work order Tabs, then click to "Quality Test" page then open the actual inspection  in pop up window neither the Work order or the quality test can be edited or have button to enter  edit mode .  instead need to close Manufacturing order and go to Quality COntrol>>Inspections and  open there to edit.

**Comment by anajuaristi** [comment]
Take in mind inspections are created in draft status. You need to advance step fordward to set values.
Try to push todo button left up side on inspection and let us now

**Comment by slevenhagen** [comment]
Yes I have changed the Status and clicked the todo button I have tested  this flow works  when opening the inspection from the Quality Control Menu and it works fine, but when attempting same step from Work order on manufacturing order is when I have this issue, Let me show steps I'm using.

Open Production Order in edit mode and Select Work Orders page tab.
![step1](https://cloud.githubusercontent.com/assets/6641230/7401046/fe4c1406-ee8e-11e4-8e98-78b3c5fbeba0.PNG)

Opened the High Lighted Work Order and then go to Quality Test page tab  ( It seems here the work order is opening in Read Only)
![step2](https://cloud.githubusercontent.com/assets/6641230/7401054/10d5d896-ee8f-11e4-96b0-4e1e9a05567d.PNG)

Then on Inspection  I clicked  ToDo  to set Status from Draft to Ready.

![step3](https://cloud.githubusercontent.com/assets/6641230/7401067/425c6f9c-ee8f-11e4-9f83-80c6e5db43bb.PNG)

The Highlighed values fields here are Read Only as you notice there is no save button on this popup.

**Comment by pedrobaeza** [comment]
This is probably an error on the handling of edit context of the web client, not the module itself, but you should click on the smartbutton "1 Created inspections" instead to get the associated inspections, which are open on background, and you can edit them.
