### ISSUE TITLE
Pequeños ajustes en el nuevo módulo de plan

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#801]
Mejoras de usabilidad
1. Sacar a la vista los botones individuales de los abastecimientos al tree
2. Hacer visible en el tree el método de abastecimiento ( rule_id del propio procurement)
3. Meter un shorcut que me permita navegar a los abastecimientos incluidos en un plan
4. La descripción, en la creación del abastecimiento en vez de llevar un texto fijo "generated from plan" ponerle la secuencia del plan ejemplo: "PPLAN-000013"
5. Igual con el campo ORIGEN, ponerle el número de plan.

Issues detectados:
1. Los abastecimientos tienen que ser creados con almacén/ubicación y rule asignada. (Mirar creación automática de abastecimientos, cómo lo hace para seleccionar la ubicación) porque si no, se van todos a excepción. 
2. Aunque desde un plan he ejecutado un abastecimiento y tiene asignado pedido de compra
Plan mayo1, pedido 92, el pedido no se visualiza en el plan

Hasta el momento esto... por la tarde sigo probando... 

Saludos!!

**Comment by anajuaristi** [comment]
Testeado en ofi... por mi parte y a falta de alguna prueba más :+1: RTM

**Comment by anajuaristi** [comment]
Bueno.. una pequeña chorradilla...
El botón de shorcut del plan a los abastecimientos se va de línea...

**Comment by anajuaristi** [comment]
Otra pequeña cosa... 
En los puntos 4 y 5 había pedido que se asigne el número de secuencia del plan y no el nombre. Se está asignando nombre en ambos. Podemos dejar en la descripción el nombre y en origen la secuencia por ejemplo
Secuencia PPLAN-000013 iría al campo origen del abastecimiento
Nombre Mayo1 iría al campo descripción

@alfredoavanzosc @pedrobaeza

**Comment by anajuaristi** [comment]
Otro pequeño bug
Al hacer la explosión del BOM, no propaga cantidades a siguientes niveles

**Comment by alfredoavanzosc** [comment]
Todo lo solicitado por Ana esta corregido, pendiente de que Pedro revise los módulos, y realice el Merge. El PR es el https://github.com/odoomrp/odoomrp-wip/pull/799.

**Comment by anajuaristi** [comment]
esto está hecho hace varias semanas.
Cierro issue
