### ISSUE TITLE
Coste real Pre y Post operación

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#803]
Hola.

Intentaré explicarme por partes, ya que hablo de dos módulos:
- El módulo mrp_production_project_estimated_cost genera las líneas analíticas para los costes de pre y post operación. Pero además, también les asigna directamente el coste real a través del campo "amount", con un valor igual al del Precio de coste del Producto asociado al Centro de producción para el coste de pre o post operación, sin tener en cuenta el tiempo que conlleva:

![image](https://cloud.githubusercontent.com/assets/8233008/7471864/80c618e0-f32c-11e4-9e3f-9dd95848b9ea.png)

Mi duda sería: si para los costes estimados se multiplica el tiempo de pre/post operación por el coste pre/post operación, ¿por qué no igual para el coste real?
- El módulo mrp_production_real_costs calcula los costes reales de una Orden de producción a través del campo "amount" de las líneas analíticas. Este campo se calcula en distintos modelos pero siguiendo la siguiente sintaxis:
  'amount': - (price \* operation_line.uptime)
  Lo cual genera que el campo "amount" sea siempre negativo para todos los costes reales, excepto para los de pre y post operación, pues aparecen en positivo en las líneas analíticas y por tanto están disminuyendo el coste, no aumentándolo.

Espero haberme explicado bien. Gran trabajo el que estáis haciendo!

**Comment by pedrobaeza** [comment]
@agaldona, esto está ya resuelto?

**Comment by anajuaristi** [comment]
Esto... lo que ha pasado es que inicialmente imputabamos en positivo y luego unificamos para que fuese como el estandar imputando los costes en negativo y se nos debio escapar cambiarlo tambien en este punto de pre y post operacion.
Gracias por reportarlo!

**Comment by anajuaristi** [comment]
En cuanto al primer punto. es correcto que se deberia tbien multiplicar. Por tanto, es un bug

**Comment by agaldona** [comment]
Acabo de revisar la última versión del código, y realmente, toda esta parte está modificada. Tanto en costes reales como en estimados, el coste se multiplica por las horas y se imputa en negativo. 

```
                if (wc.time_start and line.workcenter_id.pre_op_product):
                    name = (_('%s-%s Pre-operation') %
                            (record.name, line.workcenter_id.name))
                    product = line.workcenter_id.pre_op_product
                    amount = product.cost_price * wc.time_start
                    qty = wc.time_start
                    vals = record._prepare_cost_analytic_line(
                        journal, name, record, product, workorder=line,
                        qty=qty, amount=-amount,
                        estim_std=-(qty * product.manual_standard_cost),
                        estim_avg=-(amount))
                    analytic_line_obj.create(vals)
                if (wc.time_stop and line.workcenter_id.post_op_product):
                    name = (_('%s-%s Post-operation') %
                            (record.name, line.workcenter_id.name))
                    product = line.workcenter_id.post_op_product
                    amount = product.cost_price * wc.time_stop
                    qty = wc.time_stop
                    vals = record._prepare_cost_analytic_line(
                        journal, name, record, product, workorder=line,
                        qty=qty, amount=-amount,
                        estim_std=-(qty * product.manual_standard_cost),
                        estim_avg=-(amount))
                    analytic_line_obj.create(vals)
```

De todas formas, si veis cualquier cosa que no sea correcto me lo hacéis saber. 
Gracias!

**Comment by ghost** [comment]
A día de hoy se que habéis modificado un poco ambos módulos, así que la verdad no se si sigue aplicando este issue. Trataré de revisarlo

**Comment by pedrobaeza** [comment]
Cierro entonces
