### ISSUE TITLE
Orden de producción usando una Plantilla que no crea automáticamente variantes

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#804]
Tras instalar los módulos product_variants_no_automatic_creation, mrp_product_variants y mrp_product_variants_operations; no me deja crear una Orden de producción de una Plantilla de producto que tiene 0 variantes. De hecho, ni me aparece la Plantilla de producto en el campo correspondiente ni me aparece la opción de "Buscar más" en el campo product_template del modelo mrp.operations.

![image](https://cloud.githubusercontent.com/assets/8233008/7514978/fa4ce6f2-f4c2-11e4-8da8-d377054cd21f.png)

Quizá me estoy confundiendo con mi planteamiento: no quería crear las Variantes hasta que no se fabricasen alguna vez y así solo tener las Variantes que se han fabricado y no todas. ¿O el configurador de fabricación solo está pensado si están creadas todas las Variantes de la Plantilla?

**Comment by pedrobaeza** [comment]
Buenas, Eduardo,

En realidad, no es una cuestión de los módulos de OdooMRP, si no del método de búsqueda estándar del _product_template_, que busca las plantillas de los productos que cumplen ese criterio (https://github.com/odoo/odoo/blob/8.0/addons/product/product.py#L818). Como no hay ningún producto, no puede buscar su plantilla asociada. Si no tecleas nada, entonces sí que podrías encontrar buceando en el "Buscar más..." la plantilla que has creado.

Lo que he hecho es sobreescrir ese método para permitir buscar por el nombre del producto, y así contrarrestar ese extraño método estándar.

**Comment by anajuaristi** [comment]
Otro "truco" para saltarte este comportamiento del standar, es crear manualmente un producto "sin atributos" asociados. Para ello, vas a la plantilla, navegas a variantes y pulsas el botón "crear" a mano. Esto crea un producto vacío y ya te permite buscarlo por plantilla

**Comment by pedrobaeza** [comment]
Ana, eso ya no hace falta. Está parcheado en nuestro módulo el error del estándar.

**Comment by anajuaristi** [comment]
Si, pero sucede también en otros puntos... y con el truquillo que escribo se "arregla" en todos ellos.
Quizás el parche que deberíamos pensar es crear al menos un product_id en todos los casos, aunque pongamos no crear atributos. No sé. Conceptualmente es correcto no crear ninguno, pero en algunos sitios el sistema va a "buscar" al menos uno.

**Comment by pedrobaeza** [comment]
Está solucionado en todas partes: https://github.com/odoomrp/odoomrp-wip/blob/8.0/product_variants_no_automatic_creation/models/product.py#L111
