### ISSUE TITLE
Extensión 2: Generar por nivel y borrar rama en abastecimientos de plan

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#807]
1. Permitir generar la explosión por niveles

Añadiremos un botón en líneas de abastecimiento que sea: Generar abastecimientos solo para este nivel.
El botón genera todos los abastecimientos del siguiente nivel en la lista de materiales y no desglosa todo el árbol.
2. Permitir borrar una rama del árbol
Añadiremos un botón en líneas de abastecimiento que sea: Borrar árbol de abastecimientos de esta rama
El botón borra este abastecimiento y todos sus abastecimientos hijos, en toda la rama.

@pedrobaeza validar

**Comment by pedrobaeza** [comment]
Esto nos permite borrar alguno de los botones que estaban en cabecera.

Además, se añade un botón que sea desplegar el siguiente nivel, que hace justamente eso (en lugar de desplegar todos los niveles). Para ello, cambia el método recursivo a uno que sólo examine un nivel y devuelva lo obtenido en ese nivel, y cuando hagas la explosión de todos los niveles, simplemente llamas iterativamente a explotar niveles para cada una de las líneas devueltas.

**Comment by alfredoavanzosc** [comment]
Realizado en PR https://github.com/odoomrp/odoomrp-wip/pull/799

**Comment by anajuaristi** [comment]
Cierro
