### ISSUE TITLE
Extensión3: fusión de módulo MPS con Plan

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#808]
Vamos a simplificar y fusionar el módulo MPS con el módulo de plan.
Para ello:

Vamos a llevar los botones y sus correspondientes wizards: Importar desde ventas e importar desde compras al plan
En vez de crear el producto intermedio del mps y desde ahí un abastecimiento, se creará directamente el abastecimiento dentro del plan
Los cálculos del wizard y sus campos se harán exactamente igual que se hacen actualmente, lo único que del wizard, eliminamos el concepto "partner" en el listado (de momento para simplificar, ya veremos si luego hace falta o no)
Los campos fecha de cabecera de prevision, pasan ahora a ser los campos fecha de la cabecera del plan, para los cálculos que realiza el wizard en cuanto a cantidades de material en un periodo.

@pedrobaeza validar

**Comment by pedrobaeza** [comment]
:+1:

**Comment by alfredoavanzosc** [comment]
Realizado, se encuentra en la última subida del PR https://github.com/odoomrp/odoomrp-wip/pull/799

**Comment by anajuaristi** [comment]
Hecho. Cierro
