### ISSUE TITLE
[8.0] mrp_operation_extension module not calculate the WO schdule

### ISSUE THREAD

**Issue by jeffery9** [odoomrp/odoomrp-wip#809]
after install mrp_operation_extension, found that it does not calculate WO schedule time, instead just use the `hour_nbr` multiple with cycle, this is wrong logic.  `hour_nbr` is the time use to to get the operation of the routing to be ready to work, not the total time to finish this operation.

as the hours is wrong, so the planing calculate is wrong too.

**Comment by jeffery9** [comment]
in  class `MrpRoutingWorkcenter(models.Model):`

defined 

```
@api.one
@api.onchange('op_wc_lines')
def onchange_lines_default(self):
    for line in self.op_wc_lines:
        if line.default:
            self.workcenter_id = line.workcenter
            self.cycle_nbr = line.capacity_per_cycle
            self.hour_nbr = line.time_cycle
            break
```

routing operation `cycle_nbr` and `hour_nbr` is totally different with the original mrp module.

this method overwrite the logic of mrp_operation, the is incompatible

**Comment by jeffery9** [comment]
i think that should add  field `cycle_nbr` and `hour_nbr`  to model `mrp.operation.workcenter`

**Comment by pedrobaeza** [comment]
Hi @jeffery9, we have reused that field to avoid propagating more data between all the structure because is a dead field with no use except to display the information.

**Comment by jeffery9** [comment]
for the original design,  BOM explode calculate  2 result, one is materials requirement, and another is time requirement.  for time calculation, compute the cycle need to complete the production first, then use cycle multiple with  total time consumed in the work centers and the preparation time for the routing operation, formula is  `wc_use.hour_nbr * mult + ((wc.time_start or 0.0) + (wc.time_stop or 0.0) + cycle * (wc.time_cycle or 0.0)) * (wc.time_efficiency or 1.0)`

for the logic that you extended is very different with those original.  

code as 

```
        for wc_use in routing.workcenter_lines:
            wc = wc_use.workcenter_id
            d, m = divmod(factor, wc_use.workcenter_id.capacity_per_cycle)
            mult = (d + (m and 1.0 or 0.0))
            cycle = mult * wc_use.cycle_nbr
            result2.append({
                'name': tools.ustr(wc_use.name) + ' - ' + tools.ustr(bom.product_tmpl_id.name_get()[0][1]),
                'workcenter_id': wc.id,
                'sequence': level + (wc_use.sequence or 0),
                'cycle': cycle,
                'hour': float(wc_use.hour_nbr * mult + ((wc.time_start or 0.0) + (wc.time_stop or 0.0) + cycle * (wc.time_cycle or 0.0)) * (wc.time_efficiency or 1.0)),
            })
```

**Comment by pedrobaeza** [comment]
We have changed that to acommodate to the new semantic. Have you seen it?

**Comment by jeffery9** [comment]
yes, have see you guy have changed a lot of things, but it very hard to
understand those.  have one question is you override bom_explode result to
add `time_start` and `time_stop`, but those two properties has not beed
defined in `mrp.routing.workcenter`.

are there have any document for how to use it. thanks.

On Tue, May 12, 2015 at 7:22 PM, Pedro M. Baeza notifications@github.com
wrote:

> We have changed that to acommodate to the new semantic. Have you seen it?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/odoomrp/odoomrp-wip/issues/809#issuecomment-101243845
> .

## 

Jeffery        -odoo expert form kunshan, suzhou, china

**Comment by pedrobaeza** [comment]
Sorry, but we don't have. The funding we have is only for development.

**Comment by anajuaristi** [comment]
@jeffery9 

I'll try to explain what we are trying to do
in our case the operation can be done in a workcenter and the time cost could change if you make in one workcenter or in another
wc_hour field is related to operation on standar Odoo and we are mantaining this field but the value for operation will depend on machine cost configuration
This cost could be different depending on cycles by hour, machine cost... and so on.
At the end the sum of all operations wc_hour is the full order wc_hour

The last point is the time should change on MO depending on the number of pieces you are going to produce or the cycles you are going to launch.
How could you fix a time in an operation without knowing how many pieces you are going to obtain? This is what we are trying to fix with this changes.

About the calendar scheduling, is quite difficult to fix a good plan if we don't mix operations with machines calendar and this concept should be taken in account to calculate planned starting time and not even the standard is doing that
Just an example: if I calculate data now and machine working time is from 08:00 to 08:00 everyday, the work order should be planned for tomorrow 08:00 but it's just being planned for now. 

There is still hard work to do with calendars and capacity. Probably that would be the next big work to do on our project.

Thank you:

Ana
