### ISSUE TITLE
Costes reales ajustes y cambios

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#811]
Buenas... Hay algunas cosillas en costes reales que debemos ajustar... pongo las que he visto de entrada y según vaya haciendo más pruebas iré añadiendo más si hace falta.
1. En la pantalla de costes que se hizo que se lanza desde la OF, no se visualiza el producto
   Además, aunque se lance cuando la orden está en progreso o realizada, no contempla las líneas analíticas de imputación de los costes reales por lo que la casilla siempre está a cero.
2. Es necesario un shorcut que nos lleve directamente a los apuntes contables asociados a esta OF, para que se pueda "jugar" con las líneas de imputación. Actualmente hay que ir a través del proyecto que puede contener más OFs, y por tanto, obliga a volver a meter otro filtro

---

En su momento, al finalizar la OF hicimos que se calculase el precio de coste del producto fabricado en función de los costes reales "recopilados", esto es correcto pero creo que no lo estamos haciendo bien.
Por standar, el que debe llevar el coste unitario es el movimiento, de ahí, se crea un quant que a su vez en función del método de valoración de inventario seleccionado en la ficha del producto, actualiza o no el campo coste de dicha ficha.
Aquí 2 cambios:
1. Modificar el proceso de actualización del coste unitario del producto, teniendo en cuenta la forma standar de hacerlo (sería lo mismo que hace @pedrobaeza en el módulo landed_cost donde no se actualiza directamente la ficha, sino que se actualiza el precio unitario del quant y de ahí la ficha mediante llamadas a procedimiento standar).
En nuestro caso, habría que actualizar el precio unitario del movimiento de "producir", con los mismos cálculos que hacemos ahora. Al realizarse este movimiento actualizaría el quant y por ende la ficha de producto si es necesario pero esto no lo haremos nosotros hardcode sino llamando a procedimientos standar.
2. El standar modifica el coste en el template del producto que en fabricación, no tiene absolutamente ningún sentido ya que el coste de un producto depende fuertemente de los materiales usados en cada una de las variantes y por tanto cada variante puede tener una variación de coste importante con respecto a otra.
En el mismo punto que el standar calcula en product.template tendríamos que actualizar el campo nuevo que ya añadimos en su momento,  en product.product
Aquí me surge la duda si deberíamos seguir dejando que el standar actualice el precio de coste del template de forma standar o directamente no dejarle y que quede siempre a cero. No sé qué es mejor aquí. 

De momento creo que con esto mejoramos bastante el tema de costes reales.

**Comment by anajuaristi** [comment]
@agaldona si hay dudas me preguntas porfa.
@pedrobaeza validar los cambios

**Comment by pedrobaeza** [comment]
Sólo comentar que ya no tiene sentido actualizar el precio estándar del template.
