### ISSUE TITLE
Cambiar la fecha prevista de una OF deja tal cual las fechas de las workorders.

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#812]
Buenas.. he detectado y reportado este error a Odoo pero es bastante bloqueante para planificar por lo que lo levanto aquí en Wip para que no se nos olvide y si es necesario hacer nosotros mismos el parche:
https://github.com/odoo/odoo/issues/6694

**Comment by anajuaristi** [comment]
Resulto en parte por el fix proporcionado por Odoo
https://github.com/odoo/odoo/issues/6694

La cosa es que ahora, las OTs no se pueden planificar. Solo las OFs se pueden planificar. 
Al mover una OF, el sistema calcula fecha planificada de las OTs, pero si intentas cambiar la fecha de una OT, al grabar, le vuelve a poner la que había calculado previamente.

Este funcionamiento no tiene ningún sentido. La cosa es que puedes ir haciendo operaciones por pasos. Solo al mover la primera a antes que la fecha de la OF, le cambiaría también la fecha a la OF y al mover la última a posterior que la OF, le cambiaría la fecha prevista de fin de la OF.

Las OTs deben poder planificarse de forma independiente, si no, la fabricación por operaciones no tiene sentido. Otra cosa que se ha hecho, es modificar la vista calendario de las Ots y hacerla sobre la fecha de inicio REAL de las OTs. Ya no se pueden planificar por calendario. 

Tenemos que darle una vuelta importante a esto. Creo que ahora está peor de lo que estaba antes. 

Cambios a realizar:
1. Montar una vista calendario en OTs sobre fechas previstas.
2. Al modificar fecha prevista de inicio en OTs, verificar si fecha prevista inicio es menor que la de su padre. Si es así,modificar al padre (esto ejecutará el onchange del padre y volverá a replanificar todas las OTs, a partir de esta, lo cual creo que así a simple vista es correcto) 
3. Al modificar fecha prevista de fin en OTs, verificar si fecha prevista de fin es mayor que la de su padre. Si es así, modificar al padre. 

Con esto, estaría correcto.

@pedrobaeza valida porfa, el enfoque para resolverlo.

**Comment by pedrobaeza** [comment]
Creo que cuando dices padre, deberías hablar de OT antecesora u OT sucesora. Por lo demás, me parece correcto rectificar el comportamiento a lo debido.
