### ISSUE TITLE
CLM0305: Ampliación lista "estructura de lista de materiales"

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#823]
Actualmente se lanza la estructura en árbol de una lista de materiales desde el menú de cabecera de la propia lista. Es correcto ya que despliega la estructura de la lista con todas las listas que contiene.

Funcionalidad básica faltante:
.- NO enseña las cantidades de producto (cuidado, ya que no debe realizar la suma de cantidad en cabecera)
.- Al clickar en una de las listas de cualquier nivel, debería navegar a dicha lista.

Issue:
.- NO muestra el proceso productivo asociado. Aparece en blanco en todos los casos.

@pedrobaeza revisar y ver si me falta alguna cosa más.

**Comment by pedrobaeza** [comment]
:+1: 

Lo de la suma no sé si se podrá hacer.

**Comment by anajuaristi** [comment]
Alfredo, esto ya estaría incluido en algún PR tuyo más reciente. ¿Se puede cerrar?

**Comment by alfredoavanzosc** [comment]
Que hay Ana. Eso lo hicieron hace tiempo los becarios. El módulo es el "mrp_bom_structure_show_child". Yo he modificado este módulo la semana pasada para que muestre el precio de coste. 
Pedro ya realizó el MERGE de este módulo la semana pasada.
