### ISSUE TITLE
[mrp_bom_through_attributes] Products without BoM cannot be selected in MO

### ISSUE THREAD

**Issue by elicoidal** [odoomrp/odoomrp-wip#825]
The module works fine when the product has a BoM (it adds the requested attribute) but does not allow to select a product in the MO not linked to BoM (default Odoo behavior).
This is more an enhancement than a bug and it would require to remove the domain control at MO level which is not be desirable as is

**Comment by pedrobaeza** [comment]
Well, this means to change a lot of things in the standard. The original idea behind this module was to allow to add some raw materials depending on the selected attributes, but when treating with all our *_variants modules that inhibits the creation of product variants.

**Comment by elicoidal** [comment]
I understand indeed it might imply a deep change.
It could be a module allowing to have MO for product without BoM (we 
published that in 7).
This module can be used in your case but as well for companies who wants 
to generate the MO but are not ready to handle the BOM.

**Comment by pedrobaeza** [comment]
I have improved the README to expose this known issue then.

**Comment by anajuaristi** [comment]
Just to solve the issue... You could try to create an emply bom for the products. I think it would work on this case without touching the code or refactoring anything.
For user it would be just an small configuration. Just add an emply bom (only header without lines) and  that's all. 

@elicoidal  May you try it and tell us if it works?

Thank you

**Comment by pedrobaeza** [comment]
@anajuaristi, that's exactly the workaround I put on README (https://github.com/odoomrp/odoomrp-wip/blob/8.0/mrp_bom_through_attributes/README.rst), but it would be better to not need that.

**Comment by anajuaristi** [comment]
upsss... @pedrobaeza sorry I did not read README.

I don't know if it would be better. Having a BOM is a clear concept to see if product must to be produced. I don't know what is the impact allowing to have products to produce without a bom but just creating the empty bom the blocking point is solved so issue becames no critical. Back door found. 
:)

**Comment by elicoidal** [comment]
There is no specific impact (at least in 7.0) actually having Product 
without BoM. There is no incoming move for raw material as expected but 
that is all.
Having empty bom is OK but not ideal, the point being to simplify the 
set up for starting project.

**Comment by elicoidal** [comment]
Tested with empty bom and it does the trick for the moment.
