### ISSUE TITLE
[mrp_bom_state] it should not be able to add by_product to Active BoM 

### ISSUE THREAD

**Issue by elicoidal** [odoomrp/odoomrp-wip#826]
Currently you can edit/add by_products to active BoM.
It should not be possible if I understood well the logic of the module

**Comment by pedrobaeza** [comment]
We are actively changing this module in https://github.com/odoomrp/odoomrp-wip/pull/814, so the result is going to change a lot. I keep the issue open to see if this also happens on new version.

**Comment by anajuaristi** [comment]
@elicoidal 
We did not work very much on the by_product module. We made an small development to add by_products materials on each operation but none of our customers needs to use it so we did not strongly test. 
On the other side, we modified the bom_version module including more restrictions and so on, so please test again.
I'm closing the issue.
