### ISSUE TITLE
[mrp_bom_state] mrp_bom_by_percentage is not compatible with status logic

### ISSUE THREAD

**Issue by elicoidal** [odoomrp/odoomrp-wip#828]
It is possible to modify the BoM percentage even if historical/active is false.

Actually quite a tricky one as there might be several modification for the BoM added by multiple modules.

**Comment by anajuaristi** [comment]
mrp_bom_by_percentage check is just a help tool that allows people who build chemical formulas to know if the quantities they included on bom sum is 100 (that is 100%). System will not allow saving the formula if the sum is different from 100.
Even if you can check or uncheck the field on historical state is not impacting to the formula itself or any other data, so... quite small bug.
I'm closing
