### ISSUE TITLE
Confirm unable to complete manufacturing orders---use MRP Subcontracting

### ISSUE THREAD

**Issue by jaronemo** [odoomrp/odoomrp-wip#829]
ValueError: "null value in column "product_uom" violates not-null constraint
DETAIL:  Failing row contains (38, \u58ae\u8f2a-2101(\u52a0\u5de5) - \u58ae\u8f2a-2101(\u52a0\u5de5), 2015-05-18 09:06:43.531258, null, null, 1, 2015-05-18 09:06:43.531258, 10.000, null, null, 1, \u58ae\u8f2a-2101(\u52a0\u5de5) - \u58ae\u8f2a-2101(\u52a0\u5de5), 2015-05-18 09:06:44, null, 1, 1, confirmed, null, null, null, 1, null, 12, null, null, null, null, null, 32, 50).
" while evaluating
u'action_confirm()'

**Comment by pedrobaeza** [comment]
Please provide the full log concerning this issue, and also the data that leads to this error.

**Comment by anajuaristi** [comment]
We had no comments from @jaronemo and we did not reproduced the error. So I'm closing
