### ISSUE TITLE
[mrp_operations_extension] Not compatible with by_product

### ISSUE THREAD

**Issue by elicoidal** [odoomrp/odoomrp-wip#830]
Scenario:
I create a BoM with by_product.
When I want to Produce the finished product I receive the following message:
"Missing materials to start the production".
It seems that the move line for by_product is not in the right state (which is logical as it is not produced yet) and should be excluded from the check.

**Comment by pedrobaeza** [comment]
We haven't tried any of the modules with by_product (because we also understand this module useless with our current approach), so it can be. There's no plan for now to make it compatible.
