### ISSUE TITLE
[mrp_operations_traceability] clicking on "full traceability" has no effect

### ISSUE THREAD

**Issue by elicoidal** [odoomrp/odoomrp-wip#837]
create a MO and assign the SN. 
Go to serial number and click on "full traceability"
There is a blink but no new menu open

**Comment by anajuaristi** [comment]
That is not an OdooMRP related issue but Odoo core. 
It should be reported to odoo if I'm not mistaken

@pedrobaeza Agree?

**Comment by pedrobaeza** [comment]
The serial number is assigned when you produce the element, not before, so maybe that's the problem. Can you confirm, @elicoidal?

**Comment by elicoidal** [comment]
Cannot test it right now (see #851)

**Comment by anajuaristi** [comment]
Answered on #851 
I'm closing
