### ISSUE TITLE
quality_control_samples Falta de permisos

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#844]
Hola.

No se pueden añadir líneas (qc_sample_line) en un Rango de muestras (qc_sample) por falta de permisos:
https://github.com/odoomrp/odoomrp-wip/blob/8.0/quality_control_samples/security/ir.model.access.csv

**Comment by pedrobaeza** [comment]
Ajustados. Sólo el manager debe poder modificarlos.

Gracias por reportarlo.
