### ISSUE TITLE
Descuento de material en las reparaciones

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#847]
Lo apunto aquí para que no se olvide
Hay que probar si pasa en runbot y si es así, sería un bug de Odoo

En el entorno odoo_demo crear reparación, añadir materiales, iniciar y finalizar reparación.

Los movimientos de consumo de material, tienen como ubicación origen y destino la de la reparación (ERROR), deben tener las de línea de movimiento

No hay movimiento de salida para el producto reparado. 
No permite marcar que haya un picking de entrega

**Comment by Daniel-CA** [comment]
Tal y como esta montado el módulo actualmente el movimiento al que se refiere @anajuaristi es el movimiento de Salida del producto. En el campo Ubicación de entrega se define la ubicación final del producto una vez realizada la reparación faltaría añadir el albarán de salida del producto tal y como estaba en 6.1.
Por lo que veo lógico que el movimiento de consumo de material tenga como destino la reparación, no la ubicación final del producto una vez reparado.
Añado @pedrobaeza por si tiene algo que añadir.

**Comment by anajuaristi** [comment]
Exacto. Es un issue del core
Los movimientos del listado de materiales de consumo deben llevar las ubicaciones origen y destino de la linea y no de cabecera
La del albaran de entrega del producto reparado debe llevar las de cabecera
Y el albaran solo se crea si esta clickado el check de envio. Sino no
