### ISSUE TITLE
sale_documents_comments Comentario en factura

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#848]
Si una factura se crea desde un pedido de venta, el comentario configurado en el partner no aparece en la factura (campo "invoice_comment"). Sí aparece el comentario propagado del pedido de ventas.

**Comment by oihane** [comment]
Puedes explicarme los pasos que has seguido, por favor.

**Comment by ghost** [comment]
Sí, perdona.
1. En el partner "Cliente 0" rellené en la pestaña "Observaciones de venta", en el epígrafe "Facturas", el campo "Comentarios" (invoice_comment).
   ![image](https://cloud.githubusercontent.com/assets/8233008/7917805/3807c920-088d-11e5-8f30-b081f0212725.png)
2. Hice un pedido de venta a este "Cliente 0", del cual creo la factura desde el propio pedido pulsando en "Crear factura" y después en "Crear y ver factura".
3. Me aparece la factura en estado borrador, con el comentario del pedido de venta que tiene que propagar (correcto) pero sin el comentario para la factura:
   ![image](https://cloud.githubusercontent.com/assets/8233008/7917873/c0fe992a-088d-11e5-8c1b-81cac092a8d3.png)

El comentario para la factura solo lo trae si se crea la factura directamente, no si viene de un pedido de venta.
Si tiene que ser así, ok. Pensé que el de la factura tenía que aparecer en todas las facturas para ese partner.

**Comment by oihane** [comment]
Estas en lo cierto, ya he puesto el PR para solucionar esto, además de que hace algo de limpieza en el código.
