### ISSUE TITLE
Migration to OCA

### ISSUE THREAD

**Issue by max3903** [odoomrp/odoomrp-wip#850]
Moved to https://github.com/odoomrp/odoomrp-wip/wiki/Migration-to-OCA

**Comment by anajuaristi** [comment]
@max3903 Why do you closed the issue? it was a very good idea

I was building the full list of modules to be pasted here

**Comment by rdeheele** [comment]
@anajuaristi @max3903 has just transfer it on the wiki: https://github.com/odoomrp/odoomrp-wip/wiki/Migration-to-OCA
