### ISSUE TITLE
[mrp_operations_traceability] Cannot create MO

### ISSUE THREAD

**Issue by elicoidal** [odoomrp/odoomrp-wip#851]
In blank demo database, install mrp_operations_traceability.
Go to MO. Click create and the following popup is displayed:
Field mrp.production.created_mrp_track_lot is accessed before being computed. 

It is not possible to create a MO.

**Comment by oihane** [comment]
Hi @elicoidal 
I've installed mrp_operations_traceability in a database with only spanish localization, and I've tried to create a manufacturing order without any problem, could you please try again and if it continues failing please let us know all the modules installed and the steps you follow.

Thanks

**Comment by anajuaristi** [comment]
Hi @elicoidal 
Tested again, I could perfectly create an MO with module mrp_operations_traceability installed
Button full traceability will launch you to a list of produced materials serial number related to consumed materials serial numbers

The full traceability button in a lot, will launch you to same screen than the one you obtain if you push the button "lot traceability" on MO
Closing issue
