### ISSUE TITLE
quality_control_samples Duda con muestras tomadas

### ISSUE THREAD

**Issue by ghost** [odoomrp/odoomrp-wip#855]
Hola.

Este módulo trata, si entendí bien, de solo crear una inspección para un número limitado de muestras si la cantidad a testear está entre una cantidad mínima y una máxima (solo para movimientos de existencias). La duda que tengo es si la línea 23 de esta parte del código (https://github.com/odoomrp/odoomrp-wip/blob/8.0/quality_control_samples/models/qc_sample.py) es correcta:

![image](https://cloud.githubusercontent.com/assets/8233008/7959814/66ecc338-09fc-11e5-8d2f-ebe770e7ea10.png)

¿no sería al revés? 

23 `return line.samples_taken if qty > line.samples_taken else qty`

Por ejemplo, si mi rango a muestrear es de mínimo = 1 unidad y máximo = 100 unidades, debo muestrar solo 8 unidades (samples_taken). Si en mi movimiento de existencias traslado 15 unidades (qty), la línea de código me va a devolver 15 porque 15 < 7, cuando en realidad lo que quiero es que me haga 7.
El ejemplo por debajo, si muevo 5 unidades, la línea de código me va a devolver 7, cuando en realidad no las tengo.

**Comment by pedrobaeza** [comment]
Efectivamente, estaba cambiado el signo. Gracias por reportarlo.
