### ISSUE TITLE
Mrp properties not included.

### ISSUE THREAD

**Issue by zbik2607** [odoomrp/odoomrp-wip#863]
Module sale_mrp (mrp.property) is incompatible with procurement_plan_mrp.
property_ids are not tested when bom is exploded.

**Comment by anajuaristi** [comment]
Yes, we don't use properties but attributes and values, so procurement_plan_mrp is not considering properties.
If you want to affort this development, we will be glad of considering your contribution to the project.

by the moment, I'm closing the issue
