### ISSUE TITLE
Stock quant manual assign - move state when all unreserved

### ISSUE THREAD

**Issue by zbik2607** [odoomrp/odoomrp-wip#864]
When all quants will be unreserved and the list move.reserved_quant_ids is empty move should change state form 'assigned' to 'confirmed'.

**Comment by anajuaristi** [comment]
That's not an @odoomrp functionality but Odoo core functionality so it should be reported on odoo branches. Anyway, we are using this functionality in production and there is no issue or error on standar way of working.
I'm closing. Thank you

**Comment by zbik2607** [comment]
However, it's probably a problem @odoomrp functionality. Quants are removed from relationship reserved_quant_ids in method assign_quants (in assign_manual_quants.py). In the last line (this method) should be added:
        if not move.reserved_quant_ids:
            move.write({'state': 'confirmed'})

**Comment by anajuaristi** [comment]
do_unreserve is odoo core function
We did not change it and it is working

The correct way to manual assign would be --> first do_unreserve if you want to start again, after click manual quants
The usual way is just click manual quants.

In that case our module is just moving from confirmed to assign, but not inverse way.

I say again, do_unreserve is standard and it's working properly

**Comment by zbik2607** [comment]
Thank you, now I understand your way. But in the case of my way, when I change quants without do_unreserved. Other issue is open?

**Comment by pedrobaeza** [comment]
This should be reported as an issue to Odoo itself, not here
