### ISSUE TITLE
mrp_operations_project

### ISSUE THREAD

**Issue by Daniel-CA** [odoomrp/odoomrp-wip#87]
Creo este nuevo módulo para no recargar mas el de operaciones extendidas y dejarlo como finalizado.
Añado en este dependencia al operaciones extendida y algunas de las cosas que comento Ana y dejo la Issue por si se le ocurre alguna otra.
De momento:
Operaciones : Asociación many2many con "etapas" 
Project.task: many2one a Workorder.

PR #89

**Comment by anajuaristi** [comment]
Para no recargar no. Sera que como tiene dependencia con projects se pidio
especificamente que fuese otro modulo.
Repito que ¡¡ Hay que leer los requerimientos !!
Reviso el finde y os digo.
Gracias
