### ISSUE TITLE
mrp_production_project_estimated_cost Cost estimated prices are Negative Values

### ISSUE THREAD

**Issue by slevenhagen** [odoomrp/odoomrp-wip#885]
When Calculating "Create Estimated Cost"  on Production order all Project costs Estimated Standard and Estimated Average are now as negative Values.

I've found is related to new cost calculations from changes in Commit  542d219

[ADD] product_variant_cost: nuevo modulo que añade campo coste para l…

https://github.com/odoomrp/odoomrp-wip/commit/542d219981f3bb85a9460c449a30d63964625093#diff-8e587dc448b34d8fcf3e695108c577a3

**Comment by pedrobaeza** [comment]
Yeah, that's to be consistent with the full analytic semantic, having costs as negative amounts, and incomes as positive ones.
