### ISSUE TITLE
Rules/Constraints for mrp_product_variants

### ISSUE THREAD

**Issue by matt454357** [odoomrp/odoomrp-wip#887]
I need constraints to prevent users selecting incompatible options.  I am interested in contributing some code that would possibly implement the AC-3 algorithm.  That would be called on change of attribute value in form mrp.mrp_production_form_view, and apply a domain to restrict selectable values.  Any interest out there for this enhancement?  Anyone have a reason this would be very difficult?

**Comment by pedrobaeza** [comment]
Hi, Matt, we are already developing this module with some kind of AC-3 algorithm, but adapted for usability with attributes. I'll tell the developer to publish the WIP module in this repo for you to preview.

**Comment by matt454357** [comment]
Thank You Pedro.  Can you tell me the name of the module, so I will be able to find it when it is pushed?

**Comment by pedrobaeza** [comment]
Here you have: https://github.com/odoomrp/odoomrp-wip/pull/904

**Comment by anajuaristi** [comment]
Answered. So I'm closing
