### ISSUE TITLE
Purchasing: Is it possible to use the variant configurator in purchasing?

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#902]
Hi,
The functionality is really great to create the products using variant configurator. But does it work in purchasing?

Thanks for the help

**Comment by pedrobaeza** [comment]
https://github.com/odoomrp/odoomrp-wip/tree/8.0/purchase_product_variants

**Comment by ybofr** [comment]
Thank you Pedro

Eva P.
