### ISSUE TITLE
Error en los notes

### ISSUE THREAD

**Issue by SBollatti** [odoomrp/odoomrp-wip#905]
Estimados
Luego de actualizar ayer me encuentro con este error:

AttributeError: El campo `mrp_notes` no existe

Error de contexto:
Vista `res.partner.form`
[view_id: 126, xml_id: base.view_partner_form, model: res.partner, parent_id: n/a]

y me sucede al querer abrir cualquier partner o contacto

**Comment by SBollatti** [comment]
Desinstalé el modulo mrp_partner_note y mrp_production_note, al intentar intentar instalar nuevamente estos módulos, no fue posible

**Comment by pedrobaeza** [comment]
El módulo _mrp_production_note_ ahora está alojado en OCA: https://github.com/OCA/manufacture/tree/8.0/mrp_production_note, y el módulo _mrp_partner_note_ sigue alojado en https://github.com/odoomrp/odoomrp-utils
