### ISSUE TITLE
Task Name created in MRP Project link Shows  [False]  when No Internal Reference set on Product Master

### ISSUE THREAD

**Issue by slevenhagen** [odoomrp/odoomrp-wip#913]
At Line 143 in mrp_project_link/models/mrp_production.py 

Need Change 
                task_name = ("%s:: [%s]%s") % (record.name,
                                               record.product_id.default_code,
                                               record.product_id.name)
To
                task_name = ("%s:: [%s]%s") % (record.name,
                                               record.product_id.default_code or '',
                                               record.product_id.name)

**Comment by pedrobaeza** [comment]
@agaldona, please take this into account
