### ISSUE TITLE
mrp_production_estimated_cost sequence issues

### ISSUE THREAD

**Issue by anhdv1979** [odoomrp/odoomrp-wip#914]
When I sucessfully install  mrp_production_estimated_cost (mrp_operation_extension, mrp_operation_project, mrp_production_project_estimated_cost, mrp_project_link, product_variant_cost), I find that it doesn't install sequence and it make production order sequence of manufacturing order is not automatically created.
Pls help me check. Many thanks for your help!

**Comment by anajuaristi** [comment]
This is not odoomrp issue but odoo core issue
If you are using multicompany only first company mo sequence is created so
you must configure manually the rest of them

**Comment by anhdv1979** [comment]
Sorry but I have already manually configured but it still could not. To be frank, very supprisedDinh Vuong AnhThe Post & Telecommunication Joint Stock Company61 Tranphu road, Badinh, Hanoi, VietnamTel: (+84) 4 3 845 5946Fax: (+84) 4 3823 4128Mobile: (+84) 904237572 Email: anhdv@postef.com.vn; anhdv08121979@gmail.comWebsite: www.postef.com.vn

-------- Original Message --------
Subject: Re: [odoomrp-wip] mrp_production_estimated_cost sequence issues
(#914)
