### ISSUE TITLE
production capacity error

### ISSUE THREAD

**Issue by anhdv1979** [odoomrp/odoomrp-wip#915]
I have install production_estimated_cost & production_capacity. However when creating MO, it shows error like
![production_capacity](https://cloud.githubusercontent.com/assets/7521909/8815759/ce2613f8-3047-11e5-92ec-8dd444826686.jpg)
(I have already set min, max capacity of work center

Thanks alot for your help

**Comment by pedrobaeza** [comment]
This should be fixed by now. Please check with last version.
