### ISSUE TITLE
subcontracting, incorrect destiny location

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#918]
Adding a product manually in a subcontracting operation, assing destiny location from MO and not from subcontracting picking type

Steps to reproduce:
1. Create a BOM, asigned a route including external operation
2. use "add raw material" button on MO to add several materials to MO, taking care or selecting  external WO
3. Start external operation
4. Confirm subcontracting PO
5. Open Outgoing picking --> Destiny location on materials added using button is not the same than for the planned materials

Solution: Button Add raw materials should control if assigned operation is external and set origin and destiny taken from subcontracting picking type and not from MO itself.

**Comment by alfredoavanzosc** [comment]
Se ha modificado el módulo "mrp_subcontracting", el PR es el https://github.com/odoomrp/odoomrp-wip/pull/925

**Comment by alfredoavanzosc** [comment]
Esto ya esta hecho, los módulos modificados son "mrp_subcontracting", y "mrp_operation_extension". Pedro ya ha realizado el merge, cierro el issue.
