### ISSUE TITLE
Error en líneas fantasma de lista de materiales

### ISSUE THREAD

**Issue by mlopezgaldon** [odoomrp/odoomrp-wip#919]
Cuando una lista de materiales contiene 2 posiciones fantasma consecutivas, al ser ésta utilizada en una orden de fabricación, todos los materiales posteriores al segundo fantasma son asignados con la misma operación, la del padre.

**Comment by anajuaristi** [comment]
@pedrobaeza nos reportan este issue que en principio, se suponía arreglado pero parece que hay alguna casuistica que se nos escapa.
Te asigno a tí, aunque por si acaso pongo en copia a @oihane y @Daniel-CA por si pueden también echarle un vistazo

**Comment by mlopezgaldon** [comment]
@pedrobaeza Podrías mirar esto por favor? Muchas gracias!

**Comment by pedrobaeza** [comment]
@mlopezgaldon, conseguiste reproducir la secuencia para que esto fallara? Si es así, ponla aquí para que podamos investigarlo, ya que como te comenté no consigo reproducirlo.

**Comment by mlopezgaldon** [comment]
Al final no conseguí reproducirlo, partiendo de una instalación limpia funciona bien, la doy por cerrada.
