### ISSUE TITLE
Forzado de reservas al iniciar operación

### ISSUE THREAD

**Issue by mlopezgaldon** [odoomrp/odoomrp-wip#920]
En una orden de producción, al iniciar una operación se fuerzan las reservas de todos los productos planificados.

**Comment by anajuaristi** [comment]
@mlopezgaldon ¿Porqué cierras los issues y los vuelves a abrir?
Simplemente escribiendo algo de recordatorio es suficiente.

@Daniel-CA tiene pinta de que esto sea provocado por el standar de Odoo. 
El inicio de una operación NO DEBE forzar disponibilidad en ningún caso.

Por otro lado, solicitaban que el control de la existencia de material en una operación fuese configurable desde la categoría del producto.
Para ello, sería requerido añadir un Check en la categoría "inicio de operación SIN disponibilidad" de tal forma que si está clickado, la operación no verifique si hay o no material disponible para iniciarla.

Por defecto dicho check estará sin activar.

**Comment by mlopezgaldon** [comment]
Perdona Ana, es que sin darme cuenta las he abierto en odoomrp-utils y me ha parecido que en odoomrp-wip iban a estar mejor.

**Comment by anajuaristi** [comment]
ahhh... vale
