### ISSUE TITLE
Poder iniciar operaciones sin disponibilidad de materias primas

### ISSUE THREAD

**Issue by mlopezgaldon** [odoomrp/odoomrp-wip#921]
En Pls interesaría poder iniciar operaciones cuyas materias primas no estén del todo disponibles, la solución propuesta añadiría un check a la operación que indique si ésta puede iniciar o no con carencias de material.

**Comment by pedrobaeza** [comment]
En PR https://github.com/odoomrp/odoomrp-wip/pull/931
