### ISSUE TITLE
[QUESTION] sale_order_type y purchase_type

### ISSUE THREAD

**Issue by oihane** [odoomrp/odoomrp-wip#94]
Para @anajuaristi y @pedrobaeza 

Existe un modulo llamado `sale_order_type` que hizo @CsanchezC en el que se crean "tipos de pedidos de venta" y se le añaden los datos:
- Nombre de tipología
- Almacen (requerido)
- Secuencia de entrada
- Diario de facturación
- Diario de facturación rectificativa
- Descripción
  además hace que en el pedido de venta haya que seleccionar un tipo de manera obligatoria.

En el caso del `purchase_type` hecho en un principio por @alfredoavanzosc lo que se hace es crear "tipos de pedidos de compra" con los campos:
- Nombre de tipo
- Secuencia de pedido de compra (código)
  de manera que al tener que seleccionar un tipo en el pedido de compra lo que hace es aplicarle la secuencia que definimos, y así poder usar una secuencia por cada tipo

Con esto lo que quiero saber es si ambos tienen que ser equivalentes, como ya se ha hecho con otros módulos, o no. Ya que @mikelarre tiene que cambiar el modulo `sale_order_type` para que tenga un tipo por defecto (con la idea de evitar el olvido de seleccionarlo) y el `purchase_type` lo tengo como PR #73  sin aprobar.

**Comment by pedrobaeza** [comment]
Se podrían hacer equivalentes, teniendo en cuenta (para ambos módulos las siguientes cuestiones):
- Lo que dices de que si es obligatorio, se seleccione un tipo por defecto.
- Que los diarios de facturas y facturas rectificativas sean opcionales, de tal modo que si se rellenan, se coja ése, pero si no, se coja el que le toque.

**Comment by anajuaristi** [comment]
¿Merece la pena hacerlo para purchase_type?
En principio, esto se hizo para permitir en la agrupación de albaranes que se pudiera también crear facturas en función de tipo de pedido que se estuviera tratando para automatizar el tema de las diferentes líneas de facturación pero en compras no se hace en bloque sino factura por factura y ellos pueden seleccionar qué quieren hacer o contra qué diario tirar. 
No sé, creo que purchase_type se migró por una dependencia con el simulador de costes pero tengo duda de si se pidió en Odoomrp. 
Por mi parte, mergearía ya sale_type si es que no está mergeado y purchase_type lo aparcaría hasta nueva orden. Si no lo piden, nada. Se quita y listo.Ahora bien, si se pide y con lo que he comentado... ¿Sería necesario meter los diarios y estas cosas? Creo que no, en principio. 

Recordad, que impacta también en el módulo extensión de los bid que hemos hecho...

**Comment by pedrobaeza** [comment]
Tienes razón que en compras no tiene tanto sentido. De todas formas, los comentarios anteriores siguen vigentes para ventas. ¿Está así, @oihane?

**Comment by oihane** [comment]
Lo del tipo por defecto del `sale_order_type`, que ya está mergeado, lo tiene pendiente de hacer @mikelarre 
Y por lo que veo en el código si que hace lo del segundo punto

P.D: Mikel, cuando hagas lo de seleccionar uno por defecto comprueba el fichero `account_invoice.py`, tiene un error tipografico
