### ISSUE TITLE
[BUG] mrp_operations_start_without_material: No traslada el valor a la MO

### ISSUE THREAD

**Issue by mlopezgaldon** [odoomrp/odoomrp-wip#944]
Al confirmar una MO, aunque en la ruta haya operaciones marcadas como "iniciar sin materiales", éstas aparecen en la MO con el campo sin marcar.

**Comment by anajuaristi** [comment]
@Daniel-CA porfa, mira a ver porqué el valor del campo no se arrastra de la línea de ruta a la workorder.

Gracias
