### ISSUE TITLE
[mrp_byproduct_operations] Subproduct not being produced when operation is finished

### ISSUE THREAD

**Issue by JordiBForgeFlow** [odoomrp/odoomrp-wip#949]
I am documenting this module, but found an inconsistency in the behavior.
The current module description states: "This module allows to add the operation on BoM where the secondary products will be produced".

However when you complete the operation the subproduct is not really completed, and remains as a product to manufacture, until the manufacturing order is completed.

IMHO when the operation is completed the move associated to that subproduct should also be completed.

**Comment by pedrobaeza** [comment]
This module hasn't been worked since the beginning and, as marginal, probably now it's not working. @Daniel-CA, did you do this module? Can you check it?

**Comment by anajuaristi** [comment]
@jbeficent @pedrobaeza 
No. It's not being used by our customers and probably it's not working fine. So we should remove from odoomrp branch to another place

**Comment by JordiBForgeFlow** [comment]
Thanks @anajuaristi. Can your team prepare a priority list of the modules that require further documentation? Perhaps setting up this list as a wiki page in Github could be convenient.

Doing this @jsoroa and me will be more effective.

Thanks!!!
