### ISSUE TITLE
mrp_production_manual_close realiza movimientos de fabricación y consumo

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#964]
Según parece el módulo mrp_operations de Odoo, interpreta que si se realiza una OF, se dan por realizados todos los movimientos de consumo y producción, incluso cuando la realización de la OF fuese parcial.

Esto está causando un bug grave en el módulo mrp_production_manual_close, ya que al cerrar la OF en vez de cancelar los movimientos pendientes tanto de consumo como de producción, las realiza.
Para solucionarlo, es necesario primero ejecutar la señal de "cancelar" la OF y luego marcarla realizada. De esta forma, se cancela todo lo pendiente y la OF se deja terminada en vez de cancelada.

Además, se va a añadir una pantalla de warning indicando lo que hace el  botón. Algo así como:
"Esta acción cancelará todos los movimientos pendientes tanto de consumo como de producción y marcará la OF como realizada y no se podrá deshacer. ¿Está seguro?"

**Comment by Daniel-CA** [comment]
Al final hemos decidido hacer un cambio en el mrp_operations_extension en vez de ejecutar la señal de cancelar.
El módulo de `mrp_production_manual_close` fallaba debido a que al finalizar una orden de trabajo si esta tenía movimientos pendientes los finalizaba en vez de cancelarlos, lo que generaba el descuadre de productos.
Hay que tener en cuenta que ahora el botón de finalizar una operación no consume_y_produce como hacía antes, por si hay alguien que usaba esa operativa para producir en las operaciones.

**Comment by anajuaristi** [comment]
@Daniel-CA 
Sigue sin estar bien, ya que ejecutando el botón de cerrar la orden manualmente desde la OF(SIN que entren para nada las operaciones) Sigue realizando los movimientos de consumo y producción.

Para que esté correcto, hay que CANCELAR los movimientos de consumo y producción que queden y dejar la orden en estado REALIZADO. 
En producciones donde exista algún movimiento de producto final realizado, la OF debe quedar REALIZADA, en producciones donde no haya ningún movimiento de producto final realizado, debería quedarse cancelada.

Otra opción tal y como hablamos en otro hilo, es dar un mensaje al usuario indicando que tiene movimientos de producción y consumo pendientes y si desea dejar la orden realizada o cancelada.

**Comment by Daniel-CA** [comment]
Has probado este PR? https://github.com/OCA/manufacture/pull/79
