### ISSUE TITLE
[ERROR] procurement_purchase_no_grouping: No line grouping / JIT procurement

### ISSUE THREAD

**Issue by maljac** [odoomrp/odoomrp-wip#967]
Hi, 

I get a error in the following scenario when using  the module `procurement_purchase_no_grouping` in combination with `procurement_jit`:

**Scenario**

_Install_
Install the modules `sale, purchase, procurement_jit, procurement_purchase_no_grouping`

_Steps to reproduce_
1. Set the procurement purchase grouping in the product category `All Products` to `No line grouping`
2. Create a new product and select: Buy / Make to Order as well as "Can be sold, Can be purchased"
3. Create a new sales order and sell our new product
4. Submit the order

--> ERROR

**Reason for the Error**

In `addons/purchase/purchase.py#1476` is the following code line:

`po_line_id = po_obj.browse(cr, uid, po_id, context=context).order_line[0].id`

If you  set context to `{}` all works fine, i.e. the following line works:

`po_line_id = po_obj.browse(cr, uid, po_id, context={}).order_line[0].id`

Since editint the `make_po` method in `purchase.py` is no option, and leaving the context empty has even more _code smell_, are there any suggestions how to fix this? I have no idea what the root cause of this behaviour is!

**Comment by pedrobaeza** [comment]
Solved in https://github.com/odoomrp/odoomrp-wip/commit/99e523fbc14eea4b0c3d8baf8661110d47ddfb35

**Comment by maljac** [comment]
thanks! :+1:
