### ISSUE TITLE
[purchase_landed_cost] new_std_price is not taken from total cost (including landed costs)

### ISSUE THREAD

**Issue by cvinh** [odoomrp/odoomrp-wip#971]
Steps to reproduce : 
- start with a new product (stock=0)
- buy and receive products normally (purchase + stock)
- in purchase_cost_distribution, apply landed costs normally
- When Updating Cost, the new standard price is taken from the cost price without landed costs

Expected behaviour : 
When updating cost the new standard price should be taken from the cost price including landed costs

**Comment by cvinh** [comment]
checkout https://github.com/odoomrp/odoomrp-wip/pull/972

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/odoomrp/odoomrp-wip/commit/8af8799ea0bd1c69f6fc0d77db390c15f45f16cc
