### ISSUE TITLE
odooMRP test in github: menu for attributes has disappeared

### ISSUE THREAD

**Issue by ybofr** [odoomrp/odoomrp-wip#992]
I was using 
http://3115012-8-0-4bf732.runbot2.odoo-community.org/web?db=3115012-8-0-4bf732-all
The latest merge for OdooMRP. I could not find the menu for attributes. Picture is attached

Regards
Eva P.
<img width="327" alt="customers_-_odoo" src="https://cloud.githubusercontent.com/assets/7601880/9835527/ea51f136-59e7-11e5-8c6d-226ba1326311.png">

**Comment by pedrobaeza** [comment]
You should activate proper permissions to see this kind of things. Please don't open more issues about these questions without seeing better.

**Comment by ybofr** [comment]
Hi Pedro,

There is no way for me to know what to activate and especially as a functional consultant, I do not deal with authorizations. If as Admin, it does not work, then this is for me an issue.

best regards

**Comment by pedrobaeza** [comment]
As an Odoo consultant, you should know security groups as part of the parametrization of the system to allow users (including admin) to see some menus/options. admin doesn't have "Technical features" by default, and you has asked for the same thing several times.

**Comment by ybofr** [comment]
Hi Pedro 
As a matter if fact. I believe some of the things did not work properly. I assigned technical feature to the admin but it did not help. It is impossible for me to know exactly which group must be authorized for a module if this is not documented in the readme.
If we want more functional people supporting the system and testing the support, everyone should go from the technically oriented view to the functional oriented view knowing that functional people do not work with authorisations, and also cannot debug quickly to figure out where the issue is.
Best regards and thanks for your support

Sent from my Samsung Galaxy smartphone

-------- Original message --------

**Comment by pedrobaeza** [comment]
That's not something of our module, but Odoo itself that hides by default that menu.

**Comment by ybofr** [comment]
Ok. Thank you. I have now understood that some settings require the person to log out and log again in for them to be active and some do not. I believe this was the reason of my confusion. I added the technical features, but was not relogging, so the system still had the old settings.

We can now close the issue.

Best regards
Eva P.

**Comment by pedrobaeza** [comment]
You don't need to logout. Only refresh browser page (F5) to reload menus, because they're cached.
