### ISSUE TITLE
product_supplierinfo_for_customer doesn't calculate price correctly

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-wip#996]
Hi:

We were testing this module and a kind of bug has been introduced from short-time ago. 

Tested on runbot: http://3115098-8-0-21bd39.runbot2.odoo-community.org/web?db=3115098-8-0-21bd39-all#menu_id=110&action=100

Tested CASE:
Used product to test: Apple In-Ear Headphones
Configure prices 1 single unit for suppliers (asustek: 5€, delta PC:6€)

Configure prices 1 single unit for customers (agrolait: 10€, Axelor:11€)

---

Go to sales, create a new sale order for agrolait
Create a sales order line for ear Headphones --> Expected behavior would be unit price = 10€, It calculates 5€, just the first line for supplier

Selling to Axelor, takes also 5€ when expected behavior would be 11€

**Comment by pedrobaeza** [comment]
This is not something derived from the last change, but a general problem in v8 that I solved here, but Odoo has only applied on v9: https://github.com/odoo/odoo/pull/4505

**Comment by pedrobaeza** [comment]
I reopen again because is not the same case to continue investigating
